export type CommodityCategory =
  | "rawOre"
  | "metals"
  | "gases"
  | "chemicals"
  | "plastics"
  | "electronics"
  | "foodstuffs"
  | "meats"
  | "crops"
  | "water"
  | "pharmaceuticals"
  | "clothing"
  | "consumerGoods"
  | "parts"
  | "industrialGoods"
  | "energy"
  | "construction"
  | "livestock"
  | "spaceCommodity"
  | "farming"
  | "cybernetics"
  | "military"
  | "textiles"
  | "weaponry"
  | "vehicles"
  | "wasteland"
  | "luxury"
  | "dataMedia"
  | "biotech"
  | "dnaSupplies"
  | "geneticEquipment"
  | "cloningMaterials"
  | "bioProducts"
  | "geneticMedicine"
  | "cloneGoods"
  | "researchMaterials"
  | "bioWeapons"
  | "xenobiology"
  | "upliftGoods";

export type CommodityDef = {
  id: string;
  name: string;
  category: CommodityCategory;
  basePrice?: number;
  weight?: number;
  contraband?: boolean;
};

import { SD_COMMODITIES } from "@/engine/addons/sixthDay";

const SD_COMMODITY_DEFS: CommodityDef[] = SD_COMMODITIES.map((c) => ({
  id: c.id,
  name: c.name,
  category: c.category as CommodityCategory,
}));

export const RAW_ORE: CommodityDef[] = [
  { id: "iron_ore", name: "Iron Ore", category: "rawOre" },
  { id: "copper_ore", name: "Copper Ore", category: "rawOre" },
  { id: "aluminum_ore", name: "Aluminum Ore (Bauxite)", category: "rawOre" },
  { id: "tin_ore", name: "Tin Ore", category: "rawOre" },
  { id: "lead_ore", name: "Lead Ore", category: "rawOre" },
  { id: "zinc_ore", name: "Zinc Ore", category: "rawOre" },
  { id: "nickel_ore", name: "Nickel Ore", category: "rawOre" },
  { id: "titanium_ore", name: "Titanium Ore", category: "rawOre" },
  { id: "chromium_ore", name: "Chromium Ore", category: "rawOre" },
  { id: "manganese_ore", name: "Manganese Ore", category: "rawOre" },
  { id: "tungsten_ore", name: "Tungsten Ore", category: "rawOre" },
  { id: "cobalt_ore", name: "Cobalt Ore", category: "rawOre" },
  { id: "molybdenum_ore", name: "Molybdenum Ore", category: "rawOre" },
  { id: "uranium_ore", name: "Uranium Ore", category: "rawOre" },
  { id: "thorium_ore", name: "Thorium Ore", category: "rawOre" },
  { id: "lithium_deposits", name: "Lithium Deposits", category: "rawOre" },
  { id: "rare_earth_minerals", name: "Rare Earth Minerals", category: "rawOre" },
  { id: "silicon_ore", name: "Silicon Ore (Quartz)", category: "rawOre" },
  { id: "gold_ore", name: "Gold Ore", category: "rawOre" },
  { id: "silver_ore", name: "Silver Ore", category: "rawOre" },
  { id: "platinum_ore", name: "Platinum Ore", category: "rawOre" },
  { id: "coal_deposits", name: "Coal Deposits", category: "rawOre" },
  { id: "sulfur_deposits", name: "Sulfur Deposits", category: "rawOre" },
  { id: "phosphate_rock", name: "Phosphate Rock", category: "rawOre" },
  { id: "limestone_raw", name: "Limestone", category: "rawOre" },
  { id: "graphite_raw", name: "Graphite", category: "rawOre" },
  { id: "sand_deposits", name: "Sand Deposits", category: "rawOre" },
  { id: "gravel_deposits", name: "Gravel Deposits", category: "rawOre" },
  { id: "industrial_clay", name: "Industrial Clay", category: "rawOre" },
  { id: "scrap_metal", name: "Scrap Metal", category: "rawOre" },
  { id: "electronic_waste", name: "Electronic Waste", category: "rawOre" },
  { id: "salvaged_machinery", name: "Salvaged Machinery", category: "rawOre" },
  { id: "wasteland_salvage", name: "Wasteland Salvage", category: "rawOre" },
  { id: "construction_debris", name: "Construction Debris", category: "rawOre" },
  { id: "crude_oil", name: "Crude Oil", category: "rawOre" },
  { id: "natural_gas_raw", name: "Natural Gas (Raw)", category: "rawOre" },
];

export const METALS: CommodityDef[] = [
  { id: "steel_ingots", name: "Steel Ingots", category: "metals" },
  { id: "steel_bars", name: "Steel Bars", category: "metals" },
  { id: "steel_sheets", name: "Steel Sheets", category: "metals" },
  { id: "steel_plates", name: "Steel Plates (Armor Grade)", category: "metals" },
  { id: "steel_rods", name: "Steel Rods", category: "metals" },
  { id: "steel_wire", name: "Steel Wire", category: "metals" },
  { id: "steel_mesh", name: "Steel Mesh", category: "metals" },
  { id: "structural_steel_beams", name: "Structural Steel Beams", category: "metals" },
  { id: "stainless_steel_sheets", name: "Stainless Steel Sheets", category: "metals" },
  { id: "copper_ingots", name: "Copper Ingots", category: "metals" },
  { id: "copper_bars", name: "Copper Bars", category: "metals" },
  { id: "copper_wire", name: "Copper Wire", category: "metals" },
  { id: "copper_tubing", name: "Copper Tubing", category: "metals" },
  { id: "copper_sheets", name: "Copper Sheets", category: "metals" },
  { id: "aluminum_ingots", name: "Aluminum Ingots", category: "metals" },
  { id: "aluminum_sheets", name: "Aluminum Sheets", category: "metals" },
  { id: "aluminum_extrusions", name: "Aluminum Extrusions", category: "metals" },
  { id: "aluminum_foil", name: "Aluminum Foil", category: "metals" },
  { id: "titanium_ingots", name: "Titanium Ingots", category: "metals" },
  { id: "titanium_plates", name: "Titanium Plates", category: "metals" },
  { id: "titanium_alloy_bars", name: "Titanium Alloy Bars", category: "metals" },
  { id: "nickel_ingots", name: "Nickel Ingots", category: "metals" },
  { id: "tin_ingots", name: "Tin Ingots", category: "metals" },
  { id: "lead_ingots", name: "Lead Ingots", category: "metals" },
  { id: "zinc_ingots", name: "Zinc Ingots", category: "metals" },
  { id: "chromium_bars", name: "Chromium Bars", category: "metals" },
  { id: "tungsten_bars", name: "Tungsten Bars", category: "metals" },
  { id: "cobalt_ingots", name: "Cobalt Ingots", category: "metals" },
  { id: "gold_bars", name: "Gold Bars", category: "metals" },
  { id: "silver_bars", name: "Silver Bars", category: "metals" },
  { id: "platinum_bars", name: "Platinum Bars", category: "metals" },
  { id: "carbon_fiber_sheets", name: "Carbon Fiber Sheets", category: "metals" },
  { id: "graphene_sheets", name: "Graphene Sheets", category: "metals" },
  { id: "nano_alloy_composite", name: "Nano-Alloy Composite", category: "metals" },
  { id: "depleted_uranium_rods", name: "Depleted Uranium Rods", category: "metals" },
  { id: "reinforced_alloy_panels", name: "Reinforced Alloy Panels", category: "metals" },
  { id: "steel_ingot", name: "Steel Ingot", category: "metals" },
  { id: "copper_ingot", name: "Copper Ingot", category: "metals" },
  { id: "aluminum_ingot", name: "Aluminum Ingot", category: "metals" },
  { id: "titanium_alloy", name: "Titanium Alloy", category: "metals" },
  { id: "reactor_alloy", name: "Reactor Alloy", category: "metals" },
];

export const GASES: CommodityDef[] = [
  { id: "oxygen_industrial", name: "Oxygen (Industrial)", category: "gases" },
  { id: "oxygen_medical", name: "Oxygen (Medical Grade)", category: "gases" },
  { id: "nitrogen_liquid", name: "Liquid Nitrogen", category: "gases" },
  { id: "nitrogen_gas", name: "Nitrogen Gas", category: "gases" },
  { id: "hydrogen_gas", name: "Hydrogen Gas", category: "gases" },
  { id: "hydrogen_liquid", name: "Liquid Hydrogen", category: "gases" },
  { id: "helium_gas", name: "Helium Gas", category: "gases" },
  { id: "argon_gas", name: "Argon Gas", category: "gases" },
  { id: "co2_industrial", name: "Carbon Dioxide (Industrial)", category: "gases" },
  { id: "acetylene", name: "Acetylene", category: "gases" },
  { id: "propane_gas", name: "Propane Gas", category: "gases" },
  { id: "butane_gas", name: "Butane Gas", category: "gases" },
  { id: "methane_gas", name: "Methane Gas", category: "gases" },
  { id: "natural_gas_refined", name: "Natural Gas (Refined)", category: "gases" },
  { id: "neon_gas", name: "Neon Gas", category: "gases" },
  { id: "xenon_gas", name: "Xenon Gas", category: "gases" },
  { id: "chlorine_gas", name: "Chlorine Gas", category: "gases" },
  { id: "ammonia_gas", name: "Ammonia Gas", category: "gases" },
  { id: "compressed_air", name: "Compressed Air (Cylinders)", category: "gases" },
  { id: "sulfur_dioxide", name: "Sulfur Dioxide", category: "gases" },
];

export const CHEMICALS: CommodityDef[] = [
  { id: "sulfuric_acid", name: "Sulfuric Acid", category: "chemicals" },
  { id: "hydrochloric_acid", name: "Hydrochloric Acid", category: "chemicals" },
  { id: "nitric_acid", name: "Nitric Acid", category: "chemicals" },
  { id: "sodium_hydroxide", name: "Sodium Hydroxide (Lye)", category: "chemicals" },
  { id: "ethanol_industrial", name: "Industrial Ethanol", category: "chemicals" },
  { id: "methanol", name: "Methanol", category: "chemicals" },
  { id: "acetone", name: "Acetone", category: "chemicals" },
  { id: "bleach_industrial", name: "Industrial Bleach", category: "chemicals" },
  { id: "chemical_solvents", name: "Chemical Solvents (Mixed)", category: "chemicals" },
  { id: "industrial_adhesives", name: "Industrial Adhesives", category: "chemicals" },
  { id: "epoxy_resins", name: "Epoxy Resins", category: "chemicals" },
  { id: "paint_industrial", name: "Industrial Paint", category: "chemicals" },
  { id: "chemical_fertilizer", name: "Chemical Fertilizer (NPK)", category: "chemicals" },
  { id: "pesticides", name: "Pesticides", category: "chemicals" },
  { id: "herbicides", name: "Herbicides", category: "chemicals" },
  { id: "industrial_lubricants", name: "Industrial Lubricants", category: "chemicals" },
  { id: "hydraulic_fluid", name: "Hydraulic Fluid", category: "chemicals" },
  { id: "coolant_fluid", name: "Coolant Fluid", category: "chemicals" },
  { id: "machine_oil", name: "Machine Oil", category: "chemicals" },
  { id: "silicone_sealant", name: "Silicone Sealant", category: "chemicals" },
  { id: "polyurethane_foam", name: "Polyurethane Foam", category: "chemicals" },
  { id: "cleaning_chemicals", name: "Cleaning Chemicals", category: "chemicals" },
  { id: "water_treatment_chemicals", name: "Water Treatment Chemicals", category: "chemicals" },
  { id: "explosive_compounds", name: "Explosive Compounds", category: "chemicals" },
];

export const PLASTICS: CommodityDef[] = [
  { id: "pe_pellets", name: "Polyethylene Pellets (PE)", category: "plastics" },
  { id: "pp_pellets", name: "Polypropylene Pellets (PP)", category: "plastics" },
  { id: "pvc_granules", name: "PVC Granules", category: "plastics" },
  { id: "abs_pellets", name: "ABS Pellets", category: "plastics" },
  { id: "nylon_pellets", name: "Nylon Pellets", category: "plastics" },
  { id: "polycarbonate_sheets", name: "Polycarbonate Sheets", category: "plastics" },
  { id: "acrylic_sheets", name: "Acrylic Sheets", category: "plastics" },
  { id: "plastic_pipes", name: "Plastic Pipes (PVC/PE)", category: "plastics" },
  { id: "plastic_sheeting", name: "Plastic Sheeting (Rolls)", category: "plastics" },
  { id: "plastic_containers", name: "Plastic Containers", category: "plastics" },
  { id: "plastic_packaging", name: "Plastic Packaging Film", category: "plastics" },
  { id: "foam_insulation_boards", name: "Foam Insulation Boards", category: "plastics" },
  { id: "rubber_raw", name: "Raw Rubber", category: "plastics" },
  { id: "rubber_sheets", name: "Rubber Sheets", category: "plastics" },
  { id: "rubber_seals", name: "Rubber Seals & Gaskets", category: "plastics" },
  { id: "rubber_hoses", name: "Rubber Hoses", category: "plastics" },
  { id: "synthetic_fibers", name: "Synthetic Fibers (Polyester)", category: "plastics" },
  { id: "polymer_sheets", name: "Polymer Sheets (Mixed)", category: "plastics" },
  { id: "composite_panels", name: "Composite Panels", category: "plastics" },
  { id: "3d_print_filament", name: "3D Print Filament", category: "plastics" },
];

export const ELECTRONICS: CommodityDef[] = [
  { id: "silicon_wafers", name: "Silicon Wafers", category: "electronics" },
  { id: "microprocessors", name: "Microprocessors (CPUs)", category: "electronics" },
  { id: "memory_chips", name: "Memory Chips (RAM)", category: "electronics" },
  { id: "circuit_boards_pcb", name: "Printed Circuit Boards", category: "electronics" },
  { id: "led_panels", name: "LED Panels", category: "electronics" },
  { id: "lcd_displays", name: "LCD Display Modules", category: "electronics" },
  { id: "oled_screens", name: "OLED Screens", category: "electronics" },
  { id: "optical_sensors", name: "Optical Sensors", category: "electronics" },
  { id: "motion_sensors", name: "Motion Sensors", category: "electronics" },
  { id: "temperature_sensors", name: "Temperature Sensors", category: "electronics" },
  { id: "pressure_sensors", name: "Pressure Sensors", category: "electronics" },
  { id: "camera_modules", name: "Camera Modules", category: "electronics" },
  { id: "gps_modules", name: "GPS Modules", category: "electronics" },
  { id: "radio_transceivers", name: "Radio Transceivers", category: "electronics" },
  { id: "antenna_arrays", name: "Antenna Arrays", category: "electronics" },
  { id: "fiber_optic_cable", name: "Fiber Optic Cable", category: "electronics" },
  { id: "electrical_cable", name: "Electrical Cable (Spools)", category: "electronics" },
  { id: "wire_bundles", name: "Wire Bundles", category: "electronics" },
  { id: "cable_connectors", name: "Cable Connectors", category: "electronics" },
  { id: "resistors_capacitors", name: "Resistors & Capacitors", category: "electronics" },
  { id: "transistors", name: "Transistors", category: "electronics" },
  { id: "diodes_leds", name: "Diodes & LEDs", category: "electronics" },
  { id: "servo_motors", name: "Servo Motors", category: "electronics" },
  { id: "electric_motors_small", name: "Small Electric Motors", category: "electronics" },
  { id: "data_storage_drives", name: "Data Storage Drives", category: "electronics" },
  { id: "power_supply_units", name: "Power Supply Units", category: "electronics" },
  { id: "transformers", name: "Transformers", category: "electronics" },
  { id: "relays_switches", name: "Relays & Switches", category: "electronics" },
  { id: "navigation_systems", name: "Navigation Systems", category: "electronics" },
  { id: "surveillance_cameras", name: "Surveillance Cameras", category: "electronics" },
];

export const FOODSTUFFS: CommodityDef[] = [
  { id: "grain_rations", name: "Grain Rations", category: "foodstuffs" },
  { id: "processed_food_packs", name: "Processed Food Packs", category: "foodstuffs" },
  { id: "emergency_rations", name: "Emergency Rations (MRE)", category: "foodstuffs" },
  { id: "flour_bulk", name: "Flour (Bulk)", category: "foodstuffs" },
  { id: "sugar_refined", name: "Refined Sugar", category: "foodstuffs" },
  { id: "salt_refined", name: "Refined Salt", category: "foodstuffs" },
  { id: "cooking_oil", name: "Cooking Oil", category: "foodstuffs" },
  { id: "powdered_milk", name: "Powdered Milk", category: "foodstuffs" },
  { id: "canned_goods", name: "Canned Goods (Assorted)", category: "foodstuffs" },
  { id: "dried_pasta", name: "Dried Pasta", category: "foodstuffs" },
  { id: "instant_noodles", name: "Instant Noodles", category: "foodstuffs" },
  { id: "protein_powder", name: "Protein Powder (Bulk)", category: "foodstuffs" },
  { id: "nutrient_supplements", name: "Nutrient Supplements", category: "foodstuffs" },
  { id: "energy_bars", name: "Energy Bars", category: "foodstuffs" },
  { id: "synthetic_food_base", name: "Synthetic Food Base", category: "foodstuffs" },
  { id: "flavoring_compounds", name: "Flavoring Compounds", category: "foodstuffs" },
  { id: "preservatives", name: "Food Preservatives", category: "foodstuffs" },
  { id: "yeast_cultures", name: "Yeast Cultures", category: "foodstuffs" },
  { id: "baby_formula", name: "Baby Formula", category: "foodstuffs" },
  { id: "beverage_concentrates", name: "Beverage Concentrates", category: "foodstuffs" },
  { id: "processed_food", name: "Processed Food", category: "foodstuffs" },
];

export const MEATS: CommodityDef[] = [
  { id: "beef_carcass", name: "Beef Carcass (Whole)", category: "meats" },
  { id: "beef_cuts", name: "Beef Cuts (Processed)", category: "meats" },
  { id: "ground_beef", name: "Ground Beef (Bulk)", category: "meats" },
  { id: "pork_sides", name: "Pork Sides", category: "meats" },
  { id: "pork_cuts", name: "Pork Cuts (Processed)", category: "meats" },
  { id: "poultry_whole", name: "Poultry (Whole Birds)", category: "meats" },
  { id: "poultry_cuts", name: "Poultry Cuts (Processed)", category: "meats" },
  { id: "lamb_carcass", name: "Lamb Carcass", category: "meats" },
  { id: "fish_fresh", name: "Fresh Fish (Bulk)", category: "meats" },
  { id: "fish_frozen", name: "Frozen Fish (Bulk)", category: "meats" },
  { id: "shellfish", name: "Shellfish (Mixed)", category: "meats" },
  { id: "synthetic_meat_slabs", name: "Synthetic Meat Slabs", category: "meats" },
  { id: "insect_protein_blocks", name: "Insect Protein Blocks", category: "meats" },
  { id: "algae_protein_paste", name: "Algae Protein Paste", category: "meats" },
  { id: "sausages_bulk", name: "Sausages (Bulk)", category: "meats" },
  { id: "dried_jerky", name: "Dried Jerky", category: "meats" },
  { id: "canned_meat", name: "Canned Meat", category: "meats" },
  { id: "organ_meats", name: "Organ Meats (Offal)", category: "meats" },
  { id: "bone_meal", name: "Bone Meal", category: "meats" },
  { id: "animal_fat_tallow", name: "Animal Fat / Tallow", category: "meats" },
];

export const CROPS: CommodityDef[] = [
  { id: "wheat_grain", name: "Wheat Grain", category: "crops" },
  { id: "rice_paddy", name: "Rice (Paddy)", category: "crops" },
  { id: "corn_maize", name: "Corn / Maize", category: "crops" },
  { id: "barley", name: "Barley", category: "crops" },
  { id: "soybeans", name: "Soybeans", category: "crops" },
  { id: "potatoes", name: "Potatoes", category: "crops" },
  { id: "sweet_potatoes", name: "Sweet Potatoes", category: "crops" },
  { id: "tomatoes", name: "Tomatoes", category: "crops" },
  { id: "onions", name: "Onions", category: "crops" },
  { id: "carrots", name: "Carrots", category: "crops" },
  { id: "cabbage", name: "Cabbage", category: "crops" },
  { id: "lettuce_greens", name: "Lettuce & Greens", category: "crops" },
  { id: "beans_lentils", name: "Beans & Lentils", category: "crops" },
  { id: "peppers", name: "Peppers (Mixed)", category: "crops" },
  { id: "mushrooms", name: "Mushrooms", category: "crops" },
  { id: "apples", name: "Apples", category: "crops" },
  { id: "citrus_fruits", name: "Citrus Fruits", category: "crops" },
  { id: "bananas", name: "Bananas", category: "crops" },
  { id: "berries_mixed", name: "Berries (Mixed)", category: "crops" },
  { id: "grapes", name: "Grapes", category: "crops" },
  { id: "hydroponic_greens", name: "Hydroponic Greens", category: "crops" },
  { id: "algae_biomass", name: "Algae Biomass", category: "crops" },
  { id: "cotton_raw", name: "Raw Cotton", category: "crops" },
  { id: "tobacco_leaf", name: "Tobacco Leaf", category: "crops" },
  { id: "sugar_cane", name: "Sugar Cane", category: "crops" },
];

export const WATER: CommodityDef[] = [
  { id: "fresh_water_bulk", name: "Fresh Water (Bulk Tanks)", category: "water" },
  { id: "purified_water", name: "Purified Water", category: "water" },
  { id: "recycled_water", name: "Recycled Water", category: "water" },
  { id: "distilled_water", name: "Distilled Water", category: "water" },
  { id: "industrial_water", name: "Industrial Process Water", category: "water" },
  { id: "bottled_water", name: "Bottled Water (Consumer)", category: "water" },
  { id: "desalinated_water", name: "Desalinated Water", category: "water" },
  { id: "irrigation_water", name: "Irrigation Water", category: "water" },
  { id: "cooling_water", name: "Cooling Tower Water", category: "water" },
  { id: "ice_blocks", name: "Ice Blocks", category: "water" },
];

export const PHARMACEUTICALS: CommodityDef[] = [
  { id: "antibiotics", name: "Antibiotics (Generic)", category: "pharmaceuticals" },
  { id: "painkillers", name: "Painkillers / Analgesics", category: "pharmaceuticals" },
  { id: "anti_inflammatory", name: "Anti-Inflammatory Drugs", category: "pharmaceuticals" },
  { id: "vaccines", name: "Vaccines (Assorted)", category: "pharmaceuticals" },
  { id: "antivirals", name: "Antiviral Medications", category: "pharmaceuticals" },
  { id: "stimulants_medical", name: "Medical Stimulants", category: "pharmaceuticals" },
  { id: "sedatives", name: "Sedatives / Tranquilizers", category: "pharmaceuticals" },
  { id: "anesthetics", name: "Anesthetics", category: "pharmaceuticals" },
  { id: "blood_plasma", name: "Blood Plasma", category: "pharmaceuticals" },
  { id: "insulin", name: "Insulin", category: "pharmaceuticals" },
  { id: "surgical_supplies", name: "Surgical Supplies", category: "pharmaceuticals" },
  { id: "bandages_dressings", name: "Bandages & Dressings", category: "pharmaceuticals" },
  { id: "first_aid_kits", name: "First Aid Kits", category: "pharmaceuticals" },
  { id: "radiation_pills", name: "Anti-Radiation Pills", category: "pharmaceuticals" },
  { id: "immune_boosters", name: "Immune Boosters", category: "pharmaceuticals" },
  { id: "synthetic_organs", name: "Synthetic Organs", category: "pharmaceuticals" },
  { id: "biogel_patches", name: "BioGel Healing Patches", category: "pharmaceuticals" },
  { id: "nano_medical_capsules", name: "Nano-Medical Capsules", category: "pharmaceuticals" },
  { id: "combat_stims", name: "Combat Stimulants", category: "pharmaceuticals" },
  { id: "detox_compounds", name: "Detox Compounds", category: "pharmaceuticals" },
];

export const CLOTHING: CommodityDef[] = [
  { id: "civilian_clothing", name: "Civilian Clothing (Bulk)", category: "clothing" },
  { id: "work_uniforms", name: "Work Uniforms", category: "clothing" },
  { id: "enforcement_uniforms", name: "Enforcement Uniforms", category: "clothing" },
  { id: "military_fatigues", name: "Military Fatigues", category: "clothing" },
  { id: "protective_coveralls", name: "Protective Coveralls", category: "clothing" },
  { id: "thermal_jackets", name: "Thermal Jackets", category: "clothing" },
  { id: "rain_gear", name: "Rain Gear", category: "clothing" },
  { id: "boots_standard", name: "Boots (Standard Issue)", category: "clothing" },
  { id: "boots_tactical", name: "Boots (Tactical)", category: "clothing" },
  { id: "gloves_work", name: "Work Gloves", category: "clothing" },
  { id: "gloves_tactical", name: "Tactical Gloves", category: "clothing" },
  { id: "body_armor_light", name: "Body Armor (Light)", category: "clothing" },
  { id: "body_armor_heavy", name: "Body Armor (Heavy)", category: "clothing" },
  { id: "helmets_standard", name: "Helmets (Standard)", category: "clothing" },
  { id: "helmets_riot", name: "Helmets (Riot)", category: "clothing" },
  { id: "gas_masks", name: "Gas Masks", category: "clothing" },
  { id: "hazmat_suits", name: "Hazmat Suits", category: "clothing" },
  { id: "radiation_suits", name: "Radiation Suits", category: "clothing" },
  { id: "textile_bolts", name: "Textile Bolts (Raw Fabric)", category: "clothing" },
  { id: "synthetic_leather", name: "Synthetic Leather", category: "clothing" },
];

export const CONSUMER_GOODS: CommodityDef[] = [
  { id: "household_appliances", name: "Household Appliances", category: "consumerGoods" },
  { id: "kitchen_appliances", name: "Kitchen Appliances", category: "consumerGoods" },
  { id: "personal_electronics", name: "Personal Electronics", category: "consumerGoods" },
  { id: "communication_devices", name: "Communication Devices", category: "consumerGoods" },
  { id: "mobile_data_terminals", name: "Mobile Data Terminals", category: "consumerGoods" },
  { id: "household_furniture", name: "Household Furniture", category: "consumerGoods" },
  { id: "mattresses_bedding", name: "Mattresses & Bedding", category: "consumerGoods" },
  { id: "lighting_fixtures", name: "Lighting Fixtures", category: "consumerGoods" },
  { id: "cleaning_products", name: "Cleaning Products", category: "consumerGoods" },
  { id: "personal_hygiene", name: "Personal Hygiene Products", category: "consumerGoods" },
  { id: "toys_games", name: "Toys & Games", category: "consumerGoods" },
  { id: "books_media", name: "Books & Media", category: "consumerGoods" },
  { id: "cooking_utensils", name: "Cooking Utensils", category: "consumerGoods" },
  { id: "personal_tools", name: "Personal Tools", category: "consumerGoods" },
  { id: "water_filters", name: "Water Filters", category: "consumerGoods" },
  { id: "portable_heaters", name: "Portable Heaters", category: "consumerGoods" },
  { id: "portable_fans", name: "Portable Fans / Coolers", category: "consumerGoods" },
  { id: "personal_defense_devices", name: "Personal Defense Devices", category: "consumerGoods" },
  { id: "civic_id_cards", name: "Civic ID Cards", category: "consumerGoods" },
  { id: "food_containers", name: "Food Storage Containers", category: "consumerGoods" },
  { id: "packaged_meals", name: "Packaged Meals", category: "consumerGoods" },
  { id: "bottled_drinking_water", name: "Bottled Drinking Water", category: "consumerGoods" },
  { id: "energy_drinks", name: "Energy Drinks", category: "consumerGoods" },
  { id: "processed_snack_foods", name: "Processed Snack Foods", category: "consumerGoods" },
  { id: "synthetic_protein_bars", name: "Synthetic Protein Bars", category: "consumerGoods" },
  { id: "luxury_chocolates", name: "Luxury Chocolates", category: "consumerGoods" },
  { id: "street_food_packs", name: "Street Food Packs", category: "consumerGoods" },
  { id: "designer_clothing", name: "Designer Clothing", category: "consumerGoods" },
  { id: "casual_clothing", name: "Casual Clothing", category: "consumerGoods" },
  { id: "footwear", name: "Footwear", category: "consumerGoods" },
  { id: "soap_cleaning_supplies", name: "Soap & Cleaning Supplies", category: "consumerGoods" },
  { id: "portable_electronics", name: "Portable Electronics", category: "consumerGoods" },
  { id: "communication_tablets", name: "Communication Tablets", category: "consumerGoods" },
  { id: "personal_data_devices", name: "Personal Data Devices", category: "consumerGoods" },
  { id: "home_entertainment_systems", name: "Home Entertainment Systems", category: "consumerGoods" },
  { id: "digital_media_subscriptions", name: "Digital Media Subscriptions", category: "consumerGoods" },
  { id: "decorative_furniture", name: "Decorative Furniture", category: "consumerGoods" },
  { id: "home_lighting_fixtures", name: "Home Lighting Fixtures", category: "consumerGoods" },
  { id: "household_tools", name: "Household Tools", category: "consumerGoods" },
  { id: "smart_home_devices", name: "Smart Home Devices", category: "consumerGoods" },
  { id: "medical_first_aid_kits", name: "Medical First-Aid Kits", category: "consumerGoods" },
  { id: "recreation_equipment", name: "Recreation Equipment", category: "consumerGoods" },
  { id: "standard_work_uniforms", name: "Standard Work Uniforms", category: "consumerGoods" },
  { id: "personal_hygiene_kits", name: "Personal Hygiene Kits", category: "consumerGoods" },
  { id: "consumer_electronics_bundle", name: "Consumer Electronics Bundle", category: "consumerGoods" },
];

export const PARTS: CommodityDef[] = [
  { id: "bearings_industrial", name: "Industrial Bearings", category: "parts" },
  { id: "gears_assorted", name: "Gears (Assorted)", category: "parts" },
  { id: "valves_industrial", name: "Industrial Valves", category: "parts" },
  { id: "pressure_valves", name: "Pressure Relief Valves", category: "parts" },
  { id: "pumps_small", name: "Small Pumps", category: "parts" },
  { id: "pumps_industrial", name: "Industrial Pumps", category: "parts" },
  { id: "springs_industrial", name: "Industrial Springs", category: "parts" },
  { id: "fasteners_bolts", name: "Fasteners: Bolts & Nuts", category: "parts" },
  { id: "fasteners_screws", name: "Fasteners: Screws & Nails", category: "parts" },
  { id: "fasteners_rivets", name: "Fasteners: Rivets", category: "parts" },
  { id: "hinges_latches", name: "Hinges & Latches", category: "parts" },
  { id: "gaskets_seals", name: "Gaskets & Seals", category: "parts" },
  { id: "filters_industrial", name: "Industrial Filters", category: "parts" },
  { id: "hydraulic_cylinders", name: "Hydraulic Cylinders", category: "parts" },
  { id: "pneumatic_actuators", name: "Pneumatic Actuators", category: "parts" },
  { id: "drive_belts", name: "Drive Belts", category: "parts" },
  { id: "drive_chains", name: "Drive Chains", category: "parts" },
  { id: "couplings_fittings", name: "Couplings & Pipe Fittings", category: "parts" },
  { id: "brake_pads", name: "Brake Pads", category: "parts" },
  { id: "spark_plugs", name: "Spark Plugs", category: "parts" },
  { id: "engine_pistons", name: "Engine Pistons", category: "parts" },
  { id: "crankshafts", name: "Crankshafts", category: "parts" },
  { id: "radiator_cores", name: "Radiator Cores", category: "parts" },
  { id: "exhaust_manifolds", name: "Exhaust Manifolds", category: "parts" },
  { id: "drone_components", name: "Drone Components", category: "parts" },
  { id: "droid_chassis", name: "Droid Chassis Frame", category: "parts" },
  { id: "droid_actuator", name: "Droid Servo Actuator", category: "parts" },
  { id: "droid_ai_core", name: "Droid AI Processing Core", category: "parts" },
  { id: "droid_sensor_array", name: "Droid Sensor Array", category: "parts" },
  { id: "droid_power_cell", name: "Droid Power Cell", category: "parts" },
  { id: "droid_armor_plating", name: "Droid Armor Plating", category: "parts" },
  { id: "droid_mobility_module", name: "Droid Mobility Module", category: "parts" },
  { id: "droid_comms_unit", name: "Droid Comms Transceiver", category: "parts" },
  { id: "droid_tool_attachment", name: "Droid Tool Attachment", category: "parts" },
  { id: "droid_weapon_mount", name: "Droid Weapon Mount", category: "parts" },
  { id: "circuit_board", name: "Circuit Board", category: "parts" },
  { id: "mechanical_part", name: "Mechanical Part", category: "parts" },
  { id: "power_cable", name: "Power Cable", category: "parts" },
  { id: "utility_pipe", name: "Utility Pipe", category: "parts" },
  { id: "smart_circuitry", name: "Smart Circuitry", category: "parts" },
];

export const INDUSTRIAL_GOODS: CommodityDef[] = [
  { id: "diesel_generators", name: "Diesel Generators", category: "industrialGoods" },
  { id: "electric_generators", name: "Electric Generators", category: "industrialGoods" },
  { id: "air_compressors", name: "Air Compressors", category: "industrialGoods" },
  { id: "welding_equipment", name: "Welding Equipment", category: "industrialGoods" },
  { id: "lathe_machines", name: "Lathe Machines", category: "industrialGoods" },
  { id: "cnc_machines", name: "CNC Machines", category: "industrialGoods" },
  { id: "hydraulic_presses", name: "Hydraulic Presses", category: "industrialGoods" },
  { id: "conveyor_systems", name: "Conveyor Systems", category: "industrialGoods" },
  { id: "industrial_furnaces", name: "Industrial Furnaces", category: "industrialGoods" },
  { id: "smelting_equipment", name: "Smelting Equipment", category: "industrialGoods" },
  { id: "mining_drills", name: "Mining Drills", category: "industrialGoods" },
  { id: "excavation_equipment", name: "Excavation Equipment", category: "industrialGoods" },
  { id: "cranes_hoists", name: "Cranes & Hoists", category: "industrialGoods" },
  { id: "forklifts", name: "Forklifts", category: "industrialGoods" },
  { id: "industrial_robots", name: "Industrial Robots", category: "industrialGoods" },
  { id: "automated_assembly_lines", name: "Automated Assembly Lines", category: "industrialGoods" },
  { id: "water_purification_systems", name: "Water Purification Systems", category: "industrialGoods" },
  { id: "air_filtration_systems", name: "Air Filtration Systems", category: "industrialGoods" },
  { id: "refrigeration_units", name: "Refrigeration Units", category: "industrialGoods" },
  { id: "cargo_containers", name: "Cargo Containers", category: "industrialGoods" },
  { id: "processing_machines", name: "Processing Machines", category: "industrialGoods" },
  { id: "laboratory_instruments", name: "Laboratory Instruments", category: "industrialGoods" },
  { id: "medical_equipment", name: "Medical Equipment", category: "industrialGoods" },
  { id: "data_servers", name: "Data Servers", category: "industrialGoods" },
  { id: "transport_vehicles", name: "Transport Vehicles", category: "industrialGoods" },
  { id: "structural_steel_beams_hd", name: "Heavy-Duty Structural Beams", category: "industrialGoods" },
  { id: "reinforced_concrete_panels", name: "Reinforced Concrete Panels", category: "industrialGoods" },
  { id: "industrial_glass_sheets", name: "Industrial Glass Sheets", category: "industrialGoods" },
  { id: "composite_construction_panels", name: "Composite Construction Panels", category: "industrialGoods" },
  { id: "high_strength_fasteners", name: "High-Strength Fasteners", category: "industrialGoods" },
  { id: "industrial_bearings_hd", name: "Heavy-Duty Industrial Bearings", category: "industrialGoods" },
  { id: "hydraulic_systems", name: "Hydraulic Systems", category: "industrialGoods" },
  { id: "electric_motors", name: "Electric Motors", category: "industrialGoods" },
  { id: "industrial_pumps_hd", name: "Heavy-Duty Industrial Pumps", category: "industrialGoods" },
  { id: "power_transformers", name: "Power Transformers", category: "industrialGoods" },
  { id: "fiber_optic_trunk_cable", name: "Fiber-Optic Trunk Cable", category: "industrialGoods" },
  { id: "control_circuit_boards", name: "Control Circuit Boards", category: "industrialGoods" },
  { id: "industrial_microprocessors", name: "Industrial Microprocessors", category: "industrialGoods" },
  { id: "robotics_actuators", name: "Robotics Actuators", category: "industrialGoods" },
  { id: "industrial_sensors", name: "Industrial Sensors", category: "industrialGoods" },
  { id: "precision_machine_tools", name: "Precision Machine Tools", category: "industrialGoods" },
  { id: "assembly_line_components", name: "Assembly Line Components", category: "industrialGoods" },
  { id: "construction_machinery_parts", name: "Construction Machinery Parts", category: "industrialGoods" },
  { id: "drone_propulsion_units", name: "Drone Propulsion Units", category: "industrialGoods" },
  { id: "heavy_equipment_engines", name: "Heavy Equipment Engines", category: "industrialGoods" },
  { id: "advanced_battery_packs", name: "Advanced Battery Packs", category: "industrialGoods" },
  { id: "reactor_control_rods", name: "Reactor Control Rods", category: "industrialGoods" },
  { id: "satellite_structural_frames", name: "Satellite Structural Frames", category: "industrialGoods" },
  { id: "rocket_engine_components", name: "Rocket Engine Components", category: "industrialGoods" },
  { id: "orbital_habitat_modules", name: "Orbital Habitat Modules", category: "industrialGoods" },
  { id: "consumer_electronics", name: "Consumer Electronics", category: "industrialGoods" },
  { id: "industrial_plastic", name: "Industrial Plastic", category: "industrialGoods" },
  { id: "composite_armor_plate", name: "Composite Armor Plate", category: "industrialGoods" },
  { id: "nano_material", name: "Nano-Material", category: "industrialGoods" },
  { id: "naphtha", name: "Naphtha (Light Distillate)", category: "industrialGoods" },
  { id: "chemical_feedstock", name: "Chemical Feedstock", category: "industrialGoods" },
  { id: "syngas", name: "Synthesis Gas", category: "industrialGoods" },
  { id: "industrial_solvent", name: "Industrial Solvent", category: "industrialGoods" },
  { id: "epoxy_resin", name: "Epoxy Resin", category: "industrialGoods" },
  { id: "industrial_adhesive", name: "Industrial Adhesive", category: "industrialGoods" },
  { id: "water_treatment_chemical", name: "Water Treatment Chemical", category: "industrialGoods" },
  { id: "industrial_paint", name: "Industrial Paint", category: "industrialGoods" },
  { id: "machine_lubricant", name: "Machine Lubricant", category: "industrialGoods" },
  { id: "hydraulic_fluid", name: "Hydraulic Fluid", category: "industrialGoods" },
  { id: "chemical_fertilizer", name: "Chemical Fertilizer (NPK)", category: "industrialGoods" },
  { id: "explosive_compounds", name: "Explosive Compounds", category: "industrialGoods" },
  { id: "gravel_aggregate", name: "Gravel Aggregate", category: "industrialGoods" },
  { id: "processed_timber", name: "Processed Timber", category: "industrialGoods" },
  { id: "sawdust", name: "Sawdust & Shavings", category: "industrialGoods" },
  { id: "industrial_salt", name: "Industrial Salt", category: "industrialGoods" },
  { id: "refined_rare_earth", name: "Refined Rare Earth Elements", category: "industrialGoods" },
  { id: "lithium_refined", name: "Refined Lithium", category: "industrialGoods" },
  { id: "glass_sheet", name: "Glass Sheet", category: "industrialGoods" },
  { id: "plastic_pipe_stock", name: "Plastic Pipe Stock", category: "industrialGoods" },
  { id: "moulded_plastic_goods", name: "Moulded Plastic Goods", category: "industrialGoods" },
  { id: "plastic_housings", name: "Plastic Housings", category: "industrialGoods" },
  { id: "synthetic_rubber", name: "Synthetic Rubber", category: "industrialGoods" },
  { id: "carbon_fiber_raw", name: "Carbon Fibre (Raw)", category: "industrialGoods" },
  { id: "foam_insulation", name: "Foam Insulation", category: "industrialGoods" },
  { id: "packaging_foam", name: "Packaging Foam", category: "industrialGoods" },
  { id: "bio_polymer", name: "Bio-Polymer", category: "industrialGoods" },
  { id: "print_filament", name: "3D Print Filament", category: "industrialGoods" },
  { id: "pipe_fittings", name: "Pipe Fittings", category: "industrialGoods" },
  { id: "polycarbonate_panel", name: "Polycarbonate Panel", category: "industrialGoods" },
  { id: "consumer_goods_pack", name: "Consumer Goods Pack", category: "industrialGoods" },
  { id: "vehicle_chassis", name: "Vehicle Chassis", category: "industrialGoods" },
  { id: "furniture_units", name: "Furniture Units", category: "industrialGoods" },
  { id: "finished_clothing", name: "Finished Clothing", category: "industrialGoods" },
  { id: "precision_tooling", name: "Precision Tooling", category: "industrialGoods" },
  { id: "industrial_dies", name: "Industrial Dies", category: "industrialGoods" },
  { id: "packaging_materials", name: "Packaging Materials", category: "industrialGoods" },
  { id: "ceramic_components", name: "Ceramic Components", category: "industrialGoods" },
  { id: "medical_instruments", name: "Medical Instruments", category: "industrialGoods" },
  { id: "nano_coating", name: "Nano-Coating", category: "industrialGoods" },
  { id: "smart_alloy", name: "Smart Alloy", category: "industrialGoods" },
  { id: "superconductor_wire", name: "Superconductor Wire", category: "industrialGoods" },
  { id: "ceramic_composite", name: "Ceramic Matrix Composite", category: "industrialGoods" },
  { id: "aerospace_titanium_part", name: "Aerospace Titanium Part", category: "industrialGoods" },
  { id: "quantum_dots", name: "Quantum Dots", category: "industrialGoods" },
  { id: "industrial_diamond", name: "Industrial Diamond", category: "industrialGoods" },
];

export const ENERGY: CommodityDef[] = [
  { id: "power_cells", name: "Power Cells", category: "energy" },
  { id: "batteries_standard", name: "Batteries (Standard)", category: "energy" },
  { id: "batteries_lithium", name: "Lithium-Ion Batteries", category: "energy" },
  { id: "batteries_advanced", name: "Advanced High-Density Batteries", category: "energy" },
  { id: "fuel_cells_hydrogen", name: "Hydrogen Fuel Cells", category: "energy" },
  { id: "fuel_rods_nuclear", name: "Nuclear Fuel Rods", category: "energy" },
  { id: "refined_fuel", name: "Refined Fuel (Petroleum)", category: "energy" },
  { id: "diesel_fuel", name: "Diesel Fuel", category: "energy" },
  { id: "aviation_fuel", name: "Aviation Fuel", category: "energy" },
  { id: "synthetic_fuel", name: "Synthetic Fuel", category: "energy" },
  { id: "solar_panels", name: "Solar Panels", category: "energy" },
  { id: "solar_cells", name: "Solar Cells", category: "energy" },
  { id: "wind_turbine_blades", name: "Wind Turbine Blades", category: "energy" },
  { id: "portable_generators", name: "Portable Generators", category: "energy" },
  { id: "power_converters", name: "Power Converters", category: "energy" },
  { id: "power_conduits", name: "Power Conduits", category: "energy" },
  { id: "superconductor_wire", name: "Superconductor Wire", category: "energy" },
  { id: "energy_storage_modules", name: "Energy Storage Modules", category: "energy" },
  { id: "smart_grid_hardware", name: "Smart Grid Hardware", category: "energy" },
  { id: "high_density_energy_cells", name: "High-Density Energy Cells", category: "energy" },
  { id: "fuel_gas", name: "Fuel Gas", category: "energy" },
  { id: "biomass", name: "Biomass", category: "energy" },
];

export const CONSTRUCTION: CommodityDef[] = [
  { id: "cement_bags", name: "Cement (Bags)", category: "construction" },
  { id: "concrete_mixed", name: "Concrete (Pre-Mixed)", category: "construction" },
  { id: "reinforced_concrete", name: "Reinforced Concrete", category: "construction" },
  { id: "rebar", name: "Rebar (Reinforcing Bar)", category: "construction" },
  { id: "bricks", name: "Bricks", category: "construction" },
  { id: "cinder_blocks", name: "Cinder Blocks", category: "construction" },
  { id: "timber_beams", name: "Timber Beams", category: "construction" },
  { id: "plywood_sheets", name: "Plywood Sheets", category: "construction" },
  { id: "drywall_panels", name: "Drywall Panels", category: "construction" },
  { id: "roofing_tiles", name: "Roofing Tiles", category: "construction" },
  { id: "glass_panels", name: "Glass Panels", category: "construction" },
  { id: "insulation_rolls", name: "Insulation Rolls", category: "construction" },
  { id: "ceramic_tiles", name: "Ceramic Tiles", category: "construction" },
  { id: "asphalt", name: "Asphalt", category: "construction" },
  { id: "grout_mortar", name: "Grout & Mortar", category: "construction" },
  { id: "construction_panels", name: "Construction Panels (Prefab)", category: "construction" },
  { id: "structural_frames", name: "Structural Frames", category: "construction" },
  { id: "scaffolding", name: "Scaffolding", category: "construction" },
  { id: "waterproof_membrane", name: "Waterproof Membrane", category: "construction" },
  { id: "self_healing_concrete", name: "Self-Healing Concrete", category: "construction" },
  { id: "concrete_mix", name: "Concrete Mix", category: "construction" },
  { id: "structural_beam", name: "Structural Beam", category: "construction" },
  { id: "construction_supply_kit", name: "Construction Supply Kit", category: "construction" },
  { id: "silicon_wafer", name: "Silicon Wafer", category: "construction" },
];

export const LIVESTOCK: CommodityDef[] = [
  { id: "cattle_herds", name: "Cattle Herds", category: "livestock" },
  { id: "dairy_cattle", name: "Dairy Cattle", category: "livestock" },
  { id: "poultry_flocks", name: "Poultry Flocks", category: "livestock" },
  { id: "pork_stocks", name: "Pork Stocks", category: "livestock" },
  { id: "sheep_wool_flocks", name: "Sheep & Wool Flocks", category: "livestock" },
  { id: "goat_herds", name: "Goat Herds", category: "livestock" },
  { id: "fish_farm_stocks", name: "Fish Farm Stocks", category: "livestock" },
  { id: "insect_protein_farms", name: "Insect Protein Farms", category: "livestock" },
  { id: "synthetic_meat_vats", name: "Synthetic Meat Vats", category: "livestock" },
  { id: "dairy_production_units", name: "Dairy Production Units", category: "livestock" },
  { id: "egg_production_units", name: "Egg Production Units", category: "livestock" },
  { id: "honey_bee_colonies", name: "Honey Bee Colonies", category: "livestock" },
];

export const SPACE_COMMODITIES: CommodityDef[] = [
  { id: "orbital_fuel_cells", name: "Orbital Fuel Cells", category: "spaceCommodity" },
  { id: "zero_g_alloys", name: "Zero-G Alloys", category: "spaceCommodity" },
  { id: "radiation_shielding_plates", name: "Radiation Shielding Plates", category: "spaceCommodity" },
  { id: "life_support_cartridges", name: "Life Support Cartridges", category: "spaceCommodity" },
  { id: "orbital_construction_beams", name: "Orbital Construction Beams", category: "spaceCommodity" },
  { id: "satellite_components", name: "Satellite Components", category: "spaceCommodity" },
  { id: "vacuum_sealant_compounds", name: "Vacuum Sealant Compounds", category: "spaceCommodity" },
  { id: "microgravity_pharmaceuticals", name: "Microgravity Pharmaceuticals", category: "spaceCommodity" },
  { id: "solar_panel_arrays", name: "Solar Panel Arrays", category: "spaceCommodity" },
  { id: "docking_clamp_assemblies", name: "Docking Clamp Assemblies", category: "spaceCommodity" },
  { id: "space_suit_components", name: "Space Suit Components", category: "spaceCommodity" },
  { id: "thruster_nozzles", name: "Thruster Nozzles", category: "spaceCommodity" },
];

export const FARMING_DROPS: CommodityDef[] = [
  { id: "mutant_flora", name: "Mutant Flora", category: "farming" },
  { id: "fungal_spores", name: "Fungal Spores", category: "farming" },
  { id: "rad_crystal", name: "Rad-Crystal", category: "farming" },
  { id: "synth_protein", name: "Synth Protein", category: "farming" },
  { id: "bio_toxin", name: "Bio-Toxin Extract", category: "farming" },
  { id: "deep_root_fiber", name: "Deep Root Fiber", category: "farming" },
  { id: "waste_algae", name: "Waste Algae", category: "farming" },
  { id: "insect_protein", name: "Insect Protein", category: "farming" },
  { id: "mineral_sediment", name: "Mineral Sediment", category: "farming" },
  { id: "biolumen_extract", name: "Biolumen Extract", category: "farming" },
  { id: "ferment_sludge", name: "Ferment Sludge", category: "farming" },
  { id: "urban_pollen", name: "Urban Pollen", category: "farming" },
  { id: "chiton_shell", name: "Chiton Shell", category: "farming" },
  { id: "synth_mold", name: "Synth Mold", category: "farming" },
  { id: "bioresin", name: "Bioresin", category: "farming" },
  { id: "electric_organ", name: "Electric Organ", category: "farming" },
  { id: "cave_mushroom", name: "Cave Mushroom", category: "farming" },
  { id: "hybrid_seed", name: "Hybrid Seed", category: "farming" },
  { id: "synth_venom", name: "Synth Venom", category: "farming" },
  { id: "petrified_wood", name: "Petrified Wood", category: "farming" },
  { id: "refined_bioresin", name: "Refined Bioresin", category: "farming" },
  { id: "chiton_plating", name: "Chiton Plating", category: "farming" },
  { id: "rad_crystal_lens", name: "Rad-Crystal Lens", category: "farming" },
  { id: "bio_stimulant", name: "Bio-Stimulant", category: "farming" },
  { id: "luminous_dye", name: "Luminous Dye", category: "farming" },
  { id: "mutant_fiber_weave", name: "Mutant Fiber Weave", category: "farming" },
];

export const CYBERNETICS: CommodityDef[] = [
  { id: "neural_processing_chips", name: "Neural Processing Chips", category: "cybernetics" },
  { id: "optical_sensor_arrays", name: "Optical Sensor Arrays", category: "cybernetics" },
  { id: "synthetic_muscle_fiber", name: "Synthetic Muscle Fiber", category: "cybernetics" },
  { id: "cyber_servo_motors", name: "Cyber Servo Motors", category: "cybernetics" },
  { id: "bio_compatible_titanium", name: "Bio-Compatible Titanium", category: "cybernetics" },
  { id: "neural_interface_cables", name: "Neural Interface Cables", category: "cybernetics" },
  { id: "cybernetic_power_cells", name: "Cybernetic Power Cells", category: "cybernetics" },
  { id: "nano_surgical_tools", name: "Nano-Surgical Tools", category: "cybernetics" },
  { id: "implant_grade_polymers", name: "Implant-Grade Polymers", category: "cybernetics" },
  { id: "dermal_armor_weave", name: "Dermal Armor Weave", category: "cybernetics" },
  { id: "reflex_enhancer_chips", name: "Reflex Enhancer Chips", category: "cybernetics" },
  { id: "memory_core_modules", name: "Memory Core Modules", category: "cybernetics" },
  { id: "bioelectric_regulators", name: "Bioelectric Regulators", category: "cybernetics" },
  { id: "synthetic_nerve_bundles", name: "Synthetic Nerve Bundles", category: "cybernetics" },
  { id: "micro_hydraulic_pistons", name: "Micro-Hydraulic Pistons", category: "cybernetics" },
  { id: "cyber_joint_assemblies", name: "Cyber Joint Assemblies", category: "cybernetics" },
  { id: "cortical_processor_units", name: "Cortical Processor Units", category: "cybernetics" },
  { id: "cyber_eye_lenses", name: "Cyber-Eye Lenses", category: "cybernetics" },
  { id: "augment_calibration_kits", name: "Augment Calibration Kits", category: "cybernetics" },
  { id: "nanite_repair_solution", name: "Nanite Repair Solution", category: "cybernetics" },
  { id: "implant_rejection_meds", name: "Implant Rejection Suppressants", category: "cybernetics" },
  { id: "cyber_limb_frames", name: "Cyber-Limb Frames", category: "cybernetics" },
  { id: "weapons_grade_servos", name: "Weapons-Grade Servos", category: "cybernetics" },
  { id: "stealth_coating_compound", name: "Stealth Coating Compound", category: "cybernetics" },
  { id: "bio_neural_gel", name: "Bio-Neural Gel", category: "cybernetics" },
  { id: "quantum_co_processor", name: "Quantum Co-Processor", category: "cybernetics" },
  { id: "reactive_armor_tiles", name: "Reactive Armor Tiles", category: "cybernetics" },
  { id: "monowire_filament", name: "Monowire Filament", category: "cybernetics" },
  { id: "cyber_grade_coolant", name: "Cyber-Grade Coolant", category: "cybernetics" },
  { id: "black_market_implant_parts", name: "Black Market Implant Parts", category: "cybernetics" },
  { id: "neural_link_interface", name: "Neural Link Interface", category: "cybernetics" },
  { id: "cybernetic_eye_module", name: "Cybernetic Eye Module", category: "cybernetics" },
  { id: "dermal_armor_plating", name: "Dermal Armor Plating", category: "cybernetics" },
  { id: "combat_stimulant_injectors", name: "Combat Stimulant Injectors", category: "cybernetics" },
  { id: "exoskeleton_frame", name: "Exoskeleton Frame", category: "cybernetics" },
  { id: "cyber_prosthetic_limb", name: "Cyber-Prosthetic Limb", category: "cybernetics" },
  { id: "neural_feedback_dampeners", name: "Neural Feedback Dampeners", category: "cybernetics" },
  { id: "targeting_hud_systems", name: "Targeting HUD Systems", category: "cybernetics" },
  { id: "cybernetic_spine_unit", name: "Cybernetic Spine Unit", category: "cybernetics" },
  { id: "ai_co_pilot_module", name: "AI Co-Pilot Module", category: "cybernetics" },
  { id: "nano_repair_swarm", name: "Nano-Repair Swarm", category: "cybernetics" },
];

export const MILITARY: CommodityDef[] = [
  { id: "rifle_assemblies", name: "Rifle Assemblies", category: "military" },
  { id: "sidearm_kits", name: "Sidearm Kits", category: "military" },
  { id: "sniper_components", name: "Sniper Components", category: "military" },
  { id: "shotgun_barrels", name: "Shotgun Barrels", category: "military" },
  { id: "grenade_casings", name: "Grenade Casings", category: "military" },
  { id: "smoke_canisters", name: "Smoke Canisters", category: "military" },
  { id: "flashbang_units", name: "Flashbang Units", category: "military" },
  { id: "tear_gas_rounds", name: "Tear Gas Rounds", category: "military" },
  { id: "stun_batons", name: "Stun Batons", category: "military" },
  { id: "riot_shields", name: "Riot Shields", category: "military" },
  { id: "tactical_vests", name: "Tactical Vests", category: "military" },
  { id: "night_vision_goggles", name: "Night Vision Goggles", category: "military" },
  { id: "thermal_scopes", name: "Thermal Scopes", category: "military" },
  { id: "laser_sights", name: "Laser Sights", category: "military" },
  { id: "ballistic_plates", name: "Ballistic Plates", category: "military" },
  { id: "detonator_caps", name: "Detonator Caps", category: "military" },
  { id: "demolition_charges", name: "Demolition Charges", category: "military" },
  { id: "signal_flares", name: "Signal Flares", category: "military" },
  { id: "field_radios", name: "Field Radios", category: "military" },
  { id: "combat_rations_pack", name: "Combat Rations Pack", category: "military" },
  { id: "field_medical_kits", name: "Field Medical Kits", category: "military" },
  { id: "camouflage_netting", name: "Camouflage Netting", category: "military" },
  { id: "barbed_wire_rolls", name: "Barbed Wire Rolls", category: "military" },
  { id: "sandbag_pallets", name: "Sandbag Pallets", category: "military" },
  { id: "portable_barriers", name: "Portable Barriers", category: "military" },
  { id: "claymore_mines", name: "Claymore Mines", category: "military" },
  { id: "tripwire_alarms", name: "Tripwire Alarms", category: "military" },
  { id: "breaching_charges", name: "Breaching Charges", category: "military" },
  { id: "rappelling_gear", name: "Rappelling Gear", category: "military" },
  { id: "ghillie_suits", name: "Ghillie Suits", category: "military" },
  { id: "ammunition_crate", name: "Ammunition Crate", category: "military" },
  { id: "vehicle_armor_kit", name: "Vehicle Armor Kit", category: "military" },
];

export const TEXTILES: CommodityDef[] = [
  { id: "raw_wool", name: "Raw Wool", category: "textiles" },
  { id: "spun_yarn", name: "Spun Yarn", category: "textiles" },
  { id: "woven_fabric", name: "Woven Fabric", category: "textiles" },
  { id: "dyed_fabric", name: "Dyed Fabric", category: "textiles" },
  { id: "kevlar_fiber", name: "Kevlar Fiber", category: "textiles" },
  { id: "nomex_sheets", name: "Nomex Fire-Resistant Sheets", category: "textiles" },
  { id: "carbon_thread", name: "Carbon Thread", category: "textiles" },
  { id: "nanoweave_cloth", name: "Nanoweave Cloth", category: "textiles" },
  { id: "ballistic_fabric", name: "Ballistic Fabric", category: "textiles" },
  { id: "insulating_felt", name: "Insulating Felt", category: "textiles" },
  { id: "waterproof_canvas", name: "Waterproof Canvas", category: "textiles" },
  { id: "silk_bolts", name: "Silk Bolts", category: "textiles" },
  { id: "recycled_fiber", name: "Recycled Fiber", category: "textiles" },
  { id: "mesh_netting", name: "Mesh Netting", category: "textiles" },
  { id: "elastic_bands", name: "Elastic Bands", category: "textiles" },
  { id: "thread_spools", name: "Thread Spools", category: "textiles" },
  { id: "leather_hides", name: "Leather Hides", category: "textiles" },
  { id: "tanned_leather", name: "Tanned Leather", category: "textiles" },
  { id: "upholstery_fabric", name: "Upholstery Fabric", category: "textiles" },
  { id: "industrial_webbing", name: "Industrial Webbing", category: "textiles" },
];

export const WEAPONRY: CommodityDef[] = [
  { id: "lawgiver_frames", name: "Lawgiver Frames", category: "weaponry" },
  { id: "daystick_shafts", name: "Daystick Shafts", category: "weaponry" },
  { id: "scattergun_parts", name: "Scattergun Parts", category: "weaponry" },
  { id: "stun_pistol_cells", name: "Stun Pistol Cells", category: "weaponry" },
  { id: "hi_ex_rounds", name: "Hi-Ex Rounds", category: "weaponry" },
  { id: "armor_piercing_tips", name: "Armor-Piercing Tips", category: "weaponry" },
  { id: "incendiary_charges", name: "Incendiary Charges", category: "weaponry" },
  { id: "hotshot_laser_packs", name: "Hotshot Laser Packs", category: "weaponry" },
  { id: "gas_grenade_loads", name: "Gas Grenade Loads", category: "weaponry" },
  { id: "stumm_gas_cartridges", name: "Stumm Gas Cartridges", category: "weaponry" },
  { id: "concussion_shells", name: "Concussion Shells", category: "weaponry" },
  { id: "frag_grenade_casings", name: "Frag Grenade Casings", category: "weaponry" },
  { id: "micro_missile_pods", name: "Micro-Missile Pods", category: "weaponry" },
  { id: "railgun_slugs", name: "Railgun Slugs", category: "weaponry" },
  { id: "plasma_cutter_heads", name: "Plasma Cutter Heads", category: "weaponry" },
  { id: "energy_weapon_cores", name: "Energy Weapon Cores", category: "weaponry" },
  { id: "sonic_disruptor_units", name: "Sonic Disruptor Units", category: "weaponry" },
  { id: "emp_grenade_casings", name: "EMP Grenade Casings", category: "weaponry" },
  { id: "melta_fuel_cells", name: "Melta Fuel Cells", category: "weaponry" },
  { id: "suppressor_modules", name: "Suppressor Modules", category: "weaponry" },
  { id: "weapon_optics", name: "Weapon Optics", category: "weaponry" },
  { id: "trigger_mechanisms", name: "Trigger Mechanisms", category: "weaponry" },
  { id: "barrel_blanks", name: "Barrel Blanks", category: "weaponry" },
  { id: "magazine_springs", name: "Magazine Springs", category: "weaponry" },
  { id: "weapon_lubricant", name: "Weapon Lubricant", category: "weaponry" },
  { id: "bayonet_blades", name: "Bayonet Blades", category: "weaponry" },
  { id: "recoil_dampeners", name: "Recoil Dampeners", category: "weaponry" },
  { id: "bore_cleaning_kits", name: "Bore Cleaning Kits", category: "weaponry" },
  { id: "weapon_crates", name: "Weapon Crates", category: "weaponry" },
  { id: "holster_assemblies", name: "Holster Assemblies", category: "weaponry" },
];

export const VEHICLES_COMMODITIES: CommodityDef[] = [
  { id: "engine_blocks", name: "Engine Blocks", category: "vehicles" },
  { id: "transmission_units", name: "Transmission Units", category: "vehicles" },
  { id: "axle_assemblies", name: "Axle Assemblies", category: "vehicles" },
  { id: "wheel_tire_sets", name: "Wheel & Tire Sets", category: "vehicles" },
  { id: "brake_systems", name: "Brake Systems", category: "vehicles" },
  { id: "suspension_kits", name: "Suspension Kits", category: "vehicles" },
  { id: "exhaust_systems", name: "Exhaust Systems", category: "vehicles" },
  { id: "vehicle_electronics", name: "Vehicle Electronics", category: "vehicles" },
  { id: "windshield_panels", name: "Windshield Panels", category: "vehicles" },
  { id: "vehicle_seats", name: "Vehicle Seats", category: "vehicles" },
  { id: "fuel_tanks", name: "Fuel Tanks", category: "vehicles" },
  { id: "radiator_units", name: "Radiator Units", category: "vehicles" },
  { id: "turbocharger_kits", name: "Turbocharger Kits", category: "vehicles" },
  { id: "anti_grav_pods", name: "Anti-Grav Pods", category: "vehicles" },
  { id: "hover_propulsion_units", name: "Hover Propulsion Units", category: "vehicles" },
  { id: "armor_plating_vehicle", name: "Vehicle Armor Plating", category: "vehicles" },
  { id: "turret_mounts", name: "Turret Mounts", category: "vehicles" },
  { id: "patrol_bike_frames", name: "Patrol Bike Frames", category: "vehicles" },
  { id: "apc_hull_sections", name: "APC Hull Sections", category: "vehicles" },
  { id: "gunship_fuselage", name: "Gunship Fuselage Parts", category: "vehicles" },
  { id: "rotor_assemblies", name: "Rotor Assemblies", category: "vehicles" },
  { id: "drone_propeller_sets", name: "Drone Propeller Sets", category: "vehicles" },
  { id: "nav_computer_modules", name: "Nav Computer Modules", category: "vehicles" },
  { id: "ejection_seat_units", name: "Ejection Seat Units", category: "vehicles" },
  { id: "flight_control_systems", name: "Flight Control Systems", category: "vehicles" },
];

export const WASTELAND: CommodityDef[] = [
  { id: "rad_waste", name: "Radioactive Waste", category: "wasteland" },
  { id: "toxic_sludge", name: "Toxic Sludge", category: "wasteland" },
  { id: "mutant_hides", name: "Mutant Hides", category: "wasteland" },
  { id: "cursed_earth_soil", name: "Deadlands Soil", category: "wasteland" },
  { id: "petrified_bone", name: "Petrified Bone", category: "wasteland" },
  { id: "irradiated_water", name: "Irradiated Water", category: "wasteland" },
  { id: "scorch_dust", name: "Scorch Dust", category: "wasteland" },
  { id: "wasteland_fungus", name: "Wasteland Fungus", category: "wasteland" },
  { id: "feral_creature_parts", name: "Feral Creature Parts", category: "wasteland" },
  { id: "storm_debris", name: "Storm Debris", category: "wasteland" },
  { id: "rad_blooms", name: "Rad-Blooms", category: "wasteland" },
  { id: "salvaged_tech_scraps", name: "Salvaged Tech Scraps", category: "wasteland" },
  { id: "contaminated_metal", name: "Contaminated Metal", category: "wasteland" },
  { id: "fossil_amber", name: "Fossil Amber", category: "wasteland" },
  { id: "rad_resistant_seeds", name: "Rad-Resistant Seeds", category: "wasteland" },
  { id: "purified_rad_crystal", name: "Purified Rad-Crystal", category: "wasteland" },
  { id: "wasteland_leather", name: "Wasteland Leather", category: "wasteland" },
  { id: "desert_salt_flats", name: "Desert Salt Flats", category: "wasteland" },
  { id: "ancient_circuit_relics", name: "Ancient Circuit Relics", category: "wasteland" },
  { id: "mutant_venom_glands", name: "Mutant Venom Glands", category: "wasteland" },
];

export const LUXURY: CommodityDef[] = [
  { id: "synthetic_gemstones", name: "Synthetic Gemstones", category: "luxury" },
  { id: "crystal_art_pieces", name: "Crystal Art Pieces", category: "luxury" },
  { id: "holo_artwork", name: "Holo-Artwork", category: "luxury" },
  { id: "vintage_wines", name: "Vintage Wines", category: "luxury" },
  { id: "aged_spirits", name: "Aged Spirits", category: "luxury" },
  { id: "exotic_perfumes", name: "Exotic Perfumes", category: "luxury" },
  { id: "custom_furniture", name: "Custom Furniture", category: "luxury" },
  { id: "rare_antiques", name: "Rare Antiques", category: "luxury" },
  { id: "designer_augments", name: "Designer Augments", category: "luxury" },
  { id: "luxury_food_hampers", name: "Luxury Food Hampers", category: "luxury" },
  { id: "ornamental_metals", name: "Ornamental Metals", category: "luxury" },
  { id: "bespoke_clothing", name: "Bespoke Clothing", category: "luxury" },
  { id: "rare_data_crystals", name: "Rare Data Crystals", category: "luxury" },
  { id: "premium_stim_packs", name: "Premium Stim Packs", category: "luxury" },
  { id: "holographic_jewelry", name: "Holographic Jewelry", category: "luxury" },
  { id: "artisan_chocolates", name: "Artisan Chocolates", category: "luxury" },
  { id: "imported_coffee", name: "Imported Coffee", category: "luxury" },
  { id: "rare_teas", name: "Rare Teas", category: "luxury" },
  { id: "musical_instruments", name: "Musical Instruments", category: "luxury" },
  { id: "collector_memorabilia", name: "Collector Memorabilia", category: "luxury" },
];

export const DATA_MEDIA: CommodityDef[] = [
  { id: "data_slates", name: "Data Slates", category: "dataMedia" },
  { id: "holo_discs", name: "Holo-Discs", category: "dataMedia" },
  { id: "encrypted_data_cores", name: "Encrypted Data Cores", category: "dataMedia" },
  { id: "propaganda_broadcasts", name: "Propaganda Broadcasts", category: "dataMedia" },
  { id: "surveillance_footage", name: "Surveillance Footage Archives", category: "dataMedia" },
  { id: "research_data_packs", name: "Research Data Packs", category: "dataMedia" },
  { id: "mapping_cartridges", name: "Mapping Cartridges", category: "dataMedia" },
  { id: "intelligence_reports", name: "Intelligence Reports", category: "dataMedia" },
  { id: "training_simulations", name: "Training Simulations", category: "dataMedia" },
  { id: "entertainment_media", name: "Entertainment Media", category: "dataMedia" },
  { id: "classified_files", name: "Classified Files", category: "dataMedia" },
  { id: "biometric_databases", name: "Biometric Databases", category: "dataMedia" },
  { id: "criminal_records", name: "Criminal Records Archives", category: "dataMedia" },
  { id: "weather_data_logs", name: "Weather Data Logs", category: "dataMedia" },
  { id: "industrial_blueprints", name: "Industrial Blueprints", category: "dataMedia" },
  { id: "ai_training_datasets", name: "AI Training Datasets", category: "dataMedia" },
  { id: "neural_pattern_backups", name: "Neural Pattern Backups", category: "dataMedia" },
  { id: "genetic_sequence_data", name: "Genetic Sequence Data", category: "dataMedia" },
  { id: "tactical_overlays", name: "Tactical Overlays", category: "dataMedia" },
  { id: "citywide_sensor_logs", name: "Citywide Sensor Logs", category: "dataMedia" },
];

export const BIOTECH: CommodityDef[] = [
  { id: "stem_cell_cultures", name: "Stem Cell Cultures", category: "biotech" },
  { id: "gene_therapy_vials", name: "Gene Therapy Vials", category: "biotech" },
  { id: "cloning_substrate", name: "Cloning Substrate", category: "biotech" },
  { id: "bio_scaffold_sheets", name: "Bio-Scaffold Sheets", category: "biotech" },
  { id: "growth_hormone_vials", name: "Growth Hormone Vials", category: "biotech" },
  { id: "tissue_culture_media", name: "Tissue Culture Media", category: "biotech" },
  { id: "enzyme_concentrates", name: "Enzyme Concentrates", category: "biotech" },
  { id: "bio_reactor_catalysts", name: "Bio-Reactor Catalysts", category: "biotech" },
  { id: "prion_neutralizer", name: "Prion Neutralizer", category: "biotech" },
  { id: "biofilm_cultures", name: "Biofilm Cultures", category: "biotech" },
  { id: "gene_splicing_kits", name: "Gene Splicing Kits", category: "biotech" },
  { id: "synthetic_blood", name: "Synthetic Blood", category: "biotech" },
  { id: "nerve_growth_factor", name: "Nerve Growth Factor", category: "biotech" },
  { id: "lab_grown_skin", name: "Lab-Grown Skin", category: "biotech" },
  { id: "bone_growth_matrix", name: "Bone Growth Matrix", category: "biotech" },
  { id: "bio_adhesive", name: "Bio-Adhesive", category: "biotech" },
  { id: "viral_vectors", name: "Viral Vectors", category: "biotech" },
  { id: "plasmid_libraries", name: "Plasmid Libraries", category: "biotech" },
  { id: "cryo_preservation_fluid", name: "Cryo-Preservation Fluid", category: "biotech" },
  { id: "mutagenic_compounds", name: "Mutagenic Compounds", category: "biotech" },
  { id: "anti_mutagenic_serum", name: "Anti-Mutagenic Serum", category: "biotech" },
  { id: "rad_filter_organisms", name: "Rad-Filter Organisms", category: "biotech" },
  { id: "bio_luminescent_reagent", name: "Bio-Luminescent Reagent", category: "biotech" },
  { id: "protein_folding_templates", name: "Protein Folding Templates", category: "biotech" },
  { id: "microbiome_capsules", name: "Microbiome Capsules", category: "biotech" },
  { id: "organoid_cultures", name: "Organoid Cultures", category: "biotech" },
  { id: "bio_ink_cartridges", name: "Bio-Ink Cartridges", category: "biotech" },
  { id: "telomere_extensions", name: "Telomere Extension Vials", category: "biotech" },
  { id: "synthetic_platelets", name: "Synthetic Platelets", category: "biotech" },
  { id: "immune_booster_sera", name: "Immune Booster Sera", category: "biotech" },
  { id: "neural_stem_cells", name: "Neural Stem Cells", category: "biotech" },
  { id: "bio_scaffold_mesh", name: "Bio-Scaffold Mesh", category: "biotech" },
  { id: "genome_mapping_kits", name: "Genome Mapping Kits", category: "biotech" },
  { id: "synthetic_collagen", name: "Synthetic Collagen", category: "biotech" },
];

const XENOBIOLOGY_COMMODITIES: CommodityDef[] = [
  { id: "mutantSpores", name: "Mutant Spores", category: "xenobiology" },
  { id: "biofilterMedia", name: "Biofilter Media", category: "xenobiology" },
  { id: "xenofaunaPelts", name: "Xenofauna Pelts", category: "xenobiology" },
  { id: "radResistantSeeds", name: "Rad-Resistant Seeds", category: "xenobiology" },
  { id: "bioluminescentGel", name: "Bioluminescent Gel", category: "xenobiology" },
  { id: "decontaminationEnzymes", name: "Decontamination Enzymes", category: "xenobiology" },
  { id: "toxicPollenExtract", name: "Toxic Pollen Extract", category: "xenobiology" },
  { id: "mycorrhizalNetworkNodes", name: "Mycorrhizal Network Nodes", category: "xenobiology" },
  { id: "syntheticEcosystemKits", name: "Synthetic Ecosystem Kits", category: "xenobiology" },
  { id: "geneticArchiveDiscs", name: "Genetic Archive Discs", category: "xenobiology" },
];

const UPLIFT_COMMODITIES: CommodityDef[] = [
  { id: "neuralUpliftChips", name: "Neural Uplift Chips", category: "upliftGoods" },
  { id: "cognitiveEnhancementSerum", name: "Cognitive Enhancement Serum", category: "upliftGoods" },
  { id: "interspeciesTranslators", name: "Interspecies Translators", category: "upliftGoods" },
  { id: "upliftHabitatModules", name: "Uplift Habitat Modules", category: "upliftGoods" },
  { id: "adaptiveToolkits", name: "Adaptive Toolkits", category: "upliftGoods" },
];

const WILDLANDS_COMMODITIES: CommodityDef[] = [
  { id: "wild_meat", name: "Wildlands Meat", category: "meats", basePrice: 18, weight: 1 },
  { id: "wild_hides", name: "Wildlands Hides", category: "wasteland", basePrice: 22, weight: 1 },
  { id: "wildlands_bone_char", name: "Wildlands Bone Char", category: "meats", basePrice: 12, weight: 1 },
  { id: "medicinal_herbs", name: "Medicinal Herbs", category: "crops", basePrice: 26, weight: 1 },
  { id: "wildlands_antitoxin", name: "Wildlands Antitoxin", category: "pharmaceuticals", basePrice: 75, weight: 1 },
  { id: "wild_livestock", name: "Wildlands Livestock", category: "livestock", basePrice: 95, weight: 3 },
  { id: "exotic_pelts", name: "Exotic Pelts", category: "wasteland", basePrice: 140, weight: 1 },
  { id: "ivory_tusks", name: "Ivory Tusks", category: "wasteland", basePrice: 380, weight: 2, contraband: true },
  { id: "alpha_pheromones", name: "Alpha Pheromones", category: "biotech", basePrice: 520, weight: 1, contraband: true },
  { id: "gene_vault_samples", name: "Gene Vault Samples", category: "biotech", basePrice: 1850, weight: 1, contraband: true },
  { id: "wildlands_biomass", name: "Wildlands Biomass", category: "crops", basePrice: 8, weight: 1 },
];

// Some ids appear in more than one category list (e.g. hydraulic_fluid in
// CHEMICALS and INDUSTRIAL_GOODS); dedupe by id keeping the first occurrence
// so UI lists keyed on id never render duplicates.
const RAW_ALL_COMMODITIES: CommodityDef[] = [
  ...RAW_ORE,
  ...METALS,
  ...GASES,
  ...CHEMICALS,
  ...PLASTICS,
  ...ELECTRONICS,
  ...FOODSTUFFS,
  ...MEATS,
  ...CROPS,
  ...WATER,
  ...PHARMACEUTICALS,
  ...CLOTHING,
  ...CONSUMER_GOODS,
  ...PARTS,
  ...INDUSTRIAL_GOODS,
  ...ENERGY,
  ...CONSTRUCTION,
  ...LIVESTOCK,
  ...SPACE_COMMODITIES,
  ...FARMING_DROPS,
  ...CYBERNETICS,
  ...MILITARY,
  ...TEXTILES,
  ...WEAPONRY,
  ...VEHICLES_COMMODITIES,
  ...WASTELAND,
  ...LUXURY,
  ...DATA_MEDIA,
  ...BIOTECH,
  ...SD_COMMODITY_DEFS,
  ...XENOBIOLOGY_COMMODITIES,
  ...UPLIFT_COMMODITIES,
  ...WILDLANDS_COMMODITIES,
];

export const ALL_COMMODITIES: CommodityDef[] = (() => {
  const seen = new Set<string>();
  return RAW_ALL_COMMODITIES.filter((c) => {
    if (seen.has(c.id)) return false;
    seen.add(c.id);
    return true;
  });
})();

export const COMMODITY_CATEGORY_LABELS: Record<CommodityCategory, string> = {
  rawOre: "RAW ORE & MINERALS",
  metals: "METALS & ALLOYS",
  gases: "GASES",
  chemicals: "CHEMICALS",
  plastics: "PLASTICS & POLYMERS",
  electronics: "ELECTRONICS",
  foodstuffs: "FOODSTUFFS",
  meats: "MEATS & PROTEIN",
  crops: "CROPS & PRODUCE",
  water: "WATER",
  pharmaceuticals: "PHARMACEUTICALS",
  clothing: "CLOTHING & GEAR",
  consumerGoods: "CONSUMER GOODS",
  parts: "PARTS & COMPONENTS",
  industrialGoods: "INDUSTRIAL GOODS",
  energy: "ENERGY & FUEL",
  construction: "CONSTRUCTION",
  livestock: "LIVESTOCK",
  spaceCommodity: "SPACE COMMODITIES",
  farming: "FARMING DROPS",
  cybernetics: "CYBERNETICS & IMPLANTS",
  military: "MILITARY SUPPLIES",
  textiles: "TEXTILES & FABRICS",
  weaponry: "WEAPONRY & ORDNANCE",
  vehicles: "VEHICLES & PARTS",
  wasteland: "WASTELAND SALVAGE",
  luxury: "LUXURY GOODS",
  dataMedia: "DATA & MEDIA",
  biotech: "BIOTECH & GENETICS",
  dnaSupplies: "DNA SUPPLIES",
  geneticEquipment: "GENETIC EQUIPMENT",
  cloningMaterials: "CLONING MATERIALS",
  bioProducts: "BIO PRODUCTS",
  geneticMedicine: "GENETIC MEDICINE",
  cloneGoods: "CLONE GOODS",
  researchMaterials: "RESEARCH MATERIALS",
  bioWeapons: "BIO WEAPONS",
  xenobiology: "XENOBIOLOGY",
  upliftGoods: "UPLIFT GOODS",
};
