import type { CompanyDef, CompanyInstance } from "@/engine/types";

export function isCompanyOperational(instance: Pick<CompanyInstance, "status">): boolean {
  return instance.status !== "quarantined";
}

export const COMPANIES: CompanyDef[] = [
  // ── ENERGY ────────────────────────────────────────────────────────────
  {
    id: "helios-grid",
    name: "Helios Grid Authority",
    sector: "energy",
    tier: 2,
    description: "Primary municipal power provider. Manages grid distribution across all sectors.",
    licenseCost: 35000,
    maintenanceCost: 120,
    employment: 12000,
    taxOutput: 420,
    corruptionRisk: 3,
    effects: { power: 120, stability: 2 },
  },
  {
    id: "titan-fusion",
    name: "Titan Fusion Systems",
    sector: "energy",
    tier: 3,
    description: "Cutting-edge fusion reactor construction and operation. Expensive but transformative.",
    licenseCost: 140000,
    maintenanceCost: 400,
    employment: 45000,
    taxOutput: 1600,
    corruptionRisk: 5,
    effects: { power: 450, stability: 4 },
  },
  {
    id: "aurora-solar",
    name: "Aurora Solar Fields",
    sector: "energy",
    tier: 1,
    description: "Rooftop and tower solar array installation across residential zones.",
    licenseCost: 8000,
    maintenanceCost: 40,
    employment: 3500,
    taxOutput: 110,
    corruptionRisk: 1,
    effects: { power: 45, happiness: 1 },
  },
  {
    id: "deepcore-geothermal",
    name: "DeepCore Geothermal Works",
    sector: "energy",
    tier: 2,
    description: "Deep-bore geothermal energy extraction. Stable, reliable, low-emission.",
    licenseCost: 42000,
    maintenanceCost: 140,
    employment: 9000,
    taxOutput: 380,
    corruptionRisk: 2,
    effects: { power: 180, stability: 1 },
  },
  {
    id: "novagrid-power",
    name: "NovaGrid Power Distribution",
    sector: "energy",
    tier: 1,
    description: "Smart distribution network that reduces transmission losses and blackouts.",
    licenseCost: 9500,
    maintenanceCost: 45,
    employment: 4200,
    taxOutput: 130,
    corruptionRisk: 1,
    effects: { power: 55, stability: 2 },
  },
  {
    id: "atlas-energy-storage",
    name: "Atlas Energy Storage",
    sector: "energy",
    tier: 2,
    description: "Mega-battery arrays that buffer peak demand and prevent blackout cascades.",
    licenseCost: 28000,
    maintenanceCost: 90,
    employment: 7000,
    taxOutput: 260,
    corruptionRisk: 2,
    effects: { power: 80, stability: 3 },
  },
  {
    id: "radiant-reactor",
    name: "Radiant Reactor Services",
    sector: "energy",
    tier: 3,
    description: "Full-service nuclear reactor operations and maintenance consortium.",
    licenseCost: 120000,
    maintenanceCost: 350,
    employment: 38000,
    taxOutput: 1300,
    corruptionRisk: 6,
    effects: { power: 400, stability: 2 },
  },
  {
    id: "skyline-power-tx",
    name: "Skyline Power Transmission",
    sector: "energy",
    tier: 1,
    description: "Aerial high-voltage cable networks connecting outlying sectors to the core grid.",
    licenseCost: 6000,
    maintenanceCost: 30,
    employment: 2800,
    taxOutput: 90,
    corruptionRisk: 1,
    effects: { power: 35, stability: 1 },
  },
  {
    id: "dynamo-infra",
    name: "Dynamo Infrastructure Group",
    sector: "energy",
    tier: 2,
    description: "Energy infrastructure engineering and emergency repair specialists.",
    licenseCost: 22000,
    maintenanceCost: 80,
    employment: 8500,
    taxOutput: 280,
    corruptionRisk: 2,
    effects: { power: 90, stability: 3 },
  },
  {
    id: "continuum-power",
    name: "Continuum Power Networks",
    sector: "energy",
    tier: 2,
    description: "AI-optimized power routing that reduces waste and improves district coverage.",
    licenseCost: 30000,
    maintenanceCost: 100,
    employment: 11000,
    taxOutput: 320,
    corruptionRisk: 3,
    effects: { power: 100, stability: 2 },
  },

  // ── WATER ─────────────────────────────────────────────────────────────
  {
    id: "clearflow-water",
    name: "ClearFlow Water Authority",
    sector: "water",
    tier: 2,
    description: "Main municipal water treatment and distribution authority.",
    licenseCost: 32000,
    maintenanceCost: 110,
    employment: 11000,
    taxOutput: 340,
    corruptionRisk: 2,
    effects: { water: 110, happiness: 2 },
  },
  {
    id: "oceangate-desal",
    name: "OceanGate Desalination",
    sector: "water",
    tier: 3,
    description: "Mega-scale seawater desalination. Drought-proofs the sector indefinitely.",
    licenseCost: 150000,
    maintenanceCost: 420,
    employment: 52000,
    taxOutput: 1500,
    corruptionRisk: 4,
    effects: { water: 400, happiness: 3 },
  },
  {
    id: "hydrocycle-recycling",
    name: "HydroCycle Recycling Systems",
    sector: "water",
    tier: 1,
    description: "Grey-water recycling and closed-loop conservation systems for residential blocks.",
    licenseCost: 7500,
    maintenanceCost: 35,
    employment: 3000,
    taxOutput: 100,
    corruptionRisk: 1,
    effects: { water: 50, happiness: 1 },
  },
  {
    id: "bluevault-reservoir",
    name: "BlueVault Reservoir Company",
    sector: "water",
    tier: 2,
    description: "Underground reservoir construction and long-term water banking.",
    licenseCost: 38000,
    maintenanceCost: 130,
    employment: 10000,
    taxOutput: 300,
    corruptionRisk: 2,
    effects: { water: 130, stability: 2 },
  },
  {
    id: "urban-aquifer",
    name: "Urban Aquifer Management",
    sector: "water",
    tier: 1,
    description: "Deep aquifer tapping and pumping operations below the mega-city.",
    licenseCost: 11000,
    maintenanceCost: 50,
    employment: 4000,
    taxOutput: 140,
    corruptionRisk: 2,
    effects: { water: 70, stability: 1 },
  },
  {
    id: "rainharvest-atmos",
    name: "RainHarvest Atmospheric Systems",
    sector: "water",
    tier: 1,
    description: "Atmospheric moisture collection towers deployed across rooftops.",
    licenseCost: 6500,
    maintenanceCost: 28,
    employment: 2500,
    taxOutput: 85,
    corruptionRisk: 1,
    effects: { water: 40, happiness: 1 },
  },
  {
    id: "puritygrid-filtration",
    name: "PurityGrid Filtration Services",
    sector: "water",
    tier: 2,
    description: "Multi-stage nanofiltration plants that eradicate chemical contaminants.",
    licenseCost: 25000,
    maintenanceCost: 85,
    employment: 7500,
    taxOutput: 250,
    corruptionRisk: 2,
    effects: { water: 90, happiness: 2 },
  },
  {
    id: "aquatransit-pipeline",
    name: "AquaTransit Pipeline Works",
    sector: "water",
    tier: 2,
    description: "High-pressure pipeline networks connecting reservoirs to all districts.",
    licenseCost: 29000,
    maintenanceCost: 95,
    employment: 8800,
    taxOutput: 270,
    corruptionRisk: 2,
    effects: { water: 100, stability: 2 },
  },
  {
    id: "cleanwave-env",
    name: "CleanWave Environmental Utility",
    sector: "water",
    tier: 1,
    description: "Environmental remediation and waterway decontamination specialists.",
    licenseCost: 8500,
    maintenanceCost: 38,
    employment: 3200,
    taxOutput: 105,
    corruptionRisk: 1,
    effects: { water: 45, happiness: 2 },
  },
  {
    id: "watertrust-civic",
    name: "WaterTrust Civic Services",
    sector: "water",
    tier: 2,
    description: "Civic water utility providing subsidised supply to low-income sectors.",
    licenseCost: 20000,
    maintenanceCost: 70,
    employment: 6500,
    taxOutput: 200,
    corruptionRisk: 1,
    effects: { water: 80, happiness: 3, stability: 2 },
  },

  // ── FOOD ──────────────────────────────────────────────────────────────
  {
    id: "verticalharvest-corp",
    name: "VerticalHarvest Corporation",
    sector: "food",
    tier: 3,
    description: "Continent-scale vertical farming megaplexes. Feeds millions per facility.",
    licenseCost: 160000,
    maintenanceCost: 450,
    employment: 60000,
    taxOutput: 1800,
    corruptionRisk: 4,
    effects: { food: 350, happiness: 4 },
  },
  {
    id: "nutrientworks-bio",
    name: "NutrientWorks Biofoods",
    sector: "food",
    tier: 2,
    description: "Precision-engineered nutrient paste and meal replacement production.",
    licenseCost: 30000,
    maintenanceCost: 100,
    employment: 10500,
    taxOutput: 320,
    corruptionRisk: 3,
    effects: { food: 110, happiness: 1 },
  },
  {
    id: "urbancrop-hydro",
    name: "UrbanCrop Hydroponics",
    sector: "food",
    tier: 1,
    description: "Block-level hydroponic installation converting waste water into food.",
    licenseCost: 7000,
    maintenanceCost: 32,
    employment: 2800,
    taxOutput: 95,
    corruptionRisk: 1,
    effects: { food: 55, happiness: 2 },
  },
  {
    id: "greentower-agri",
    name: "GreenTower AgriLabs",
    sector: "food",
    tier: 2,
    description: "Research-driven agricultural genetics lab producing high-yield crop strains.",
    licenseCost: 35000,
    maintenanceCost: 115,
    employment: 12000,
    taxOutput: 380,
    corruptionRisk: 2,
    effects: { food: 130, happiness: 2 },
  },
  {
    id: "proteinvat-ind",
    name: "ProteinVat Industries",
    sector: "food",
    tier: 2,
    description: "Cultured meat and protein vat complexes. Efficient, scalable, unappealing.",
    licenseCost: 28000,
    maintenanceCost: 90,
    employment: 9000,
    taxOutput: 280,
    corruptionRisk: 2,
    effects: { food: 100, happiness: -1 },
  },
  {
    id: "metrofarm-coop",
    name: "MetroFarm Cooperative",
    sector: "food",
    tier: 1,
    description: "Citizen-run cooperative farming network in undeveloped city margins.",
    licenseCost: 5000,
    maintenanceCost: 22,
    employment: 5000,
    taxOutput: 70,
    corruptionRisk: 1,
    effects: { food: 45, happiness: 3, stability: 1 },
  },
  {
    id: "synthmeal-processing",
    name: "SynthMeal Processing Group",
    sector: "food",
    tier: 2,
    description: "Industrial synthetic nutrition production and block-level distribution.",
    licenseCost: 27000,
    maintenanceCost: 88,
    employment: 9500,
    taxOutput: 270,
    corruptionRisk: 3,
    effects: { food: 95, happiness: 0 },
  },
  {
    id: "algaecore-nutrition",
    name: "AlgaeCore Nutritional Systems",
    sector: "food",
    tier: 1,
    description: "Algae cultivation tanks producing high-density nutrition supplements.",
    licenseCost: 6500,
    maintenanceCost: 28,
    employment: 2200,
    taxOutput: 88,
    corruptionRisk: 1,
    effects: { food: 42, water: 10 },
  },
  {
    id: "freshstack-logistics",
    name: "FreshStack Produce Logistics",
    sector: "food",
    tier: 1,
    description: "Cold-chain logistics network ensuring food reaches all districts safely.",
    licenseCost: 8000,
    maintenanceCost: 36,
    employment: 4500,
    taxOutput: 110,
    corruptionRisk: 1,
    effects: { food: 30, happiness: 2, trade: 40 },
  },
  {
    id: "civic-food-dist",
    name: "Civic Food Distribution Authority",
    sector: "food",
    tier: 1,
    description: "State-adjacent food distribution to low-income residential blocks.",
    licenseCost: 5500,
    maintenanceCost: 25,
    employment: 3500,
    taxOutput: 75,
    corruptionRisk: 1,
    effects: { food: 35, happiness: 3, stability: 2 },
  },

  // ── CONSTRUCTION ──────────────────────────────────────────────────────
  {
    id: "titanbuild",
    name: "TitanBuild Construction",
    sector: "construction",
    tier: 3,
    description: "The city's largest megastructure builder. Handles everything from mega-blocks to perimeter walls.",
    licenseCost: 130000,
    maintenanceCost: 380,
    employment: 48000,
    taxOutput: 1400,
    corruptionRisk: 6,
    effects: { steel: 80, goods: 40, stability: 3 },
  },
  {
    id: "ironspan-eng",
    name: "IronSpan Engineering",
    sector: "construction",
    tier: 2,
    description: "Structural engineering firm specialising in transit bridges and elevated platforms.",
    licenseCost: 38000,
    maintenanceCost: 125,
    employment: 14000,
    taxOutput: 400,
    corruptionRisk: 4,
    effects: { steel: 30, stability: 2 },
  },
  {
    id: "atlas-structural",
    name: "Atlas Structural Systems",
    sector: "construction",
    tier: 2,
    description: "Pre-fabricated structural components for rapid hab-block assembly.",
    licenseCost: 29000,
    maintenanceCost: 95,
    employment: 10000,
    taxOutput: 300,
    corruptionRisk: 3,
    effects: { steel: 25, goods: 15 },
  },
  {
    id: "metroforge-steelworks",
    name: "MetroForge Steelworks",
    sector: "construction",
    tier: 2,
    description: "Primary steel processing and supply chain for all city construction projects.",
    licenseCost: 44000,
    maintenanceCost: 145,
    employment: 18000,
    taxOutput: 500,
    corruptionRisk: 3,
    effects: { steel: 50, goods: 20 },
  },
  {
    id: "concretecore-ind",
    name: "ConcreteCore Industrial",
    sector: "construction",
    tier: 1,
    description: "Mass concrete and aggregate production feeding city construction projects.",
    licenseCost: 9000,
    maintenanceCost: 40,
    employment: 4000,
    taxOutput: 125,
    corruptionRisk: 2,
    effects: { steel: 15, goods: 10 },
  },
  {
    id: "skyline-megastructures",
    name: "Skyline MegaStructures",
    sector: "construction",
    tier: 3,
    description: "Elite megastructure design firm responsible for the tallest blocks in the city.",
    licenseCost: 110000,
    maintenanceCost: 320,
    employment: 35000,
    taxOutput: 1200,
    corruptionRisk: 5,
    effects: { steel: 60, goods: 30, stability: 4 },
  },
  {
    id: "urbanframe-dev",
    name: "UrbanFrame Development",
    sector: "construction",
    tier: 1,
    description: "Mid-tier residential development contractor for worker housing construction.",
    licenseCost: 8000,
    maintenanceCost: 35,
    employment: 5000,
    taxOutput: 115,
    corruptionRisk: 2,
    effects: { steel: 12, happiness: 1 },
  },
  {
    id: "heavylift-infra",
    name: "HeavyLift Infrastructure",
    sector: "construction",
    tier: 2,
    description: "Heavy equipment logistics and crane operations for deep infrastructure work.",
    licenseCost: 31000,
    maintenanceCost: 105,
    employment: 11000,
    taxOutput: 330,
    corruptionRisk: 3,
    effects: { steel: 22, stability: 2 },
  },
  {
    id: "primeconstruct-civic",
    name: "PrimeConstruct Civic Builders",
    sector: "construction",
    tier: 1,
    description: "Civic contract specialists building public facilities and government infrastructure.",
    licenseCost: 7500,
    maintenanceCost: 32,
    employment: 4500,
    taxOutput: 105,
    corruptionRisk: 2,
    effects: { steel: 10, stability: 3 },
  },
  {
    id: "foundryworks-materials",
    name: "FoundryWorks Materials",
    sector: "construction",
    tier: 1,
    description: "Raw materials processing delivering alloys and composites to construction sites.",
    licenseCost: 8500,
    maintenanceCost: 38,
    employment: 3800,
    taxOutput: 120,
    corruptionRisk: 2,
    effects: { steel: 20, goods: 8 },
  },

  // ── MANUFACTURING ─────────────────────────────────────────────────────
  {
    id: "omnifabrication",
    name: "OmniFabrication Systems",
    sector: "manufacturing",
    tier: 3,
    description: "Fully-automated mega-factory producing everything from consumables to weapons.",
    licenseCost: 145000,
    maintenanceCost: 410,
    employment: 55000,
    taxOutput: 1700,
    corruptionRisk: 5,
    effects: { goods: 200, steel: 60 },
  },
  {
    id: "vector-robotics-mfg",
    name: "Vector Robotics Manufacturing",
    sector: "manufacturing",
    tier: 3,
    description: "Advanced robotics systems manufacturer. Supplies the city's automation backbone.",
    licenseCost: 160000,
    maintenanceCost: 440,
    employment: 40000,
    taxOutput: 1900,
    corruptionRisk: 4,
    effects: { goods: 180, steel: 40 },
  },
  {
    id: "alloytech-refining",
    name: "AlloyTech Refining",
    sector: "manufacturing",
    tier: 2,
    description: "Specialist metal alloy refinement producing high-grade materials.",
    licenseCost: 40000,
    maintenanceCost: 130,
    employment: 15000,
    taxOutput: 460,
    corruptionRisk: 3,
    effects: { steel: 45, goods: 20 },
  },
  {
    id: "titan-assembly-lines",
    name: "Titan Assembly Lines",
    sector: "manufacturing",
    tier: 2,
    description: "Mass production assembly facilities producing consumer and industrial goods.",
    licenseCost: 36000,
    maintenanceCost: 120,
    employment: 20000,
    taxOutput: 420,
    corruptionRisk: 3,
    effects: { goods: 80, steel: 20 },
  },
  {
    id: "ironpulse-industry",
    name: "IronPulse Industry Group",
    sector: "manufacturing",
    tier: 2,
    description: "Heavy industry group managing multiple manufacturing facilities.",
    licenseCost: 32000,
    maintenanceCost: 108,
    employment: 17000,
    taxOutput: 380,
    corruptionRisk: 4,
    effects: { goods: 70, steel: 30 },
  },
  {
    id: "metroforge-industrial",
    name: "MetroForge Industrial Complex",
    sector: "manufacturing",
    tier: 3,
    description: "City-scale industrial complex spanning multiple zones. Dominant economic force.",
    licenseCost: 180000,
    maintenanceCost: 500,
    employment: 70000,
    taxOutput: 2200,
    corruptionRisk: 7,
    effects: { goods: 220, steel: 80, fuel: 30 },
  },
  {
    id: "deepworks-fabricators",
    name: "DeepWorks Machine Fabricators",
    sector: "manufacturing",
    tier: 1,
    description: "Underground machining shops producing specialist components for city infrastructure.",
    licenseCost: 10000,
    maintenanceCost: 44,
    employment: 4000,
    taxOutput: 135,
    corruptionRisk: 2,
    effects: { goods: 30, steel: 10 },
  },
  {
    id: "nexus-production",
    name: "Nexus Production Facilities",
    sector: "manufacturing",
    tier: 2,
    description: "Mid-tier production network manufacturing consumer goods and supplies.",
    licenseCost: 27000,
    maintenanceCost: 90,
    employment: 13000,
    taxOutput: 330,
    corruptionRisk: 3,
    effects: { goods: 60, steel: 15 },
  },
  {
    id: "steelpulse-network",
    name: "SteelPulse Industrial Network",
    sector: "manufacturing",
    tier: 2,
    description: "Steel and materials processing network distributing to all city contractors.",
    licenseCost: 35000,
    maintenanceCost: 115,
    employment: 14000,
    taxOutput: 400,
    corruptionRisk: 3,
    effects: { steel: 55, goods: 15 },
  },
  {
    id: "primefabrication",
    name: "PrimeFabrication Works",
    sector: "manufacturing",
    tier: 1,
    description: "General fabrication workshop network producing parts on city contracts.",
    licenseCost: 9000,
    maintenanceCost: 40,
    employment: 5000,
    taxOutput: 125,
    corruptionRisk: 2,
    effects: { goods: 25, steel: 8 },
  },

  // ── TRANSPORT ─────────────────────────────────────────────────────────
  {
    id: "skyrail-transit",
    name: "SkyRail Transit Authority",
    sector: "transport",
    tier: 3,
    description: "The city's primary mass transit megaoperator. Moves millions every tick.",
    licenseCost: 170000,
    maintenanceCost: 460,
    employment: 65000,
    taxOutput: 2000,
    corruptionRisk: 5,
    effects: { trade: 300, happiness: 4, stability: 3 },
  },
  {
    id: "metromag-transport",
    name: "MetroMag Transport Systems",
    sector: "transport",
    tier: 2,
    description: "Maglev-based cargo and passenger transit between sectors.",
    licenseCost: 55000,
    maintenanceCost: 175,
    employment: 18000,
    taxOutput: 580,
    corruptionRisk: 3,
    effects: { trade: 180, stability: 2 },
  },
  {
    id: "aerolift-logistics",
    name: "AeroLift Logistics",
    sector: "transport",
    tier: 2,
    description: "Air cargo and drone logistics company handling high-priority deliveries.",
    licenseCost: 48000,
    maintenanceCost: 155,
    employment: 14000,
    taxOutput: 500,
    corruptionRisk: 3,
    effects: { trade: 150, fuel: 20 },
  },
  {
    id: "freightline-cargo",
    name: "FreightLine Cargo Networks",
    sector: "transport",
    tier: 2,
    description: "Surface freight network operating thousands of automated cargo vehicles.",
    licenseCost: 42000,
    maintenanceCost: 138,
    employment: 22000,
    taxOutput: 450,
    corruptionRisk: 4,
    effects: { trade: 130, fuel: 15, goods: 20 },
  },
  {
    id: "horizon-skyport",
    name: "Horizon Skyport Services",
    sector: "transport",
    tier: 3,
    description: "Mega-skyport operator managing intercity trade and passenger platforms.",
    licenseCost: 190000,
    maintenanceCost: 520,
    employment: 72000,
    taxOutput: 2400,
    corruptionRisk: 5,
    effects: { trade: 400, stability: 2 },
  },
  {
    id: "transitflow-urban",
    name: "TransitFlow Urban Mobility",
    sector: "transport",
    tier: 1,
    description: "Street-level urban mobility systems connecting hab-blocks to transit hubs.",
    licenseCost: 8000,
    maintenanceCost: 34,
    employment: 6000,
    taxOutput: 110,
    corruptionRisk: 1,
    effects: { trade: 50, happiness: 2 },
  },
  {
    id: "velocity-freight",
    name: "Velocity Freight Consortium",
    sector: "transport",
    tier: 2,
    description: "Express freight consortium specialising in time-critical cargo runs.",
    licenseCost: 36000,
    maintenanceCost: 118,
    employment: 13000,
    taxOutput: 390,
    corruptionRisk: 3,
    effects: { trade: 120, fuel: 10 },
  },
  {
    id: "cargocore-dist",
    name: "CargoCore Distribution",
    sector: "transport",
    tier: 1,
    description: "Central cargo routing and distribution hub for internal city supply chains.",
    licenseCost: 9000,
    maintenanceCost: 40,
    employment: 5000,
    taxOutput: 130,
    corruptionRisk: 2,
    effects: { trade: 60, goods: 10 },
  },
  {
    id: "swiftroute-courier",
    name: "SwiftRoute Courier Systems",
    sector: "transport",
    tier: 1,
    description: "High-speed courier network for medical, governmental, and judicial dispatch.",
    licenseCost: 6500,
    maintenanceCost: 28,
    employment: 4500,
    taxOutput: 90,
    corruptionRisk: 1,
    effects: { trade: 40, stability: 1 },
  },
  {
    id: "urbantransit-civic",
    name: "UrbanTransit Civic Authority",
    sector: "transport",
    tier: 2,
    description: "Civic transit authority managing subsidised routes into the underhive.",
    licenseCost: 24000,
    maintenanceCost: 80,
    employment: 12000,
    taxOutput: 260,
    corruptionRisk: 2,
    effects: { trade: 80, happiness: 3, stability: 2 },
  },

  // ── TECH ──────────────────────────────────────────────────────────────
  {
    id: "novalogic-systems",
    name: "NovaLogic Systems",
    sector: "tech",
    tier: 2,
    description: "City management software and logistics optimisation AI systems.",
    licenseCost: 38000,
    maintenanceCost: 120,
    employment: 9000,
    taxOutput: 420,
    corruptionRisk: 2,
    effects: { research: 8, crime: -2, stability: 2 },
  },
  {
    id: "quantumstack-computing",
    name: "QuantumStack Computing",
    sector: "tech",
    tier: 3,
    description: "Quantum computing cluster providing city-wide predictive analytics.",
    licenseCost: 200000,
    maintenanceCost: 550,
    employment: 28000,
    taxOutput: 2200,
    corruptionRisk: 3,
    effects: { research: 25, crime: -5, stability: 3 },
  },
  {
    id: "helix-data",
    name: "Helix Data Networks",
    sector: "tech",
    tier: 2,
    description: "Secure data infrastructure for governmental and judicial systems.",
    licenseCost: 40000,
    maintenanceCost: 128,
    employment: 8000,
    taxOutput: 400,
    corruptionRisk: 2,
    effects: { research: 7, stability: 2 },
  },
  {
    id: "signalforge-comms",
    name: "SignalForge Communications",
    sector: "tech",
    tier: 2,
    description: "City-wide communications infrastructure and emergency broadcast systems.",
    licenseCost: 32000,
    maintenanceCost: 105,
    employment: 9500,
    taxOutput: 360,
    corruptionRisk: 2,
    effects: { research: 5, stability: 3 },
  },
  {
    id: "neuralcore-analytics",
    name: "NeuralCore Analytics",
    sector: "tech",
    tier: 2,
    description: "Predictive crime analytics and population behavior modeling systems.",
    licenseCost: 45000,
    maintenanceCost: 145,
    employment: 7500,
    taxOutput: 440,
    corruptionRisk: 3,
    effects: { research: 9, crime: -3 },
  },
  {
    id: "apex-software",
    name: "Apex Software Industries",
    sector: "tech",
    tier: 2,
    description: "Enterprise software solutions for city administration and resource management.",
    licenseCost: 28000,
    maintenanceCost: 92,
    employment: 6000,
    taxOutput: 320,
    corruptionRisk: 2,
    effects: { research: 6, stability: 2 },
  },
  {
    id: "skyline-cybernetics",
    name: "Skyline Cybernetics",
    sector: "tech",
    tier: 3,
    description: "Cybernetics R&D megacorp. Develops enhancements for enforcers and security forces.",
    licenseCost: 175000,
    maintenanceCost: 480,
    employment: 35000,
    taxOutput: 1900,
    corruptionRisk: 5,
    effects: { research: 20, crime: -6, stability: 2 },
  },
  {
    id: "vector-ai",
    name: "Vector AI Systems",
    sector: "tech",
    tier: 3,
    description: "Advanced military and surveillance AI — the backbone of the city's prediction network.",
    licenseCost: 190000,
    maintenanceCost: 510,
    employment: 25000,
    taxOutput: 2100,
    corruptionRisk: 4,
    effects: { research: 22, crime: -8 },
  },
  {
    id: "synapse-data",
    name: "Synapse Data Authority",
    sector: "tech",
    tier: 2,
    description: "Centralised data authority managing citizen records and biometric surveillance.",
    licenseCost: 44000,
    maintenanceCost: 142,
    employment: 7000,
    taxOutput: 420,
    corruptionRisk: 4,
    effects: { research: 8, crime: -3, stability: 1 },
  },
  {
    id: "nexus-intel-labs",
    name: "Nexus Intelligence Labs",
    sector: "tech",
    tier: 2,
    description: "R&D labs developing next-gen surveillance, forensics, and intelligence tools.",
    licenseCost: 38000,
    maintenanceCost: 122,
    employment: 6500,
    taxOutput: 380,
    corruptionRisk: 3,
    effects: { research: 10, crime: -2 },
  },

  // ── MEDICAL ───────────────────────────────────────────────────────────
  {
    id: "bionova-medical",
    name: "BioNova Medical Systems",
    sector: "medical",
    tier: 3,
    description: "Tier-1 medical megacorp operating trauma centers and research hospitals.",
    licenseCost: 155000,
    maintenanceCost: 430,
    employment: 55000,
    taxOutput: 1600,
    corruptionRisk: 4,
    effects: { med: 120, happiness: 5 },
  },
  {
    id: "civiccare-hospital",
    name: "CivicCare Hospital Network",
    sector: "medical",
    tier: 2,
    description: "Municipally-affiliated hospital network serving all district populations.",
    licenseCost: 40000,
    maintenanceCost: 130,
    employment: 16000,
    taxOutput: 380,
    corruptionRisk: 2,
    effects: { med: 60, happiness: 3 },
  },
  {
    id: "genomepath-biolabs",
    name: "GenomePath Biolabs",
    sector: "medical",
    tier: 2,
    description: "Genetic research labs focused on population health and mutation containment.",
    licenseCost: 52000,
    maintenanceCost: 165,
    employment: 9000,
    taxOutput: 480,
    corruptionRisk: 4,
    effects: { med: 45, research: 8 },
  },
  {
    id: "medaxis-pharma",
    name: "MedAxis Pharmaceuticals",
    sector: "medical",
    tier: 2,
    description: "Pharma manufacturing for city-wide medication, anaesthetics, and combat drugs.",
    licenseCost: 44000,
    maintenanceCost: 140,
    employment: 11000,
    taxOutput: 440,
    corruptionRisk: 5,
    effects: { med: 55, happiness: 1 },
  },
  {
    id: "lifepulse-emergency",
    name: "LifePulse Emergency Care",
    sector: "medical",
    tier: 1,
    description: "Emergency medical response teams embedded across all major districts.",
    licenseCost: 9000,
    maintenanceCost: 40,
    employment: 4500,
    taxOutput: 115,
    corruptionRisk: 1,
    effects: { med: 25, happiness: 2 },
  },
  {
    id: "regenix-bioeng",
    name: "Regenix Bioengineering",
    sector: "medical",
    tier: 3,
    description: "Advanced tissue regeneration and cybernetic implant medical division.",
    licenseCost: 130000,
    maintenanceCost: 370,
    employment: 30000,
    taxOutput: 1400,
    corruptionRisk: 5,
    effects: { med: 100, research: 12, happiness: 3 },
  },
  {
    id: "healthgrid-medical",
    name: "HealthGrid Medical Services",
    sector: "medical",
    tier: 1,
    description: "Distributed primary care clinics serving block-level populations.",
    licenseCost: 7000,
    maintenanceCost: 30,
    employment: 4000,
    taxOutput: 95,
    corruptionRisk: 1,
    effects: { med: 22, happiness: 3, stability: 1 },
  },
  {
    id: "vitalcore-hospital",
    name: "VitalCore Research Hospital",
    sector: "medical",
    tier: 2,
    description: "Combined research hospital and training facility for judicial medical teams.",
    licenseCost: 48000,
    maintenanceCost: 152,
    employment: 13000,
    taxOutput: 450,
    corruptionRisk: 2,
    effects: { med: 50, research: 7 },
  },
  {
    id: "curewave-logistics",
    name: "CureWave Medical Logistics",
    sector: "medical",
    tier: 1,
    description: "Cold-chain medical supply logistics ensuring med supplies reach crisis zones.",
    licenseCost: 7500,
    maintenanceCost: 33,
    employment: 3500,
    taxOutput: 100,
    corruptionRisk: 1,
    effects: { med: 20, stability: 1 },
  },
  {
    id: "public-health-auth",
    name: "Public Health Authority",
    sector: "medical",
    tier: 2,
    description: "Disease surveillance, vaccination programs, and epidemic response.",
    licenseCost: 25000,
    maintenanceCost: 82,
    employment: 10000,
    taxOutput: 240,
    corruptionRisk: 2,
    effects: { med: 35, happiness: 4, stability: 2 },
  },

  // ── FINANCE ───────────────────────────────────────────────────────────
  {
    id: "ironledger-financial",
    name: "IronLedger Financial",
    sector: "finance",
    tier: 2,
    description: "City's primary financial auditing and treasury management firm.",
    licenseCost: 36000,
    maintenanceCost: 115,
    employment: 8000,
    taxOutput: 500,
    corruptionRisk: 4,
    effects: { trade: 100, stability: 2 },
  },
  {
    id: "metrocredit-bank",
    name: "MetroCredit Bank",
    sector: "finance",
    tier: 2,
    description: "Residential credit bank with branches across all sectors. High tax yield.",
    licenseCost: 42000,
    maintenanceCost: 130,
    employment: 12000,
    taxOutput: 600,
    corruptionRisk: 5,
    effects: { trade: 120, happiness: 1 },
  },
  {
    id: "apex-trade",
    name: "Apex Trade Consortium",
    sector: "finance",
    tier: 3,
    description: "Intercity trade and commerce megaconsortium. Handles 30% of city exports.",
    licenseCost: 190000,
    maintenanceCost: 520,
    employment: 65000,
    taxOutput: 2500,
    corruptionRisk: 8,
    effects: { trade: 500, stability: 1 },
  },
  {
    id: "skyline-markets",
    name: "Skyline Markets Exchange",
    sector: "finance",
    tier: 3,
    description: "Automated futures and resource exchange. Massive revenue, significant risk.",
    licenseCost: 200000,
    maintenanceCost: 550,
    employment: 22000,
    taxOutput: 2800,
    corruptionRisk: 9,
    effects: { trade: 600 },
  },
  {
    id: "titan-commerce",
    name: "Titan Commerce Group",
    sector: "finance",
    tier: 2,
    description: "Diversified commercial holding company with wide sector exposure.",
    licenseCost: 50000,
    maintenanceCost: 160,
    employment: 15000,
    taxOutput: 650,
    corruptionRisk: 5,
    effects: { trade: 150, goods: 15 },
  },
  {
    id: "urbantrade-syndicate",
    name: "UrbanTrade Syndicate",
    sector: "finance",
    tier: 1,
    description: "Street-level merchant syndicate. Questionable connections but strong income.",
    licenseCost: 10000,
    maintenanceCost: 44,
    employment: 6000,
    taxOutput: 160,
    corruptionRisk: 6,
    effects: { trade: 80 },
  },
  {
    id: "civic-treasury-auth",
    name: "Civic Treasury Authority",
    sector: "finance",
    tier: 2,
    description: "Quasi-governmental treasury management and bond issuance authority.",
    licenseCost: 30000,
    maintenanceCost: 98,
    employment: 7000,
    taxOutput: 420,
    corruptionRisk: 3,
    effects: { trade: 90, stability: 3 },
  },
  {
    id: "continental-finance",
    name: "Continental Finance Bureau",
    sector: "finance",
    tier: 3,
    description: "Continent-wide investment bureau. Enormous revenue, enormous risk.",
    licenseCost: 175000,
    maintenanceCost: 490,
    employment: 28000,
    taxOutput: 2300,
    corruptionRisk: 8,
    effects: { trade: 450 },
  },
  {
    id: "novacapital",
    name: "NovaCapital Investment",
    sector: "finance",
    tier: 2,
    description: "Venture capital and infrastructure investment firm funding city expansions.",
    licenseCost: 44000,
    maintenanceCost: 140,
    employment: 6000,
    taxOutput: 560,
    corruptionRisk: 4,
    effects: { trade: 110, stability: 2 },
  },
  {
    id: "primetrade-mercantile",
    name: "PrimeTrade Mercantile",
    sector: "finance",
    tier: 1,
    description: "Mercantile network handling district-level commerce and retail taxation.",
    licenseCost: 8000,
    maintenanceCost: 35,
    employment: 5000,
    taxOutput: 140,
    corruptionRisk: 3,
    effects: { trade: 60, happiness: 1 },
  },

  // ── CIVIC ─────────────────────────────────────────────────────────────
  {
    id: "dept-urban-maint",
    name: "Department of Urban Maintenance",
    sector: "civic",
    tier: 1,
    description: "Basic city upkeep services: road repair, waste collection, lighting.",
    licenseCost: 5000,
    maintenanceCost: 22,
    employment: 8000,
    taxOutput: 80,
    corruptionRisk: 2,
    effects: { stability: 3, happiness: 1 },
  },
  {
    id: "civic-infra-auth",
    name: "Civic Infrastructure Authority",
    sector: "civic",
    tier: 2,
    description: "Central infrastructure oversight authority managing all city assets.",
    licenseCost: 28000,
    maintenanceCost: 92,
    employment: 14000,
    taxOutput: 300,
    corruptionRisk: 3,
    effects: { stability: 5, happiness: 2 },
  },
  {
    id: "emergency-response-dir",
    name: "Emergency Response Directorate",
    sector: "civic",
    tier: 2,
    description: "Integrated emergency response: fire, disaster, chemical, and radiological threats.",
    licenseCost: 32000,
    maintenanceCost: 105,
    employment: 15000,
    taxOutput: 280,
    corruptionRisk: 2,
    effects: { stability: 4, happiness: 2, crime: -1 },
  },
  {
    id: "public-housing-bureau",
    name: "Public Housing Bureau",
    sector: "civic",
    tier: 1,
    description: "State housing allocation agency for low-income residential blocks.",
    licenseCost: 6500,
    maintenanceCost: 28,
    employment: 5000,
    taxOutput: 85,
    corruptionRisk: 3,
    effects: { happiness: 3, stability: 2 },
  },
  {
    id: "pop-registry-office",
    name: "Population Registry Office",
    sector: "civic",
    tier: 1,
    description: "Biometric citizen registration and census management authority.",
    licenseCost: 5500,
    maintenanceCost: 24,
    employment: 3500,
    taxOutput: 72,
    corruptionRisk: 2,
    effects: { stability: 2, crime: -1 },
  },
  {
    id: "waste-management-auth",
    name: "Waste Management Authority",
    sector: "civic",
    tier: 2,
    description: "City-wide industrial and residential waste processing and containment.",
    licenseCost: 22000,
    maintenanceCost: 72,
    employment: 12000,
    taxOutput: 240,
    corruptionRisk: 3,
    effects: { happiness: 3, stability: 2 },
  },
  {
    id: "transit-reg-bureau",
    name: "Transit Regulation Bureau",
    sector: "civic",
    tier: 1,
    description: "Regulatory body overseeing all licensed transport operators in the city.",
    licenseCost: 6000,
    maintenanceCost: 26,
    employment: 2500,
    taxOutput: 78,
    corruptionRisk: 2,
    effects: { stability: 2, trade: 20 },
  },
  {
    id: "civil-safety-admin",
    name: "Civil Safety Administration",
    sector: "civic",
    tier: 2,
    description: "Multi-hazard safety authority coordinating with The Authority on emergencies.",
    licenseCost: 25000,
    maintenanceCost: 82,
    employment: 11000,
    taxOutput: 260,
    corruptionRisk: 2,
    effects: { stability: 4, happiness: 2, crime: -2 },
  },
  {
    id: "disaster-recovery",
    name: "Disaster Recovery Agency",
    sector: "civic",
    tier: 2,
    description: "Long-term recovery and reconstruction agency following major incidents.",
    licenseCost: 26000,
    maintenanceCost: 86,
    employment: 10000,
    taxOutput: 240,
    corruptionRisk: 3,
    effects: { stability: 3, happiness: 2 },
  },
  {
    id: "central-city-admin",
    name: "Central City Administration",
    sector: "civic",
    tier: 3,
    description: "The apex civic administrative authority overseeing all city services from the Grand Hall.",
    licenseCost: 100000,
    maintenanceCost: 290,
    employment: 40000,
    taxOutput: 1200,
    corruptionRisk: 4,
    effects: { stability: 8, happiness: 4, crime: -3, trade: 60 },
  },
];

export const COMPANIES_MAP: Record<string, CompanyDef> = {};
for (const c of COMPANIES) {
  COMPANIES_MAP[c.id] = c;
}

export const COMPANY_SECTOR_LABELS: Record<string, string> = {
  energy: "ENERGY",
  water: "WATER",
  food: "FOOD",
  construction: "CONSTRUCTION",
  manufacturing: "MANUFACTURING",
  transport: "TRANSPORT",
  tech: "TECHNOLOGY",
  medical: "MEDICAL",
  finance: "FINANCE",
  civic: "CIVIC",
};

export const COMPANY_SECTOR_ICONS: Record<string, string> = {
  energy: "zap",
  water: "droplet",
  food: "package",
  construction: "tool",
  manufacturing: "settings",
  transport: "truck",
  tech: "cpu",
  medical: "activity",
  finance: "trending-up",
  civic: "users",
};
