import { LABOUR_DAY_BOOSTER_IDS } from "@/engine/labourDay";

export type EdictEffect = {
  happiness?: number;
  crime?: number;
  corruption?: number;
  unrest?: number;
  diseaseRisk?: number;
  employment?: number;
  credits?: number;
  creditsPerTick?: number;
  populationGrowth?: number;
  populationGrowthRate?: number;
  infrastructureRepair?: number;
  lawEnforcement?: number;
  lawOrder?: number;
  defenseRating?: number;
  foodProduction?: number;
  researchSpeed?: number;
  tradeIncome?: number;
  factionInfluence?: { factionId: string; delta: number };
  bordersClosed?: boolean;
};

export type EdictDef = {
  id: string;
  name: string;
  description: string;
  category: "security" | "economic" | "social" | "infrastructure" | "political";
  cost: number;
  durationTicks: number;
  cooldownTicks: number;
  effects: EdictEffect;
  requiresAuthority?: number;
};

export const EDICTS: EdictDef[] = [
  {
    id: "emergency_lockdown",
    name: "Emergency Sector Lockdown",
    description: "Seal all sector transit points for 6 ticks. Crime plummets but happiness and economic activity crater.",
    category: "security",
    cost: 50000,
    durationTicks: 6,
    cooldownTicks: 20,
    effects: {
      crime: -15,
      happiness: -8,
      employment: -5,
      unrest: 4,
    },
  },
  {
    id: "stimulus_package",
    name: "Economic Stimulus Package",
    description: "Inject emergency credits into the local economy for 8 ticks. Boosts employment and happiness but costs heavily.",
    category: "economic",
    cost: 120000,
    durationTicks: 8,
    cooldownTicks: 24,
    effects: {
      happiness: 5,
      employment: 8,
      creditsPerTick: -5000,
      corruption: 2,
    },
  },
  {
    id: "emergency_rations",
    name: "Emergency Ration Distribution",
    description: "Distribute emergency food supplies across all districts for 5 ticks. Reduces unrest at cost of credits.",
    category: "social",
    cost: 40000,
    durationTicks: 5,
    cooldownTicks: 14,
    effects: {
      happiness: 6,
      unrest: -5,
      creditsPerTick: -3000,
    },
  },
  {
    id: "infrastructure_blitz",
    name: "Infrastructure Repair Blitz",
    description: "Mobilize all available repair crews and droids for 4 ticks. Rapid infrastructure recovery but drains resources.",
    category: "infrastructure",
    cost: 80000,
    durationTicks: 4,
    cooldownTicks: 16,
    effects: {
      infrastructureRepair: 12,
      creditsPerTick: -8000,
      employment: 3,
    },
  },
  {
    id: "anti_corruption_purge",
    name: "Anti-Corruption Purge",
    description: "Launch aggressive internal affairs sweep for 6 ticks. Dramatically reduces corruption but destabilizes the bureaucracy.",
    category: "political",
    cost: 60000,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: {
      corruption: -10,
      happiness: -3,
      employment: -2,
      unrest: 2,
    },
    requiresAuthority: 3,
  },
  {
    id: "gang_amnesty",
    name: "Gang Amnesty Program",
    description: "Offer temporary amnesty to minor offenders for 8 ticks. Reduces crime and gang influence but erodes law authority.",
    category: "social",
    cost: 30000,
    durationTicks: 8,
    cooldownTicks: 30,
    effects: {
      crime: -8,
      unrest: -4,
      lawEnforcement: -5,
      factionInfluence: { factionId: "gangs", delta: -10 },
    },
  },
  {
    id: "forced_labor_decree",
    name: "Forced Labor Mobilization",
    description: "Conscript unemployed citizens into public works for 6 ticks. Boosts employment and infrastructure but happiness tanks.",
    category: "economic",
    cost: 25000,
    durationTicks: 6,
    cooldownTicks: 20,
    effects: {
      employment: 12,
      infrastructureRepair: 5,
      happiness: -10,
      unrest: 6,
      crime: -3,
    },
    requiresAuthority: 5,
  },
  {
    id: "media_blackout",
    name: "Sector Media Blackout",
    description: "Suppress all public communications for 4 ticks. Prevents panic but breeds distrust and corruption.",
    category: "political",
    cost: 35000,
    durationTicks: 4,
    cooldownTicks: 18,
    effects: {
      unrest: -6,
      corruption: 4,
      happiness: -4,
      crime: 2,
    },
  },
  {
    id: "public_works_festival",
    name: "Civic Unity Festival",
    description: "Sponsor a sector-wide public event for 3 ticks. Major happiness boost but expensive and briefly raises crime.",
    category: "social",
    cost: 90000,
    durationTicks: 3,
    cooldownTicks: 20,
    effects: {
      happiness: 12,
      unrest: -8,
      crime: 3,
      creditsPerTick: -6000,
    },
  },
  {
    id: "corporate_audit",
    name: "Corporate Sector Audit",
    description: "Mandate a full audit of all licensed corporations for 5 ticks. Reduces corruption and boosts revenue but corps fight back.",
    category: "economic",
    cost: 45000,
    durationTicks: 5,
    cooldownTicks: 22,
    effects: {
      corruption: -6,
      creditsPerTick: 8000,
      happiness: -2,
      factionInfluence: { factionId: "corps", delta: -8 },
    },
    requiresAuthority: 2,
  },
  {
    id: "mass_surveillance_sweep",
    name: "Mass Surveillance Sweep",
    description: "Activate all surveillance assets for a sector-wide dragnet lasting 5 ticks. Dramatically reduces crime but erodes trust.",
    category: "security",
    cost: 55000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: {
      crime: -12,
      happiness: -4,
      corruption: 1,
      lawEnforcement: 3,
    },
  },
  {
    id: "emergency_power_reroute",
    name: "Emergency Power Reroute",
    description: "Override power grid protocols to boost industrial output for 4 ticks. Risks grid instability.",
    category: "infrastructure",
    cost: 45000,
    durationTicks: 4,
    cooldownTicks: 16,
    effects: {
      employment: 4,
      creditsPerTick: 4000,
      happiness: -2,
    },
  },
  {
    id: "propaganda_blitz",
    name: "Propaganda Broadcast Blitz",
    description: "Saturate all media channels with state messaging for 6 ticks. Reduces unrest and boosts loyalty but increases corruption.",
    category: "political",
    cost: 50000,
    durationTicks: 6,
    cooldownTicks: 20,
    effects: {
      unrest: -7,
      happiness: 4,
      corruption: 3,
      crime: 1,
    },
  },
  {
    id: "trade_tariff_suspension",
    name: "Trade Tariff Suspension",
    description: "Temporarily lift all import tariffs for 5 ticks. Boosts trade income but undercuts local industry.",
    category: "economic",
    cost: 35000,
    durationTicks: 5,
    cooldownTicks: 22,
    effects: {
      creditsPerTick: 10000,
      employment: -3,
      happiness: 3,
    },
  },
  {
    id: "mutant_outreach",
    name: "Mutant Community Outreach",
    description: "Send mediators into mutant zones for 6 ticks. Reduces mutant faction hostility and crime in their territories.",
    category: "social",
    cost: 30000,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: {
      crime: -4,
      happiness: 3,
      unrest: -3,
      factionInfluence: { factionId: "mutants", delta: -6 },
    },
  },
  {
    id: "shadow_ops_crackdown",
    name: "Shadow Operations Crackdown",
    description: "Deploy black ops teams against the shadow faction for 4 ticks. High impact but expensive and controversial.",
    category: "security",
    cost: 100000,
    durationTicks: 4,
    cooldownTicks: 28,
    effects: {
      crime: -10,
      happiness: -5,
      unrest: 3,
      factionInfluence: { factionId: "gangs", delta: -12 },
    },
    requiresAuthority: 4,
  },
  {
    id: "mass_hiring_initiative",
    name: "Mass Hiring Initiative",
    description: "Government-funded jobs program for 8 ticks. Dramatically boosts employment but costs heavily in credits.",
    category: "economic",
    cost: 150000,
    durationTicks: 8,
    cooldownTicks: 30,
    effects: {
      employment: 15,
      happiness: 4,
      creditsPerTick: -10000,
      unrest: -3,
    },
  },
  {
    id: "martial_curfew_extension",
    name: "Extended Martial Curfew",
    description: "Extend curfew hours and enforce strict movement controls for 5 ticks. Maximum crime reduction at severe social cost.",
    category: "security",
    cost: 40000,
    durationTicks: 5,
    cooldownTicks: 22,
    effects: {
      crime: -18,
      unrest: 8,
      happiness: -12,
      lawEnforcement: 5,
    },
    requiresAuthority: 3,
  },
  {
    id: "public_health_emergency",
    name: "Public Health Emergency",
    description: "Declare a public health emergency and mobilize all medical resources for 4 ticks. Boosts happiness and reduces crime.",
    category: "social",
    cost: 70000,
    durationTicks: 4,
    cooldownTicks: 20,
    effects: {
      happiness: 8,
      crime: -3,
      unrest: -4,
      diseaseRisk: -8,
      creditsPerTick: -5000,
    },
  },
  {
    id: "debt_amnesty",
    name: "Citizen Debt Amnesty",
    description: "Forgive all citizen debts for 3 ticks. Massive happiness boost but devastating to treasury.",
    category: "economic",
    cost: 200000,
    durationTicks: 3,
    cooldownTicks: 36,
    effects: {
      happiness: 15,
      unrest: -10,
      creditsPerTick: -15000,
      corruption: 2,
    },
  },
  {
    id: "tourism_campaign",
    name: "City Tourism Campaign",
    description: "Launch a sector-wide advertising blitz to attract visitors for 8 ticks. Boosts tourist count and income but costs credits.",
    category: "economic",
    cost: 60000,
    durationTicks: 8,
    cooldownTicks: 24,
    effects: {
      happiness: 3,
      creditsPerTick: -4000,
      employment: 2,
    },
  },
  {
    id: "tourist_security_detail",
    name: "Tourist Security Detail",
    description: "Deploy dedicated security patrols in tourist zones for 6 ticks. Improves satisfaction and reduces crime but costs resources.",
    category: "security",
    cost: 40000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: {
      crime: -4,
      happiness: 2,
      creditsPerTick: -3000,
    },
  },
  {
    id: "cultural_festival_week",
    name: "Cultural Festival Week",
    description: "Host a massive cultural event attracting visitors for 4 ticks. Major tourism boost with high costs.",
    category: "social",
    cost: 80000,
    durationTicks: 4,
    cooldownTicks: 20,
    effects: {
      happiness: 8,
      unrest: -3,
      creditsPerTick: -8000,
      employment: 3,
    },
  },
  {
    id: "restrict_tourist_zones",
    name: "Restrict Tourist Zones",
    description: "Confine tourists to designated safe sectors for 6 ticks. Reduces crime impact but lowers satisfaction and income.",
    category: "security",
    cost: 20000,
    durationTicks: 6,
    cooldownTicks: 16,
    effects: {
      crime: -3,
      happiness: -2,
      creditsPerTick: 2000,
    },
  },

  // ── ADDITIONAL SECURITY EDICTS ──────────────────────────────────────
  {
    id: "lethal_force_authorization",
    name: "Lethal Force Authorization",
    description: "Authorize enforcers to use deadly force for 4 ticks. Crime plummets but fear and unrest spike.",
    category: "security",
    cost: 45000,
    durationTicks: 4,
    cooldownTicks: 24,
    effects: { crime: -14, happiness: -10, unrest: 6, lawEnforcement: 4 },
    requiresAuthority: 4,
  },
  {
    id: "district_quarantine_sweep",
    name: "District Quarantine Sweep",
    description: "Lock down and sweep individual districts for contraband and fugitives over 5 ticks.",
    category: "security",
    cost: 35000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: { crime: -8, happiness: -4, unrest: 2, corruption: -1 },
  },
  {
    id: "emergency_drone_swarm",
    name: "Emergency Drone Swarm",
    description: "Deploy a massive drone swarm for real-time surveillance for 3 ticks. Extreme crime suppression.",
    category: "security",
    cost: 70000,
    durationTicks: 3,
    cooldownTicks: 20,
    effects: { crime: -16, happiness: -6, unrest: 4, lawEnforcement: 5 },
    requiresAuthority: 3,
  },
  {
    id: "underworld_sting_operation",
    name: "Underworld Sting Operation",
    description: "Infiltrate and dismantle black market networks over 6 ticks. High cost but devastates organized crime.",
    category: "security",
    cost: 90000,
    durationTicks: 6,
    cooldownTicks: 28,
    effects: { crime: -10, corruption: -4, creditsPerTick: -4000, factionInfluence: { factionId: "gangs", delta: -15 } },
    requiresAuthority: 3,
  },
  {
    id: "weapons_confiscation_drive",
    name: "Weapons Confiscation Drive",
    description: "Door-to-door weapon searches for 4 ticks. Reduces violent crime but enrages citizens.",
    category: "security",
    cost: 30000,
    durationTicks: 4,
    cooldownTicks: 22,
    effects: { crime: -6, happiness: -8, unrest: 5, lawEnforcement: 2 },
    requiresAuthority: 2,
  },
  {
    id: "neural_pacification_broadcast",
    name: "Neural Pacification Broadcast",
    description: "Broadcast calming subliminal signals for 3 ticks. Eliminates unrest but raises ethical concerns.",
    category: "security",
    cost: 80000,
    durationTicks: 3,
    cooldownTicks: 30,
    effects: { unrest: -12, happiness: -2, corruption: 3, crime: -3 },
    requiresAuthority: 5,
  },

  // ── ADDITIONAL ECONOMIC EDICTS ──────────────────────────────────────
  {
    id: "emergency_market_stabilization",
    name: "Emergency Market Stabilization",
    description: "Government intervention to prevent economic crash for 6 ticks. Costly but prevents depression.",
    category: "economic",
    cost: 180000,
    durationTicks: 6,
    cooldownTicks: 30,
    effects: { creditsPerTick: -12000, happiness: 4, employment: 5, unrest: -3 },
  },
  {
    id: "price_gouging_crackdown",
    name: "Price Gouging Crackdown",
    description: "Arrest merchants exploiting crisis pricing for 4 ticks. Stabilizes prices but chills trade.",
    category: "economic",
    cost: 25000,
    durationTicks: 4,
    cooldownTicks: 16,
    effects: { happiness: 4, creditsPerTick: -2000, corruption: -2, employment: -1 },
  },
  {
    id: "industrial_nationalization",
    name: "Industrial Nationalization",
    description: "Seize key industries under government control for 8 ticks. Massive production boost at social cost.",
    category: "economic",
    cost: 200000,
    durationTicks: 8,
    cooldownTicks: 36,
    effects: { employment: 10, creditsPerTick: 8000, happiness: -6, corruption: 4, factionInfluence: { factionId: "corps", delta: -20 } },
    requiresAuthority: 5,
  },
  {
    id: "luxury_tax_decree",
    name: "Luxury Tax Decree",
    description: "Impose emergency taxes on luxury goods and augmentations for 5 ticks.",
    category: "economic",
    cost: 15000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: { creditsPerTick: 6000, happiness: -3, unrest: 1 },
  },
  {
    id: "worker_overtime_mandate",
    name: "Worker Overtime Mandate",
    description: "Mandate extended shifts in all factories for 4 ticks. Boosts output but burns workers out.",
    category: "economic",
    cost: 20000,
    durationTicks: 4,
    cooldownTicks: 20,
    effects: { employment: 6, happiness: -8, creditsPerTick: 5000, unrest: 3 },
  },
  {
    id: "credit_printing_spree",
    name: "Credit Printing Spree",
    description: "Inflate the money supply for 3 ticks. Instant cash but devastating long-term corruption.",
    category: "economic",
    cost: 10000,
    durationTicks: 3,
    cooldownTicks: 30,
    effects: { creditsPerTick: 20000, corruption: 6, happiness: -2, unrest: 2 },
  },

  // ── ADDITIONAL SOCIAL EDICTS ────────────────────────────────────────
  {
    id: "mass_vaccination_drive",
    name: "Mass Vaccination Drive",
    description: "City-wide emergency vaccination campaign for 5 ticks. Halts disease spread.",
    category: "social",
    cost: 60000,
    durationTicks: 5,
    cooldownTicks: 24,
    effects: { happiness: 5, crime: -1, diseaseRisk: -6, creditsPerTick: -4000, populationGrowth: 0.001 },
  },
  {
    id: "food_riot_relief",
    name: "Food Riot Relief",
    description: "Emergency food distribution to quell violent food protests for 3 ticks.",
    category: "social",
    cost: 50000,
    durationTicks: 3,
    cooldownTicks: 14,
    effects: { unrest: -10, happiness: 6, creditsPerTick: -8000, crime: -4 },
  },
  {
    id: "refugee_integration_push",
    name: "Refugee Integration Push",
    description: "Fast-track refugee processing and housing for 6 ticks. Reduces refugee crime and boosts workforce.",
    category: "social",
    cost: 45000,
    durationTicks: 6,
    cooldownTicks: 20,
    effects: { happiness: 4, employment: 4, crime: -2, creditsPerTick: -3000 },
  },
  {
    id: "homeless_shelter_surge",
    name: "Homeless Shelter Surge",
    description: "Open emergency shelters across all sectors for 5 ticks. Reduces street crime and improves morale.",
    category: "social",
    cost: 35000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: { happiness: 6, crime: -3, unrest: -4, creditsPerTick: -3000 },
  },
  {
    id: "youth_amnesty_program",
    name: "Youth Amnesty Program",
    description: "Pardon minor youth offenders and place them in vocational training for 8 ticks.",
    category: "social",
    cost: 40000,
    durationTicks: 8,
    cooldownTicks: 28,
    effects: { crime: -4, happiness: 3, employment: 3, creditsPerTick: -2000 },
  },
  {
    id: "mental_health_crisis_response",
    name: "Mental Health Crisis Response",
    description: "Deploy crisis counselors and psych teams city-wide for 4 ticks.",
    category: "social",
    cost: 55000,
    durationTicks: 4,
    cooldownTicks: 20,
    effects: { happiness: 8, crime: -2, unrest: -3, creditsPerTick: -5000 },
  },

  // ── ADDITIONAL INFRASTRUCTURE EDICTS ────────────────────────────────
  {
    id: "power_grid_override",
    name: "Power Grid Override",
    description: "Bypass safety limits on the power grid for 3 ticks. Massive power output at risk of failure.",
    category: "infrastructure",
    cost: 40000,
    durationTicks: 3,
    cooldownTicks: 16,
    effects: { employment: 3, creditsPerTick: 6000, happiness: -2 },
  },
  {
    id: "transit_system_overhaul",
    name: "Transit Emergency Overhaul",
    description: "Shut down and repair the entire transit system over 4 ticks. Short-term pain for long-term gain.",
    category: "infrastructure",
    cost: 100000,
    durationTicks: 4,
    cooldownTicks: 30,
    effects: { employment: -4, happiness: -6, infrastructureRepair: 15, creditsPerTick: -6000 },
  },
  {
    id: "water_main_emergency",
    name: "Water Main Emergency Repair",
    description: "Emergency repair of critical water infrastructure for 3 ticks.",
    category: "infrastructure",
    cost: 50000,
    durationTicks: 3,
    cooldownTicks: 14,
    effects: { happiness: 3, infrastructureRepair: 8, creditsPerTick: -5000 },
  },
  {
    id: "communications_tower_boost",
    name: "Communications Tower Boost",
    description: "Amplify all comm towers to maximum output for 4 ticks. Improves coordination and morale.",
    category: "infrastructure",
    cost: 30000,
    durationTicks: 4,
    cooldownTicks: 18,
    effects: { happiness: 3, lawEnforcement: 2, creditsPerTick: -2000 },
  },
  {
    id: "factory_overdrive",
    name: "Factory Overdrive Protocol",
    description: "Push all industrial facilities to 150% capacity for 4 ticks. Risks equipment failure.",
    category: "infrastructure",
    cost: 60000,
    durationTicks: 4,
    cooldownTicks: 20,
    effects: { employment: 5, creditsPerTick: 8000, happiness: -4, infrastructureRepair: -3 },
  },
  {
    id: "demolition_clearance",
    name: "Demolition and Clearance Order",
    description: "Demolish condemned buildings to make room for new construction over 3 ticks.",
    category: "infrastructure",
    cost: 35000,
    durationTicks: 3,
    cooldownTicks: 16,
    effects: { happiness: -3, employment: 4, infrastructureRepair: 6, crime: -2 },
  },

  // ── ADDITIONAL POLITICAL EDICTS ─────────────────────────────────────
  {
    id: "opposition_leader_arrest",
    name: "Opposition Leader Arrest",
    description: "Arrest prominent opposition figures for 5 ticks. Silences dissent but breeds resentment.",
    category: "political",
    cost: 25000,
    durationTicks: 5,
    cooldownTicks: 28,
    effects: { unrest: -5, happiness: -6, corruption: 3, crime: 2 },
    requiresAuthority: 4,
  },
  {
    id: "public_confession_broadcast",
    name: "Public Confession Broadcast",
    description: "Force corrupt officials to publicly confess on broadcast for 2 ticks. Dramatic corruption drop.",
    category: "political",
    cost: 30000,
    durationTicks: 2,
    cooldownTicks: 24,
    effects: { corruption: -8, happiness: 4, unrest: -2, lawEnforcement: 1 },
    requiresAuthority: 3,
  },
  {
    id: "emergency_election",
    name: "Emergency Election",
    description: "Call a snap election for district representatives over 3 ticks. Resets political tension.",
    category: "political",
    cost: 40000,
    durationTicks: 3,
    cooldownTicks: 36,
    effects: { unrest: -8, happiness: 5, corruption: -3, crime: 2 },
  },
  {
    id: "faction_negotiation_summit",
    name: "Faction Negotiation Summit",
    description: "Bring all major factions to the table for 6 ticks. Reduces tensions across the board.",
    category: "political",
    cost: 75000,
    durationTicks: 6,
    cooldownTicks: 30,
    effects: { unrest: -6, happiness: 3, corruption: -2, crime: -2, factionInfluence: { factionId: "corps", delta: -5 } },
  },
  {
    id: "state_of_emergency_decree",
    name: "State of Emergency Decree",
    description: "Declare full state of emergency for 8 ticks. Maximum authority but severe social consequences.",
    category: "political",
    cost: 100000,
    durationTicks: 8,
    cooldownTicks: 36,
    effects: { crime: -10, unrest: 8, happiness: -10, lawEnforcement: 6, corruption: 4 },
    requiresAuthority: 5,
  },
  {
    id: "amnesty_for_dissidents",
    name: "Amnesty for Dissidents",
    description: "Pardon political prisoners and release detainees for 4 ticks. Massive goodwill at security cost.",
    category: "political",
    cost: 20000,
    durationTicks: 4,
    cooldownTicks: 24,
    effects: { happiness: 10, unrest: -6, crime: 4, lawEnforcement: -3 },
  },
  {
    id: "grand_revival",
    name: "Grand Revival Festival",
    description: "City-wide religious festival for 5 ticks. Mandatory attendance. Ecstatic worship. Productivity plummets.",
    category: "social",
    cost: 40000,
    durationTicks: 5,
    cooldownTicks: 25,
    effects: { happiness: 8, unrest: -5, employment: -3, crime: -2 },
  },
  {
    id: "heretic_purge",
    name: "Heretic Purge",
    description: "Systematic arrest and detention of religious dissidents for 4 ticks. Faith through fear.",
    category: "security",
    cost: 60000,
    durationTicks: 4,
    cooldownTicks: 30,
    effects: { crime: -5, happiness: -8, unrest: -4, corruption: 3, lawOrder: 3 },
    requiresAuthority: 4,
  },
  {
    id: "divine_revelation",
    name: "Divine Revelation Broadcast",
    description: "Commander receives a 'divine vision' broadcast on all screens for 3 ticks. The faithful rejoice. Skeptics despair.",
    category: "political",
    cost: 25000,
    durationTicks: 3,
    cooldownTicks: 20,
    effects: { happiness: 4, unrest: -6, corruption: 3 },
  },
  {
    id: "temple_construction_drive",
    name: "Temple Construction Drive",
    description: "Emergency religious infrastructure program for 6 ticks. Every district gets a shrine.",
    category: "infrastructure",
    cost: 80000,
    durationTicks: 6,
    cooldownTicks: 35,
    effects: { happiness: 5, employment: 4, unrest: -3, credits: -30000 },
  },
  {
    id: "miracle_announcement",
    name: "Miracle Announcement",
    description: "Declare a miraculous event in the Grand Temple. 2-tick morale surge. Truth optional.",
    category: "political",
    cost: 15000,
    durationTicks: 2,
    cooldownTicks: 18,
    effects: { happiness: 6, unrest: -4, corruption: 2 },
  },
  {
    id: "inquisition_sweep",
    name: "Grand Inquisition Sweep",
    description: "Door-to-door religious compliance checks for 5 ticks. Apostates identified and detained.",
    category: "security",
    cost: 50000,
    durationTicks: 5,
    cooldownTicks: 28,
    effects: { crime: -6, happiness: -10, unrest: -3, lawOrder: 4, corruption: 4 },
    requiresAuthority: 5,
  },
  {
    id: "holy_war_declaration",
    name: "Holy War Declaration",
    description: "Declare religious war against an external enemy for 8 ticks. Zealous fervor boosts defense.",
    category: "security",
    cost: 100000,
    durationTicks: 8,
    cooldownTicks: 40,
    effects: { defenseRating: 8, happiness: -4, unrest: 5, crime: 3, employment: 3 },
    requiresAuthority: 5,
  },
  {
    id: "mass_baptism",
    name: "Mass Conversion Ceremony",
    description: "City-wide conversion ceremony for 3 ticks. All citizens 'voluntarily' embrace the state faith.",
    category: "social",
    cost: 30000,
    durationTicks: 3,
    cooldownTicks: 22,
    effects: { happiness: 3, unrest: -4, crime: -1, corruption: 2 },
  },
  {
    id: "relic_discovery",
    name: "Sacred Relic Discovery",
    description: "Announce the discovery of a holy artifact for 4 ticks. Pilgrims flock. Revenue surges.",
    category: "economic",
    cost: 20000,
    durationTicks: 4,
    cooldownTicks: 24,
    effects: { happiness: 5, tradeIncome: 800, unrest: -3 },
  },
  {
    id: "doomsday_prophecy",
    name: "Doomsday Prophecy Announcement",
    description: "Prophesy the end times for 3 ticks. Citizens panic-buy supplies. Obedience surges.",
    category: "political",
    cost: 10000,
    durationTicks: 3,
    cooldownTicks: 20,
    effects: { happiness: -5, unrest: -3, lawOrder: 3, foodProduction: -3 },
  },

  // ── MIGRATION EDICTS ────────────────────────────────────────────────
  {
    id: "seal_all_borders",
    name: "Seal All Borders",
    description: "Lock down every entry and exit point to the city for 12 ticks. No immigration, no emigration, no one in or out. Trade income drops and happiness plummets, but population is frozen in place.",
    category: "security",
    cost: 150000,
    durationTicks: 12,
    cooldownTicks: 36,
    effects: {
      happiness: -6,
      unrest: 5,
      crime: -3,
      creditsPerTick: -5000,
      employment: -2,
      bordersClosed: true,
    },
    requiresAuthority: 4,
  },
  {
    id: "wasteland_expedition_mandate",
    name: "Wasteland Expedition Mandate",
    description: "Authorize and fund a wave of wasteland expeditions for 10 ticks. Increased discovery chance and reduced expedition costs.",
    category: "political",
    cost: 40000,
    durationTicks: 10,
    cooldownTicks: 30,
    effects: { happiness: 2, credits: -2000, employment: 1 },
  },
  {
    id: "class_solidarity_decree",
    name: "Class Solidarity Decree",
    description: "Mandate inter-class cooperation programs for 8 ticks. Reduces tension between citizen classes but costs credits and irritates the corporate elite.",
    category: "social",
    cost: 35000,
    durationTicks: 8,
    cooldownTicks: 20,
    effects: { happiness: 4, unrest: -4, credits: -3000, corruption: 1 },
  },
  {
    id: "faction_appeasement_fund",
    name: "Faction Appeasement Fund",
    description: "Establish a discretionary fund for faction gifts and bribes for 6 ticks. Reduces faction threat but increases corruption.",
    category: "political",
    cost: 60000,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: { corruption: 3, unrest: -3, happiness: 1 },
    requiresAuthority: 2,
  },
  {
    id: "emergency_infrastructure_blitz",
    name: "Emergency Infrastructure Blitz",
    description: "Triple all repair crew output for 8 ticks. Mobilize every construction droid and work crew. Infrastructure recovers rapidly but the overtime costs are brutal.",
    category: "infrastructure",
    cost: 80000,
    durationTicks: 8,
    cooldownTicks: 20,
    effects: { infrastructureRepair: 5, credits: -8000, employment: 2, happiness: 1 },
  },
  {
    id: "seasonal_preparedness_act",
    name: "Seasonal Preparedness Act",
    description: "Stockpile emergency supplies and reinforce infrastructure against seasonal events for 12 ticks. Reduces seasonal damage but costs heavily.",
    category: "infrastructure",
    cost: 50000,
    durationTicks: 12,
    cooldownTicks: 30,
    effects: { happiness: 2, infrastructureRepair: 2, credits: -3000 },
  },
  {
    id: "trade_ai_authorization",
    name: "Trade AI Authorization",
    description: "Authorize the city trade AI to operate with expanded parameters for 10 ticks. Automatic resource balancing and emergency procurement.",
    category: "economic",
    cost: 25000,
    durationTicks: 10,
    cooldownTicks: 16,
    effects: { credits: -1000, employment: 1, happiness: 1 },
  },
  {
    id: "gene_wright_amnesty",
    name: "Gene Wright Amnesty",
    description: "Offer temporary amnesty to genetic modification practitioners for 6 ticks. Unlicensed clinics can register. Reduces crime but angers law enforcement.",
    category: "social",
    cost: 20000,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: { crime: -6, happiness: 3, lawEnforcement: -4, corruption: 2 },
  },
  {
    id: "reactor_cult_tolerance",
    name: "Reactor Cult Tolerance Act",
    description: "Officially recognize the Eternal Flame as a legitimate religious organization for 8 ticks. Reduces cult-related unrest but disturbs secular citizens.",
    category: "political",
    cost: 15000,
    durationTicks: 8,
    cooldownTicks: 20,
    effects: { unrest: -5, happiness: -1, corruption: 1 },
  },
  {
    id: "undercity_reclamation",
    name: "Undercity Reclamation Order",
    description: "Launch a coordinated effort to bring order to the undercity districts for 10 ticks. Expensive but dramatically reduces crime and gang influence in lower sectors.",
    category: "security",
    cost: 100000,
    durationTicks: 10,
    cooldownTicks: 30,
    effects: { crime: -10, lawEnforcement: 5, happiness: 2, unrest: -3, credits: -5000 },
    requiresAuthority: 3,
  },
  {
    id: "prestige_propaganda_campaign",
    name: "Prestige Propaganda Campaign",
    description: "Launch a city-wide media campaign celebrating the Commander's achievements for 6 ticks. Boosts happiness and loyalty but the sycophancy breeds corruption.",
    category: "political",
    cost: 30000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: { happiness: 5, unrest: -4, corruption: 3 },
  },
  {
    id: "district_specialization_grant",
    name: "District Specialization Grant",
    description: "Fund district development programs for 8 ticks. Accelerates specialization leveling and provides economic bonuses to specialized districts.",
    category: "economic",
    cost: 45000,
    durationTicks: 8,
    cooldownTicks: 24,
    effects: { employment: 3, happiness: 2, credits: -2000 },
  },
  {
    id: "civil_war_ceasefire_order",
    name: "Civil War Ceasefire Order",
    description: "Impose a mandatory ceasefire on all active faction conflicts for 6 ticks. Heavy enforcement costs. If no civil war is active, provides a general peace dividend.",
    category: "security",
    cost: 75000,
    durationTicks: 6,
    cooldownTicks: 20,
    effects: { unrest: -8, crime: -4, happiness: 3, lawEnforcement: 3, credits: -5000 },
    requiresAuthority: 4,
  },

  // ── Sandbox expansion batch ──────────────────────────────────────────
  // Twelve additional edicts spread across categories to give the
  // sandbox more short-term levers. Infrastructure was the lightest
  // category so it gets four; the rest fill out underweight corners of
  // security, economic, social, and political.
  {
    id: "rolling_blackout_protocol",
    name: "Rolling Blackout Protocol",
    description: "Ration the grid with scheduled district-by-district power cuts for 5 ticks. The lights stay on where they matter most, but everyone else hates it.",
    category: "infrastructure",
    cost: 10000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: { happiness: -4, unrest: 3, infrastructureRepair: 2, creditsPerTick: 1500 },
  },
  {
    id: "transit_fare_holiday",
    name: "Transit Fare Holiday",
    description: "Suspend all transit fares for 6 ticks. Citizens move freely, jobs fill faster, the treasury bleeds.",
    category: "infrastructure",
    cost: 25000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: { happiness: 4, employment: 3, creditsPerTick: -2500 },
  },
  {
    id: "signal_priority_override",
    name: "Emergency Signal Priority Override",
    description: "Override traffic and rail signals to give emergency services a permanent green wave for 4 ticks. Faster response everywhere; commuters fume.",
    category: "infrastructure",
    cost: 15000,
    durationTicks: 4,
    cooldownTicks: 12,
    effects: { lawEnforcement: 3, crime: -2, happiness: -2 },
  },
  {
    id: "drone_resupply_corridor",
    name: "Drone Resupply Corridor",
    description: "Open a continuous drone-flown supply lane to under-served outer sectors for 8 ticks. Costs fuel and credits but holds the periphery together.",
    category: "infrastructure",
    cost: 35000,
    durationTicks: 8,
    cooldownTicks: 22,
    effects: { foodProduction: 4, happiness: 3, creditsPerTick: -2000, unrest: -2 },
  },
  {
    id: "windfall_levy_decree",
    name: "Windfall Levy Decree",
    description: "Impose a one-time windfall tax on corporate balances for 4 ticks. Big revenue lift, real political cost; the boardrooms remember this for years.",
    category: "economic",
    cost: 20000,
    durationTicks: 4,
    cooldownTicks: 30,
    effects: { creditsPerTick: 4500, happiness: -4, corruption: 2, tradeIncome: -3, unrest: 2 },
    requiresAuthority: 3,
  },
  {
    id: "subsidized_basics_program",
    name: "Subsidized Basics Program",
    description: "Cap and subsidize the price of food, water, and fuel for 6 ticks. Citizens love it; the treasury notices immediately.",
    category: "economic",
    cost: 20000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: { happiness: 6, unrest: -3, creditsPerTick: -3500 },
  },
  {
    id: "free_clinic_night",
    name: "Free Clinic Night Initiative",
    description: "Open every public clinic for free walk-in care every night for 5 ticks. Big morale lift; modest hit to law enforcement budgets that get rerouted.",
    category: "social",
    cost: 18000,
    durationTicks: 5,
    cooldownTicks: 15,
    effects: { happiness: 5, unrest: -2, lawEnforcement: -1 },
  },
  {
    id: "quiet_hours_decree",
    name: "Citywide Quiet Hours Decree",
    description: "Mandate noise curfews across all residential sectors for 6 ticks. People sleep better; clubs and night markets quietly seethe.",
    category: "social",
    cost: 5000,
    durationTicks: 6,
    cooldownTicks: 14,
    effects: { happiness: 2, unrest: -2, creditsPerTick: -500 },
  },
  {
    id: "checkpoint_saturation",
    name: "Checkpoint Saturation Order",
    description: "Stand up rolling checkpoints on every major artery for 5 ticks. Crime collapses, but every commute becomes a misery.",
    category: "security",
    cost: 30000,
    durationTicks: 5,
    cooldownTicks: 18,
    effects: { crime: -8, happiness: -5, lawEnforcement: 4, unrest: 2 },
  },
  {
    id: "informant_bounty_surge",
    name: "Informant Bounty Surge",
    description: "Triple cash bounties on tipsters for 6 ticks. Information floods in. Some of it is even true.",
    category: "security",
    cost: 22000,
    durationTicks: 6,
    cooldownTicks: 16,
    effects: { crime: -5, corruption: 2, lawEnforcement: 2, creditsPerTick: -1500 },
  },
  {
    id: "town_hall_marathon",
    name: "Commander's Town Hall Marathon",
    description: "Personally host open-mic sessions in every district for 4 ticks. Happiness climbs and unrest cools while people feel heard.",
    category: "political",
    cost: 12000,
    durationTicks: 4,
    cooldownTicks: 16,
    effects: { happiness: 4, unrest: -3, corruption: -1 },
  },
  {
    id: "petty_offense_amnesty",
    name: "Petty Offense Amnesty",
    description: "Forgive all outstanding citations and minor warrants for 5 ticks. Reduces friction with the public; emboldens the chancers.",
    category: "political",
    cost: 8000,
    durationTicks: 5,
    cooldownTicks: 20,
    effects: { happiness: 3, unrest: -2, crime: 2, lawEnforcement: -2 },
  },

  // ── Sandbox expansion batch (round 2) ────────────────────────────────
  // Twelve more short-term edicts. This round leans on dramatic security
  // and economic levers and adds a couple more political and
  // infrastructure plays to round out the sandbox.
  {
    id: "exo_armor_mobilization",
    name: "Exo-Armor Mobilization",
    description: "Field heavy power-armor units in flashpoint districts for 5 ticks. Crime collapses; the optics are not subtle.",
    category: "security",
    cost: 60000,
    durationTicks: 5,
    cooldownTicks: 22,
    effects: { crime: -9, lawEnforcement: 5, happiness: -3, defenseRating: 2 },
    requiresAuthority: 3,
  },
  {
    id: "deep_scan_sweep",
    name: "Deep Scan Sweep",
    description: "Authorize building-by-building bio/contraband scans for 6 ticks. Catches a lot. Misses nothing. Citizens notice both.",
    category: "security",
    cost: 28000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: { crime: -6, corruption: -2, happiness: -3, lawEnforcement: 3 },
  },
  {
    id: "perimeter_hardening_drive",
    name: "Perimeter Hardening Drive",
    description: "Reinforce sector wall fortifications and sensor lines for 8 ticks. Defenders dig in deep; civilian budgets feel the squeeze.",
    category: "security",
    cost: 55000,
    durationTicks: 8,
    cooldownTicks: 28,
    effects: { defenseRating: 4, infrastructureRepair: 2, creditsPerTick: -1500 },
  },
  {
    id: "innovation_grant_burst",
    name: "Innovation Grant Burst",
    description: "Fire a one-shot wave of R&D grants for 6 ticks. Research output spikes; the grant office runs on coffee.",
    category: "economic",
    cost: 40000,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: { researchSpeed: 4, happiness: 2, creditsPerTick: -2000 },
  },
  {
    id: "wage_freeze_decree",
    name: "Public-Sector Wage Freeze",
    description: "Suspend public-sector wage increases for 6 ticks. Treasury breathes; morale doesn't.",
    category: "economic",
    cost: 0,
    durationTicks: 6,
    cooldownTicks: 24,
    effects: { creditsPerTick: 3500, happiness: -4, unrest: 2, employment: -1 },
  },
  {
    id: "emergency_debt_buyback",
    name: "Emergency Debt Buyback",
    description: "Have the city repurchase distressed citizen debt at par for 4 ticks. Big upfront cost, big morale lift, real political capital.",
    category: "economic",
    cost: 80000,
    durationTicks: 4,
    cooldownTicks: 30,
    effects: { happiness: 7, unrest: -5, employment: 2, creditsPerTick: -3000 },
    requiresAuthority: 3,
  },
  {
    id: "youth_employment_corps",
    name: "Youth Employment Corps",
    description: "Stand up paid public-works placements for under-25s for 8 ticks. Streets clear of idle teens; payroll office groans.",
    category: "social",
    cost: 25000,
    durationTicks: 8,
    cooldownTicks: 22,
    effects: { employment: 5, crime: -3, happiness: 3, creditsPerTick: -2000 },
  },
  {
    id: "elder_pension_top_up",
    name: "Elder Pension Top-Up",
    description: "Issue a one-cycle bonus to every retiree's pension for 5 ticks. The grateful constituency is the most reliable kind.",
    category: "social",
    cost: 30000,
    durationTicks: 5,
    cooldownTicks: 20,
    effects: { happiness: 5, unrest: -3, populationGrowth: 0.002, creditsPerTick: -2500 },
  },
  {
    id: "sewage_overhaul_blitz",
    name: "Sewage Overhaul Blitz",
    description: "Run an emergency rebuild on the under-district sanitation grid for 8 ticks. Disease drops; the smell improves; budget evaporates.",
    category: "infrastructure",
    cost: 45000,
    durationTicks: 8,
    cooldownTicks: 26,
    effects: { happiness: 4, infrastructureRepair: 4, populationGrowth: 0.002, creditsPerTick: -2500 },
  },
  {
    id: "skywalk_pedestrian_priority",
    name: "Skywalk Pedestrian Priority",
    description: "Reserve elevated walkways for foot traffic only for 6 ticks. People love it; cargo operators reroute and grumble.",
    category: "infrastructure",
    cost: 12000,
    durationTicks: 6,
    cooldownTicks: 18,
    effects: { happiness: 3, tradeIncome: -2, infrastructureRepair: 1 },
  },
  {
    id: "loyalty_review_board",
    name: "Loyalty Review Board Convened",
    description: "Stand up an independent panel to vet senior officials for 5 ticks. Corruption flushes out; nervous resignations follow.",
    category: "political",
    cost: 22000,
    durationTicks: 5,
    cooldownTicks: 24,
    effects: { corruption: -4, happiness: 2, unrest: 1, lawEnforcement: 1 },
    requiresAuthority: 2,
  },
  {
    id: "open_records_initiative",
    name: "Open Records Initiative",
    description: "Publish full ledgers, contracts, and meeting minutes for 6 ticks. Trust climbs; a few skeletons fall out of closets.",
    category: "political",
    cost: 8000,
    durationTicks: 6,
    cooldownTicks: 22,
    effects: { happiness: 4, corruption: -3, unrest: -2 },
  },
  // Task #529: second lever on troop training speed alongside the
  // facility route (Task #526). While active, unit training orders placed
  // are 25% faster (min 1 tick), stacking with training facilities up to
  // a combined 50% cut. The reduction is applied AT ORDER TIME inside
  // engine/pendingConstruction.ts (getTrainingSpeedReduction reads
  // state.activeEdicts for this id) — it is NOT an EdictEffect key, so
  // the per-tick edict loop only handles the upkeep drain below.
  {
    id: "accelerated_training_doctrine",
    name: "Accelerated Training Doctrine",
    description: "Compress drills, run ranges around the clock, and waive rest rotations for 16 ticks. Troop training orders placed while active complete 25% faster (stacks with training facilities, up to 50% total), but instructor overtime drains the treasury every tick.",
    category: "security",
    cost: 60000,
    durationTicks: 16,
    cooldownTicks: 36,
    effects: {
      creditsPerTick: -4000,
    },
  },
];

import { BB_EDICTS } from "@/engine/addons/bigBrother";
import { SD_EDICTS } from "@/engine/addons/sixthDay";

// These are deliberately omitted from EDICTS so they do not appear as
// authorable Law-screen directives. Labour Day responses grant them directly,
// while the normal edict processor still provides ticking, save persistence,
// offline expiry, and cooldown bookkeeping.
const LABOUR_DAY_EDICTS: EdictDef[] = [
  {
    id: LABOUR_DAY_BOOSTER_IDS[0],
    name: "Paid Leave Dividend",
    description: "A short paid-leave window returns a Labour Fund dividend to working households.",
    category: "social",
    cost: 0,
    durationTicks: 8,
    cooldownTicks: 0,
    effects: { creditsPerTick: 900 },
  },
  {
    id: LABOUR_DAY_BOOSTER_IDS[1],
    name: "Public Works Drive",
    description: "Union crews receive a public-works dividend for the holiday week.",
    category: "infrastructure",
    cost: 0,
    durationTicks: 8,
    cooldownTicks: 0,
    effects: { creditsPerTick: 600, tradeIncome: 300 },
  },
  {
    id: LABOUR_DAY_BOOSTER_IDS[2],
    name: "Production Push",
    description: "A tightly rationed holiday production push pays crews for keeping the lines moving.",
    category: "economic",
    cost: 0,
    durationTicks: 8,
    cooldownTicks: 0,
    effects: { creditsPerTick: 1500 },
  },
];

export const ALL_EDICTS: EdictDef[] = [...EDICTS, ...BB_EDICTS, ...SD_EDICTS];

export function getEdictById(id: string): EdictDef | undefined {
  return (
    ALL_EDICTS.find((e) => e.id === id) ??
    LABOUR_DAY_EDICTS.find((e) => e.id === id)
  );
}
