export type IllnessCategory = "regular" | "humorous" | "megacity" | "mutation" | "radiation";

export type IllnessDef = {
  id: string;
  name: string;
  category: IllnessCategory;
  description: string;
  medications: string[];
  productionChain: string[];
  researchChain: string[];
  events: string[];
  effects: Partial<{
    hospitalLoad: number;
    happiness: number;
    productivity: number;
    unrest: number;
    crime: number;
    population: number;
  }>;
};

export const ILLNESS_CATEGORIES: Record<IllnessCategory, string> = {
  regular: "COMMON ILLNESSES",
  humorous: "BIZARRE CONDITIONS",
  megacity: "MEGACITY MEDICAL",
  mutation: "MUTATIONS",
  radiation: "RADIATION SICKNESS",
};

export const ILLNESSES: IllnessDef[] = [
  {
    id: "seasonal_flu",
    name: "Seasonal Flu",
    category: "regular",
    description: "Viral respiratory infection. Spreads rapidly through dense habitation blocks.",
    medications: ["FluVax-C", "Antiviral Tabs"],
    productionChain: ["Viral sample collection", "Protein antigen synthesis", "Stabilizer compound mixing", "Sterile vial production", "Cold storage packaging"],
    researchChain: ["Viral strain cataloging", "Antigen targeting", "Vaccine stability testing", "Mass immunization logistics"],
    events: ["Flu Season Begins", "Vaccination Campaign", "Workforce Sick Leave Spike"],
    effects: { hospitalLoad: 12, happiness: -4, productivity: -8 },
  },
  {
    id: "bacterial_pneumonia",
    name: "Bacterial Pneumonia",
    category: "regular",
    description: "Aggressive bacterial lung infection. Thrives in poorly ventilated underhive sectors.",
    medications: ["AeroMycin Antibiotic"],
    productionChain: ["Bacterial culture labs", "Antibiotic fermentation", "Chemical purification", "Tablet pressing", "Pharmacy distribution"],
    researchChain: ["Antibiotic strain discovery", "Lung infection modeling", "Resistance suppression tech"],
    events: ["Hospital Bed Shortage", "Antibiotic Resistance Warning"],
    effects: { hospitalLoad: 15, happiness: -4, productivity: -8 },
  },
  {
    id: "food_poisoning",
    name: "Food Poisoning",
    category: "regular",
    description: "Mass contamination from street vendor circuits and nutrient paste irregularities.",
    medications: ["DigestAid Rehydration Pack", "GastroClear Tablets"],
    productionChain: ["Electrolyte extraction", "Chemical stabilization", "Powder sachet packaging"],
    researchChain: ["Urban food pathogen tracking", "Sanitation analytics"],
    events: ["Street Vendor Contamination", "Health Inspector Crackdown"],
    effects: { hospitalLoad: 8, happiness: -5, unrest: 2 },
  },
  {
    id: "heatstroke",
    name: "Heatstroke",
    category: "regular",
    description: "Thermal overload from industrial heat venting and climate control failures.",
    medications: ["Coolant IV Solution"],
    productionChain: ["Electrolyte synthesis", "Medical IV bag production", "Refrigerated transport"],
    researchChain: ["Climate hazard monitoring", "Cooling treatment optimization"],
    events: ["Urban Heat Wave", "Power Grid Stress"],
    effects: { hospitalLoad: 12, happiness: -6, productivity: -10 },
  },
  {
    id: "dermal_infection",
    name: "Dermal Infection",
    category: "regular",
    description: "Skin infections rampant in slum sectors. Spreads through contaminated water.",
    medications: ["SkinShield Antibiotic Cream"],
    productionChain: ["Antibiotic compound synthesis", "Medical gel production", "Tube filling line"],
    researchChain: ["Urban bacteria mapping", "Skin microbiome studies"],
    events: ["Slum Infection Outbreak", "Free Clinic Campaign"],
    effects: { hospitalLoad: 6, happiness: -3 },
  },
  {
    id: "laughing_lung",
    name: "Laughing Lung",
    category: "humorous",
    description: "Citizens uncontrollably laugh while coughing. Highly contagious. Mildly entertaining.",
    medications: ["GiggleGone Suppressant"],
    productionChain: ["Humor receptor inhibitor synthesis", "Capsule manufacturing", "Public pharmacy rollout"],
    researchChain: ["Laughter reflex mapping", "Respiratory neural circuits"],
    events: ["Mass Laughter Riot", "Comedy Club Quarantine"],
    effects: { hospitalLoad: 5, happiness: 2, productivity: -8 },
  },
  {
    id: "bureaucratic_paralysis",
    name: "Bureaucratic Paralysis",
    category: "humorous",
    description: "Citizens freeze whenever paperwork appears. Administrative sectors grind to a halt.",
    medications: ["Adminex Motivation Shots"],
    productionChain: ["Neural stimulant extraction", "Injectable ampoules", "Civic clinic distribution"],
    researchChain: ["Administrative trauma studies", "Cognitive overload suppression"],
    events: ["Permit Office Shutdown", "Citywide Form Backlog"],
    effects: { productivity: -15, unrest: 5 },
  },
  {
    id: "neon_eye",
    name: "Neon Eye",
    category: "humorous",
    description: "Eyes glow from excessive billboard exposure. Sufferers can see in the dark.",
    medications: ["OptiShade Drops"],
    productionChain: ["Anti-photon compound synthesis", "Sterile eyedrop filling"],
    researchChain: ["Photonic retinal damage", "Advertising light mitigation"],
    events: ["Billboard Malfunction Storm", "Nighttime Vision Boost"],
    effects: { hospitalLoad: 3, happiness: -2 },
  },
  {
    id: "caffeine_heart",
    name: "Caffeine Heart",
    category: "humorous",
    description: "Caused by extreme energy drink consumption. Hearts beat at 200 BPM.",
    medications: ["PulseBalancer Tablets"],
    productionChain: ["Heart rhythm stabilizer synthesis", "Tablet press factory"],
    researchChain: ["Urban stimulant addiction studies", "Metabolic regulation"],
    events: ["Energy Drink Recall", "Citizen Productivity Spike"],
    effects: { hospitalLoad: 7, productivity: 5, happiness: -3 },
  },
  {
    id: "holo_rash",
    name: "Holo Rash",
    category: "humorous",
    description: "Skin irritation from cheap holographic clothing. Fashion victims everywhere.",
    medications: ["DermalFilter Cream"],
    productionChain: ["Polymer neutralizers", "Skin repair compounds", "Cream packaging"],
    researchChain: ["Synthetic fabric toxicity", "Nano-fiber safety"],
    events: ["Fashion District Outbreak", "Clothing Industry Lawsuit"],
    effects: { hospitalLoad: 4, happiness: -4, crime: 1 },
  },
  {
    id: "towerblock_lung",
    name: "Towerblock Lung",
    category: "megacity",
    description: "Pollution disease caused by dense city living. The underhive signature illness.",
    medications: ["AeroPure Nanoinhaler"],
    productionChain: ["Nano-filter fabrication", "Medical inhaler assembly", "Distribution via clinics"],
    researchChain: ["Pollution particle mapping", "Lung nanomedicine"],
    events: ["Smog Crisis", "Air Purification Subsidy"],
    effects: { hospitalLoad: 14, happiness: -5, productivity: -7 },
  },
  {
    id: "comm_signal_burn",
    name: "Comm-Signal Burn",
    category: "megacity",
    description: "Brain stress from constant data streams. Information overload made physical.",
    medications: ["NeuroQuiet Patches"],
    productionChain: ["Neural stabilizer synthesis", "Patch manufacturing"],
    researchChain: ["Cognitive overload modeling", "Neural signal dampening"],
    events: ["Citywide Data Storm", "Network Outage Relief"],
    effects: { hospitalLoad: 8, happiness: -6, productivity: -10 },
  },
  {
    id: "hover_traffic_vertigo",
    name: "Hover Traffic Vertigo",
    category: "megacity",
    description: "Dizziness caused by heavy aerial traffic. Upper-level dwellers most affected.",
    medications: ["BalanceAid Injectors"],
    productionChain: ["Inner ear stabilizer synthesis", "Auto-injector assembly"],
    researchChain: ["Vestibular system simulation", "Motion tolerance drugs"],
    events: ["Aerial Traffic Jam", "Pilot License Review"],
    effects: { hospitalLoad: 6, happiness: -3, productivity: -4 },
  },
  {
    id: "riot_gas_residue",
    name: "Riot Gas Residue Syndrome",
    category: "megacity",
    description: "Aftereffects from security gas deployment. The cost of crowd control.",
    medications: ["ToxiClear Detox Kits"],
    productionChain: ["Chemical neutralizers", "Portable detox kits"],
    researchChain: ["Crowd-control chemical analysis", "Detoxification nanotech"],
    events: ["Protest Crackdown", "Civil Rights Investigation"],
    effects: { hospitalLoad: 9, happiness: -7, unrest: 8 },
  },
  {
    id: "synthetic_food_dependency",
    name: "Synthetic Food Dependency",
    category: "megacity",
    description: "Citizens addicted to cheap nutrient paste. Withdrawal causes severe symptoms.",
    medications: ["NutraReset Therapy"],
    productionChain: ["Metabolic regulators", "Nutrient replacement capsules"],
    researchChain: ["Synthetic diet health impacts", "Metabolic rebalancing"],
    events: ["Food Riots", "Organic Farm Subsidy"],
    effects: { hospitalLoad: 10, happiness: -8, unrest: 6, crime: 3 },
  },
  {
    id: "dermal_scaling",
    name: "Dermal Scaling",
    category: "mutation",
    description: "Citizens develop reptile-like skin. Social stigma. Enhanced durability.",
    medications: ["ScaleSoft Serum"],
    productionChain: ["Genetic stabilizer compounds", "Injectable serum labs"],
    researchChain: ["Mutation genome mapping", "Cellular skin repair"],
    events: ["Mutation Registry Act", "Black Market Mutation Clinics"],
    effects: { happiness: -4, unrest: 5, crime: 2 },
  },
  {
    id: "glowblood",
    name: "Glowblood",
    category: "mutation",
    description: "Blood emits faint light due to radiation exposure. Makes stealth impossible.",
    medications: ["RadNeutral Infusion"],
    productionChain: ["Radiation-binding isotopes", "Medical infusion bags"],
    researchChain: ["Radiation metabolism", "Cellular shielding proteins"],
    events: ["Night Patrol Detection Boost", "Radiation Leak Investigation"],
    effects: { happiness: -3, crime: -2 },
  },
  {
    id: "bone_density_surge",
    name: "Bone Density Surge",
    category: "mutation",
    description: "Citizens develop extremely dense skeletons. Enhanced strength but mobility issues.",
    medications: ["OsteoBalance Injections"],
    productionChain: ["Bone regulator peptides", "Sterile injector kits"],
    researchChain: ["Skeletal growth control", "Calcium metabolism modeling"],
    events: ["Industrial Workforce Boost", "Hospital Equipment Stress"],
    effects: { hospitalLoad: 5, productivity: 3, happiness: -2 },
  },
  {
    id: "gilled_throat",
    name: "Gilled Throat",
    category: "mutation",
    description: "Citizens develop minor gill structures. Opens aquatic labor opportunities.",
    medications: ["RespiraMod Gene Therapy"],
    productionChain: ["Gene editing vectors", "Cryogenic storage"],
    researchChain: ["Amphibious mutation genetics", "Respiratory adaptation"],
    events: ["Aquatic Labor Opportunities", "Mutation Rights Movement"],
    effects: { happiness: -3, unrest: 4 },
  },
  {
    id: "hyper_melanin",
    name: "Hyper-Melanin Skin",
    category: "mutation",
    description: "Skin becomes extremely radiation resistant. Valued in hazardous sectors.",
    medications: ["MelanoReg Therapy"],
    productionChain: ["Pigment regulator enzymes", "Dermal treatment clinics"],
    researchChain: ["Radiation protection biology", "Pigment control genetics"],
    events: ["Radiation Workforce Program", "Mutation Employment Act"],
    effects: { happiness: -1, productivity: 2 },
  },
  {
    id: "acute_radiation_sickness",
    name: "Acute Radiation Sickness",
    category: "radiation",
    description: "Exposure from reactor leaks, dirty bombs, or industrial accidents. Lethal without treatment.",
    medications: ["RadAway Serum", "BoneMarrow Stimulators"],
    productionChain: ["Isotope absorption compound synthesis", "Chelation chemical refinement", "Injectable serum formulation", "Sterile ampoule manufacturing", "Emergency stockpile distribution"],
    researchChain: ["Radiation dose mapping", "Cellular DNA repair compounds", "Hematopoietic recovery drugs", "Emergency treatment protocols"],
    events: ["Reactor Accident", "Nuclear Transport Crash", "Emergency Hospital Overflow"],
    effects: { hospitalLoad: 25, happiness: -10, productivity: -15, population: -50 },
  },
  {
    id: "chronic_radiation_fatigue",
    name: "Chronic Radiation Fatigue",
    category: "radiation",
    description: "Long-term exposure in polluted districts. Permanent tiredness and weakness.",
    medications: ["RadShield Tablets"],
    productionChain: ["Trace mineral extraction", "Anti-radiation compound synthesis", "Capsule manufacturing", "Worker distribution programs"],
    researchChain: ["Long-term radiation metabolism", "Cellular repair proteins", "Radiation tolerance genetics"],
    events: ["Worker Productivity Drop", "Radiation Worker Compensation Program"],
    effects: { hospitalLoad: 8, productivity: -12, happiness: -5 },
  },
  {
    id: "glowing_dermatitis",
    name: "Glowing Dermatitis",
    category: "radiation",
    description: "Skin becomes luminous and burns easily. Some citizens exploit the glow.",
    medications: ["DermRad Cream"],
    productionChain: ["Radiation neutralizing enzymes", "Skin regeneration gel", "Medical cream packaging"],
    researchChain: ["Dermal radiation damage studies", "Skin regeneration biotech"],
    events: ["Cosmetic Panic", "Illegal Glow Clubs"],
    effects: { hospitalLoad: 6, happiness: -4, crime: 2 },
  },
  {
    id: "nuclear_cataracts",
    name: "Nuclear Cataracts",
    category: "radiation",
    description: "Eyes cloud due to radiation exposure. Vision impairment surge across sectors.",
    medications: ["OptiClear Lens Implants"],
    productionChain: ["Synthetic lens manufacturing", "Surgical nanopolymer production", "Ophthalmology clinic deployment"],
    researchChain: ["Radiation eye damage", "Artificial ocular implants"],
    events: ["Vision Impairment Surge", "Free Surgery Programs"],
    effects: { hospitalLoad: 10, happiness: -6, productivity: -8 },
  },
  {
    id: "bone_ash_syndrome",
    name: "Bone Ash Syndrome",
    category: "radiation",
    description: "Bones weaken and crumble from radiation damage. Construction workers most at risk.",
    medications: ["OsteoRad Injectors"],
    productionChain: ["Calcium stabilizer synthesis", "Bone regeneration peptides", "Injector manufacturing"],
    researchChain: ["Skeletal radiation damage", "Regenerative bone therapies"],
    events: ["Construction Worker Disability Spike", "Medical Subsidy Programs"],
    effects: { hospitalLoad: 12, productivity: -10, happiness: -5 },
  },
  {
    id: "gamma_fever",
    name: "Gamma Fever",
    category: "radiation",
    description: "Extreme fever caused by gamma radiation damage. Requires immediate hospitalization.",
    medications: ["GammaCool IV"],
    productionChain: ["Heat-regulating compounds", "Cellular stabilizers", "IV bag manufacturing"],
    researchChain: ["Radiation fever modeling", "Thermal cell regulation"],
    events: ["Hospital Overcrowding", "Quarantine Wards Activated"],
    effects: { hospitalLoad: 20, happiness: -8, productivity: -12 },
  },
  {
    id: "mutation_trigger_syndrome",
    name: "Mutation Trigger Syndrome",
    category: "radiation",
    description: "Radiation exposure triggers unstable physical mutations. Panic and stigma follow.",
    medications: ["GenomeLock Serum"],
    productionChain: ["Genetic stabilizer synthesis", "Viral gene therapy vectors", "Cryogenic medical storage"],
    researchChain: ["Radiation mutation genetics", "DNA stabilization therapies"],
    events: ["Mutation Panic", "Black Market Mutation Clinics"],
    effects: { hospitalLoad: 15, happiness: -10, unrest: 10, crime: 5 },
  },
  {
    id: "rad_lung",
    name: "Rad Lung",
    category: "radiation",
    description: "Radioactive dust damages lung tissue. Miners and waste workers most affected.",
    medications: ["NanoFilter Inhaler"],
    productionChain: ["Nanoparticle lung filters", "Inhaler device assembly", "Pharmacy distribution"],
    researchChain: ["Radioactive particulate study", "Nanomedical lung repair"],
    events: ["Smog Storms", "Mine Worker Protests"],
    effects: { hospitalLoad: 14, productivity: -10, happiness: -6, unrest: 4 },
  },
  {
    id: "neon_blood_disorder",
    name: "Neon Blood Disorder",
    category: "radiation",
    description: "Blood becomes radioactive and luminous. Medical curiosity tourism emerges.",
    medications: ["IsotopeFlush Infusion"],
    productionChain: ["Chelating agents", "Isotope binding compounds", "Infusion bag production"],
    researchChain: ["Blood radiation chemistry", "Cellular detoxification"],
    events: ["Night Patrol Detection Bonuses", "Medical Curiosity Tourism"],
    effects: { hospitalLoad: 8, happiness: -3, crime: -1 },
  },
  {
    id: "reactor_worker_collapse",
    name: "Reactor Worker Collapse",
    category: "radiation",
    description: "Extreme radiation fatigue affecting reactor technicians. Strikes and shutdowns.",
    medications: ["RegenStim Booster"],
    productionChain: ["Metabolic stimulants", "Cellular repair compounds", "Booster injector manufacturing"],
    researchChain: ["Worker radiation tolerance", "Occupational radiation medicine"],
    events: ["Reactor Maintenance Strikes", "Emergency Reactor Shutdown"],
    effects: { hospitalLoad: 11, productivity: -14, unrest: 7 },
  },
];

export const ILLNESS_CATEGORY_ICONS: Record<IllnessCategory, string> = {
  regular: "thermometer",
  humorous: "smile",
  megacity: "activity",
  mutation: "zap",
  radiation: "alert-triangle",
};
