export type ResourceNodeType =
  | "scrap"
  | "fuel"
  | "game_hunting"
  | "flora"
  | "minerals"
  | "water"
  | "salvage_tech"
  | "bio_samples"
  | "coastal"
  | "ocean";

export type ResourceNodeRichness = "scarce" | "moderate" | "rich" | "abundant";

export const RESOURCE_NODE_LABELS: Record<ResourceNodeType, string> = {
  scrap: "Scrap Salvage",
  fuel: "Fuel Deposit",
  game_hunting: "Hunting Grounds",
  flora: "Harvestable Flora",
  minerals: "Mineral Deposit",
  water: "Water Source",
  salvage_tech: "Tech Salvage",
  bio_samples: "Bio-Specimen Site",
  coastal: "Coastal Yield",
  ocean: "Deep Ocean Site",
};

export const RESOURCE_NODE_ICONS: Record<ResourceNodeType, string> = {
  scrap: "tool",
  fuel: "droplet",
  game_hunting: "crosshair",
  flora: "feather",
  minerals: "hexagon",
  water: "cloud-rain",
  salvage_tech: "cpu",
  bio_samples: "activity",
  coastal: "anchor",
  ocean: "navigation",
};

export const RESOURCE_NODE_COLORS: Record<ResourceNodeType, string> = {
  scrap: "#B87333",
  fuel: "#FF9500",
  game_hunting: "#8B4513",
  flora: "#228B22",
  minerals: "#C0C0C0",
  water: "#4DA6FF",
  salvage_tech: "#B855FF",
  bio_samples: "#00CED1",
  coastal: "#4A90B8",
  ocean: "#2A5080",
};

export const RICHNESS_LABELS: Record<ResourceNodeRichness, string> = {
  scarce: "SCARCE",
  moderate: "MODERATE",
  rich: "RICH",
  abundant: "ABUNDANT",
};

export const RICHNESS_MULT: Record<ResourceNodeRichness, number> = {
  scarce: 0.5,
  moderate: 1.0,
  rich: 1.5,
  abundant: 2.0,
};

export type ResourceNodeYield = {
  credits?: number;
  food?: number;
  fuel?: number;
  steel?: number;
  medSupplies?: number;
  ammo?: number;
};

export type ResourceNodeDef = {
  locationId: string;
  resourceType: ResourceNodeType;
  richness: ResourceNodeRichness;
  surveyCost: number;
  exploitCost: number;
  yieldPerTick: ResourceNodeYield;
  dangerLevel: number;
  depletionTicks: number;
  notes: string;
};

export const RESOURCE_NODE_DEFS: ResourceNodeDef[] = [
  {
    locationId: "rn-iron-gulch",
    resourceType: "minerals",
    richness: "rich",
    surveyCost: 2000,
    exploitCost: 15000,
    yieldPerTick: { steel: 80, credits: 500 },
    dangerLevel: 25,
    depletionTicks: 800,
    notes: "High-grade iron ore exposed by tectonic shift. Pre-war miners started a shaft — their skeletons mark the entrance.",
  },
  {
    locationId: "rn-blackwater-seep",
    resourceType: "fuel",
    richness: "abundant",
    surveyCost: 3000,
    exploitCost: 25000,
    yieldPerTick: { fuel: 120, credits: 800 },
    dangerLevel: 35,
    depletionTicks: 600,
    notes: "Crude oil bubbling to the surface through fractured bedrock. Smells terrible. Burns beautifully.",
  },
  {
    locationId: "rn-verdant-hollow",
    resourceType: "flora",
    richness: "moderate",
    surveyCost: 1500,
    exploitCost: 8000,
    yieldPerTick: { food: 60, medSupplies: 20 },
    dangerLevel: 15,
    depletionTicks: 0,
    notes: "Sheltered valley where pre-war botanical gardens went feral. Medicinal herbs grow alongside edible mutant fruit. Tastes odd. Nutritious though.",
  },
  {
    locationId: "rn-rust-canyon",
    resourceType: "scrap",
    richness: "abundant",
    surveyCost: 1000,
    exploitCost: 6000,
    yieldPerTick: { steel: 100, credits: 300 },
    dangerLevel: 20,
    depletionTicks: 1200,
    notes: "A canyon filled with pre-war vehicles, appliances, and industrial debris. Decades of dumping created a scavenger's paradise. Tetanus is the main predator.",
  },
  {
    locationId: "rn-staghorn-wastes",
    resourceType: "game_hunting",
    richness: "moderate",
    surveyCost: 1500,
    exploitCost: 10000,
    yieldPerTick: { food: 90, credits: 200 },
    dangerLevel: 40,
    depletionTicks: 0,
    notes: "Mutant megafauna roam these plains. Stag-like creatures with bony exoskeletons. Excellent protein source. They fight back.",
  },
  {
    locationId: "rn-aquifer-seven",
    resourceType: "water",
    richness: "rich",
    surveyCost: 2500,
    exploitCost: 18000,
    yieldPerTick: { credits: 1200 },
    dangerLevel: 10,
    depletionTicks: 0,
    notes: "Deep underground aquifer. Remarkably clean. In the wasteland, clean water is worth more than gold. Much more.",
  },
  {
    locationId: "rn-datacore-crash",
    resourceType: "salvage_tech",
    richness: "rich",
    surveyCost: 4000,
    exploitCost: 30000,
    yieldPerTick: { credits: 2000 },
    dangerLevel: 50,
    depletionTicks: 400,
    notes: "Crashed military logistics satellite. Data cores intact. Pre-war encryption, but the hardware alone is priceless. Automated defense turrets still active.",
  },
  {
    locationId: "rn-spore-caves",
    resourceType: "bio_samples",
    richness: "moderate",
    surveyCost: 3000,
    exploitCost: 20000,
    yieldPerTick: { medSupplies: 40, credits: 600 },
    dangerLevel: 55,
    depletionTicks: 0,
    notes: "Cave network hosting bioluminescent organisms with remarkable regenerative properties. Pharmaceutical potential is enormous. So is the smell.",
  },
  {
    locationId: "rn-pipeline-junction",
    resourceType: "fuel",
    richness: "moderate",
    surveyCost: 1500,
    exploitCost: 12000,
    yieldPerTick: { fuel: 60, credits: 400 },
    dangerLevel: 30,
    depletionTicks: 500,
    notes: "Pre-war pipeline crossroads. Three major lines converge here. Residual pressure keeps fuel flowing. Bandits know this too.",
  },
  {
    locationId: "rn-boneyard-flats",
    resourceType: "scrap",
    richness: "moderate",
    surveyCost: 800,
    exploitCost: 5000,
    yieldPerTick: { steel: 50, ammo: 10 },
    dangerLevel: 35,
    depletionTicks: 900,
    notes: "Military vehicle graveyard. Tanks, APCs, artillery pieces — all destroyed but full of salvageable parts. And unexploded ordnance. Careful.",
  },
  {
    locationId: "rn-crystal-ridge",
    resourceType: "minerals",
    richness: "moderate",
    surveyCost: 2000,
    exploitCost: 14000,
    yieldPerTick: { credits: 900, steel: 30 },
    dangerLevel: 20,
    depletionTicks: 700,
    notes: "Ridge formation rich in crystalline minerals. Pre-war geologists mapped extensive deposits before being eaten by something. Surveys suggest the something has moved on.",
  },
  {
    locationId: "rn-marshbloom-delta",
    resourceType: "flora",
    richness: "rich",
    surveyCost: 1200,
    exploitCost: 9000,
    yieldPerTick: { food: 80, medSupplies: 35, credits: 200 },
    dangerLevel: 25,
    depletionTicks: 0,
    notes: "Wetland delta where radiation-resistant reed species produce edible tubers. Also home to carnivorous lilies. Harvest carefully.",
  },
  {
    locationId: "rn-silent-springs",
    resourceType: "water",
    richness: "moderate",
    surveyCost: 1800,
    exploitCost: 11000,
    yieldPerTick: { credits: 700 },
    dangerLevel: 15,
    depletionTicks: 0,
    notes: "Natural spring emerging from limestone caves. Locals consider it sacred. They're right — it's one of the few uncontaminated sources within 500km.",
  },
  {
    locationId: "rn-predator-vale",
    resourceType: "game_hunting",
    richness: "rich",
    surveyCost: 2500,
    exploitCost: 16000,
    yieldPerTick: { food: 140, credits: 500 },
    dangerLevel: 65,
    depletionTicks: 0,
    notes: "Dense canyon ecosystem teeming with mutant fauna. Apex predators the size of trucks. Hunting is extremely rewarding. Survival is not guaranteed.",
  },
  {
    locationId: "rn-bunker-19-wreck",
    resourceType: "salvage_tech",
    richness: "moderate",
    surveyCost: 3500,
    exploitCost: 22000,
    yieldPerTick: { credits: 1400, ammo: 15 },
    dangerLevel: 45,
    depletionTicks: 350,
    notes: "Collapsed government bunker. Most levels flooded but upper storage contains pre-war tech, medical equipment, and weapons caches. Automated sentries patrol level 3.",
  },
  {
    locationId: "rn-glowing-basin",
    resourceType: "bio_samples",
    richness: "rich",
    surveyCost: 4000,
    exploitCost: 28000,
    yieldPerTick: { medSupplies: 60, credits: 1000 },
    dangerLevel: 70,
    depletionTicks: 0,
    notes: "Irradiated depression hosting extremophile organisms. Their cells repair DNA damage. Biotech applications are staggering. Getting samples without dying is the challenge.",
  },
  {
    locationId: "rn-copper-teeth",
    resourceType: "minerals",
    richness: "scarce",
    surveyCost: 1000,
    exploitCost: 7000,
    yieldPerTick: { steel: 25, credits: 250 },
    dangerLevel: 15,
    depletionTicks: 500,
    notes: "Copper and zinc deposits in weathered rock formations. Not glamorous. Not dangerous. Honest work in dishonest times.",
  },
  {
    locationId: "rn-razorback-range",
    resourceType: "game_hunting",
    richness: "scarce",
    surveyCost: 1000,
    exploitCost: 6000,
    yieldPerTick: { food: 40, credits: 100 },
    dangerLevel: 30,
    depletionTicks: 0,
    notes: "Rocky highland with sparse mutant goat herds. Small returns but consistent. The goats have six legs and bad attitudes.",
  },
  {
    locationId: "rn-magma-vents",
    resourceType: "fuel",
    richness: "abundant",
    surveyCost: 4000,
    exploitCost: 32000,
    yieldPerTick: { fuel: 140, credits: 900 },
    dangerLevel: 75,
    depletionTicks: 0,
    notes: "Geothermal vents tap pre-collapse magma chambers. Pipes melt. Crews rotate weekly. The output is worth every funeral.",
  },
  {
    locationId: "rn-fossil-quarry",
    resourceType: "minerals",
    richness: "rich",
    surveyCost: 2200,
    exploitCost: 16000,
    yieldPerTick: { steel: 70, credits: 700 },
    dangerLevel: 20,
    depletionTicks: 750,
    notes: "Pre-war fossil dig converted into open-pit mining. The paleontologists left their equipment. The equipment still works.",
  },
  {
    locationId: "rn-windmill-graveyard",
    resourceType: "scrap",
    richness: "rich",
    surveyCost: 1200,
    exploitCost: 7500,
    yieldPerTick: { steel: 90, credits: 350 },
    dangerLevel: 18,
    depletionTicks: 1000,
    notes: "Three hundred toppled wind turbines. Fiberglass blades long enough to roof a town. Copper windings still in the nacelles.",
  },
  {
    locationId: "rn-thunder-plains",
    resourceType: "game_hunting",
    richness: "abundant",
    surveyCost: 2800,
    exploitCost: 18000,
    yieldPerTick: { food: 160, credits: 600 },
    dangerLevel: 70,
    depletionTicks: 0,
    notes: "Bison-sized herd things stampede the plains every dusk. Meat by the truckload. Hunters by the bodybag.",
  },
  {
    locationId: "rn-mistveil-springs",
    resourceType: "water",
    richness: "abundant",
    surveyCost: 3000,
    exploitCost: 22000,
    yieldPerTick: { credits: 1500 },
    dangerLevel: 25,
    depletionTicks: 0,
    notes: "Permanent fog forest. Condensation nets pull clean water from the air all day. The air also pulls things from the forest.",
  },
  {
    locationId: "rn-orbital-debris-field",
    resourceType: "salvage_tech",
    richness: "abundant",
    surveyCost: 4500,
    exploitCost: 34000,
    yieldPerTick: { credits: 2200, ammo: 20 },
    dangerLevel: 75,
    depletionTicks: 350,
    notes: "Constellation of dead satellites still de-orbits over this stretch. New tech rains down weekly. Some of it is still hot.",
  },
  {
    locationId: "rn-fungal-grottos",
    resourceType: "bio_samples",
    richness: "rich",
    surveyCost: 3200,
    exploitCost: 24000,
    yieldPerTick: { medSupplies: 70, credits: 1100 },
    dangerLevel: 50,
    depletionTicks: 0,
    notes: "Cathedral-sized cave system colonised by intelligent slime molds. Pharmaceutical gold. Wear a mask. Wear two.",
  },
  {
    locationId: "rn-greenhouse-ruins",
    resourceType: "flora",
    richness: "rich",
    surveyCost: 1800,
    exploitCost: 11000,
    yieldPerTick: { food: 110, medSupplies: 30, credits: 250 },
    dangerLevel: 18,
    depletionTicks: 0,
    notes: "Collapsed agricultural domes, glass shattered for kilometres. The hybrid crops inside went feral and kept producing.",
  },
  {
    locationId: "rn-uranium-pit",
    resourceType: "minerals",
    richness: "abundant",
    surveyCost: 4500,
    exploitCost: 35000,
    yieldPerTick: { credits: 1800, steel: 20 },
    dangerLevel: 80,
    depletionTicks: 600,
    notes: "Open-cast uranium pit. Geiger counters scream a kilometre out. The right buyer pays more than the right buyer should.",
  },
  {
    locationId: "rn-tar-pits-collective",
    resourceType: "fuel",
    richness: "scarce",
    surveyCost: 1300,
    exploitCost: 9000,
    yieldPerTick: { fuel: 50, credits: 200 },
    dangerLevel: 80,
    depletionTicks: 0,
    notes: "Black asphalt sinks edged by skeletons of mutants who learned about tar pits the hard way. Drilling rigs disappear overnight.",
  },
  {
    locationId: "rn-saltmarsh-shallows",
    resourceType: "flora",
    richness: "scarce",
    surveyCost: 900,
    exploitCost: 5500,
    yieldPerTick: { food: 50, medSupplies: 20 },
    dangerLevel: 12,
    depletionTicks: 0,
    notes: "Brackish reedbeds. Diluted nutrition, modest medicine. Honest work for desperate harvesters.",
  },
  {
    locationId: "rn-titan-bones",
    resourceType: "game_hunting",
    richness: "moderate",
    surveyCost: 1700,
    exploitCost: 12000,
    yieldPerTick: { food: 100, credits: 400 },
    dangerLevel: 55,
    depletionTicks: 0,
    notes: "A thing died here a hundred years ago. Its ribs still arch over the road. The smaller predators that ate it never left.",
  },
  {
    locationId: "rn-tidewreck-shoals",
    resourceType: "coastal",
    richness: "rich",
    surveyCost: 1400,
    exploitCost: 9500,
    yieldPerTick: { steel: 85, credits: 400 },
    dangerLevel: 25,
    depletionTicks: 1000,
    notes: "Pre-war freighters beached in the storm of '47. Low tide exposes new wrecks every cycle. The crabs have learned to wait.",
  },
  {
    locationId: "rn-saltworks-pans",
    resourceType: "coastal",
    richness: "moderate",
    surveyCost: 1400,
    exploitCost: 9500,
    yieldPerTick: { credits: 800, medSupplies: 15 },
    dangerLevel: 20,
    depletionTicks: 0,
    notes: "Evaporation flats stretch past the horizon. Salt pays. Lithium brine pays better. The pans are guarded by something that does not need water.",
  },
  {
    locationId: "rn-blackreef-platform",
    resourceType: "ocean",
    richness: "abundant",
    surveyCost: 4200,
    exploitCost: 28000,
    yieldPerTick: { fuel: 130, credits: 850 },
    dangerLevel: 60,
    depletionTicks: 700,
    notes: "Abandoned deep-water rig. The pumps still work. Nobody alive remembers who owns it. Whoever boards first owns it.",
  },
  {
    locationId: "rn-leviathan-grounds",
    resourceType: "ocean",
    richness: "rich",
    surveyCost: 3000,
    exploitCost: 19000,
    yieldPerTick: { food: 150, medSupplies: 30, credits: 500 },
    dangerLevel: 70,
    depletionTicks: 0,
    notes: "Cold trench where the things that survived the bombs grew large. Harpooners go out in threes. Two come back, on average.",
  },
  {
    locationId: "rn-glacier-melt",
    resourceType: "water",
    richness: "abundant",
    surveyCost: 2800,
    exploitCost: 20000,
    yieldPerTick: { credits: 1400 },
    dangerLevel: 20,
    depletionTicks: 0,
    notes: "Pre-war ice cap, still bleeding clean meltwater into a chain of crater lakes. The water is older than the war. Tastes that way.",
  },
  {
    locationId: "rn-cistern-vault",
    resourceType: "water",
    richness: "rich",
    surveyCost: 2200,
    exploitCost: 16000,
    yieldPerTick: { credits: 1150 },
    dangerLevel: 12,
    depletionTicks: 1200,
    notes: "Sealed municipal cistern, untouched since the bombs. Forty thousand cubic metres of pre-war drinking water. Whoever opens the door owns a city.",
  },
  {
    locationId: "rn-server-sepulchre",
    resourceType: "salvage_tech",
    richness: "rich",
    surveyCost: 4000,
    exploitCost: 28000,
    yieldPerTick: { credits: 1900, steel: 15 },
    dangerLevel: 45,
    depletionTicks: 400,
    notes: "Buried pre-war datacentre. Backup generators still cycle. Whatever was indexing humanity finished its work and started indexing something else.",
  },
  {
    locationId: "rn-trauma-ward-7",
    resourceType: "bio_samples",
    richness: "moderate",
    surveyCost: 2500,
    exploitCost: 18000,
    yieldPerTick: { medSupplies: 45, credits: 550 },
    dangerLevel: 45,
    depletionTicks: 0,
    notes: "Pre-war emergency wing. Sealed during triage. The supply lockers are intact. The patients did not consent to remaining.",
  },
  {
    locationId: "rn-orbital-anchor",
    resourceType: "salvage_tech",
    richness: "abundant",
    surveyCost: 5000,
    exploitCost: 34000,
    yieldPerTick: { credits: 2300, steel: 30, ammo: 15 },
    dangerLevel: 65,
    depletionTicks: 350,
    notes: "Base of a collapsed space elevator. The tether snapped and laid a thousand kilometres of carbon ribbon across two continents. The anchor is what's left. The anchor is enough.",
  },
  {
    locationId: "rn-munitions-vault",
    resourceType: "scrap",
    richness: "scarce",
    surveyCost: 800,
    exploitCost: 5500,
    yieldPerTick: { steel: 30, ammo: 8, credits: 150 },
    dangerLevel: 25,
    depletionTicks: 800,
    notes: "Mothballed pre-war ammo dump. Half the crates are stable. The other half taught the last salvage team a lesson the rest are still learning.",
  },
  {
    locationId: "rn-pipeline-graveyard",
    resourceType: "fuel",
    richness: "scarce",
    surveyCost: 1200,
    exploitCost: 7500,
    yieldPerTick: { fuel: 40, credits: 180 },
    dangerLevel: 18,
    depletionTicks: 700,
    notes: "Severed pre-war fuel artery. Residual gasoline still pools in the low spots. Light a match anywhere within a kilometre and you become history.",
  },
  {
    locationId: "rn-pharma-tomb",
    resourceType: "bio_samples",
    richness: "rich",
    surveyCost: 3500,
    exploitCost: 26000,
    yieldPerTick: { medSupplies: 65, credits: 1050 },
    dangerLevel: 60,
    depletionTicks: 0,
    notes: "Sealed pharmaceutical archive carved into the mountain. Cold storage held. The trial subjects in subbasement four were not on any inventory ledger.",
  },
];

export type ResourceNodeState = {
  surveyed: Record<string, boolean>;
  exploiting: Record<string, { startTick: number; ticksRemaining: number }>;
  depleted: string[];
  totalYielded: Record<string, number>;
  haltedRemaining?: Record<string, number>;
};

export function createDefaultResourceNodeState(): ResourceNodeState {
  return {
    surveyed: {},
    exploiting: {},
    depleted: [],
    totalYielded: {},
  };
}

export function getNodeDef(locationId: string): ResourceNodeDef | undefined {
  return RESOURCE_NODE_DEFS.find((n) => n.locationId === locationId);
}
