export type SpyOpCategory = "reconnaissance" | "sabotage" | "assassination" | "counter_intel" | "propaganda" | "infiltration" | "theft" | "cyber" | "black_ops" | "intel_gathering" | "special_missions" | "strategic" | "psychological" | "advanced_intel" | "extreme" | "covert_logistics" | "ultra_black";

export type SpyOpDef = {
  id: string;
  name: string;
  category: SpyOpCategory;
  description: string;
  cost: number;
  riskLevel: number;
  duration: number;
  successRate: number;
};

export const SPY_OP_CATEGORIES: Record<SpyOpCategory, string> = {
  reconnaissance: "RECONNAISSANCE",
  sabotage: "SABOTAGE",
  assassination: "ASSASSINATION",
  counter_intel: "COUNTER INTELLIGENCE",
  propaganda: "PROPAGANDA",
  infiltration: "INFILTRATION",
  theft: "THEFT OPERATIONS",
  cyber: "CYBER OPERATIONS",
  black_ops: "BLACK OPERATIONS",
  intel_gathering: "INTELLIGENCE GATHERING",
  special_missions: "SPECIAL MISSIONS",
  strategic: "STRATEGIC OPS",
  psychological: "PSYCHOLOGICAL OPS",
  advanced_intel: "ADVANCED INTELLIGENCE",
  extreme: "EXTREME OPERATIONS",
  covert_logistics: "COVERT LOGISTICS",
  ultra_black: "ULTRA BLACK OPS",
};

export const SPY_OPS: SpyOpDef[] = [
  { id: "surveillance_rival", name: "Surveillance of Rival District", category: "reconnaissance", description: "Monitor rival district activities and movements.", cost: 500, riskLevel: 2, duration: 3, successRate: 85 },
  { id: "corporate_spying", name: "Corporate Spying", category: "reconnaissance", description: "Infiltrate megacorp communications for intel.", cost: 800, riskLevel: 4, duration: 5, successRate: 75 },
  { id: "drone_recon", name: "Drone Reconnaissance", category: "reconnaissance", description: "Deploy surveillance drones over target areas.", cost: 600, riskLevel: 3, duration: 2, successRate: 90 },
  { id: "satellite_monitoring", name: "Satellite Monitoring", category: "reconnaissance", description: "Task orbital assets for persistent surveillance.", cost: 2000, riskLevel: 1, duration: 1, successRate: 95 },
  { id: "signal_interception", name: "Signal Interception", category: "reconnaissance", description: "Tap into enemy communications channels.", cost: 1000, riskLevel: 5, duration: 4, successRate: 70 },
  { id: "electronic_eavesdrop", name: "Electronic Eavesdropping", category: "reconnaissance", description: "Plant listening devices in target buildings.", cost: 700, riskLevel: 5, duration: 3, successRate: 72 },
  { id: "building_infiltrate", name: "Building Infiltration", category: "reconnaissance", description: "Covertly enter and search target structures.", cost: 1200, riskLevel: 7, duration: 2, successRate: 65 },
  { id: "informant_recruit", name: "Citizen Informant Recruitment", category: "reconnaissance", description: "Turn citizens into intelligence sources.", cost: 400, riskLevel: 4, duration: 6, successRate: 60 },
  { id: "data_center_infiltrate", name: "Data Center Infiltration", category: "reconnaissance", description: "Access secure data repositories physically.", cost: 1500, riskLevel: 8, duration: 3, successRate: 55 },
  { id: "traffic_monitoring", name: "Traffic Monitoring", category: "reconnaissance", description: "Track movement patterns across sectors.", cost: 300, riskLevel: 1, duration: 2, successRate: 92 },
  { id: "power_grid_sabotage", name: "Power Grid Sabotage", category: "sabotage", description: "Disrupt enemy power infrastructure.", cost: 2000, riskLevel: 8, duration: 2, successRate: 60 },
  { id: "comms_disruption", name: "Communications Disruption", category: "sabotage", description: "Jam or destroy communications networks.", cost: 1500, riskLevel: 7, duration: 2, successRate: 65 },
  { id: "factory_sabotage", name: "Factory Machinery Sabotage", category: "sabotage", description: "Cripple industrial production capacity.", cost: 1800, riskLevel: 7, duration: 3, successRate: 62 },
  { id: "transport_disruption", name: "Transportation Disruption", category: "sabotage", description: "Disable transit systems and supply routes.", cost: 1200, riskLevel: 6, duration: 2, successRate: 68 },
  { id: "convoy_intercept", name: "Supply Convoy Interception", category: "sabotage", description: "Ambush and seize supply shipments.", cost: 2500, riskLevel: 8, duration: 1, successRate: 55 },
  { id: "weapon_depot_sabotage", name: "Weapon Depot Sabotage", category: "sabotage", description: "Destroy enemy ammunition and weapon stores.", cost: 3000, riskLevel: 9, duration: 2, successRate: 50 },
  { id: "missile_guidance_hack", name: "Missile Guidance Interference", category: "sabotage", description: "Corrupt targeting data in missile systems.", cost: 4000, riskLevel: 9, duration: 4, successRate: 45 },
  { id: "reactor_shutdown", name: "Reactor Shutdown Sabotage", category: "sabotage", description: "Force emergency shutdown of enemy reactors.", cost: 5000, riskLevel: 10, duration: 3, successRate: 40 },
  { id: "software_hacking", name: "Industrial Software Hacking", category: "sabotage", description: "Inject malware into industrial control systems.", cost: 2000, riskLevel: 6, duration: 4, successRate: 65 },
  { id: "military_equip_damage", name: "Military Equipment Damage", category: "sabotage", description: "Sabotage vehicles and weapons in storage.", cost: 2500, riskLevel: 8, duration: 2, successRate: 55 },
  { id: "political_assassination", name: "Political Assassination", category: "assassination", description: "Eliminate key political figures.", cost: 10000, riskLevel: 10, duration: 5, successRate: 40 },
  { id: "corp_exec_elimination", name: "Corporate Executive Elimination", category: "assassination", description: "Remove hostile corporate leadership.", cost: 8000, riskLevel: 9, duration: 4, successRate: 45 },
  { id: "crime_boss_elimination", name: "Crime Boss Elimination", category: "assassination", description: "Neutralize criminal organization leaders.", cost: 6000, riskLevel: 8, duration: 3, successRate: 50 },
  { id: "military_officer_removal", name: "Military Officer Removal", category: "assassination", description: "Eliminate enemy military commanders.", cost: 12000, riskLevel: 10, duration: 5, successRate: 35 },
  { id: "spy_network_elimination", name: "Spy Network Elimination", category: "assassination", description: "Systematically dismantle enemy spy cells.", cost: 8000, riskLevel: 9, duration: 8, successRate: 45 },
  { id: "spy_detection_sweep", name: "Spy Detection Sweep", category: "counter_intel", description: "Scan for enemy agents within your territory.", cost: 1000, riskLevel: 2, duration: 3, successRate: 70 },
  { id: "double_agent_recruit", name: "Double Agent Recruitment", category: "counter_intel", description: "Turn enemy spies into your assets.", cost: 3000, riskLevel: 7, duration: 6, successRate: 40 },
  { id: "enemy_spy_interrogation", name: "Enemy Spy Interrogation", category: "counter_intel", description: "Extract intelligence from captured agents.", cost: 500, riskLevel: 3, duration: 2, successRate: 65 },
  { id: "secure_comms_upgrade", name: "Secure Communications Upgrade", category: "counter_intel", description: "Harden communications against interception.", cost: 2000, riskLevel: 1, duration: 5, successRate: 90 },
  { id: "false_intel_broadcast", name: "False Intelligence Broadcast", category: "counter_intel", description: "Feed misinformation to enemy intelligence.", cost: 800, riskLevel: 4, duration: 3, successRate: 75 },
  { id: "media_manipulation", name: "Media Manipulation", category: "propaganda", description: "Control media narratives for political gain.", cost: 1500, riskLevel: 4, duration: 4, successRate: 70 },
  { id: "public_opinion_campaign", name: "Public Opinion Campaign", category: "propaganda", description: "Shift public sentiment on key issues.", cost: 1000, riskLevel: 3, duration: 5, successRate: 72 },
  { id: "disinfo_release", name: "Disinformation Release", category: "propaganda", description: "Spread false information to confuse enemies.", cost: 600, riskLevel: 5, duration: 2, successRate: 80 },
  { id: "election_influence", name: "Election Influence", category: "propaganda", description: "Manipulate democratic processes covertly.", cost: 5000, riskLevel: 8, duration: 8, successRate: 55 },
  { id: "protest_instigation", name: "Protest Instigation", category: "propaganda", description: "Organize civil unrest in enemy territory.", cost: 800, riskLevel: 6, duration: 2, successRate: 68 },
  { id: "govt_infiltration", name: "Government Infiltration", category: "infiltration", description: "Plant agents in enemy government.", cost: 5000, riskLevel: 9, duration: 10, successRate: 35 },
  { id: "corp_infiltration", name: "Corporate Infiltration", category: "infiltration", description: "Embed operatives in megacorporations.", cost: 4000, riskLevel: 8, duration: 8, successRate: 40 },
  { id: "criminal_org_infiltration", name: "Criminal Organization Infiltration", category: "infiltration", description: "Insert agents into criminal networks.", cost: 3000, riskLevel: 8, duration: 6, successRate: 45 },
  { id: "military_infiltration", name: "Military Infiltration", category: "infiltration", description: "Penetrate enemy military command structures.", cost: 6000, riskLevel: 10, duration: 10, successRate: 30 },
  { id: "research_facility_infiltration", name: "Research Facility Infiltration", category: "infiltration", description: "Access classified research programs.", cost: 4000, riskLevel: 9, duration: 6, successRate: 38 },
  { id: "tech_theft", name: "Technology Theft", category: "theft", description: "Steal advanced technology blueprints.", cost: 5000, riskLevel: 8, duration: 4, successRate: 50 },
  { id: "prototype_weapon_theft", name: "Prototype Weapon Theft", category: "theft", description: "Acquire enemy prototype weapons.", cost: 8000, riskLevel: 9, duration: 5, successRate: 40 },
  { id: "data_archive_theft", name: "Data Archive Theft", category: "theft", description: "Copy entire intelligence databases.", cost: 3000, riskLevel: 7, duration: 3, successRate: 55 },
  { id: "nuclear_material_theft", name: "Nuclear Material Theft", category: "theft", description: "Secure fissile materials from enemy stockpiles.", cost: 15000, riskLevel: 10, duration: 6, successRate: 30 },
  { id: "ai_core_theft", name: "AI Core Theft", category: "theft", description: "Extract military AI processing cores.", cost: 10000, riskLevel: 9, duration: 5, successRate: 35 },
  { id: "network_intrusion", name: "Network Intrusion", category: "cyber", description: "Penetrate enemy digital infrastructure.", cost: 2000, riskLevel: 5, duration: 3, successRate: 65 },
  { id: "city_database_hack", name: "City Database Hack", category: "cyber", description: "Access city-wide citizen and infrastructure data.", cost: 3000, riskLevel: 6, duration: 4, successRate: 60 },
  { id: "financial_disruption", name: "Financial System Disruption", category: "cyber", description: "Crash enemy economic systems.", cost: 5000, riskLevel: 8, duration: 3, successRate: 50 },
  { id: "military_command_hack", name: "Military Command Hack", category: "cyber", description: "Access enemy military command networks.", cost: 8000, riskLevel: 9, duration: 5, successRate: 40 },
  { id: "drone_control_hijack", name: "Drone Control Hijack", category: "cyber", description: "Take control of enemy autonomous systems.", cost: 4000, riskLevel: 7, duration: 2, successRate: 55 },
  { id: "false_flag", name: "False Flag Attack", category: "black_ops", description: "Stage attack to implicate another faction.", cost: 8000, riskLevel: 10, duration: 3, successRate: 45 },
  { id: "secret_weapons_test_theft", name: "Secret Weapons Test Theft", category: "black_ops", description: "Acquire data from covert weapons programs.", cost: 12000, riskLevel: 10, duration: 6, successRate: 35 },
  { id: "strategic_sabotage", name: "Strategic Sabotage", category: "black_ops", description: "Cripple critical infrastructure at scale.", cost: 10000, riskLevel: 10, duration: 4, successRate: 40 },
  { id: "asset_extraction", name: "Asset Extraction Mission", category: "black_ops", description: "Extract high-value agents from enemy territory.", cost: 6000, riskLevel: 9, duration: 2, successRate: 50 },
  { id: "covert_surveillance_grid", name: "Covert Surveillance Grid", category: "black_ops", description: "Deploy hidden sensor network in enemy territory.", cost: 5000, riskLevel: 7, duration: 8, successRate: 60 },
  { id: "economic_intel", name: "Economic Intelligence", category: "intel_gathering", description: "Map enemy economic strengths and vulnerabilities.", cost: 800, riskLevel: 3, duration: 4, successRate: 80 },
  { id: "military_intel", name: "Military Intelligence", category: "intel_gathering", description: "Assess enemy military capabilities.", cost: 1200, riskLevel: 5, duration: 5, successRate: 70 },
  { id: "political_intel", name: "Political Intelligence", category: "intel_gathering", description: "Monitor political dynamics and power shifts.", cost: 600, riskLevel: 3, duration: 3, successRate: 82 },
  { id: "population_monitoring", name: "Population Monitoring", category: "intel_gathering", description: "Track citizen sentiment and movements.", cost: 400, riskLevel: 2, duration: 2, successRate: 88 },
  { id: "infrastructure_mapping", name: "Infrastructure Mapping", category: "intel_gathering", description: "Create detailed maps of enemy infrastructure.", cost: 1000, riskLevel: 4, duration: 5, successRate: 75 },
  { id: "hostage_rescue", name: "Hostage Rescue", category: "special_missions", description: "Extract hostages from enemy custody.", cost: 8000, riskLevel: 9, duration: 1, successRate: 45 },
  { id: "prisoner_extraction", name: "Prisoner Extraction", category: "special_missions", description: "Break out imprisoned agents or VIPs.", cost: 6000, riskLevel: 9, duration: 2, successRate: 40 },
  { id: "defector_escort", name: "Defector Escort", category: "special_missions", description: "Safely extract defectors to your territory.", cost: 4000, riskLevel: 7, duration: 3, successRate: 55 },
  { id: "artifact_recovery", name: "Artifact Recovery", category: "special_missions", description: "Recover valuable items from hostile zones.", cost: 5000, riskLevel: 8, duration: 4, successRate: 50 },
  { id: "missing_agent_recovery", name: "Missing Agent Recovery", category: "special_missions", description: "Locate and recover lost operatives.", cost: 3000, riskLevel: 7, duration: 5, successRate: 48 },
  { id: "long_term_infiltration", name: "Long-Term Infiltration", category: "strategic", description: "Deep cover agent placement for years.", cost: 10000, riskLevel: 8, duration: 20, successRate: 35 },
  { id: "spy_network_expansion", name: "Spy Network Expansion", category: "strategic", description: "Grow your intelligence apparatus.", cost: 5000, riskLevel: 5, duration: 10, successRate: 65 },
  { id: "deep_cover_ops", name: "Deep Cover Operations", category: "strategic", description: "Maintain agents in deep cover indefinitely.", cost: 8000, riskLevel: 7, duration: 15, successRate: 50 },
  { id: "secret_alliance_negotiation", name: "Secret Alliance Negotiation", category: "strategic", description: "Forge covert agreements with other factions.", cost: 6000, riskLevel: 6, duration: 8, successRate: 55 },
  { id: "hidden_base_construction", name: "Hidden Base Construction", category: "strategic", description: "Build covert operational facilities.", cost: 15000, riskLevel: 6, duration: 12, successRate: 70 },
  { id: "fear_campaign", name: "Fear Campaign", category: "psychological", description: "Spread terror to destabilize enemy populations.", cost: 2000, riskLevel: 6, duration: 5, successRate: 72 },
  { id: "rumor_spreading", name: "Rumor Spreading", category: "psychological", description: "Plant destabilizing rumors across districts.", cost: 500, riskLevel: 3, duration: 3, successRate: 80 },
  { id: "leadership_destabilization", name: "Leadership Destabilization", category: "psychological", description: "Undermine confidence in enemy leaders.", cost: 3000, riskLevel: 7, duration: 6, successRate: 55 },
  { id: "reputation_destruction", name: "Reputation Destruction", category: "psychological", description: "Systematically destroy a target's reputation.", cost: 2500, riskLevel: 5, duration: 5, successRate: 65 },
  { id: "crisis_manipulation", name: "Crisis Manipulation", category: "psychological", description: "Exploit disasters for strategic advantage.", cost: 1500, riskLevel: 6, duration: 3, successRate: 68 },
  { id: "ai_surveillance_network", name: "AI Surveillance Network", category: "advanced_intel", description: "Deploy AI-powered mass surveillance.", cost: 10000, riskLevel: 4, duration: 8, successRate: 85 },
  { id: "predictive_crime_modeling", name: "Predictive Crime Modeling", category: "advanced_intel", description: "AI predicts criminal activity before it happens.", cost: 6000, riskLevel: 3, duration: 6, successRate: 78 },
  { id: "drone_spy_swarm", name: "Drone Spy Swarm Deployment", category: "advanced_intel", description: "Blanket area with micro surveillance drones.", cost: 4000, riskLevel: 5, duration: 3, successRate: 80 },
  { id: "satellite_spy_grid", name: "Satellite Spy Grid", category: "advanced_intel", description: "Orbital surveillance constellation.", cost: 20000, riskLevel: 2, duration: 10, successRate: 92 },
  { id: "quantum_encryption_break", name: "Quantum Encryption Breaking", category: "advanced_intel", description: "Crack unbreakable communications.", cost: 15000, riskLevel: 6, duration: 8, successRate: 50 },
  { id: "black_site_interrogation", name: "Black Site Interrogations", category: "extreme", description: "Enhanced interrogation in secret facilities.", cost: 3000, riskLevel: 8, duration: 2, successRate: 70 },
  { id: "political_coup_support", name: "Political Coup Support", category: "extreme", description: "Provide covert support for regime change.", cost: 20000, riskLevel: 10, duration: 10, successRate: 30 },
  { id: "secret_weapon_deployment", name: "Secret Weapon Deployment", category: "extreme", description: "Deploy classified weapons covertly.", cost: 25000, riskLevel: 10, duration: 3, successRate: 55 },
  { id: "shadow_govt_manipulation", name: "Shadow Government Manipulation", category: "extreme", description: "Control governments from the shadows.", cost: 30000, riskLevel: 10, duration: 15, successRate: 25 },
  { id: "war_provocation", name: "War Provocation", category: "extreme", description: "Engineer incidents to provoke conflict.", cost: 15000, riskLevel: 10, duration: 5, successRate: 50 },
  { id: "secret_weapons_transport", name: "Secret Weapons Transport", category: "covert_logistics", description: "Move weapons through hidden channels.", cost: 3000, riskLevel: 7, duration: 3, successRate: 65 },
  { id: "hidden_bunker_construction", name: "Hidden Bunker Construction", category: "covert_logistics", description: "Build secret underground facilities.", cost: 12000, riskLevel: 5, duration: 10, successRate: 75 },
  { id: "covert_supply_network", name: "Covert Supply Network", category: "covert_logistics", description: "Establish hidden logistics chains.", cost: 5000, riskLevel: 6, duration: 8, successRate: 65 },
  { id: "smuggling_routes", name: "Underground Smuggling Routes", category: "covert_logistics", description: "Create secret transport corridors.", cost: 4000, riskLevel: 7, duration: 6, successRate: 60 },
  { id: "spy_safehouse_creation", name: "Spy Safehouse Creation", category: "covert_logistics", description: "Establish agent hideouts and safe rooms.", cost: 2000, riskLevel: 4, duration: 4, successRate: 80 },
  { id: "memory_alteration", name: "Memory Alteration Program", category: "ultra_black", description: "Erase and rewrite human memories.", cost: 20000, riskLevel: 10, duration: 5, successRate: 35 },
  { id: "synthetic_identity", name: "Synthetic Identity Creation", category: "ultra_black", description: "Create entirely fabricated persons.", cost: 8000, riskLevel: 7, duration: 6, successRate: 65 },
  { id: "experimental_spy_tech", name: "Experimental Spy Tech Testing", category: "ultra_black", description: "Field test cutting-edge espionage technology.", cost: 10000, riskLevel: 8, duration: 4, successRate: 50 },
  { id: "autonomous_spy_drones", name: "Autonomous Spy Drones", category: "ultra_black", description: "Self-directed AI espionage platforms.", cost: 12000, riskLevel: 6, duration: 5, successRate: 72 },
  { id: "neural_hacking_ops", name: "Neural Hacking Operations", category: "ultra_black", description: "Directly hack human neural interfaces.", cost: 15000, riskLevel: 10, duration: 3, successRate: 40 },
  { id: "population_surveillance_grid", name: "Population Surveillance Grid", category: "ultra_black", description: "Total population monitoring system.", cost: 25000, riskLevel: 5, duration: 12, successRate: 85 },
  { id: "citywide_tracking_implants", name: "Citywide Tracking Implants", category: "ultra_black", description: "Covert tracking chips in citizen implants.", cost: 30000, riskLevel: 8, duration: 15, successRate: 60 },
  { id: "deepfake_broadcasts", name: "Deepfake Leadership Broadcasts", category: "ultra_black", description: "AI-generated false broadcasts from leaders.", cost: 5000, riskLevel: 7, duration: 2, successRate: 70 },
  { id: "remote_sabotage_networks", name: "Remote Sabotage Networks", category: "ultra_black", description: "Pre-positioned sabotage devices citywide.", cost: 20000, riskLevel: 9, duration: 10, successRate: 55 },
  { id: "strategic_shadow_warfare", name: "Strategic Shadow Warfare", category: "ultra_black", description: "Full-spectrum covert warfare operations.", cost: 50000, riskLevel: 10, duration: 20, successRate: 30 },
];
