export type RecipeDef = {
  id: string;
  name: string;
  category: "extraction" | "refining" | "manufacturing" | "advanced" | "military" | "cybernetics" | "chemicals" | "plastics" | "finished";
  inputs: Record<string, number>;
  outputs: Record<string, number>;
  buildingKey: string;
  workersKey?: string;
  ticksPerCycle: number;
};

export const SUPPLY_CHAIN_RECIPES: RecipeDef[] = [
  // ── EXTRACTION (raw resources from buildings) ────────────────────────
  {
    id: "mine_iron",
    name: "Iron Mining",
    category: "extraction",
    inputs: {},
    outputs: { iron_ore: 20 },
    buildingKey: "metalFoundryComplexes",
    workersKey: "miningCrews",
    ticksPerCycle: 1,
  },
  {
    id: "mine_copper",
    name: "Copper Mining",
    category: "extraction",
    inputs: {},
    outputs: { copper_ore: 12 },
    buildingKey: "metalFoundryComplexes",
    workersKey: "miningCrews",
    ticksPerCycle: 1,
  },
  {
    id: "mine_silicon",
    name: "Silicon Extraction",
    category: "extraction",
    inputs: {},
    outputs: { silicon_ore: 8 },
    buildingKey: "advancedMaterialsRefineries",
    workersKey: "miningCrews",
    ticksPerCycle: 1,
  },
  {
    id: "mine_rare_earth",
    name: "Rare Earth Mining",
    category: "extraction",
    inputs: {},
    outputs: { rare_earth_minerals: 3 },
    buildingKey: "advancedMaterialsRefineries",
    workersKey: "miningCrews",
    ticksPerCycle: 2,
  },
  {
    id: "harvest_biomass",
    name: "Biomass Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { biomass: 15 },
    buildingKey: "industrialHydroponicFarms",
    ticksPerCycle: 1,
  },
  {
    id: "extract_fuel_gas",
    name: "Fuel Gas Extraction",
    category: "extraction",
    inputs: {},
    outputs: { fuel_gas: 10 },
    buildingKey: "geothermalWells",
    ticksPerCycle: 1,
  },
  {
    id: "scrap_recycling",
    name: "Scrap Metal Recycling",
    category: "extraction",
    inputs: {},
    outputs: { scrap_metal: 18 },
    buildingKey: "industrialRecyclingFacilities",
    workersKey: "recyclingFacilityWorkers",
    ticksPerCycle: 1,
  },
  {
    id: "ewaste_recovery",
    name: "E-Waste Recovery",
    category: "extraction",
    inputs: {},
    outputs: { electronic_waste: 8 },
    buildingKey: "industrialRecyclingFacilities",
    ticksPerCycle: 1,
  },

  // ── REFINING (raw ore → basic materials) ────────────────────────────
  {
    id: "smelt_steel",
    name: "Steel Smelting",
    category: "refining",
    inputs: { iron_ore: 10, coal_deposits: 3 },
    outputs: { steel_ingot: 8 },
    buildingKey: "metalFoundryComplexes",
    workersKey: "materialsProcessingTeams",
    ticksPerCycle: 1,
  },
  {
    id: "refine_copper",
    name: "Copper Refining",
    category: "refining",
    inputs: { copper_ore: 8 },
    outputs: { copper_ingot: 6 },
    buildingKey: "metalFoundryComplexes",
    ticksPerCycle: 1,
  },
  {
    id: "refine_aluminum",
    name: "Aluminum Refining",
    category: "refining",
    inputs: { aluminum_ore: 10 },
    outputs: { aluminum_ingot: 6 },
    buildingKey: "constructionMaterialRefineries",
    ticksPerCycle: 1,
  },
  {
    id: "process_silicon",
    name: "Silicon Processing",
    category: "refining",
    inputs: { silicon_ore: 6 },
    outputs: { silicon_wafer: 4 },
    buildingKey: "advancedMaterialsRefineries",
    ticksPerCycle: 1,
  },
  {
    id: "refine_titanium",
    name: "Titanium Refining",
    category: "refining",
    inputs: { titanium_ore: 5 },
    outputs: { titanium_alloy: 3 },
    buildingKey: "advancedMaterialsRefineries",
    ticksPerCycle: 2,
  },
  {
    id: "produce_concrete",
    name: "Concrete Production",
    category: "refining",
    inputs: { limestone_raw: 8, sand_deposits: 6 },
    outputs: { concrete_mix: 10 },
    buildingKey: "constructionMaterialRefineries",
    ticksPerCycle: 1,
  },
  {
    id: "produce_plastics",
    name: "Plastics Synthesis",
    category: "refining",
    inputs: { fuel_gas: 5 },
    outputs: { industrial_plastic: 6 },
    buildingKey: "megaManufacturingPlants",
    ticksPerCycle: 1,
  },
  {
    id: "reclaim_scrap",
    name: "Scrap Reclamation",
    category: "refining",
    inputs: { scrap_metal: 12 },
    outputs: { steel_ingot: 5, copper_ingot: 2 },
    buildingKey: "industrialRecyclingFacilities",
    workersKey: "recyclingFacilityWorkers",
    ticksPerCycle: 1,
  },

  // ── MANUFACTURING (materials → parts/goods) ─────────────────────────
  {
    id: "make_structural_beams",
    name: "Structural Beam Fabrication",
    category: "manufacturing",
    inputs: { steel_ingot: 6 },
    outputs: { structural_beam: 4 },
    buildingKey: "megaManufacturingPlants",
    workersKey: "factoryWorkerCrews",
    ticksPerCycle: 1,
  },
  {
    id: "make_cables",
    name: "Cable Manufacturing",
    category: "manufacturing",
    inputs: { copper_ingot: 4, industrial_plastic: 2 },
    outputs: { power_cable: 6 },
    buildingKey: "megaManufacturingPlants",
    workersKey: "factoryWorkerCrews",
    ticksPerCycle: 1,
  },
  {
    id: "make_pipes",
    name: "Pipe Fabrication",
    category: "manufacturing",
    inputs: { steel_ingot: 3, industrial_plastic: 2 },
    outputs: { utility_pipe: 5 },
    buildingKey: "constructionMaterialRefineries",
    ticksPerCycle: 1,
  },
  {
    id: "make_circuits",
    name: "Circuit Board Assembly",
    category: "manufacturing",
    inputs: { silicon_wafer: 3, copper_ingot: 2 },
    outputs: { circuit_board: 4 },
    buildingKey: "roboticsFabricationFacilities",
    workersKey: "factoryWorkerCrews",
    ticksPerCycle: 1,
  },
  {
    id: "make_mech_parts",
    name: "Mechanical Parts Assembly",
    category: "manufacturing",
    inputs: { steel_ingot: 4, aluminum_ingot: 2 },
    outputs: { mechanical_part: 5 },
    buildingKey: "automatedAssemblyLines",
    workersKey: "factoryWorkerCrews",
    ticksPerCycle: 1,
  },
  {
    id: "make_electronics",
    name: "Electronics Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 3, power_cable: 2 },
    outputs: { consumer_electronics: 4 },
    buildingKey: "roboticsFabricationFacilities",
    ticksPerCycle: 1,
  },
  {
    id: "process_food",
    name: "Food Processing",
    category: "manufacturing",
    inputs: { biomass: 10 },
    outputs: { processed_food: 8 },
    buildingKey: "syntheticFoodPlants",
    ticksPerCycle: 1,
  },
  {
    id: "make_construction_supplies",
    name: "Construction Supply Bundling",
    category: "manufacturing",
    inputs: { structural_beam: 3, concrete_mix: 5, utility_pipe: 2 },
    outputs: { construction_supply_kit: 3 },
    buildingKey: "supplyChainDistributionCenters",
    ticksPerCycle: 1,
  },

  // ── ADVANCED (high-tier transformations) ────────────────────────────
  {
    id: "make_smart_circuits",
    name: "Smart Circuitry Fabrication",
    category: "advanced",
    inputs: { circuit_board: 4, rare_earth_minerals: 2 },
    outputs: { smart_circuitry: 3 },
    buildingKey: "cyberneticsDevelopmentFacilities",
    workersKey: "aiSystemsEngineers",
    ticksPerCycle: 2,
  },
  {
    id: "make_composite_armor",
    name: "Composite Armor Production",
    category: "advanced",
    inputs: { titanium_alloy: 3, steel_ingot: 4 },
    outputs: { composite_armor_plate: 2 },
    buildingKey: "advancedMaterialsRefineries",
    ticksPerCycle: 2,
  },
  {
    id: "make_reactor_alloys",
    name: "Reactor Alloy Synthesis",
    category: "advanced",
    inputs: { titanium_alloy: 2, rare_earth_minerals: 3 },
    outputs: { reactor_alloy: 2 },
    buildingKey: "advancedMaterialsRefineries",
    ticksPerCycle: 3,
  },
  {
    id: "make_nano_materials",
    name: "Nanomaterial Fabrication",
    category: "advanced",
    inputs: { smart_circuitry: 2, rare_earth_minerals: 2 },
    outputs: { nano_material: 1 },
    buildingKey: "experimentalTechVaults",
    workersKey: "cyberneticsResearchers",
    ticksPerCycle: 3,
  },

  // ── DROID PART PRODUCTION ───────────────────────────────────────────
  {
    id: "make_droid_chassis",
    name: "Droid Chassis Assembly",
    category: "manufacturing",
    inputs: { steel_ingot: 4, aluminum_ingot: 3 },
    outputs: { droid_chassis: 2 },
    buildingKey: "roboticsFabricationFacilities",
    workersKey: "factoryWorkerCrews",
    ticksPerCycle: 2,
  },
  {
    id: "make_droid_actuators",
    name: "Droid Actuator Manufacturing",
    category: "manufacturing",
    inputs: { mechanical_part: 3, titanium_alloy: 1 },
    outputs: { droid_actuator: 3 },
    buildingKey: "roboticsFabricationFacilities",
    ticksPerCycle: 2,
  },
  {
    id: "make_droid_processors",
    name: "Droid AI Core Fabrication",
    category: "advanced",
    inputs: { smart_circuitry: 2, circuit_board: 2 },
    outputs: { droid_ai_core: 2 },
    buildingKey: "cyberneticsDevelopmentFacilities",
    workersKey: "aiSystemsEngineers",
    ticksPerCycle: 2,
  },
  {
    id: "make_droid_sensors",
    name: "Droid Sensor Array Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 2, rare_earth_minerals: 1 },
    outputs: { droid_sensor_array: 3 },
    buildingKey: "roboticsFabricationFacilities",
    ticksPerCycle: 1,
  },
  {
    id: "make_droid_power_cells",
    name: "Droid Power Cell Production",
    category: "manufacturing",
    inputs: { reactor_alloy: 1, copper_ingot: 3 },
    outputs: { droid_power_cell: 2 },
    buildingKey: "automatedAssemblyLines",
    ticksPerCycle: 2,
  },

  // ── MILITARY MANUFACTURING ─────────────────────────────────────────
  {
    id: "make_ammo",
    name: "Ammunition Production",
    category: "military",
    inputs: { steel_ingot: 3, copper_ingot: 2 },
    outputs: { ammunition_crate: 8 },
    buildingKey: "weaponsArmoryDepots",
    ticksPerCycle: 1,
  },
  {
    id: "make_armor_plate",
    name: "Vehicle Armor Plating",
    category: "military",
    inputs: { composite_armor_plate: 2, structural_beam: 2 },
    outputs: { vehicle_armor_kit: 1 },
    buildingKey: "armoredVehicleGarages",
    ticksPerCycle: 2,
  },

  // ── WILDLANDS (hunting, foraging, tanning, distillation) ─────────────
  {
    id: "wild_hunt",
    name: "Apex Hunt",
    category: "extraction",
    inputs: {},
    outputs: { wild_meat: 8, wild_hides: 4, wildlands_bone_char: 3 },
    buildingKey: "apexHuntersLodges",
    ticksPerCycle: 1,
  },
  {
    id: "wild_hydroponic",
    name: "Hydroponic Cultivation",
    category: "extraction",
    inputs: {},
    outputs: { medicinal_herbs: 6, wildlands_biomass: 10 },
    buildingKey: "hydroponicDomes",
    ticksPerCycle: 1,
  },
  {
    id: "wild_livestock_raise",
    name: "Feral Livestock Raising",
    category: "extraction",
    inputs: {},
    outputs: { wild_livestock: 3, wild_meat: 4, wild_hides: 2 },
    buildingKey: "feralLivestockPens",
    ticksPerCycle: 2,
  },
  {
    id: "wild_bioreserve",
    name: "Bioreserve Yield",
    category: "extraction",
    inputs: {},
    outputs: { wildlands_biomass: 14, wild_livestock: 2 },
    buildingKey: "wildlandsBioreserves",
    ticksPerCycle: 2,
  },
  {
    id: "wild_ranger_collection",
    name: "Ranger Salvage Sweep",
    category: "extraction",
    inputs: {},
    outputs: { ivory_tusks: 1, wild_hides: 2, alpha_pheromones: 1 },
    buildingKey: "wildlandsRangerStations",
    ticksPerCycle: 3,
  },
  {
    id: "wild_antitoxin",
    name: "Antitoxin Distillation",
    category: "manufacturing",
    inputs: { medicinal_herbs: 6 },
    outputs: { wildlands_antitoxin: 3 },
    buildingKey: "frontierApothecaries",
    ticksPerCycle: 2,
  },
  {
    id: "wild_tan_pelts",
    name: "Pelt Tanning",
    category: "manufacturing",
    inputs: { wild_hides: 5 },
    outputs: { exotic_pelts: 2 },
    buildingKey: "bushTanneries",
    ticksPerCycle: 2,
  },
  {
    id: "wild_gene_vault_archive",
    name: "Gene Vault Sequencing",
    category: "advanced",
    inputs: { wildlands_biomass: 4, medicinal_herbs: 2 },
    outputs: { wildlands_antitoxin: 1 },
    buildingKey: "geneVaults",
    ticksPerCycle: 3,
  },

  // ── FARMING EXTRACTION (raw drops from farming buildings) ────────────
  {
    id: "farm_mutant_flora",
    name: "Mutant Flora Cultivation",
    category: "extraction",
    inputs: {},
    outputs: { mutant_flora: 10 },
    buildingKey: "mutantFloraGreenhouses",
    ticksPerCycle: 1,
  },
  {
    id: "farm_fungal_spores",
    name: "Fungal Spore Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { fungal_spores: 8 },
    buildingKey: "fungalSporeFarms",
    ticksPerCycle: 1,
  },
  {
    id: "farm_rad_crystal",
    name: "Rad-Crystal Mining",
    category: "extraction",
    inputs: {},
    outputs: { rad_crystal: 5 },
    buildingKey: "radCrystalMines",
    ticksPerCycle: 2,
  },
  {
    id: "farm_synth_protein",
    name: "Synth Protein Brewing",
    category: "extraction",
    inputs: {},
    outputs: { synth_protein: 12 },
    buildingKey: "synthProteinBreweries",
    ticksPerCycle: 1,
  },
  {
    id: "farm_bio_toxin",
    name: "Bio-Toxin Extraction",
    category: "extraction",
    inputs: {},
    outputs: { bio_toxin: 6 },
    buildingKey: "toxinHarvestLabs",
    ticksPerCycle: 2,
  },
  {
    id: "farm_deep_root_fiber",
    name: "Deep Root Fiber Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { deep_root_fiber: 10 },
    buildingKey: "deepRootExtractors",
    ticksPerCycle: 1,
  },
  {
    id: "farm_waste_algae",
    name: "Waste Algae Cultivation",
    category: "extraction",
    inputs: {},
    outputs: { waste_algae: 15 },
    buildingKey: "algaeBloomPonds",
    ticksPerCycle: 1,
  },
  {
    id: "farm_insect_protein",
    name: "Insect Protein Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { insect_protein: 12 },
    buildingKey: "insectProteinHatcheries",
    ticksPerCycle: 1,
  },
  {
    id: "farm_mineral_sediment",
    name: "Mineral Sediment Collection",
    category: "extraction",
    inputs: {},
    outputs: { mineral_sediment: 8 },
    buildingKey: "crystalSedimentPools",
    ticksPerCycle: 1,
  },
  {
    id: "farm_biolumen_extract",
    name: "Biolumen Extract Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { biolumen_extract: 6 },
    buildingKey: "bioLuminPlantations",
    ticksPerCycle: 2,
  },
  {
    id: "farm_ferment_sludge",
    name: "Ferment Sludge Production",
    category: "extraction",
    inputs: {},
    outputs: { ferment_sludge: 14 },
    buildingKey: "wasteFermentationVats",
    ticksPerCycle: 1,
  },
  {
    id: "farm_urban_pollen",
    name: "Urban Pollen Collection",
    category: "extraction",
    inputs: {},
    outputs: { urban_pollen: 8 },
    buildingKey: "aerialPollenCollectors",
    ticksPerCycle: 1,
  },
  {
    id: "farm_chiton_shell",
    name: "Chiton Shell Harvesting",
    category: "extraction",
    inputs: {},
    outputs: { chiton_shell: 7 },
    buildingKey: "chitonShellRanches",
    ticksPerCycle: 1,
  },
  {
    id: "farm_synth_mold",
    name: "Synth Mold Cultivation",
    category: "extraction",
    inputs: {},
    outputs: { synth_mold: 10 },
    buildingKey: "moldCultureChambers",
    ticksPerCycle: 1,
  },
  {
    id: "farm_bioresin",
    name: "Bioresin Tapping",
    category: "extraction",
    inputs: {},
    outputs: { bioresin: 8 },
    buildingKey: "resinTapStations",
    ticksPerCycle: 1,
  },
  {
    id: "farm_electric_organ",
    name: "Electric Organ Extraction",
    category: "extraction",
    inputs: {},
    outputs: { electric_organ: 4 },
    buildingKey: "electricEelFarms",
    ticksPerCycle: 2,
  },
  {
    id: "farm_cave_mushroom",
    name: "Cave Mushroom Farming",
    category: "extraction",
    inputs: {},
    outputs: { cave_mushroom: 12 },
    buildingKey: "mushroomCaveNetworks",
    ticksPerCycle: 1,
  },
  {
    id: "farm_hybrid_seed",
    name: "Hybrid Seed Production",
    category: "extraction",
    inputs: {},
    outputs: { hybrid_seed: 6 },
    buildingKey: "seedBankVaults",
    ticksPerCycle: 2,
  },
  {
    id: "farm_synth_venom",
    name: "Synth Venom Milking",
    category: "extraction",
    inputs: {},
    outputs: { synth_venom: 4 },
    buildingKey: "venomMilkingStations",
    ticksPerCycle: 2,
  },
  {
    id: "farm_petrified_wood",
    name: "Petrified Wood Quarrying",
    category: "extraction",
    inputs: {},
    outputs: { petrified_wood: 6 },
    buildingKey: "petrifiedWoodQuarries",
    ticksPerCycle: 1,
  },

  // ── FARMING REFINING (drop chains) ──────────────────────────────────
  {
    id: "refine_bioresin",
    name: "Refined Bioresin Processing",
    category: "refining",
    inputs: { bioresin: 6, waste_algae: 4 },
    outputs: { refined_bioresin: 4 },
    buildingKey: "resinTapStations",
    ticksPerCycle: 2,
  },
  {
    id: "make_chiton_plating",
    name: "Chiton Armor Plating",
    category: "manufacturing",
    inputs: { chiton_shell: 5, mineral_sediment: 3 },
    outputs: { chiton_plating: 3 },
    buildingKey: "chitonShellRanches",
    ticksPerCycle: 2,
  },
  {
    id: "cut_rad_crystal_lens",
    name: "Rad-Crystal Lens Cutting",
    category: "manufacturing",
    inputs: { rad_crystal: 4 },
    outputs: { rad_crystal_lens: 2 },
    buildingKey: "radCrystalMines",
    ticksPerCycle: 3,
  },
  {
    id: "brew_bio_stimulant",
    name: "Bio-Stimulant Brewing",
    category: "manufacturing",
    inputs: { bio_toxin: 3, synth_venom: 2, fungal_spores: 4 },
    outputs: { bio_stimulant: 2 },
    buildingKey: "toxinHarvestLabs",
    ticksPerCycle: 3,
  },
  {
    id: "make_luminous_dye",
    name: "Luminous Dye Synthesis",
    category: "manufacturing",
    inputs: { biolumen_extract: 4, urban_pollen: 3 },
    outputs: { luminous_dye: 3 },
    buildingKey: "bioLuminPlantations",
    ticksPerCycle: 2,
  },
  {
    id: "weave_mutant_fiber",
    name: "Mutant Fiber Weaving",
    category: "manufacturing",
    inputs: { deep_root_fiber: 6, mutant_flora: 4, synth_mold: 3 },
    outputs: { mutant_fiber_weave: 3 },
    buildingKey: "deepRootExtractors",
    ticksPerCycle: 2,
  },

  // ── CYBERNETICS ──────────────────────────────────────────────────────
  {
    id: "basic_augmentation",
    name: "Basic Augmentation Services",
    category: "cybernetics",
    inputs: { synthetic_muscle_fiber: 2, bio_compatible_titanium: 1 },
    outputs: { cyber_prosthetic_limb: 1 },
    buildingKey: "augmentationClinics",
    ticksPerCycle: 2,
  },
  {
    id: "cyber_surgery",
    name: "Cybernetic Surgery",
    category: "cybernetics",
    inputs: { neural_processing_chips: 2, cyber_servo_motors: 1, nano_surgical_tools: 1 },
    outputs: { cybernetic_spine_unit: 1 },
    buildingKey: "cyberSurgeryHospitals",
    ticksPerCycle: 3,
  },
  {
    id: "neural_research",
    name: "Neural Interface Research",
    category: "cybernetics",
    inputs: { neural_processing_chips: 3, neural_feedback_dampeners: 2 },
    outputs: { neural_link_interface: 2 },
    buildingKey: "neuralResearchLabs",
    ticksPerCycle: 3,
  },
  {
    id: "implant_production",
    name: "Implant Mass Production",
    category: "cybernetics",
    inputs: { bio_compatible_titanium: 3, cyber_servo_motors: 2, optical_sensor_arrays: 1 },
    outputs: { cyber_prosthetic_limb: 2, cybernetic_eye_module: 1 },
    buildingKey: "implantManufacturingPlants",
    ticksPerCycle: 2,
  },
  {
    id: "cyber_recycling",
    name: "Cybernetic Component Recycling",
    category: "cybernetics",
    inputs: {},
    outputs: { synthetic_muscle_fiber: 3, cyber_servo_motors: 2, scrap_metal: 5 },
    buildingKey: "cyberneticRecyclingFacilities",
    ticksPerCycle: 2,
  },
  {
    id: "military_augmentation",
    name: "Military-Grade Augmentation",
    category: "cybernetics",
    inputs: { combat_stimulant_injectors: 2, dermal_armor_plating: 2, targeting_hud_systems: 1 },
    outputs: { exoskeleton_frame: 1 },
    buildingKey: "militaryAugmentationLabs",
    ticksPerCycle: 4,
  },
  {
    id: "ai_training",
    name: "AI Co-Pilot Training",
    category: "cybernetics",
    inputs: { neural_processing_chips: 4, neural_link_interface: 1 },
    outputs: { ai_co_pilot_module: 1 },
    buildingKey: "aiTrainingDataCenters",
    ticksPerCycle: 4,
  },
  {
    id: "nano_fabrication",
    name: "Nano-Component Fabrication",
    category: "cybernetics",
    inputs: { nano_surgical_tools: 1, bio_compatible_titanium: 2 },
    outputs: { nano_repair_swarm: 2, nano_surgical_tools: 1 },
    buildingKey: "nanoFabricationLabs",
    ticksPerCycle: 3,
  },
  {
    id: "biotech_cultivation",
    name: "Biotech Tissue Cultivation",
    category: "cybernetics",
    inputs: { biomass: 5 },
    outputs: { synthetic_muscle_fiber: 3, bio_compatible_titanium: 2 },
    buildingKey: "biotechFarms",
    ticksPerCycle: 2,
  },
  {
    id: "black_market_implants",
    name: "Black Market Implant Assembly",
    category: "cybernetics",
    inputs: { synthetic_muscle_fiber: 1, cyber_servo_motors: 1 },
    outputs: { cyber_prosthetic_limb: 1, combat_stimulant_injectors: 1 },
    buildingKey: "blackMarketCyberClinics",
    ticksPerCycle: 2,
  },

  // ── COMMERCIAL ──────────────────────────────────────────────────────
  {
    id: "mega_mall_trade",
    name: "Mega-Mall Trade Operations",
    category: "manufacturing",
    inputs: { consumer_electronics: 3, processed_food: 2 },
    outputs: { luxury_food_hampers: 2, entertainment_media: 1 },
    buildingKey: "megaMallComplexes",
    ticksPerCycle: 2,
  },
  {
    id: "data_brokerage",
    name: "Data Brokerage Services",
    category: "manufacturing",
    inputs: { circuit_board: 2 },
    outputs: { data_slates: 3, intelligence_reports: 1 },
    buildingKey: "dataServiceBureaus",
    ticksPerCycle: 2,
  },
  {
    id: "cyberware_retail",
    name: "Cyberware Retail Distribution",
    category: "manufacturing",
    inputs: { cyber_prosthetic_limb: 1, optical_sensor_arrays: 1 },
    outputs: { designer_augments: 1 },
    buildingKey: "cyberwareRetailChains",
    ticksPerCycle: 3,
  },

  // ── WASTELAND ───────────────────────────────────────────────────────
  {
    id: "wasteland_scavenging",
    name: "Wasteland Scavenging Operations",
    category: "extraction",
    inputs: {},
    outputs: { salvaged_tech_scraps: 4, contaminated_metal: 3, storm_debris: 2 },
    buildingKey: "wastelandScavengerOutposts",
    ticksPerCycle: 1,
  },
  {
    id: "rad_waste_processing",
    name: "Radioactive Waste Processing",
    category: "refining",
    inputs: { rad_waste: 5, contaminated_metal: 3 },
    outputs: { purified_rad_crystal: 2, steel_ingot: 3 },
    buildingKey: "radWasteProcessingPlants",
    ticksPerCycle: 3,
  },
  {
    id: "mutant_trade",
    name: "Mutant Trade Exchange",
    category: "manufacturing",
    inputs: { mutant_hides: 2, feral_creature_parts: 2 },
    outputs: { wasteland_leather: 3, mutant_venom_glands: 1 },
    buildingKey: "mutantTradeDepots",
    ticksPerCycle: 2,
  },
  {
    id: "salvage_tech_repair",
    name: "Salvage Tech Restoration",
    category: "manufacturing",
    inputs: { salvaged_tech_scraps: 4, circuit_board: 1 },
    outputs: { ancient_circuit_relics: 1, mechanical_part: 2 },
    buildingKey: "salvageTechWorkshops",
    ticksPerCycle: 3,
  },
  {
    id: "rad_farm_production",
    name: "Rad-Resistant Farming",
    category: "extraction",
    inputs: { rad_resistant_seeds: 2 },
    outputs: { processed_food: 6, rad_resistant_seeds: 1 },
    buildingKey: "radResistantFarmDomes",
    ticksPerCycle: 2,
  },
  {
    id: "fossil_excavation",
    name: "Fossil Excavation",
    category: "extraction",
    inputs: {},
    outputs: { fossil_amber: 3, petrified_bone: 2 },
    buildingKey: "fossilExcavationSites",
    ticksPerCycle: 2,
  },
  {
    id: "mutant_ranching",
    name: "Mutant Creature Ranching",
    category: "extraction",
    inputs: {},
    outputs: { mutant_hides: 4, feral_creature_parts: 3, mutant_venom_glands: 1 },
    buildingKey: "mutantCreatureRanches",
    ticksPerCycle: 1,
  },
  {
    id: "cursed_earth_survey",
    name: "Deadlands Survey",
    category: "extraction",
    inputs: {},
    outputs: { cursed_earth_soil: 5, rad_blooms: 3, mapping_cartridges: 1 },
    buildingKey: "cursedEarthSurveyTeams",
    ticksPerCycle: 2,
  },

  // ── VEHICLES ────────────────────────────────────────────────────────
  {
    id: "patrol_bike_production",
    name: "Patrol Bike Assembly",
    category: "manufacturing",
    inputs: { engine_blocks: 1, wheel_tire_sets: 2, vehicle_electronics: 1 },
    outputs: { patrol_bike_frames: 1 },
    buildingKey: "patrolBikeFactories",
    ticksPerCycle: 3,
  },
  {
    id: "apc_assembly",
    name: "APC Assembly",
    category: "manufacturing",
    inputs: { apc_hull_sections: 1, engine_blocks: 2, armor_plating_vehicle: 2 },
    outputs: { vehicle_armor_kit: 1 },
    buildingKey: "apcAssemblyPlants",
    ticksPerCycle: 4,
  },
  {
    id: "gunship_assembly",
    name: "Gunship Assembly",
    category: "manufacturing",
    inputs: { gunship_fuselage: 1, rotor_assemblies: 2, flight_control_systems: 1 },
    outputs: { nav_computer_modules: 1 },
    buildingKey: "gunshipHangars",
    ticksPerCycle: 5,
  },
  {
    id: "civilian_vehicle_production",
    name: "Civilian Vehicle Production",
    category: "manufacturing",
    inputs: { engine_blocks: 1, transmission_units: 1, wheel_tire_sets: 4 },
    outputs: { vehicle_seats: 4, exhaust_systems: 1 },
    buildingKey: "civilianVehiclePlants",
    ticksPerCycle: 3,
  },
  {
    id: "drone_manufacturing",
    name: "Drone Manufacturing",
    category: "manufacturing",
    inputs: { drone_propeller_sets: 2, circuit_board: 2, vehicle_electronics: 1 },
    outputs: { nav_computer_modules: 3 },
    buildingKey: "droneManufacturingBays",
    ticksPerCycle: 1,
  },
  {
    id: "engine_testing",
    name: "Engine Testing & QC",
    category: "manufacturing",
    inputs: { engine_blocks: 2, fuel_tanks: 1 },
    outputs: { turbocharger_kits: 1, engine_blocks: 1 },
    buildingKey: "engineTestingFacilities",
    ticksPerCycle: 3,
  },
  {
    id: "tire_tread_production",
    name: "Tire & Tread Production",
    category: "manufacturing",
    inputs: { industrial_plastic: 3, steel_ingot: 1 },
    outputs: { wheel_tire_sets: 4 },
    buildingKey: "tireTreadFactories",
    ticksPerCycle: 2,
  },
  {
    id: "vehicle_recycling",
    name: "Vehicle Recycling",
    category: "extraction",
    inputs: {},
    outputs: { scrap_metal: 8, engine_blocks: 1, mechanical_part: 3 },
    buildingKey: "vehicleRecyclingYards",
    ticksPerCycle: 2,
  },

  // ── BIOTECH ─────────────────────────────────────────────────────────
  {
    id: "gene_splicing",
    name: "Gene Splicing Research",
    category: "manufacturing",
    inputs: { biomass: 3, circuit_board: 1 },
    outputs: { gene_splicing_kits: 2, gene_therapy_vials: 1 },
    buildingKey: "geneSplicingLabs",
    ticksPerCycle: 3,
  },
  {
    id: "tissue_cloning",
    name: "Tissue Cloning",
    category: "manufacturing",
    inputs: { stem_cell_cultures: 2, cloning_substrate: 2 },
    outputs: { lab_grown_skin: 2, bone_growth_matrix: 1 },
    buildingKey: "cloningFacilities",
    ticksPerCycle: 3,
  },
  {
    id: "stem_cell_cultivation",
    name: "Stem Cell Cultivation",
    category: "extraction",
    inputs: { biomass: 2 },
    outputs: { stem_cell_cultures: 3, tissue_culture_media: 2 },
    buildingKey: "stemCellBanks",
    ticksPerCycle: 2,
  },
  {
    id: "bio_reactor_processing",
    name: "Bio-Reactor Processing",
    category: "refining",
    inputs: { biomass: 4, tissue_culture_media: 2 },
    outputs: { enzyme_concentrates: 3, bio_reactor_catalysts: 2 },
    buildingKey: "bioReactorFarms",
    ticksPerCycle: 2,
  },
  {
    id: "synthetic_blood_production",
    name: "Synthetic Blood Production",
    category: "manufacturing",
    inputs: { stem_cell_cultures: 1, enzyme_concentrates: 2 },
    outputs: { synthetic_blood: 4 },
    buildingKey: "syntheticBloodBanks",
    ticksPerCycle: 2,
  },
  {
    id: "prion_research",
    name: "Prion Neutralizer Research",
    category: "manufacturing",
    inputs: { enzyme_concentrates: 3, bio_reactor_catalysts: 1 },
    outputs: { prion_neutralizer: 2 },
    buildingKey: "prionResearchContainment",
    ticksPerCycle: 4,
  },
  {
    id: "cryo_preservation",
    name: "Cryo-Preservation Production",
    category: "manufacturing",
    inputs: { enzyme_concentrates: 1, tissue_culture_media: 2 },
    outputs: { cryo_preservation_fluid: 3 },
    buildingKey: "cryoPreservationVaults",
    ticksPerCycle: 2,
  },
  {
    id: "mutagenic_testing",
    name: "Mutagenic Compound Synthesis",
    category: "manufacturing",
    inputs: { bio_reactor_catalysts: 2, gene_splicing_kits: 1 },
    outputs: { mutagenic_compounds: 2, anti_mutagenic_serum: 1 },
    buildingKey: "mutagenicTestingLabs",
    ticksPerCycle: 3,
  },
  {
    id: "rad_bio_filtering",
    name: "Rad Bio-Filter Cultivation",
    category: "extraction",
    inputs: { biomass: 3 },
    outputs: { rad_filter_organisms: 4 },
    buildingKey: "radBioFilterStations",
    ticksPerCycle: 2,
  },

  // ── TEXTILES ────────────────────────────────────────────────────────
  {
    id: "wool_processing",
    name: "Wool Processing",
    category: "refining",
    inputs: { raw_wool: 6 },
    outputs: { spun_yarn: 4 },
    buildingKey: "woolProcessingMills",
    ticksPerCycle: 1,
  },
  {
    id: "fabric_weaving",
    name: "Fabric Weaving",
    category: "manufacturing",
    inputs: { spun_yarn: 4 },
    outputs: { woven_fabric: 3, dyed_fabric: 2 },
    buildingKey: "weavingFactories",
    ticksPerCycle: 2,
  },
  {
    id: "kevlar_production",
    name: "Kevlar Fiber Production",
    category: "manufacturing",
    inputs: { industrial_plastic: 3, carbon_thread: 2 },
    outputs: { kevlar_fiber: 3, ballistic_fabric: 2 },
    buildingKey: "kevlarProductionPlants",
    ticksPerCycle: 3,
  },
  {
    id: "leather_tanning",
    name: "Leather Tanning",
    category: "refining",
    inputs: { leather_hides: 4 },
    outputs: { tanned_leather: 3 },
    buildingKey: "leatherTanneries",
    ticksPerCycle: 2,
  },
  {
    id: "nanoweave_spinning",
    name: "Nanoweave Spinning",
    category: "manufacturing",
    inputs: { nano_material: 2, carbon_thread: 3 },
    outputs: { nanoweave_cloth: 2 },
    buildingKey: "nanoweaveSpinners",
    ticksPerCycle: 3,
  },
  {
    id: "uniform_tailoring",
    name: "Uniform Tailoring",
    category: "manufacturing",
    inputs: { woven_fabric: 3, kevlar_fiber: 1 },
    outputs: { tactical_vests: 2 },
    buildingKey: "uniformTailoringShops",
    ticksPerCycle: 2,
  },
  {
    id: "fiber_recycling",
    name: "Fiber Recycling",
    category: "extraction",
    inputs: {},
    outputs: { recycled_fiber: 5, thread_spools: 3 },
    buildingKey: "recycledFiberPlants",
    ticksPerCycle: 1,
  },
  {
    id: "synthetic_fabric_extrusion",
    name: "Synthetic Fabric Extrusion",
    category: "manufacturing",
    inputs: { industrial_plastic: 3, recycled_fiber: 2 },
    outputs: { waterproof_canvas: 3, mesh_netting: 2 },
    buildingKey: "syntheticFabricExtruders",
    ticksPerCycle: 2,
  },

  // ── MUNITIONS / MILITARY ────────────────────────────────────────────
  {
    id: "small_arms_production",
    name: "Small Arms Production",
    category: "manufacturing",
    inputs: { steel_ingot: 3, mechanical_part: 2, trigger_mechanisms: 2 },
    outputs: { rifle_assemblies: 2, sidearm_kits: 2 },
    buildingKey: "smallArmsFactories",
    ticksPerCycle: 2,
  },
  {
    id: "ammunition_pressing",
    name: "Ammunition Pressing",
    category: "manufacturing",
    inputs: { steel_ingot: 2, copper_ingot: 1 },
    outputs: { ammunition_crate: 6 },
    buildingKey: "ammunitionPressLines",
    ticksPerCycle: 1,
  },
  {
    id: "explosives_production",
    name: "Explosives & Ordnance Production",
    category: "manufacturing",
    inputs: { steel_ingot: 2, detonator_caps: 2 },
    outputs: { grenade_casings: 5, demolition_charges: 3 },
    buildingKey: "explosivesOrdnancePlants",
    ticksPerCycle: 1,
  },
  {
    id: "body_armor_forging",
    name: "Body Armor Forging",
    category: "manufacturing",
    inputs: { ballistic_fabric: 2, composite_armor_plate: 2 },
    outputs: { ballistic_plates: 3, tactical_vests: 2 },
    buildingKey: "bodyArmorForges",
    ticksPerCycle: 2,
  },
  {
    id: "optics_assembly",
    name: "Optics & Sights Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 2, silicon_wafer: 1 },
    outputs: { thermal_scopes: 2, night_vision_goggles: 1, laser_sights: 1 },
    buildingKey: "opticsAndSightsLabs",
    ticksPerCycle: 3,
  },
  {
    id: "field_equipment_production",
    name: "Field Equipment Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 1, processed_food: 3 },
    outputs: { field_radios: 2, combat_rations_pack: 3, field_medical_kits: 1 },
    buildingKey: "fieldEquipmentAssembly",
    ticksPerCycle: 2,
  },
  {
    id: "energy_weapon_production",
    name: "Energy Weapon Forging",
    category: "manufacturing",
    inputs: { reactor_alloy: 2, smart_circuitry: 2, energy_weapon_cores: 1 },
    outputs: { hotshot_laser_packs: 3, energy_weapon_cores: 1 },
    buildingKey: "energyWeaponForges",
    ticksPerCycle: 4,
  },
  {
    id: "fortification_materials",
    name: "Fortification Material Production",
    category: "manufacturing",
    inputs: { steel_ingot: 2, concrete_mix: 3 },
    outputs: { barbed_wire_rolls: 4, sandbag_pallets: 5, portable_barriers: 2 },
    buildingKey: "fortificationMaterialYards",
    ticksPerCycle: 1,
  },
  {
    id: "special_weapons_rd",
    name: "Special Weapons R&D",
    category: "manufacturing",
    inputs: { reactor_alloy: 3, smart_circuitry: 2, titanium_alloy: 2 },
    outputs: { railgun_slugs: 3, micro_missile_pods: 2 },
    buildingKey: "specialWeaponsDivision",
    ticksPerCycle: 3,
  },

  // ── INFRASTRUCTURE ──────────────────────────────────────────────────
  {
    id: "waste_incineration",
    name: "Waste Incineration Power",
    category: "refining",
    inputs: { scrap_metal: 3 },
    outputs: { steel_ingot: 1, power_cable: 2 },
    buildingKey: "wasteIncinerationPlants",
    ticksPerCycle: 1,
  },
  {
    id: "air_purification",
    name: "Air Purification Processing",
    category: "extraction",
    inputs: {},
    outputs: { purified_water: 2 },
    buildingKey: "airPurificationTowers",
    ticksPerCycle: 2,
  },

  // ── RAW MATERIALS EXTRACTION ──────────────────────────────────────
  {
    id: "deep_core_mining",
    name: "Deep Core Mineral Extraction",
    category: "extraction",
    inputs: {},
    outputs: { iron_ore: 30, titanium_ore: 4, rare_earth_minerals: 2 },
    buildingKey: "deepCoreExcavators",
    ticksPerCycle: 2,
  },
  {
    id: "open_pit_mining",
    name: "Open Pit Mining",
    category: "extraction",
    inputs: {},
    outputs: { iron_ore: 25, copper_ore: 15 },
    buildingKey: "openPitMineExpansion",
    ticksPerCycle: 1,
  },
  {
    id: "scrap_yard_processing",
    name: "Scrap Yard Sorting",
    category: "extraction",
    inputs: {},
    outputs: { scrap_metal: 25, electronic_waste: 6 },
    buildingKey: "scrapYardProcessingHub",
    ticksPerCycle: 1,
  },
  {
    id: "quarry_crushing",
    name: "Quarry & Aggregate Crushing",
    category: "extraction",
    inputs: {},
    outputs: { limestone_raw: 15, sand_deposits: 12, gravel_aggregate: 10 },
    buildingKey: "quarryAndCrushingPlant",
    ticksPerCycle: 1,
  },
  {
    id: "rare_earth_separation",
    name: "Rare Earth Element Separation",
    category: "refining",
    inputs: { rare_earth_minerals: 6 },
    outputs: { refined_rare_earth: 3, lithium_refined: 2 },
    buildingKey: "rareEarthSeparationFac",
    ticksPerCycle: 2,
  },
  {
    id: "silica_purification",
    name: "Silica Purification",
    category: "refining",
    inputs: { sand_deposits: 10 },
    outputs: { silicon_ore: 6, glass_sheet: 4 },
    buildingKey: "sandAndSilicaProcessing",
    ticksPerCycle: 1,
  },
  {
    id: "coal_gasification",
    name: "Coal Gasification",
    category: "refining",
    inputs: { coal_deposits: 8 },
    outputs: { syngas: 10, chemical_feedstock: 5 },
    buildingKey: "coalGasificationPlant",
    ticksPerCycle: 1,
  },
  {
    id: "ore_washing",
    name: "Ore Washing & Grading",
    category: "refining",
    inputs: { iron_ore: 15 },
    outputs: { iron_ore: 20, sand_deposits: 3 },
    buildingKey: "oreWashingStation",
    ticksPerCycle: 1,
  },
  {
    id: "timber_milling",
    name: "Timber Processing",
    category: "extraction",
    inputs: {},
    outputs: { processed_timber: 8, sawdust: 4 },
    buildingKey: "timberProcessingMill",
    ticksPerCycle: 1,
  },
  {
    id: "salt_harvesting",
    name: "Salt Evaporation Harvest",
    category: "extraction",
    inputs: {},
    outputs: { industrial_salt: 12 },
    buildingKey: "saltEvaporationPonds",
    ticksPerCycle: 2,
  },

  // ── CHEMICAL PROCESSING ───────────────────────────────────────────
  {
    id: "petrochemical_cracking",
    name: "Petrochemical Cracking",
    category: "chemicals",
    inputs: { crude_oil: 10 },
    outputs: { chemical_feedstock: 8, fuel_gas: 6, naphtha: 4 },
    buildingKey: "petrochemicalCrackingTowers",
    ticksPerCycle: 1,
  },
  {
    id: "acid_production",
    name: "Industrial Acid Production",
    category: "chemicals",
    inputs: { chemical_feedstock: 4, industrial_salt: 2 },
    outputs: { sulfuric_acid: 5, hydrochloric_acid: 3 },
    buildingKey: "acidProductionPlant",
    ticksPerCycle: 1,
  },
  {
    id: "solvent_distillation",
    name: "Solvent Distillation",
    category: "chemicals",
    inputs: { naphtha: 4 },
    outputs: { industrial_solvent: 6, acetone: 3 },
    buildingKey: "industrialSolventWorks",
    ticksPerCycle: 1,
  },
  {
    id: "fertilizer_synthesis",
    name: "NPK Fertilizer Synthesis",
    category: "chemicals",
    inputs: { chemical_feedstock: 5, industrial_salt: 3 },
    outputs: { chemical_fertilizer: 8 },
    buildingKey: "fertilizerSynthesisPlant",
    ticksPerCycle: 1,
  },
  {
    id: "explosives_compounding",
    name: "Explosives Compounding",
    category: "chemicals",
    inputs: { chemical_feedstock: 4, sulfuric_acid: 2 },
    outputs: { explosive_compounds: 3 },
    buildingKey: "explosivesCompoundingFacility",
    ticksPerCycle: 2,
  },
  {
    id: "adhesives_production",
    name: "Adhesives & Resins Production",
    category: "chemicals",
    inputs: { naphtha: 3, chemical_feedstock: 2 },
    outputs: { epoxy_resin: 4, industrial_adhesive: 3 },
    buildingKey: "adhesivesAndResinsFactory",
    ticksPerCycle: 1,
  },
  {
    id: "water_treatment_chem",
    name: "Water Treatment Chemical Production",
    category: "chemicals",
    inputs: { industrial_salt: 4 },
    outputs: { water_treatment_chemical: 6 },
    buildingKey: "waterTreatmentChemWorks",
    ticksPerCycle: 1,
  },
  {
    id: "paint_production",
    name: "Industrial Paint & Coatings",
    category: "chemicals",
    inputs: { industrial_solvent: 3, chemical_feedstock: 2 },
    outputs: { industrial_paint: 5 },
    buildingKey: "paintAndCoatingsPlant",
    ticksPerCycle: 1,
  },
  {
    id: "lubricant_production",
    name: "Lubricant & Fluid Processing",
    category: "chemicals",
    inputs: { crude_oil: 5 },
    outputs: { machine_lubricant: 6, hydraulic_fluid: 4 },
    buildingKey: "lubricantsAndFluidsMill",
    ticksPerCycle: 1,
  },

  // ── PLASTICS PROCESSING ───────────────────────────────────────────
  {
    id: "polymer_extrusion",
    name: "Polymer Extrusion",
    category: "plastics",
    inputs: { industrial_plastic: 6, naphtha: 2 },
    outputs: { pe_pellets: 5, pp_pellets: 4, plastic_pipe_stock: 3 },
    buildingKey: "polymerExtrusionPlant",
    ticksPerCycle: 1,
  },
  {
    id: "injection_moulding",
    name: "Injection Moulding",
    category: "plastics",
    inputs: { pe_pellets: 4, pp_pellets: 3 },
    outputs: { moulded_plastic_goods: 6, plastic_housings: 4 },
    buildingKey: "injectionMouldingFacility",
    ticksPerCycle: 1,
  },
  {
    id: "synthetic_rubber_prod",
    name: "Synthetic Rubber Production",
    category: "plastics",
    inputs: { chemical_feedstock: 4, fuel_gas: 3 },
    outputs: { synthetic_rubber: 5, rubber_seals: 3 },
    buildingKey: "syntheticRubberWorks",
    ticksPerCycle: 1,
  },
  {
    id: "composite_lamination",
    name: "Composite Panel Lamination",
    category: "plastics",
    inputs: { industrial_plastic: 3, carbon_fiber_raw: 2 },
    outputs: { composite_panels: 3, carbon_fiber_sheets: 2 },
    buildingKey: "compositeLaminationMill",
    ticksPerCycle: 2,
  },
  {
    id: "foam_production",
    name: "Foam Manufacturing",
    category: "plastics",
    inputs: { industrial_plastic: 4, chemical_feedstock: 2 },
    outputs: { foam_insulation: 6, packaging_foam: 4 },
    buildingKey: "foamManufacturingPlant",
    ticksPerCycle: 1,
  },
  {
    id: "plastic_recycling",
    name: "Plastic Recycling",
    category: "plastics",
    inputs: {},
    outputs: { industrial_plastic: 8, pe_pellets: 3 },
    buildingKey: "plasticRecyclingComplex",
    ticksPerCycle: 1,
  },
  {
    id: "bioplastics_research",
    name: "Bio-Plastics Synthesis",
    category: "plastics",
    inputs: { biomass: 6 },
    outputs: { industrial_plastic: 4, bio_polymer: 3 },
    buildingKey: "bioPlasticsLab",
    ticksPerCycle: 2,
  },
  {
    id: "filament_production",
    name: "3D Print Filament Production",
    category: "plastics",
    inputs: { pe_pellets: 3, pp_pellets: 2 },
    outputs: { print_filament: 5 },
    buildingKey: "filamentProductionLine",
    ticksPerCycle: 1,
  },
  {
    id: "pvc_pipe_fabrication",
    name: "PVC Pipe & Fittings",
    category: "plastics",
    inputs: { industrial_plastic: 5 },
    outputs: { plastic_pipe_stock: 6, pipe_fittings: 4 },
    buildingKey: "pvcPipeAndFittingsPlant",
    ticksPerCycle: 1,
  },
  {
    id: "polycarbonate_pressing",
    name: "Polycarbonate Panel Pressing",
    category: "plastics",
    inputs: { industrial_plastic: 4, chemical_feedstock: 2 },
    outputs: { polycarbonate_panel: 4 },
    buildingKey: "polycarbonatePanelWorks",
    ticksPerCycle: 1,
  },

  // ── FINISHED GOODS MANUFACTURING ──────────────────────────────────
  {
    id: "consumer_goods_assembly",
    name: "Consumer Goods Assembly",
    category: "finished",
    inputs: { moulded_plastic_goods: 3, mechanical_part: 2, circuit_board: 1 },
    outputs: { consumer_electronics: 4, consumer_goods_pack: 3 },
    buildingKey: "consumerGoodsFactory",
    ticksPerCycle: 1,
  },
  {
    id: "electronics_final_assembly",
    name: "Electronics Final Assembly",
    category: "finished",
    inputs: { circuit_board: 4, plastic_housings: 3, copper_ingot: 2 },
    outputs: { consumer_electronics: 5, data_slates: 2 },
    buildingKey: "electronicsAssemblyPlant",
    ticksPerCycle: 1,
  },
  {
    id: "vehicle_assembly",
    name: "Vehicle Assembly",
    category: "finished",
    inputs: { steel_ingot: 8, mechanical_part: 4, circuit_board: 2, synthetic_rubber: 3 },
    outputs: { vehicle_chassis: 2 },
    buildingKey: "vehicleManufacturingComplex",
    ticksPerCycle: 2,
  },
  {
    id: "furniture_production",
    name: "Furniture & Fittings Production",
    category: "finished",
    inputs: { processed_timber: 4, moulded_plastic_goods: 2, steel_ingot: 1 },
    outputs: { furniture_units: 5 },
    buildingKey: "furnitureAndFittingsPlant",
    ticksPerCycle: 1,
  },
  {
    id: "textile_weaving",
    name: "Textile Milling",
    category: "finished",
    inputs: { synthetic_rubber: 2, industrial_plastic: 3 },
    outputs: { woven_fabric: 6, finished_clothing: 4 },
    buildingKey: "textileMillComplex",
    ticksPerCycle: 1,
  },
  {
    id: "tool_die_production",
    name: "Tool & Die Manufacturing",
    category: "finished",
    inputs: { steel_ingot: 4, titanium_alloy: 1 },
    outputs: { precision_tooling: 3, industrial_dies: 2 },
    buildingKey: "toolAndDieWorks",
    ticksPerCycle: 1,
  },
  {
    id: "packaging_production",
    name: "Packaging & Crating",
    category: "finished",
    inputs: { processed_timber: 2, industrial_plastic: 2 },
    outputs: { packaging_materials: 6 },
    buildingKey: "packagingAndCratingPlant",
    ticksPerCycle: 1,
  },
  {
    id: "glass_ceramics_prod",
    name: "Glass & Ceramics Production",
    category: "finished",
    inputs: { sand_deposits: 6, limestone_raw: 3 },
    outputs: { glass_sheet: 5, ceramic_components: 3 },
    buildingKey: "glassAndCeramicsWorks",
    ticksPerCycle: 1,
  },
  {
    id: "medical_device_fab",
    name: "Medical Device Fabrication",
    category: "finished",
    inputs: { circuit_board: 2, titanium_alloy: 1, polycarbonate_panel: 2 },
    outputs: { medical_instruments: 3 },
    buildingKey: "medicalDeviceFabLab",
    ticksPerCycle: 2,
  },

  // ── ADVANCED MATERIALS ────────────────────────────────────────────
  {
    id: "nano_materials_synthesis",
    name: "Nano-Materials Synthesis",
    category: "advanced",
    inputs: { rare_earth_minerals: 3, smart_circuitry: 2 },
    outputs: { nano_material: 2, nano_coating: 1 },
    buildingKey: "nanoMaterialsResearchLab",
    ticksPerCycle: 3,
  },
  {
    id: "smart_materials_fab",
    name: "Smart Materials Fabrication",
    category: "advanced",
    inputs: { titanium_alloy: 2, circuit_board: 2, nano_material: 1 },
    outputs: { smart_alloy: 2 },
    buildingKey: "smartMaterialsFabrication",
    ticksPerCycle: 2,
  },
  {
    id: "superconductor_production",
    name: "Superconductor Production",
    category: "advanced",
    inputs: { refined_rare_earth: 3, copper_ingot: 4 },
    outputs: { superconductor_wire: 2 },
    buildingKey: "superconductorFoundry",
    ticksPerCycle: 3,
  },
  {
    id: "reactor_alloy_forging",
    name: "Reactor Alloy Forging",
    category: "advanced",
    inputs: { titanium_alloy: 3, rare_earth_minerals: 2, steel_ingot: 4 },
    outputs: { reactor_alloy: 3 },
    buildingKey: "reactorAlloySmeltingBay",
    ticksPerCycle: 3,
  },
  {
    id: "ceramic_matrix_composites",
    name: "Ceramic Matrix Composite Production",
    category: "advanced",
    inputs: { ceramic_components: 3, carbon_fiber_raw: 2 },
    outputs: { ceramic_composite: 2 },
    buildingKey: "ceramicMatrixCompositeLab",
    ticksPerCycle: 2,
  },
  {
    id: "aerospace_titanium_forging",
    name: "Aerospace Titanium Forging",
    category: "advanced",
    inputs: { titanium_alloy: 4, steel_ingot: 2 },
    outputs: { aerospace_titanium_part: 2 },
    buildingKey: "aerospaceGradeTitaniumMill",
    ticksPerCycle: 2,
  },
  {
    id: "carbon_fibre_spinning",
    name: "Carbon Fibre Spinning",
    category: "advanced",
    inputs: { chemical_feedstock: 4 },
    outputs: { carbon_fiber_raw: 3, carbon_fiber_sheets: 2 },
    buildingKey: "carbonFibreSpinningPlant",
    ticksPerCycle: 2,
  },
  {
    id: "quantum_dot_fabrication",
    name: "Quantum Dot Fabrication",
    category: "advanced",
    inputs: { refined_rare_earth: 2, silicon_wafer: 3 },
    outputs: { quantum_dots: 2 },
    buildingKey: "quantumDotFabricationLab",
    ticksPerCycle: 3,
  },
  {
    id: "industrial_diamond_synthesis",
    name: "Industrial Diamond Synthesis",
    category: "advanced",
    inputs: { coal_deposits: 10 },
    outputs: { industrial_diamond: 2 },
    buildingKey: "industrialDiamondSynthesizer",
    ticksPerCycle: 3,
  },

  // ── PHARMACEUTICALS ───────────────────────────────────────────────
  {
    id: "antibiotic_synthesis",
    name: "Antibiotic Synthesis",
    category: "chemicals",
    inputs: { biomass: 4, chemical_feedstock: 3 },
    outputs: { antibiotics: 4 },
    buildingKey: "pharmaceuticalPlants",
    ticksPerCycle: 2,
  },
  {
    id: "painkiller_production",
    name: "Painkiller Production",
    category: "chemicals",
    inputs: { chemical_feedstock: 3, biomass: 2 },
    outputs: { painkillers: 5 },
    buildingKey: "pharmaceuticalPlants",
    ticksPerCycle: 1,
  },
  {
    id: "vaccine_manufacturing",
    name: "Vaccine Manufacturing",
    category: "chemicals",
    inputs: { stem_cell_cultures: 2, enzyme_concentrates: 2, biomass: 3 },
    outputs: { vaccines: 3 },
    buildingKey: "vaccineResearchLabs",
    ticksPerCycle: 3,
  },
  {
    id: "radiation_pill_production",
    name: "Anti-Radiation Pill Production",
    category: "chemicals",
    inputs: { chemical_feedstock: 4, rad_filter_organisms: 2 },
    outputs: { radiation_pills: 5 },
    buildingKey: "radPharmacyLabs",
    ticksPerCycle: 2,
  },
  {
    id: "combat_stim_production",
    name: "Combat Stimulant Production",
    category: "chemicals",
    inputs: { bio_stimulant: 2, chemical_feedstock: 3 },
    outputs: { combat_stims: 3 },
    buildingKey: "militaryPharmLabs",
    ticksPerCycle: 2,
  },
  {
    id: "biogel_patch_manufacturing",
    name: "BioGel Patch Manufacturing",
    category: "chemicals",
    inputs: { synthetic_blood: 2, bio_polymer: 3 },
    outputs: { biogel_patches: 4 },
    buildingKey: "biogelProductionLabs",
    ticksPerCycle: 2,
  },
  {
    id: "surgical_supply_production",
    name: "Surgical Supply Production",
    category: "manufacturing",
    inputs: { steel_ingot: 2, polycarbonate_panel: 2, antibiotics: 1 },
    outputs: { surgical_supplies: 3 },
    buildingKey: "surgicalSupplyFactories",
    ticksPerCycle: 2,
  },
  {
    id: "first_aid_kit_assembly",
    name: "First Aid Kit Assembly",
    category: "manufacturing",
    inputs: { painkillers: 2, antibiotics: 1, woven_fabric: 1 },
    outputs: { first_aid_kits: 4 },
    buildingKey: "medicalKitAssemblyLines",
    ticksPerCycle: 1,
  },
  {
    id: "immune_booster_brewing",
    name: "Immune Booster Brewing",
    category: "chemicals",
    inputs: { enzyme_concentrates: 2, gene_therapy_vials: 1 },
    outputs: { immune_boosters: 3 },
    buildingKey: "immunologyResearchLabs",
    ticksPerCycle: 3,
  },
  {
    id: "detox_compound_synthesis",
    name: "Detox Compound Synthesis",
    category: "chemicals",
    inputs: { chemical_feedstock: 3, anti_mutagenic_serum: 1 },
    outputs: { detox_compounds: 4 },
    buildingKey: "detoxificationPlants",
    ticksPerCycle: 2,
  },

  // ── FOOD PROCESSING ───────────────────────────────────────────────
  {
    id: "grain_ration_production",
    name: "Grain Ration Production",
    category: "manufacturing",
    inputs: { biomass: 6, processed_food: 4 },
    outputs: { grain_rations: 8 },
    buildingKey: "grainProcessingMills",
    ticksPerCycle: 1,
  },
  {
    id: "emergency_ration_packing",
    name: "Emergency Ration Packing",
    category: "manufacturing",
    inputs: { processed_food: 5, packaging_materials: 2 },
    outputs: { emergency_rations: 6 },
    buildingKey: "rationPackingFacilities",
    ticksPerCycle: 1,
  },
  {
    id: "canned_goods_production",
    name: "Canned Goods Production",
    category: "manufacturing",
    inputs: { processed_food: 4, aluminum_ingot: 2 },
    outputs: { canned_goods: 6 },
    buildingKey: "canningFactories",
    ticksPerCycle: 1,
  },
  {
    id: "protein_powder_processing",
    name: "Protein Powder Processing",
    category: "manufacturing",
    inputs: { synth_protein: 6, insect_protein: 4 },
    outputs: { protein_powder: 8 },
    buildingKey: "proteinProcessingPlants",
    ticksPerCycle: 1,
  },
  {
    id: "energy_bar_production",
    name: "Energy Bar Production",
    category: "manufacturing",
    inputs: { protein_powder: 3, processed_food: 2, packaging_materials: 1 },
    outputs: { energy_bars: 6 },
    buildingKey: "nutritionBarLines",
    ticksPerCycle: 1,
  },
  {
    id: "synthetic_meat_fabrication",
    name: "Synthetic Meat Fabrication",
    category: "manufacturing",
    inputs: { stem_cell_cultures: 2, tissue_culture_media: 3, biomass: 4 },
    outputs: { synthetic_meat_slabs: 5 },
    buildingKey: "syntheticMeatVats",
    ticksPerCycle: 2,
  },
  {
    id: "insect_protein_block_pressing",
    name: "Insect Protein Block Pressing",
    category: "manufacturing",
    inputs: { insect_protein: 8 },
    outputs: { insect_protein_blocks: 6 },
    buildingKey: "insectProcessingPlants",
    ticksPerCycle: 1,
  },
  {
    id: "algae_paste_production",
    name: "Algae Protein Paste Production",
    category: "manufacturing",
    inputs: { waste_algae: 10 },
    outputs: { algae_protein_paste: 6 },
    buildingKey: "algaeProcessingFacilities",
    ticksPerCycle: 1,
  },
  {
    id: "nutrient_supplement_production",
    name: "Nutrient Supplement Production",
    category: "manufacturing",
    inputs: { cave_mushroom: 4, fungal_spores: 3, biomass: 2 },
    outputs: { nutrient_supplements: 5 },
    buildingKey: "nutrientSynthesisLabs",
    ticksPerCycle: 2,
  },
  {
    id: "beverage_concentrate_production",
    name: "Beverage Concentrate Production",
    category: "manufacturing",
    inputs: { ferment_sludge: 6, biomass: 3 },
    outputs: { beverage_concentrates: 5 },
    buildingKey: "beverageConcentratePlants",
    ticksPerCycle: 1,
  },

  // ── ELECTRONICS MANUFACTURING ─────────────────────────────────────
  {
    id: "microprocessor_fabrication",
    name: "Microprocessor Fabrication",
    category: "advanced",
    inputs: { silicon_wafer: 4, smart_circuitry: 2, rare_earth_minerals: 1 },
    outputs: { microprocessors: 3 },
    buildingKey: "microprocessorFabs",
    workersKey: "aiSystemsEngineers",
    ticksPerCycle: 3,
  },
  {
    id: "memory_chip_production",
    name: "Memory Chip Production",
    category: "advanced",
    inputs: { silicon_wafer: 3, circuit_board: 2 },
    outputs: { memory_chips: 4 },
    buildingKey: "memoryChipFabs",
    ticksPerCycle: 2,
  },
  {
    id: "led_panel_assembly",
    name: "LED Panel Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 2, copper_ingot: 2, polycarbonate_panel: 1 },
    outputs: { led_panels: 4 },
    buildingKey: "ledPanelAssemblyPlants",
    ticksPerCycle: 1,
  },
  {
    id: "surveillance_camera_assembly",
    name: "Surveillance Camera Assembly",
    category: "manufacturing",
    inputs: { circuit_board: 2, silicon_wafer: 1, plastic_housings: 2 },
    outputs: { surveillance_cameras: 3 },
    buildingKey: "surveillanceEquipmentFactories",
    ticksPerCycle: 2,
  },
  {
    id: "data_server_assembly",
    name: "Data Server Assembly",
    category: "advanced",
    inputs: { microprocessors: 3, memory_chips: 4, circuit_board: 3, power_cable: 2 },
    outputs: { data_servers: 2 },
    buildingKey: "dataServerFabrication",
    ticksPerCycle: 3,
  },
  {
    id: "fiber_optic_production",
    name: "Fiber Optic Cable Production",
    category: "manufacturing",
    inputs: { glass_sheet: 4, industrial_plastic: 2 },
    outputs: { fiber_optic_cable: 6 },
    buildingKey: "fiberOpticExtrusionPlants",
    ticksPerCycle: 1,
  },
  {
    id: "radio_transceiver_production",
    name: "Radio Transceiver Production",
    category: "manufacturing",
    inputs: { circuit_board: 2, copper_ingot: 3, plastic_housings: 1 },
    outputs: { radio_transceivers: 3 },
    buildingKey: "communicationsEquipmentFactories",
    ticksPerCycle: 2,
  },
  {
    id: "sensor_module_production",
    name: "Sensor Module Production",
    category: "manufacturing",
    inputs: { circuit_board: 3, silicon_wafer: 2, rare_earth_minerals: 1 },
    outputs: { optical_sensors: 3, motion_sensors: 2 },
    buildingKey: "sensorModuleFactories",
    ticksPerCycle: 2,
  },

  // ── CONSTRUCTION MATERIALS ────────────────────────────────────────
  {
    id: "reinforced_concrete_production",
    name: "Reinforced Concrete Production",
    category: "manufacturing",
    inputs: { concrete_mix: 6, steel_ingot: 3 },
    outputs: { reinforced_concrete: 5 },
    buildingKey: "reinforcedConcretePlants",
    ticksPerCycle: 1,
  },
  {
    id: "rebar_fabrication",
    name: "Rebar Fabrication",
    category: "manufacturing",
    inputs: { steel_ingot: 5 },
    outputs: { rebar: 8 },
    buildingKey: "rebarMillFacilities",
    ticksPerCycle: 1,
  },
  {
    id: "glass_panel_production",
    name: "Glass Panel Production",
    category: "manufacturing",
    inputs: { glass_sheet: 4, aluminum_ingot: 1 },
    outputs: { glass_panels: 5 },
    buildingKey: "glassPanelWorks",
    ticksPerCycle: 1,
  },
  {
    id: "insulation_roll_production",
    name: "Insulation Roll Production",
    category: "manufacturing",
    inputs: { foam_insulation: 4, recycled_fiber: 3 },
    outputs: { insulation_rolls: 6 },
    buildingKey: "insulationRollFactories",
    ticksPerCycle: 1,
  },
  {
    id: "self_healing_concrete_synthesis",
    name: "Self-Healing Concrete Synthesis",
    category: "advanced",
    inputs: { concrete_mix: 5, bio_reactor_catalysts: 2, nano_material: 1 },
    outputs: { self_healing_concrete: 3 },
    buildingKey: "advancedConcreteLabs",
    ticksPerCycle: 3,
  },
  {
    id: "scaffolding_production",
    name: "Scaffolding Production",
    category: "manufacturing",
    inputs: { steel_ingot: 4, aluminum_ingot: 2 },
    outputs: { scaffolding: 5 },
    buildingKey: "scaffoldingFabricationYards",
    ticksPerCycle: 1,
  },
  {
    id: "waterproof_membrane_production",
    name: "Waterproof Membrane Production",
    category: "manufacturing",
    inputs: { industrial_plastic: 3, synthetic_rubber: 2 },
    outputs: { waterproof_membrane: 5 },
    buildingKey: "membraneProductionLines",
    ticksPerCycle: 1,
  },

  // ── ENERGY PRODUCTION ─────────────────────────────────────────────
  {
    id: "lithium_battery_production",
    name: "Lithium-Ion Battery Production",
    category: "manufacturing",
    inputs: { lithium_refined: 3, copper_ingot: 2, plastic_housings: 2 },
    outputs: { batteries_lithium: 4 },
    buildingKey: "batteryManufacturingPlants",
    ticksPerCycle: 2,
  },
  {
    id: "solar_panel_assembly",
    name: "Solar Panel Assembly",
    category: "manufacturing",
    inputs: { silicon_wafer: 4, glass_sheet: 3, aluminum_ingot: 2 },
    outputs: { solar_panels: 3 },
    buildingKey: "solarPanelAssemblyPlants",
    ticksPerCycle: 2,
  },
  {
    id: "hydrogen_fuel_cell_production",
    name: "Hydrogen Fuel Cell Production",
    category: "advanced",
    inputs: { reactor_alloy: 2, platinum_bars: 1, polycarbonate_panel: 2 },
    outputs: { fuel_cells_hydrogen: 2 },
    buildingKey: "fuelCellFabrication",
    ticksPerCycle: 3,
  },
  {
    id: "power_cell_assembly",
    name: "Power Cell Assembly",
    category: "manufacturing",
    inputs: { batteries_lithium: 2, circuit_board: 1, copper_ingot: 2 },
    outputs: { power_cells: 3 },
    buildingKey: "powerCellAssemblyPlants",
    ticksPerCycle: 2,
  },
  {
    id: "nuclear_fuel_rod_fabrication",
    name: "Nuclear Fuel Rod Fabrication",
    category: "advanced",
    inputs: { uranium_ore: 5, reactor_alloy: 2, titanium_alloy: 1 },
    outputs: { fuel_rods_nuclear: 2 },
    buildingKey: "nuclearFuelProcessingPlants",
    ticksPerCycle: 4,
  },
  {
    id: "synthetic_fuel_production",
    name: "Synthetic Fuel Production",
    category: "refining",
    inputs: { syngas: 6, chemical_feedstock: 3 },
    outputs: { synthetic_fuel: 5 },
    buildingKey: "syntheticFuelRefineries",
    ticksPerCycle: 1,
  },
  {
    id: "refined_fuel_distillation",
    name: "Refined Fuel Distillation",
    category: "refining",
    inputs: { crude_oil: 8 },
    outputs: { refined_fuel: 6, diesel_fuel: 4 },
    buildingKey: "fuelDistillationTowers",
    ticksPerCycle: 1,
  },
  {
    id: "smart_grid_hardware_production",
    name: "Smart Grid Hardware Production",
    category: "advanced",
    inputs: { circuit_board: 3, smart_circuitry: 2, fiber_optic_cable: 2 },
    outputs: { smart_grid_hardware: 2 },
    buildingKey: "smartGridManufacturing",
    ticksPerCycle: 3,
  },

  // ── LUXURY GOODS ──────────────────────────────────────────────────
  {
    id: "synthetic_gemstone_production",
    name: "Synthetic Gemstone Production",
    category: "advanced",
    inputs: { rare_earth_minerals: 3, industrial_diamond: 1 },
    outputs: { synthetic_gemstones: 3 },
    buildingKey: "gemSynthesisLabs",
    ticksPerCycle: 3,
  },
  {
    id: "holo_artwork_creation",
    name: "Holo-Artwork Creation",
    category: "manufacturing",
    inputs: { circuit_board: 2, led_panels: 2, data_slates: 1 },
    outputs: { holo_artwork: 2 },
    buildingKey: "holoArtStudios",
    ticksPerCycle: 3,
  },
  {
    id: "exotic_perfume_distillation",
    name: "Exotic Perfume Distillation",
    category: "manufacturing",
    inputs: { mutant_flora: 4, urban_pollen: 3, industrial_solvent: 2 },
    outputs: { exotic_perfumes: 3 },
    buildingKey: "perfumeDistilleries",
    ticksPerCycle: 2,
  },
  {
    id: "ornamental_metal_crafting",
    name: "Ornamental Metal Crafting",
    category: "manufacturing",
    inputs: { gold_ore: 3, silver_ore: 3, titanium_alloy: 1 },
    outputs: { ornamental_metals: 3 },
    buildingKey: "ornamentalMetalWorkshops",
    ticksPerCycle: 2,
  },
  {
    id: "bespoke_clothing_tailoring",
    name: "Bespoke Clothing Tailoring",
    category: "manufacturing",
    inputs: { nanoweave_cloth: 2, luminous_dye: 2, tanned_leather: 1 },
    outputs: { bespoke_clothing: 2 },
    buildingKey: "bespokeTailorShops",
    ticksPerCycle: 3,
  },

  // ── CONSUMER GOODS MANUFACTURING ──────────────────────────────────
  {
    id: "household_appliance_production",
    name: "Household Appliance Production",
    category: "finished",
    inputs: { consumer_electronics: 3, moulded_plastic_goods: 2, mechanical_part: 2 },
    outputs: { household_appliances: 4 },
    buildingKey: "applianceManufacturingPlants",
    ticksPerCycle: 2,
  },
  {
    id: "personal_electronics_assembly",
    name: "Personal Electronics Assembly",
    category: "finished",
    inputs: { microprocessors: 2, memory_chips: 2, led_panels: 1, batteries_lithium: 1 },
    outputs: { personal_electronics: 3 },
    buildingKey: "personalElectronicsAssembly",
    ticksPerCycle: 2,
  },
  {
    id: "communication_device_production",
    name: "Communication Device Production",
    category: "finished",
    inputs: { circuit_board: 2, radio_transceivers: 1, batteries_lithium: 1, plastic_housings: 1 },
    outputs: { communication_devices: 3 },
    buildingKey: "communicationDeviceFactories",
    ticksPerCycle: 2,
  },
  {
    id: "water_filter_production",
    name: "Water Filter Production",
    category: "manufacturing",
    inputs: { industrial_plastic: 3, ceramic_components: 2 },
    outputs: { water_filters: 5 },
    buildingKey: "waterFilterFactories",
    ticksPerCycle: 1,
  },
  {
    id: "cleaning_product_mixing",
    name: "Cleaning Product Mixing",
    category: "chemicals",
    inputs: { chemical_feedstock: 3, industrial_solvent: 2 },
    outputs: { cleaning_chemicals: 6 },
    buildingKey: "cleaningProductMixingPlants",
    ticksPerCycle: 1,
  },

  // ── CLOTHING & GEAR ───────────────────────────────────────────────
  {
    id: "civilian_clothing_production",
    name: "Civilian Clothing Production",
    category: "finished",
    inputs: { woven_fabric: 4, thread_spools: 2 },
    outputs: { civilian_clothing: 6 },
    buildingKey: "garmentFactories",
    ticksPerCycle: 1,
  },
  {
    id: "hazmat_suit_production",
    name: "Hazmat Suit Production",
    category: "manufacturing",
    inputs: { waterproof_canvas: 3, rubber_seals: 2, polycarbonate_panel: 1 },
    outputs: { hazmat_suits: 2 },
    buildingKey: "protectiveGearFactories",
    ticksPerCycle: 2,
  },
  {
    id: "gas_mask_production",
    name: "Gas Mask Production",
    category: "manufacturing",
    inputs: { synthetic_rubber: 2, polycarbonate_panel: 1, ceramic_components: 1 },
    outputs: { gas_masks: 3 },
    buildingKey: "respiratorFactories",
    ticksPerCycle: 2,
  },
  {
    id: "work_uniform_production",
    name: "Work Uniform Production",
    category: "finished",
    inputs: { woven_fabric: 3, dyed_fabric: 2, thread_spools: 1 },
    outputs: { work_uniforms: 5 },
    buildingKey: "uniformProductionLines",
    ticksPerCycle: 1,
  },
  {
    id: "body_armor_light_production",
    name: "Light Body Armor Production",
    category: "manufacturing",
    inputs: { kevlar_fiber: 3, ballistic_fabric: 2, composite_armor_plate: 1 },
    outputs: { body_armor_light: 2 },
    buildingKey: "lightArmorFactories",
    ticksPerCycle: 2,
  },

  // ── WATER PROCESSING ──────────────────────────────────────────────
  {
    id: "water_purification",
    name: "Water Purification",
    category: "refining",
    inputs: { water_treatment_chemical: 3 },
    outputs: { purified_water: 8 },
    buildingKey: "waterPurificationStations",
    ticksPerCycle: 1,
  },
  {
    id: "bottled_water_production",
    name: "Bottled Water Production",
    category: "manufacturing",
    inputs: { purified_water: 4, moulded_plastic_goods: 2 },
    outputs: { bottled_water: 6 },
    buildingKey: "bottlingPlants",
    ticksPerCycle: 1,
  },
  {
    id: "distilled_water_production",
    name: "Distilled Water Production",
    category: "refining",
    inputs: { purified_water: 6 },
    outputs: { distilled_water: 4 },
    buildingKey: "distillationFacilities",
    ticksPerCycle: 2,
  },

  // ── GASES PROCESSING ──────────────────────────────────────────────
  {
    id: "oxygen_production",
    name: "Industrial Oxygen Production",
    category: "refining",
    inputs: { purified_water: 4 },
    outputs: { oxygen_industrial: 6, hydrogen_gas: 4 },
    buildingKey: "electrolysisPlants",
    ticksPerCycle: 1,
  },
  {
    id: "medical_oxygen_refinement",
    name: "Medical Oxygen Refinement",
    category: "refining",
    inputs: { oxygen_industrial: 4 },
    outputs: { oxygen_medical: 3 },
    buildingKey: "medicalGasRefineries",
    ticksPerCycle: 2,
  },
  {
    id: "ammonia_synthesis",
    name: "Ammonia Synthesis",
    category: "chemicals",
    inputs: { hydrogen_gas: 4, nitrogen_gas: 2 },
    outputs: { ammonia_gas: 5 },
    buildingKey: "ammoniaSynthesisPlants",
    ticksPerCycle: 1,
  },

  // ── SPACE COMMODITIES ─────────────────────────────────────────────
  {
    id: "orbital_fuel_cell_production",
    name: "Orbital Fuel Cell Production",
    category: "advanced",
    inputs: { fuel_cells_hydrogen: 2, reactor_alloy: 2, aerospace_titanium_part: 1 },
    outputs: { orbital_fuel_cells: 2 },
    buildingKey: "orbitalFuelCellFabs",
    ticksPerCycle: 4,
  },
  {
    id: "radiation_shielding_production",
    name: "Radiation Shielding Production",
    category: "advanced",
    inputs: { composite_armor_plate: 3, reactor_alloy: 2, lead_ore: 4 },
    outputs: { radiation_shielding_plates: 2 },
    buildingKey: "radiationShieldingPlants",
    ticksPerCycle: 3,
  },
  {
    id: "life_support_cartridge_production",
    name: "Life Support Cartridge Production",
    category: "advanced",
    inputs: { oxygen_medical: 3, water_filters: 2, circuit_board: 1 },
    outputs: { life_support_cartridges: 2 },
    buildingKey: "lifeSupportManufacturing",
    ticksPerCycle: 3,
  },
  {
    id: "satellite_component_assembly",
    name: "Satellite Component Assembly",
    category: "advanced",
    inputs: { smart_circuitry: 3, solar_panels: 2, aerospace_titanium_part: 2 },
    outputs: { satellite_components: 2 },
    buildingKey: "satelliteAssemblyBays",
    ticksPerCycle: 4,
  },

  // ── DATA & MEDIA ──────────────────────────────────────────────────
  {
    id: "encrypted_data_core_production",
    name: "Encrypted Data Core Production",
    category: "advanced",
    inputs: { data_slates: 3, smart_circuitry: 2 },
    outputs: { encrypted_data_cores: 2 },
    buildingKey: "dataEncryptionFacilities",
    ticksPerCycle: 3,
  },
  {
    id: "training_simulation_production",
    name: "Training Simulation Production",
    category: "manufacturing",
    inputs: { data_slates: 2, circuit_board: 2 },
    outputs: { training_simulations: 3 },
    buildingKey: "simulationDesignStudios",
    ticksPerCycle: 2,
  },
  {
    id: "propaganda_broadcast_production",
    name: "Propaganda Broadcast Production",
    category: "manufacturing",
    inputs: { data_slates: 2, entertainment_media: 1 },
    outputs: { propaganda_broadcasts: 3 },
    buildingKey: "propagandaMediaCenters",
    ticksPerCycle: 1,
  },

  // ── INDUSTRIAL PARTS ──────────────────────────────────────────────
  {
    id: "bearing_production",
    name: "Industrial Bearing Production",
    category: "manufacturing",
    inputs: { steel_ingot: 3, machine_lubricant: 1 },
    outputs: { bearings_industrial: 6 },
    buildingKey: "precisionBearingMills",
    ticksPerCycle: 1,
  },
  {
    id: "gear_manufacturing",
    name: "Gear Manufacturing",
    category: "manufacturing",
    inputs: { steel_ingot: 4, precision_tooling: 1 },
    outputs: { gears_assorted: 6 },
    buildingKey: "gearCuttingFactories",
    ticksPerCycle: 1,
  },
  {
    id: "valve_production",
    name: "Industrial Valve Production",
    category: "manufacturing",
    inputs: { steel_ingot: 2, copper_ingot: 1, rubber_seals: 2 },
    outputs: { valves_industrial: 4 },
    buildingKey: "valveManufacturingPlants",
    ticksPerCycle: 1,
  },
  {
    id: "hydraulic_cylinder_production",
    name: "Hydraulic Cylinder Production",
    category: "manufacturing",
    inputs: { steel_ingot: 3, rubber_seals: 2, hydraulic_fluid: 2 },
    outputs: { hydraulic_cylinders: 3 },
    buildingKey: "hydraulicComponentFactories",
    ticksPerCycle: 2,
  },
  {
    id: "fastener_production",
    name: "Fastener Production",
    category: "manufacturing",
    inputs: { steel_ingot: 3 },
    outputs: { fasteners_bolts: 8, fasteners_screws: 6 },
    buildingKey: "fastenerStampingPlants",
    ticksPerCycle: 1,
  },

  // ── METALS REFINING ───────────────────────────────────────────────
  {
    id: "gold_smelting",
    name: "Gold Smelting",
    category: "refining",
    inputs: { gold_ore: 5 },
    outputs: { gold_bars: 3 },
    buildingKey: "preciousMetalSmelters",
    ticksPerCycle: 2,
  },
  {
    id: "silver_smelting",
    name: "Silver Smelting",
    category: "refining",
    inputs: { silver_ore: 5 },
    outputs: { silver_bars: 3 },
    buildingKey: "preciousMetalSmelters",
    ticksPerCycle: 2,
  },
  {
    id: "platinum_refining",
    name: "Platinum Refining",
    category: "refining",
    inputs: { platinum_ore: 4 },
    outputs: { platinum_bars: 2 },
    buildingKey: "platinumRefineryBays",
    ticksPerCycle: 3,
  },
  {
    id: "tungsten_smelting",
    name: "Tungsten Smelting",
    category: "refining",
    inputs: { tungsten_ore: 5 },
    outputs: { tungsten_bars: 3 },
    buildingKey: "highTempSmelters",
    ticksPerCycle: 2,
  },
  {
    id: "graphene_production",
    name: "Graphene Sheet Production",
    category: "advanced",
    inputs: { graphite_raw: 4, chemical_feedstock: 2 },
    outputs: { graphene_sheets: 2 },
    buildingKey: "grapheneProductionLabs",
    ticksPerCycle: 3,
  },
];

export const INTERMEDIATE_STOCKPILE_IDS = [
  "iron_ore", "copper_ore", "aluminum_ore", "silicon_ore", "titanium_ore",
  "rare_earth_minerals", "coal_deposits", "limestone_raw", "sand_deposits",
  "fuel_gas", "biomass", "scrap_metal", "electronic_waste",
  "steel_ingot", "copper_ingot", "aluminum_ingot", "silicon_wafer",
  "titanium_alloy", "industrial_plastic", "concrete_mix",
  "structural_beam", "power_cable", "utility_pipe", "circuit_board",
  "mechanical_part", "consumer_electronics", "processed_food",
  "construction_supply_kit",
  "smart_circuitry", "composite_armor_plate", "reactor_alloy", "nano_material",
  "droid_chassis", "droid_actuator", "droid_ai_core", "droid_sensor_array",
  "droid_power_cell", "droid_armor_plating", "droid_mobility_module",
  "droid_comms_unit", "droid_tool_attachment", "droid_weapon_mount",
  "ammunition_crate", "vehicle_armor_kit",
  "mutant_flora", "fungal_spores", "rad_crystal", "synth_protein",
  "bio_toxin", "deep_root_fiber", "waste_algae", "insect_protein",
  "mineral_sediment", "biolumen_extract", "ferment_sludge", "urban_pollen",
  "chiton_shell", "synth_mold", "bioresin", "electric_organ",
  "cave_mushroom", "hybrid_seed", "synth_venom", "petrified_wood",
  "refined_bioresin", "chiton_plating", "rad_crystal_lens",
  "bio_stimulant", "luminous_dye", "mutant_fiber_weave",
  "neural_processing_chips", "optical_sensor_arrays", "synthetic_muscle_fiber",
  "cyber_servo_motors", "bio_compatible_titanium", "nano_surgical_tools",
  "neural_link_interface", "cybernetic_eye_module", "dermal_armor_plating",
  "combat_stimulant_injectors", "exoskeleton_frame", "cyber_prosthetic_limb",
  "neural_feedback_dampeners", "targeting_hud_systems", "cybernetic_spine_unit",
  "ai_co_pilot_module", "nano_repair_swarm",
  "purified_water",
  // ── WASTELAND ─────────────────────────────────────────────────────
  "salvaged_tech_scraps", "contaminated_metal", "storm_debris",
  "mutant_hides", "feral_creature_parts", "cursed_earth_soil",
  "rad_waste", "purified_rad_crystal", "wasteland_leather",
  "mutant_venom_glands", "fossil_amber", "petrified_bone",
  "rad_blooms", "ancient_circuit_relics", "rad_resistant_seeds",
  // ── VEHICLES ──────────────────────────────────────────────────────
  "engine_blocks", "transmission_units", "wheel_tire_sets",
  "vehicle_electronics", "armor_plating_vehicle", "patrol_bike_frames",
  "apc_hull_sections", "gunship_fuselage", "rotor_assemblies",
  "flight_control_systems", "drone_propeller_sets", "nav_computer_modules",
  "fuel_tanks", "turbocharger_kits", "vehicle_seats", "exhaust_systems",
  // ── BIOTECH ───────────────────────────────────────────────────────
  "stem_cell_cultures", "cloning_substrate", "tissue_culture_media",
  "enzyme_concentrates", "bio_reactor_catalysts", "synthetic_blood",
  "prion_neutralizer", "cryo_preservation_fluid", "mutagenic_compounds",
  "anti_mutagenic_serum", "rad_filter_organisms", "gene_splicing_kits",
  "gene_therapy_vials", "lab_grown_skin", "bone_growth_matrix",
  // ── TEXTILES ──────────────────────────────────────────────────────
  "raw_wool", "spun_yarn", "woven_fabric", "dyed_fabric",
  "kevlar_fiber", "carbon_thread", "nanoweave_cloth", "ballistic_fabric",
  "leather_hides", "tanned_leather", "recycled_fiber", "thread_spools",
  "waterproof_canvas", "mesh_netting",
  // ── MILITARY / MUNITIONS ──────────────────────────────────────────
  "rifle_assemblies", "sidearm_kits", "grenade_casings", "demolition_charges",
  "ballistic_plates", "tactical_vests", "thermal_scopes", "night_vision_goggles",
  "laser_sights", "field_radios", "combat_rations_pack", "field_medical_kits",
  "barbed_wire_rolls", "sandbag_pallets", "portable_barriers",
  "detonator_caps", "trigger_mechanisms",
  // ── WEAPONRY ──────────────────────────────────────────────────────
  "hotshot_laser_packs", "energy_weapon_cores", "railgun_slugs",
  "micro_missile_pods",
  // ── COMMERCIAL ────────────────────────────────────────────────────
  "data_slates", "intelligence_reports", "entertainment_media",
  "luxury_food_hampers", "designer_augments", "mapping_cartridges",
  // ── RAW MATERIALS ───────────────────────────────────────────────
  "gravel_aggregate", "processed_timber", "sawdust", "industrial_salt",
  "refined_rare_earth", "lithium_refined", "glass_sheet", "syngas",
  "chemical_feedstock", "crude_oil",
  // ── CHEMICALS ───────────────────────────────────────────────────
  "naphtha", "sulfuric_acid", "hydrochloric_acid", "industrial_solvent",
  "acetone", "chemical_fertilizer", "explosive_compounds", "epoxy_resin",
  "industrial_adhesive", "water_treatment_chemical", "industrial_paint",
  "machine_lubricant", "hydraulic_fluid",
  // ── PLASTICS ────────────────────────────────────────────────────
  "pe_pellets", "pp_pellets", "plastic_pipe_stock", "moulded_plastic_goods",
  "plastic_housings", "synthetic_rubber", "rubber_seals", "carbon_fiber_raw",
  "carbon_fiber_sheets", "composite_panels", "foam_insulation",
  "packaging_foam", "bio_polymer", "print_filament", "pipe_fittings",
  "polycarbonate_panel",
  // ── FINISHED GOODS ──────────────────────────────────────────────
  "consumer_goods_pack", "vehicle_chassis", "furniture_units",
  "woven_fabric", "finished_clothing", "precision_tooling",
  "industrial_dies", "packaging_materials", "ceramic_components",
  "medical_instruments",
  // ── ADVANCED MATERIALS ──────────────────────────────────────────
  "nano_coating", "smart_alloy", "superconductor_wire",
  "ceramic_composite", "aerospace_titanium_part", "quantum_dots",
  "industrial_diamond",
  // ── PHARMACEUTICALS ───────────────────────────────────────────
  "antibiotics", "painkillers", "vaccines", "radiation_pills",
  "combat_stims", "biogel_patches", "surgical_supplies",
  "first_aid_kits", "immune_boosters", "detox_compounds",
  // ── FOOD PROCESSING ───────────────────────────────────────────
  "grain_rations", "emergency_rations", "canned_goods",
  "protein_powder", "energy_bars", "synthetic_meat_slabs",
  "insect_protein_blocks", "algae_protein_paste",
  "nutrient_supplements", "beverage_concentrates",
  // ── ELECTRONICS ───────────────────────────────────────────────
  "microprocessors", "memory_chips", "led_panels",
  "surveillance_cameras", "data_servers", "fiber_optic_cable",
  "radio_transceivers", "optical_sensors", "motion_sensors",
  // ── CONSTRUCTION ──────────────────────────────────────────────
  "reinforced_concrete", "rebar", "glass_panels",
  "insulation_rolls", "self_healing_concrete", "scaffolding",
  "waterproof_membrane",
  // ── ENERGY ────────────────────────────────────────────────────
  "batteries_lithium", "solar_panels", "fuel_cells_hydrogen",
  "power_cells", "fuel_rods_nuclear", "synthetic_fuel",
  "refined_fuel", "diesel_fuel", "smart_grid_hardware",
  // ── LUXURY GOODS ──────────────────────────────────────────────
  "synthetic_gemstones", "holo_artwork", "exotic_perfumes",
  "ornamental_metals", "bespoke_clothing",
  // ── CONSUMER GOODS ────────────────────────────────────────────
  "household_appliances", "personal_electronics",
  "communication_devices", "water_filters", "cleaning_chemicals",
  // ── CLOTHING & GEAR ───────────────────────────────────────────
  "civilian_clothing", "hazmat_suits", "gas_masks",
  "work_uniforms", "body_armor_light",
  // ── WATER ─────────────────────────────────────────────────────
  "bottled_water", "distilled_water",
  // ── GASES ─────────────────────────────────────────────────────
  "oxygen_industrial", "oxygen_medical", "hydrogen_gas",
  "ammonia_gas", "nitrogen_gas",
  // ── SPACE COMMODITIES ─────────────────────────────────────────
  "orbital_fuel_cells", "radiation_shielding_plates",
  "life_support_cartridges", "satellite_components",
  // ── DATA & MEDIA ──────────────────────────────────────────────
  "encrypted_data_cores", "training_simulations",
  "propaganda_broadcasts",
  // ── INDUSTRIAL PARTS ──────────────────────────────────────────
  "bearings_industrial", "gears_assorted", "valves_industrial",
  "hydraulic_cylinders", "fasteners_bolts", "fasteners_screws",
  // ── METALS ────────────────────────────────────────────────────
  "gold_bars", "silver_bars", "platinum_bars", "tungsten_bars",
  "graphene_sheets",
  // ── ORE INPUTS (needed for new recipes) ───────────────────────
  "gold_ore", "silver_ore", "platinum_ore", "tungsten_ore",
  "graphite_raw", "uranium_ore", "lead_ore",
] as const;

export function createInitialStockpiles(): Record<string, number> {
  const sp: Record<string, number> = {};
  for (const id of INTERMEDIATE_STOCKPILE_IDS) {
    sp[id] = 0;
  }
  sp.iron_ore = 200;
  sp.copper_ore = 100;
  sp.coal_deposits = 80;
  sp.limestone_raw = 120;
  sp.sand_deposits = 100;
  sp.scrap_metal = 150;
  sp.fuel_gas = 60;
  sp.biomass = 80;
  sp.steel_ingot = 50;
  sp.copper_ingot = 30;
  sp.concrete_mix = 40;
  sp.circuit_board = 15;
  sp.mechanical_part = 20;
  sp.structural_beam = 25;
  sp.processed_food = 40;
  sp.ammunition_crate = 30;
  sp.crude_oil = 100;
  sp.industrial_salt = 40;
  sp.chemical_feedstock = 30;
  sp.industrial_plastic = 25;
  sp.processed_timber = 20;
  sp.naphtha = 15;
  sp.clonedOrgans = 0;
  sp.syntheticMeat = 0;
  sp.gmProduce = 0;
  sp.growthMedium = 0;
  sp.stemCells = 0;
  sp.crisprGuides = 0;
  sp.cloneNutrientPacks = 0;
  sp.bioink = 0;
  sp.geneticVaccines = 0;
  sp.cloneStabilizers = 0;
  return sp;
}

type CompiledRecipe = RecipeDef & {
  inputEntries: ReadonlyArray<readonly [string, number]>;
  outputEntries: ReadonlyArray<readonly [string, number]>;
};

/** Worker scaling used by civilian supply-chain outputs. */
export function getWorkerOutputMultiplier(workerCount: number): number {
  return Math.min(2, 0.5 + workerCount * 0.1);
}

const COMPILED_RECIPES: ReadonlyArray<CompiledRecipe> = SUPPLY_CHAIN_RECIPES.map((r) => ({
  ...r,
  inputEntries: Object.entries(r.inputs) as Array<[string, number]>,
  outputEntries: Object.entries(r.outputs) as Array<[string, number]>,
}));

export function processSupplyChain(
  stockpiles: Record<string, number>,
  buildings: Record<string, number>,
  units: Record<string, number>,
  totalTicks: number
): { updatedStockpiles: Record<string, number>; produced: string[]; starved: string[] } {
  const sp = { ...stockpiles };
  const produced: string[] = [];
  const starved: string[] = [];

  for (const recipe of COMPILED_RECIPES) {
    const bldgCount = buildings[recipe.buildingKey] ?? 0;
    if (bldgCount <= 0) continue;

    if (recipe.ticksPerCycle > 1 && totalTicks % recipe.ticksPerCycle !== 0) continue;

    const workerCount = recipe.workersKey ? (units[recipe.workersKey] ?? 0) : 0;
    if (recipe.workersKey && workerCount <= 0) {
      starved.push(recipe.name);
      continue;
    }

    const workerMultiplier = recipe.workersKey
      ? getWorkerOutputMultiplier(workerCount)
      : 1;

    const batches = bldgCount;

    let canProduce = true;
    for (const [inputId, qty] of recipe.inputEntries) {
      if ((sp[inputId] ?? 0) < qty * batches) {
        canProduce = false;
        break;
      }
    }

    if (!canProduce) {
      starved.push(recipe.name);
      continue;
    }

    let anyOutput = false;
    for (const [, qty] of recipe.outputEntries) {
      if (Math.floor(qty * batches * workerMultiplier) > 0) {
        anyOutput = true;
        break;
      }
    }
    if (!anyOutput) {
      starved.push(recipe.name);
      continue;
    }

    for (const [inputId, qty] of recipe.inputEntries) {
      sp[inputId] = (sp[inputId] ?? 0) - qty * batches;
    }

    for (const [outputId, qty] of recipe.outputEntries) {
      const outputAmount = Math.floor(qty * batches * workerMultiplier);
      sp[outputId] = (sp[outputId] ?? 0) + outputAmount;
    }

    produced.push(recipe.name);
  }

  return { updatedStockpiles: sp, produced, starved };
}
