export type WastelandSectorType = "dust_wasteland" | "ruined_urban" | "collapsed_highway" | "scrap_field" | "radiation_crater" | "abandoned_industrial" | "buried_military" | "mutant_nest" | "black_market_camp" | "research_ruins";

export type WastelandResourceRarity = "common" | "rare" | "very_rare";

export type WastelandFactionDef = {
  id: string;
  name: string;
};

export type RaiderGangDef = {
  id: string;
  name: string;
  leader: string;
  territory: string;
  trait: string;
  isCannibal: boolean;
  tier: "standard" | "elite" | "legendary";
};

export type WastelandStructureDef = {
  id: string;
  name: string;
  category: string;
};

export type WastelandEventDef = {
  id: string;
  name: string;
  category: string;
  description: string;
};

export type WastelandTechDef = {
  id: string;
  name: string;
  category: string;
};

export type WastelandDiscoveryDef = {
  id: string;
  name: string;
  rarity: WastelandResourceRarity;
};

export const SECTOR_TYPE_DISTRIBUTION: Record<WastelandSectorType, { count: number; label: string }> = {
  dust_wasteland: { count: 180, label: "Open Dust Wasteland" },
  ruined_urban: { count: 70, label: "Ruined Urban Blocks" },
  collapsed_highway: { count: 60, label: "Collapsed Highways" },
  scrap_field: { count: 50, label: "Scrap Fields" },
  radiation_crater: { count: 40, label: "Radiation Craters" },
  abandoned_industrial: { count: 35, label: "Abandoned Industrial Zones" },
  buried_military: { count: 25, label: "Buried Military Sites" },
  mutant_nest: { count: 20, label: "Mutant Nests" },
  black_market_camp: { count: 10, label: "Black Market Camps" },
  research_ruins: { count: 10, label: "Hidden Research Ruins" },
};

export const WASTELAND_RESOURCES: { name: string; rarity: WastelandResourceRarity }[] = [
  { name: "Scrap Metal", rarity: "common" },
  { name: "Steel", rarity: "common" },
  { name: "Fuel", rarity: "common" },
  { name: "Electronics", rarity: "common" },
  { name: "Chemicals", rarity: "common" },
  { name: "Uranium", rarity: "rare" },
  { name: "Rare Metals", rarity: "rare" },
  { name: "Military Tech", rarity: "rare" },
  { name: "Prototype Weapons", rarity: "rare" },
  { name: "Nuclear Materials", rarity: "very_rare" },
  { name: "AI Cores", rarity: "very_rare" },
  { name: "Alien Artifacts", rarity: "very_rare" },
];

export const SCAVENGER_FACTIONS: WastelandFactionDef[] = [
  { id: "dust_runners", name: "Dust Runners" },
  { id: "rust_wolves", name: "Rust Wolves" },
  { id: "sand_vultures", name: "Sand Vultures" },
  { id: "scrap_cartel", name: "Scrap Cartel" },
  { id: "iron_nomads", name: "Iron Nomads" },
  { id: "ash_traders", name: "Ash Traders" },
  { id: "rad_hunters", name: "Rad Hunters" },
  { id: "broken_gear_clan", name: "Broken Gear Clan" },
  { id: "salvage_guild", name: "The Salvage Guild" },
  { id: "scorch_raiders", name: "Scorch Raiders" },
  { id: "dust_market_syndicate", name: "Dust Market Syndicate" },
  { id: "reactor_children", name: "Reactor Children" },
  { id: "rust_brotherhood", name: "The Rust Brotherhood" },
  { id: "wasteland_survey_corps", name: "Wasteland Survey Corps" },
  { id: "black_iron_caravan", name: "Black Iron Caravan" },
  { id: "circuit_seekers", name: "The Circuit Seekers" },
  { id: "steel_vulture_band", name: "Steel Vulture Band" },
  { id: "old_war_collectors", name: "Old War Collectors" },
  { id: "burned_engineers", name: "The Burned Engineers" },
  { id: "desert_forge_clan", name: "Desert Forge Clan" },
  { id: "sand_crawlers", name: "Sand Crawlers" },
  { id: "rust_crown_syndicate", name: "Rust Crown Syndicate" },
  { id: "gear_priests", name: "The Gear Priests" },
  { id: "battery_reclaimers", name: "Battery Reclaimers" },
  { id: "scrap_kings", name: "Scrap Kings" },
  { id: "nomad_salvage_union", name: "Nomad Salvage Union" },
  { id: "radio_tower_clan", name: "Radio Tower Clan" },
  { id: "iron_shovel_company", name: "Iron Shovel Company" },
  { id: "reactor_salvagers", name: "Reactor Salvagers" },
  { id: "dust_market_league", name: "The Dust Market League" },
  { id: "copper_jackals", name: "The Copper Jackals" },
  { id: "scrap_barons", name: "Scrap Barons" },
  { id: "vault_breakers", name: "Vault Breakers" },
  { id: "scavenger_engineers", name: "Scavenger Engineers" },
  { id: "wasteland_prospectors", name: "Wasteland Prospectors" },
  { id: "sandstorm_traders", name: "Sandstorm Traders" },
  { id: "broken_satellite_hunters", name: "Broken Satellite Hunters" },
  { id: "junkyard_legion", name: "The Junkyard Legion" },
  { id: "rust_drifters", name: "Rust Drifters" },
  { id: "salvage_pilots", name: "Salvage Pilots" },
  { id: "desert_mechanics", name: "Desert Mechanics" },
  { id: "scrap_city_merchants", name: "Scrap City Merchants" },
  { id: "nomad_prospectors", name: "Nomad Prospectors" },
  { id: "gearwheel_nomads", name: "Gearwheel Nomads" },
  { id: "dust_cartographers", name: "The Dust Cartographers" },
  { id: "salvage_marines", name: "Salvage Marines" },
  { id: "wreck_divers", name: "Wreck Divers" },
  { id: "sand_road_guild", name: "Sand Road Guild" },
  { id: "rustline_traders", name: "Rustline Traders" },
  { id: "steel_diggers", name: "The Steel Diggers" },
];

export const RAIDER_GANGS: RaiderGangDef[] = [
  { id: "iron_hyenas", name: "Iron Hyenas", leader: "Karg the Splitjaw", territory: "Highway ruins", trait: "Vehicle ambush experts", isCannibal: false, tier: "standard" },
  { id: "bone_caravan", name: "The Bone Caravan", leader: "Mother Raze", territory: "Desert trade routes", trait: "Eats captives, raids caravans", isCannibal: true, tier: "standard" },
  { id: "chrome_jackals", name: "Chrome Jackals", leader: "Dax Chromehand", territory: "Scrapyards", trait: "Cybernetic scavengers", isCannibal: false, tier: "standard" },
  { id: "dust_serpents", name: "Dust Serpents", leader: "Talon Vesk", territory: "Canyon roads", trait: "Sniper ambushes", isCannibal: false, tier: "standard" },
  { id: "ash_butchers", name: "Ash Butchers", leader: "Gorr the Devourer", territory: "Burned cities", trait: "Ritual cannibal cult", isCannibal: true, tier: "standard" },
  { id: "rust_kings", name: "Rust Kings", leader: "Baron Cog", territory: "Factory ruins", trait: "Armored vehicles", isCannibal: false, tier: "standard" },
  { id: "furnace_clan", name: "The Furnace Clan", leader: "Magra Steelvein", territory: "Smelter complexes", trait: "Improvised weapons", isCannibal: false, tier: "standard" },
  { id: "scrap_vultures", name: "Scrap Vultures", leader: "Hollow Eye", territory: "Aircraft graveyards", trait: "Salvage drones", isCannibal: false, tier: "standard" },
  { id: "conveyor_wolves", name: "The Conveyor Wolves", leader: "Rax Beltbreaker", territory: "Old assembly lines", trait: "Industrial traps", isCannibal: false, tier: "standard" },
  { id: "gearbone_collective", name: "Gearbone Collective", leader: "The Tinkerer", territory: "Robotics labs", trait: "Cybernetic cannibal augmenters", isCannibal: true, tier: "standard" },
  { id: "black_asphalt_riders", name: "Black Asphalt Riders", leader: "Road Captain Dorne", territory: "Major highways", trait: "Vehicle raiders", isCannibal: false, tier: "standard" },
  { id: "fuel_reavers", name: "The Fuel Reavers", leader: "Ignis Torque", territory: "Fuel depots", trait: "Incendiary weapons", isCannibal: false, tier: "standard" },
  { id: "dust_cyclone_riders", name: "Dust Cyclone Riders", leader: "Tornado Jack", territory: "Open desert", trait: "Hit-and-run tactics", isCannibal: false, tier: "standard" },
  { id: "wreck_hunters", name: "The Wreck Hunters", leader: "Axle Blood", territory: "Vehicle graveyards", trait: "Armored salvage", isCannibal: false, tier: "standard" },
  { id: "meat_convoy", name: "The Meat Convoy", leader: "Chef Morrax", territory: "Trade routes", trait: "Mobile cannibal feast", isCannibal: true, tier: "standard" },
  { id: "broken_tower_clan", name: "The Broken Tower Clan", leader: "Widow Skarn", territory: "Ruined skyscrapers", trait: "Vertical ambushes", isCannibal: false, tier: "standard" },
  { id: "elevator_rats", name: "The Elevator Rats", leader: "Liftmaster Crow", territory: "Collapsed buildings", trait: "Tunnel warfare", isCannibal: false, tier: "standard" },
  { id: "concrete_warlords", name: "Concrete Warlords", leader: "Lord Cinder", territory: "Urban ruins", trait: "Fortified positions", isCannibal: false, tier: "standard" },
  { id: "neon_scavengers", name: "The Neon Scavengers", leader: "Prism V", territory: "Entertainment districts", trait: "Electronic traps", isCannibal: false, tier: "standard" },
  { id: "feast_court", name: "The Feast Court", leader: "King Maw", territory: "Underground warrens", trait: "Ritualized cannibalism", isCannibal: true, tier: "standard" },
  { id: "rad_wolves", name: "Rad Wolves", leader: "Fang Reactor", territory: "Irradiated zones", trait: "Radiation immunity", isCannibal: false, tier: "standard" },
  { id: "glowborn", name: "The Glowborn", leader: "Sister Fallout", territory: "Nuclear craters", trait: "Mutation worship", isCannibal: false, tier: "standard" },
  { id: "uranium_skulls", name: "Uranium Skulls", leader: "Captain Fission", territory: "Reactor ruins", trait: "Radioactive weapons", isCannibal: false, tier: "standard" },
  { id: "atomic_reapers", name: "Atomic Reapers", leader: "Gamma Jack", territory: "Nuclear wastelands", trait: "Heavy weapons", isCannibal: false, tier: "standard" },
  { id: "devouring_choir", name: "The Devouring Choir", leader: "Prophet Hunger", territory: "Desert temples", trait: "Cannibal cult religion", isCannibal: true, tier: "standard" },
  { id: "circuit_breakers", name: "Circuit Breakers", leader: "Data Knife", territory: "Data centers", trait: "EMP weapons", isCannibal: false, tier: "standard" },
  { id: "drone_pirates", name: "Drone Pirates", leader: "Captain Hex", territory: "Drone graveyards", trait: "Hijacked drones", isCannibal: false, tier: "standard" },
  { id: "ai_worshippers", name: "AI Worshippers", leader: "Oracle Grid", territory: "AI research ruins", trait: "AI-guided tactics", isCannibal: false, tier: "standard" },
  { id: "signal_hunters", name: "The Signal Hunters", leader: "Static Vex", territory: "Communications ruins", trait: "Signal jamming", isCannibal: false, tier: "standard" },
  { id: "cyber_flesh_cult", name: "Cyber Flesh Cult", leader: "Doctor Gnaw", territory: "Medical ruins", trait: "Cybernetic cannibalism", isCannibal: true, tier: "standard" },
  { id: "sand_drifters", name: "Sand Drifters", leader: "Warlord Varn", territory: "Deep desert", trait: "Desert survival", isCannibal: false, tier: "standard" },
  { id: "bone_nomads", name: "Bone Nomads", leader: "Mother Dust", territory: "Bone fields", trait: "Nomadic cannibals", isCannibal: true, tier: "standard" },
  { id: "desert_wolves", name: "Desert Wolves", leader: "Iron Prophet", territory: "Oasis ruins", trait: "Water control", isCannibal: false, tier: "standard" },
  { id: "iron_nomads_raider", name: "Iron Nomads", leader: "Cutter Vale", territory: "Metal wastes", trait: "Armor smithing", isCannibal: false, tier: "standard" },
  { id: "storm_riders", name: "Storm Riders", leader: "Captain Sandstorm", territory: "Storm corridors", trait: "Storm navigation", isCannibal: false, tier: "standard" },
  { id: "steel_legion", name: "The Steel Legion", leader: "General Ironclad", territory: "Military ruins", trait: "Military discipline", isCannibal: false, tier: "elite" },
  { id: "armored_brotherhood", name: "The Armored Brotherhood", leader: "Warlord Tank", territory: "Vehicle depots", trait: "Heavy armor", isCannibal: false, tier: "elite" },
  { id: "iron_market_syndicate", name: "The Iron Market Syndicate", leader: "Broker Steele", territory: "Trade hubs", trait: "Economic warfare", isCannibal: false, tier: "elite" },
  { id: "blood_engineers", name: "The Blood Engineers", leader: "Surgeon Prime", territory: "Factories", trait: "Industrial cannibalism", isCannibal: true, tier: "elite" },
  { id: "salvage_empire", name: "The Salvage Empire", leader: "Emperor Scrap", territory: "Mega scrapyards", trait: "Resource domination", isCannibal: false, tier: "elite" },
  { id: "ash_titans", name: "The Ash Titans", leader: "Titan Ash", territory: "Volcanic zones", trait: "Fire weapons mastery", isCannibal: false, tier: "legendary" },
  { id: "bone_kingdom", name: "The Bone Kingdom", leader: "The Bone King", territory: "Ossuary wastes", trait: "Cannibal empire", isCannibal: true, tier: "legendary" },
  { id: "wasteland_knights", name: "The Wasteland Knights", leader: "Knight Commander Dusk", territory: "Fortress ruins", trait: "Code of honor", isCannibal: false, tier: "legendary" },
  { id: "reactor_throne", name: "The Reactor Throne", leader: "King Isotope", territory: "Reactor complexes", trait: "Nuclear power", isCannibal: false, tier: "legendary" },
  { id: "black_war_caravan", name: "The Black War Caravan", leader: "War Master Obsidian", territory: "All territories", trait: "Mobile fortress", isCannibal: false, tier: "legendary" },
  { id: "devourer_horde", name: "The Devourer Horde", leader: "The Great Mouth", territory: "Everywhere", trait: "Cannibal army", isCannibal: true, tier: "legendary" },
  { id: "rust_dominion", name: "The Rust Dominion", leader: "Lord Corrosion", territory: "Industrial ruins", trait: "Chemical weapons", isCannibal: false, tier: "legendary" },
  { id: "eternal_raiders", name: "The Eternal Raiders", leader: "Immortal Rex", territory: "Ancient ruins", trait: "Undying warfare", isCannibal: false, tier: "legendary" },
  { id: "sand_emperor_army", name: "The Sand Emperor's Army", leader: "Emperor Sandstorm", territory: "Desert empire", trait: "Mass mobilization", isCannibal: false, tier: "legendary" },
  { id: "great_hunger", name: "The Great Hunger", leader: "The Starving God", territory: "Wasteland domain", trait: "Cannibal empire", isCannibal: true, tier: "legendary" },
];

export const WASTELAND_STRUCTURES: WastelandStructureDef[] = [
  { id: "collapsed_skyscraper", name: "Collapsed Skyscraper", category: "ruins" },
  { id: "broken_megablock", name: "Broken Megablock", category: "ruins" },
  { id: "destroyed_airport", name: "Destroyed Airport Terminal", category: "ruins" },
  { id: "crashed_maglev", name: "Crashed Maglev Station", category: "ruins" },
  { id: "ruined_stadium", name: "Ruined Stadium", category: "ruins" },
  { id: "burned_residential", name: "Burned Residential Tower", category: "ruins" },
  { id: "abandoned_shopping", name: "Abandoned Shopping Complex", category: "ruins" },
  { id: "fallen_comm_tower", name: "Fallen Communications Tower", category: "ruins" },
  { id: "collapsed_highway_junction", name: "Collapsed Highway Junction", category: "ruins" },
  { id: "buried_subway", name: "Buried Subway Entrance", category: "ruins" },
  { id: "old_steel_mill", name: "Old Steel Mill", category: "industrial" },
  { id: "oil_refinery_ruins", name: "Oil Refinery Ruins", category: "industrial" },
  { id: "chemical_plant_remains", name: "Chemical Plant Remains", category: "industrial" },
  { id: "cargo_warehouse", name: "Cargo Warehouse", category: "industrial" },
  { id: "scrap_recycling_plant", name: "Scrap Recycling Plant", category: "industrial" },
  { id: "nuclear_power_station", name: "Nuclear Power Station", category: "industrial" },
  { id: "robotics_assembly_plant", name: "Robotics Assembly Plant", category: "industrial" },
  { id: "machine_factory_ruins", name: "Machine Factory Ruins", category: "industrial" },
  { id: "industrial_furnace", name: "Industrial Furnace Complex", category: "industrial" },
  { id: "cargo_container_yard", name: "Cargo Container Yard", category: "industrial" },
  { id: "wasteland_missile_silo", name: "Missile Silo", category: "military" },
  { id: "wasteland_military_bunker", name: "Military Bunker", category: "military" },
  { id: "wasteland_radar_tower", name: "Radar Tower", category: "military" },
  { id: "wasteland_artillery_battery", name: "Artillery Battery", category: "military" },
  { id: "wasteland_drone_base", name: "Drone Launch Base", category: "military" },
  { id: "underground_command", name: "Underground Command Center", category: "military" },
  { id: "military_prison_ruins", name: "Military Prison Ruins", category: "military" },
  { id: "wasteland_vehicle_depot", name: "Armored Vehicle Depot", category: "military" },
  { id: "nuclear_weapons_vault", name: "Nuclear Weapons Vault", category: "military" },
  { id: "wasteland_military_airfield", name: "Military Airfield", category: "military" },
  { id: "biotech_lab", name: "Biotech Lab", category: "research" },
  { id: "ai_research_center", name: "AI Research Center", category: "research" },
  { id: "energy_weapons_lab_ruins", name: "Energy Weapons Lab", category: "research" },
  { id: "nanotech_lab", name: "Nanotech Lab", category: "research" },
  { id: "robotics_research", name: "Robotics Research Facility", category: "research" },
  { id: "military_testing_ground", name: "Military Testing Ground", category: "research" },
  { id: "orbital_control_facility", name: "Orbital Control Facility", category: "research" },
  { id: "experimental_reactor_lab", name: "Experimental Reactor Lab", category: "research" },
  { id: "satellite_monitoring", name: "Satellite Monitoring Center", category: "research" },
  { id: "cyber_warfare_bunker", name: "Cyber Warfare Bunker", category: "research" },
  { id: "raider_camp", name: "Raider Camp", category: "camps" },
  { id: "nomad_caravan_site", name: "Nomad Caravan Site", category: "camps" },
  { id: "scavenger_scrapyard", name: "Scavenger Scrapyard", category: "camps" },
  { id: "smuggler_hideout", name: "Smuggler Hideout", category: "camps" },
  { id: "mutant_nest_structure", name: "Mutant Nest", category: "camps" },
  { id: "black_market_bazaar", name: "Black Market Bazaar", category: "camps" },
  { id: "survivor_shelter", name: "Survivor Shelter", category: "camps" },
  { id: "refugee_camp", name: "Refugee Camp", category: "camps" },
  { id: "mercenary_outpost", name: "Mercenary Outpost", category: "camps" },
  { id: "sand_trader_post", name: "Sand Trader Post", category: "camps" },
  { id: "old_dam", name: "Old Dam", category: "infrastructure" },
  { id: "power_transmission", name: "Power Transmission Station", category: "infrastructure" },
  { id: "water_purification_ruins", name: "Water Purification Plant", category: "infrastructure" },
  { id: "fuel_depot_ruins", name: "Fuel Depot", category: "infrastructure" },
  { id: "pipeline_control", name: "Pipeline Control Station", category: "infrastructure" },
  { id: "desert_solar_farm", name: "Desert Solar Farm Ruins", category: "infrastructure" },
  { id: "wind_turbine_field", name: "Wind Turbine Field", category: "infrastructure" },
  { id: "satellite_uplink", name: "Satellite Uplink Dish", category: "infrastructure" },
  { id: "power_grid_hub", name: "Power Grid Hub", category: "infrastructure" },
  { id: "transport_logistics", name: "Transport Logistics Center", category: "infrastructure" },
  { id: "alien_monolith", name: "Alien Monolith", category: "exotic" },
  { id: "orbital_weapon_uplink", name: "Orbital Weapon Uplink Tower", category: "exotic" },
  { id: "underground_megabunker", name: "Underground Megabunker", category: "exotic" },
  { id: "prewar_ai_vault", name: "Prewar AI Server Vault", category: "exotic" },
  { id: "cryogenic_storage_vault", name: "Cryogenic Storage Vault", category: "exotic" },
  { id: "nanite_swarm_chamber", name: "Nanite Swarm Chamber", category: "exotic" },
  { id: "magnetic_anomaly_tower", name: "Magnetic Anomaly Tower", category: "exotic" },
  { id: "gravity_experiment_lab", name: "Gravity Experiment Lab", category: "exotic" },
  { id: "plasma_energy_core", name: "Plasma Energy Core Chamber", category: "exotic" },
  { id: "time_locked_vault", name: "Time-Locked Vault", category: "exotic" },
  { id: "subway_tunnel_network", name: "Subway Tunnel Network", category: "underground" },
  { id: "secret_bunker_city", name: "Secret Bunker City", category: "underground" },
  { id: "military_tunnel_system", name: "Military Tunnel System", category: "underground" },
  { id: "underground_factory", name: "Underground Factory", category: "underground" },
  { id: "deep_research_bunker", name: "Deep Research Bunker", category: "underground" },
  { id: "secret_vault_complex", name: "Secret Vault Complex", category: "underground" },
  { id: "nuclear_shelter_network", name: "Nuclear Shelter Network", category: "underground" },
  { id: "hidden_weapons_depot", name: "Hidden Weapons Depot", category: "underground" },
  { id: "subterranean_ai_core", name: "Subterranean AI Core", category: "underground" },
  { id: "deep_mining_facility", name: "Deep Mining Facility", category: "underground" },
  { id: "massive_scrapyard", name: "Massive Scrapyard", category: "misc" },
  { id: "aircraft_graveyard", name: "Aircraft Graveyard", category: "misc" },
  { id: "vehicle_junkyard", name: "Vehicle Junkyard", category: "misc" },
  { id: "rusted_warship", name: "Rusted Warship Wreck", category: "misc" },
  { id: "drone_graveyard", name: "Drone Graveyard", category: "misc" },
  { id: "weapon_test_crater", name: "Weapon Test Crater", category: "misc" },
  { id: "mass_grave_site", name: "Mass Grave Site", category: "misc" },
  { id: "radiation_lake", name: "Radiation Lake", category: "misc" },
  { id: "old_prison_complex", name: "Old Prison Complex", category: "misc" },
  { id: "ruined_govt_building", name: "Ruined Government Building", category: "misc" },
  { id: "fallen_orbital_elevator", name: "Fallen Orbital Elevator Base", category: "megastructures" },
  { id: "giant_mech_factory", name: "Giant Mech Factory", category: "megastructures" },
  { id: "autonomous_war_factory", name: "Autonomous War Factory", category: "megastructures" },
  { id: "orbital_defense_uplink", name: "Orbital Defense Uplink", category: "megastructures" },
  { id: "planetary_defense_cannon", name: "Planetary Defense Cannon Ruins", category: "megastructures" },
  { id: "mega_reactor_complex", name: "Mega Reactor Complex", category: "megastructures" },
  { id: "military_ai_supercomputer", name: "Military AI Supercomputer", category: "megastructures" },
  { id: "space_launch_complex", name: "Space Launch Complex", category: "megastructures" },
  { id: "subterranean_city", name: "Subterranean City", category: "megastructures" },
  { id: "ancient_sealed_fortress", name: "Ancient Sealed Fortress", category: "megastructures" },
];

export const WASTELAND_EVENTS: WastelandEventDef[] = [
  { id: "collapsed_mall", name: "Collapsed Mall", category: "ruins_salvage", description: "Recover consumer goods and electronics." },
  { id: "abandoned_factory_event", name: "Abandoned Factory", category: "ruins_salvage", description: "Salvage steel and machinery." },
  { id: "deserted_highway_convoy", name: "Deserted Highway Convoy", category: "ruins_salvage", description: "Find vehicles and ammunition." },
  { id: "crushed_cargo_train", name: "Crushed Cargo Train", category: "ruins_salvage", description: "Scattered industrial resources." },
  { id: "fallen_skybridge", name: "Fallen Skybridge", category: "ruins_salvage", description: "Rare alloys buried under rubble." },
  { id: "collapsed_data_center", name: "Collapsed Data Center", category: "ruins_salvage", description: "Recover encrypted AI chips." },
  { id: "forgotten_storage_bunker", name: "Forgotten Storage Bunker", category: "ruins_salvage", description: "Large supply cache." },
  { id: "buried_military_depot_event", name: "Buried Military Depot", category: "ruins_salvage", description: "Missile parts and ammo." },
  { id: "destroyed_tank_column", name: "Destroyed Tank Column", category: "ruins_salvage", description: "Scrap armored vehicles." },
  { id: "satellite_crash_site", name: "Satellite Crash Site", category: "ruins_salvage", description: "Advanced electronics salvage." },
  { id: "sudden_radiation_spike", name: "Sudden Radiation Spike", category: "radiation_hazard", description: "Dangerous radiation levels detected." },
  { id: "glowing_crater", name: "Glowing Crater Discovered", category: "radiation_hazard", description: "Highly radioactive impact zone." },
  { id: "contaminated_groundwater", name: "Contaminated Groundwater", category: "radiation_hazard", description: "Poisoned water pocket found." },
  { id: "radioactive_dust_storm", name: "Radioactive Dust Storm", category: "radiation_hazard", description: "Deadly irradiated sandstorm." },
  { id: "toxic_chemical_fog", name: "Toxic Chemical Fog", category: "radiation_hazard", description: "Dense poisonous cloud bank." },
  { id: "mutated_fungal_bloom", name: "Mutated Fungal Bloom", category: "radiation_hazard", description: "Dangerous mutant fungi spreading." },
  { id: "abandoned_reactor_meltdown", name: "Abandoned Reactor Meltdown Zone", category: "radiation_hazard", description: "Active meltdown site discovered." },
  { id: "nuclear_waste_pit", name: "Nuclear Waste Dumping Pit", category: "radiation_hazard", description: "Illegal dumping ground found." },
  { id: "hazardous_gas_vents", name: "Hazardous Gas Vent Field", category: "radiation_hazard", description: "Toxic gas venting from underground." },
  { id: "emp_radiation_storm", name: "EMP Radiation Storm", category: "radiation_hazard", description: "Electromagnetic pulse disrupts equipment." },
  { id: "raider_ambush", name: "Raider Ambush", category: "hostile", description: "Raiders attack your expedition." },
  { id: "mutant_pack_attack", name: "Mutant Pack Attack", category: "hostile", description: "Wild mutant creatures attack." },
  { id: "sniper_nest", name: "Sniper Nest in Ruins", category: "hostile", description: "Hidden sniper opens fire." },
  { id: "drone_patrol_confrontation", name: "Drone Patrol Confrontation", category: "hostile", description: "Rogue military drones engage." },
  { id: "scavenger_trap_field", name: "Scavenger Trap Field", category: "hostile", description: "Explosive traps everywhere." },
  { id: "land_mine_patch", name: "Land Mine Patch", category: "hostile", description: "Military minefield discovered." },
  { id: "rogue_security_robots", name: "Rogue Security Robots", category: "hostile", description: "Automated sentries activate." },
  { id: "hidden_artillery_turret", name: "Hidden Artillery Turret", category: "hostile", description: "Automated gun emplacement fires." },
  { id: "armored_bandit_convoy", name: "Armored Bandit Convoy", category: "hostile", description: "Heavy raider force appears." },
  { id: "mutant_warlord_tribute", name: "Mutant Warlord Demands Tribute", category: "hostile", description: "Pay or fight." },
  { id: "hidden_bunker_discovery", name: "Hidden Underground Bunker", category: "discovery", description: "Sealed bunker found below surface." },
  { id: "lost_govt_archive", name: "Lost Government Archive", category: "discovery", description: "Pre-war government vault." },
  { id: "experimental_weapons_lab_event", name: "Experimental Weapons Lab", category: "discovery", description: "Prototype weapons found." },
  { id: "military_research_ruins", name: "Military Research Ruins", category: "discovery", description: "Classified research data recovered." },
  { id: "underground_subway_network", name: "Underground Subway Network", category: "discovery", description: "Intact tunnel system found." },
  { id: "old_power_grid_hub", name: "Old Power Grid Control Hub", category: "discovery", description: "Reactivatable power systems." },
  { id: "abandoned_maglev_station", name: "Abandoned Maglev Station", category: "discovery", description: "Salvageable transport tech." },
  { id: "military_drone_bunker", name: "Military Drone Storage", category: "discovery", description: "Dormant combat drones found." },
  { id: "hidden_missile_silo", name: "Hidden Missile Silo Entrance", category: "discovery", description: "Underground launch facility." },
  { id: "prewar_hospital", name: "Prewar Hospital Complex", category: "discovery", description: "Medical supplies and data." },
  { id: "wandering_refugee_caravan", name: "Wandering Refugee Caravan", category: "survivor", description: "Desperate refugees seeking shelter." },
  { id: "lone_wasteland_hermit", name: "Lone Wasteland Hermit", category: "survivor", description: "Isolated survivor with knowledge." },
  { id: "merchant_caravan_trade", name: "Merchant Caravan", category: "survivor", description: "Traders offering rare goods." },
  { id: "injured_scout", name: "Injured Scout Asking Help", category: "survivor", description: "Wounded explorer needs aid." },
  { id: "scientists_in_ruins", name: "Scientists Hiding in Ruins", category: "survivor", description: "Researchers with valuable data." },
  { id: "scavenger_alliance_request", name: "Scavenger Alliance Request", category: "survivor", description: "Scavengers want to join forces." },
  { id: "children_survivor_camp", name: "Children Survivor Camp", category: "survivor", description: "Orphaned children need rescue." },
  { id: "soldier_mercenary_group", name: "Former Soldier Mercenaries", category: "survivor", description: "Trained fighters for hire." },
  { id: "nomad_tribe_migration", name: "Nomad Tribe Migration", category: "survivor", description: "Tribal group passing through." },
  { id: "prison_escapees", name: "Prison Escapees", category: "survivor", description: "Escaped convicts, dangerous or not." },
  { id: "smuggler_trade_caravan", name: "Smuggler Trade Caravan", category: "black_market", description: "Illegal goods for sale." },
  { id: "illegal_cybernetics_trader", name: "Illegal Cybernetics Trader", category: "black_market", description: "Black market augmentations." },
  { id: "contraband_weapon_dealer", name: "Contraband Weapon Dealer", category: "black_market", description: "Illegal weapons available." },
  { id: "stolen_reactor_fuel_broker", name: "Stolen Reactor Fuel Broker", category: "black_market", description: "Nuclear materials for sale." },
  { id: "mutagen_serum_trader", name: "Mutagen Serum Trader", category: "black_market", description: "Mutation serums available." },
  { id: "ai_chip_smuggler", name: "AI Chip Smuggler", category: "black_market", description: "Stolen AI processors." },
  { id: "rogue_military_engineer", name: "Rogue Military Engineer", category: "black_market", description: "Weapons modifications offered." },
  { id: "nuclear_material_dealer", name: "Nuclear Material Dealer", category: "black_market", description: "Fissile materials available." },
  { id: "pirate_drone_vendor", name: "Pirate Drone Vendor", category: "black_market", description: "Hijacked drones for sale." },
  { id: "data_hacker_intel", name: "Data Hacker Selling Intel", category: "black_market", description: "Intelligence data available." },
  { id: "massive_sandstorm", name: "Massive Sandstorm", category: "environmental", description: "Blinding sandstorm halts operations." },
  { id: "lightning_storm_ruins", name: "Lightning Storm Over Ruins", category: "environmental", description: "Electrical storm causes fires." },
  { id: "sinkhole_reveals_bunker", name: "Sinkhole Opens Revealing Bunker", category: "environmental", description: "Ground collapse exposes structure." },
  { id: "desert_wildfire", name: "Desert Wildfire Spreads", category: "environmental", description: "Fire consuming wasteland vegetation." },
  { id: "toxic_rain_cloud", name: "Toxic Rain Cloud", category: "environmental", description: "Acid rain contaminates area." },
  { id: "magnetic_anomaly_zone", name: "Magnetic Anomaly Zone", category: "environmental", description: "Equipment malfunctions in area." },
  { id: "underground_tremor", name: "Underground Tremor Collapse", category: "environmental", description: "Seismic activity causes damage." },
  { id: "dust_tornado", name: "Dust Tornado", category: "environmental", description: "Violent dust devil disrupts area." },
  { id: "meteor_impact", name: "Meteor Impact", category: "environmental", description: "Space debris strikes nearby." },
  { id: "subterranean_cavern", name: "Subterranean Cavern Discovered", category: "environmental", description: "Natural cave system found." },
  { id: "rogue_ai_broadcast", name: "Rogue AI Broadcast Signal", category: "technology", description: "Unknown AI transmitting." },
  { id: "automated_defense_activates", name: "Automated Defense System Activates", category: "technology", description: "Pre-war defenses come online." },
  { id: "satellite_uplink_signal", name: "Satellite Uplink Signal", category: "technology", description: "Orbital asset detected." },
  { id: "lost_research_drone", name: "Lost Research Drone Recovered", category: "technology", description: "Functional drone with data." },
  { id: "weapon_prototype_site", name: "Weapon Prototype Test Site", category: "technology", description: "Experimental weapons found." },
  { id: "autonomous_factory_operating", name: "Autonomous Factory Still Operating", category: "technology", description: "Self-running factory discovered." },
  { id: "training_simulator_bunker", name: "Military Training Simulator", category: "technology", description: "Working simulation systems." },
  { id: "holographic_distress_beacon", name: "Holographic Distress Beacon", category: "technology", description: "Ancient holographic SOS signal." },
  { id: "nuclear_monitoring_station", name: "Nuclear Monitoring Station", category: "technology", description: "Radiation tracking systems." },
  { id: "underground_cyber_node", name: "Underground Cyber Warfare Node", category: "technology", description: "Active cyber warfare systems." },
  { id: "alien_artifact_fragment", name: "Alien Artifact Fragment", category: "rare_discovery", description: "Object of unknown origin." },
  { id: "hidden_nuclear_vault", name: "Hidden Nuclear Vault", category: "rare_discovery", description: "Sealed nuclear weapons storage." },
  { id: "prototype_mech_hangar", name: "Prototype Mech Hangar", category: "rare_discovery", description: "Giant combat mech found." },
  { id: "underground_cryogenic_vault", name: "Underground Cryogenic Vault", category: "rare_discovery", description: "Frozen pre-war specimens." },
  { id: "advanced_nanotech_cache", name: "Advanced Nanotech Cache", category: "rare_discovery", description: "Self-replicating nanites." },
  { id: "secret_intel_archive", name: "Secret Intelligence Archive", category: "rare_discovery", description: "Classified intelligence trove." },
  { id: "lost_orbital_command", name: "Lost Orbital Command Center", category: "rare_discovery", description: "Facility controlling orbital assets." },
  { id: "strategic_war_ai_core", name: "Strategic War AI Core", category: "rare_discovery", description: "Functional strategic AI system." },
  { id: "stealth_aircraft_hangar", name: "Prototype Stealth Aircraft Hangar", category: "rare_discovery", description: "Invisible aircraft discovered." },
  { id: "ancient_superweapon_site", name: "Ancient Superweapon Test Site", category: "rare_discovery", description: "Pre-war doomsday weapon." },
  { id: "strange_radio_numbers", name: "Strange Radio Signal", category: "mystery", description: "Repeating number broadcast." },
  { id: "invisible_anomaly_field", name: "Invisible Anomaly Field", category: "mystery", description: "Unseen force field barrier." },
  { id: "time_stopped_sector", name: "Time-Stopped Sector Pocket", category: "mystery", description: "Time frozen in small area." },
  { id: "holographic_ghost_city", name: "Holographic City Ghost", category: "mystery", description: "Phantom city projection." },
  { id: "unknown_underground_machine", name: "Unknown Underground Machine", category: "mystery", description: "Massive machine humming below." },
  { id: "impossible_gravity", name: "Impossible Gravity Fluctuation", category: "mystery", description: "Gravity anomaly detected." },
  { id: "phantom_convoy", name: "Phantom Convoy Sighting", category: "mystery", description: "Ghost vehicles on highway." },
  { id: "underground_creature_noises", name: "Underground Creature Noises", category: "mystery", description: "Unknown life form detected." },
  { id: "weather_machine_running", name: "Artificial Weather Machine", category: "mystery", description: "Weather control device active." },
  { id: "sealed_vault_unknown", name: "Sealed Vault Unknown Origin", category: "mystery", description: "Vault of completely unknown purpose." },
];

export const WASTELAND_TECHS: WastelandTechDef[] = [
  { id: "advanced_scrap_sorting", name: "Advanced Scrap Sorting", category: "salvage" },
  { id: "automated_salvage_drones", name: "Automated Salvage Drones", category: "salvage" },
  { id: "magnetic_scrap_collectors", name: "Magnetic Scrap Collectors", category: "salvage" },
  { id: "industrial_salvage_rigs", name: "Industrial Salvage Rigs", category: "salvage" },
  { id: "structural_collapse_scanning", name: "Structural Collapse Scanning", category: "salvage" },
  { id: "salvage_robotics", name: "Salvage Robotics", category: "salvage" },
  { id: "autonomous_wreck_cutters", name: "Autonomous Wreck Cutters", category: "salvage" },
  { id: "heavy_salvage_cranes", name: "Heavy Salvage Cranes", category: "salvage" },
  { id: "rare_metal_extraction", name: "Rare Metal Extraction", category: "salvage" },
  { id: "urban_salvage_mapping", name: "Urban Salvage Mapping", category: "salvage" },
  { id: "radiation_resistant_clothing", name: "Radiation-Resistant Clothing", category: "survival" },
  { id: "desert_survival_training", name: "Desert Survival Training", category: "survival" },
  { id: "wasteland_water_extraction", name: "Wasteland Water Extraction", category: "survival" },
  { id: "dust_storm_shelters", name: "Dust Storm Shelters", category: "survival" },
  { id: "portable_oxygen_filters", name: "Portable Oxygen Filters", category: "survival" },
  { id: "radiation_detox_drugs", name: "Radiation Detox Drugs", category: "survival" },
  { id: "emergency_food_synthesizers", name: "Emergency Food Synthesizers", category: "survival" },
  { id: "field_medicine_kits", name: "Field Medicine Kits", category: "survival" },
  { id: "survival_exoskeletons", name: "Survival Exoskeletons", category: "survival" },
  { id: "heat_resistant_armor", name: "Heat Resistant Armor", category: "survival" },
  { id: "sand_crawler_vehicles", name: "Sand Crawler Vehicles", category: "transport" },
  { id: "armored_convoy_trucks", name: "Armored Convoy Trucks", category: "transport" },
  { id: "hover_scavenger_bikes", name: "Hover Scavenger Bikes", category: "transport" },
  { id: "wasteland_fuel_refining", name: "Wasteland Fuel Refining", category: "transport" },
  { id: "long_range_fuel_storage", name: "Long-Range Fuel Storage", category: "transport" },
  { id: "dust_engine_filtration", name: "Dust Engine Filtration", category: "transport" },
  { id: "radiation_proof_engines", name: "Radiation-Proof Engines", category: "transport" },
  { id: "convoy_escort_drones", name: "Convoy Escort Drones", category: "transport" },
  { id: "mobile_repair_vehicles", name: "Mobile Repair Vehicles", category: "transport" },
  { id: "autonomous_supply_trucks", name: "Autonomous Supply Trucks", category: "transport" },
  { id: "sector_scanning_satellites", name: "Sector Scanning Satellites", category: "exploration" },
  { id: "drone_recon_networks", name: "Drone Reconnaissance Networks", category: "exploration" },
  { id: "wasteland_radar_arrays", name: "Wasteland Radar Arrays", category: "exploration" },
  { id: "subsurface_scanning", name: "Subsurface Scanning", category: "exploration" },
  { id: "ruin_mapping_ai", name: "Ruin Mapping AI", category: "exploration" },
  { id: "deep_bunker_scanners", name: "Deep Bunker Scanners", category: "exploration" },
  { id: "anomaly_detection_sensors", name: "Anomaly Detection Sensors", category: "exploration" },
  { id: "thermal_desert_scanners", name: "Thermal Desert Scanners", category: "exploration" },
  { id: "mutant_tracking_sensors", name: "Mutant Tracking Sensors", category: "exploration" },
  { id: "resource_density_scanners", name: "Resource Density Scanners", category: "exploration" },
  { id: "raider_suppression_doctrine", name: "Raider Suppression Doctrine", category: "warfare" },
  { id: "convoy_defense_systems", name: "Convoy Defense Systems", category: "warfare" },
  { id: "anti_ambush_radar", name: "Anti-Ambush Radar", category: "warfare" },
  { id: "desert_artillery_deployment", name: "Desert Artillery Deployment", category: "warfare" },
  { id: "mobile_missile_trucks", name: "Mobile Missile Trucks", category: "warfare" },
  { id: "anti_raider_patrol_drones", name: "Anti-Raider Patrol Drones", category: "warfare" },
  { id: "automated_defense_towers", name: "Automated Defense Towers", category: "warfare" },
  { id: "armored_patrol_vehicles", name: "Armored Patrol Vehicles", category: "warfare" },
  { id: "wasteland_mine_clearing", name: "Wasteland Mine Clearing", category: "warfare" },
  { id: "rapid_response_strike", name: "Rapid Response Strike Units", category: "warfare" },
  { id: "radiation_scrubbing_towers", name: "Radiation Scrubbing Towers", category: "environmental" },
  { id: "desert_terraforming", name: "Desert Terraforming Trials", category: "environmental" },
  { id: "air_filtration_megaplants", name: "Air Filtration Megaplants", category: "environmental" },
  { id: "toxic_soil_neutralization", name: "Toxic Soil Neutralization", category: "environmental" },
  { id: "groundwater_purification", name: "Groundwater Purification", category: "environmental" },
  { id: "atmospheric_dust_control", name: "Atmospheric Dust Control", category: "environmental" },
  { id: "artificial_rain", name: "Artificial Rain Experiments", category: "environmental" },
  { id: "desert_cooling_towers", name: "Desert Cooling Towers", category: "environmental" },
  { id: "wind_barrier_systems", name: "Wind Barrier Systems", category: "environmental" },
  { id: "sandstorm_prediction_ai", name: "Sandstorm Prediction AI", category: "environmental" },
  { id: "nanite_terrain_repair", name: "Nanite Terrain Repair", category: "advanced" },
  { id: "drone_swarm_exploration", name: "Drone Swarm Exploration", category: "advanced" },
  { id: "ai_wasteland_analysis", name: "AI Wasteland Analysis", category: "advanced" },
  { id: "autonomous_defense_outposts", name: "Autonomous Defense Outposts", category: "advanced" },
  { id: "self_building_frontier_bases", name: "Self-Building Frontier Bases", category: "advanced" },
  { id: "robotic_excavation", name: "Robotic Excavation", category: "advanced" },
  { id: "terrain_stabilization_nanites", name: "Terrain Stabilization Nanites", category: "advanced" },
  { id: "wasteland_weather_manipulation", name: "Wasteland Weather Manipulation", category: "advanced" },
  { id: "smart_exploration_satellites", name: "Smart Exploration Satellites", category: "advanced" },
  { id: "autonomous_sector_surveying", name: "Autonomous Sector Surveying", category: "advanced" },
  { id: "orbital_wasteland_scanners", name: "Orbital Wasteland Scanners", category: "rare" },
  { id: "megabunker_excavation", name: "Underground Megabunker Excavation", category: "rare" },
  { id: "nuclear_cleanup_drones", name: "Nuclear Cleanup Drones", category: "rare" },
  { id: "anti_mutant_bio_weapons", name: "Anti-Mutant Bio Weapons", category: "rare" },
  { id: "autonomous_wasteland_cities", name: "Autonomous Wasteland Cities", category: "rare" },
  { id: "wasteland_terraforming_networks", name: "Wasteland Terraforming Networks", category: "ultra" },
  { id: "orbital_salvage_operations", name: "Orbital Salvage Operations", category: "ultra" },
  { id: "desert_agriculture_megaprojects", name: "Desert Agriculture Megaprojects", category: "ultra" },
  { id: "wasteland_ai_prediction", name: "Wasteland AI Prediction Systems", category: "ultra" },
  { id: "automated_scavenger_cities", name: "Automated Scavenger Cities", category: "ultra" },
  { id: "atmospheric_radiation_shields", name: "Atmospheric Radiation Shields", category: "ultra" },
  { id: "underground_megacity_tunnels", name: "Underground Megacity Tunnels", category: "ultra" },
  { id: "desert_ocean_desalination", name: "Desert Ocean Desalination", category: "ultra" },
  { id: "wasteland_defense_grids", name: "Wasteland Defense Grids", category: "ultra" },
  { id: "orbital_kinetic_defense", name: "Orbital Kinetic Strike Defense", category: "ultra" },
  { id: "deep_vault_construction", name: "Deep Underground Vault Construction", category: "ultra" },
  { id: "robotic_mining_armies", name: "Robotic Mining Armies", category: "ultra" },
  { id: "anti_sandstorm_shield_domes", name: "Anti-Sandstorm Shield Domes", category: "ultra" },
  { id: "wasteland_cloning_medicine", name: "Wasteland Cloning Medicine", category: "ultra" },
  { id: "bioengineered_desert_crops", name: "Bioengineered Desert Crops", category: "ultra" },
  { id: "atmospheric_stabilizers", name: "Atmospheric Stabilizers", category: "ultra" },
  { id: "autonomous_resource_harvesting", name: "Autonomous Resource Harvesting", category: "ultra" },
  { id: "planetary_desert_repair", name: "Planetary Desert Repair Networks", category: "ultra" },
];

export const WASTELAND_DISCOVERIES: WastelandDiscoveryDef[] = [
  { id: "buried_weapons_cache", name: "Buried Weapons Cache", rarity: "common" },
  { id: "abandoned_tank", name: "Abandoned Tank", rarity: "common" },
  { id: "prototype_drone_disc", name: "Prototype Drone", rarity: "rare" },
  { id: "rare_metals_vein", name: "Rare Metals Vein", rarity: "rare" },
  { id: "uranium_deposit", name: "Uranium Deposit", rarity: "rare" },
  { id: "lost_convoy_cargo", name: "Lost Convoy Cargo", rarity: "common" },
  { id: "sealed_military_crate", name: "Sealed Military Crate", rarity: "common" },
  { id: "reactor_fuel_rods", name: "Reactor Fuel Rods", rarity: "rare" },
  { id: "encrypted_military_data", name: "Encrypted Military Data", rarity: "rare" },
  { id: "rare_electronics_disc", name: "Rare Electronics", rarity: "common" },
  { id: "smuggled_contraband", name: "Smuggled Contraband Stash", rarity: "common" },
  { id: "hidden_ammo_bunker", name: "Hidden Ammo Bunker", rarity: "common" },
  { id: "medical_supply_cache", name: "Medical Supply Cache", rarity: "common" },
  { id: "old_currency_vault", name: "Old Currency Vault", rarity: "rare" },
  { id: "experimental_armor_suit", name: "Experimental Armor Suit", rarity: "very_rare" },
  { id: "robotics_parts", name: "Robotics Parts", rarity: "common" },
  { id: "drone_components", name: "Drone Components", rarity: "common" },
  { id: "satellite_guidance_chip", name: "Satellite Guidance Chip", rarity: "rare" },
  { id: "military_ai_fragment", name: "Military AI Fragment", rarity: "very_rare" },
  { id: "rare_energy_cell", name: "Rare Energy Cell", rarity: "rare" },
  { id: "nuclear_waste_containers", name: "Nuclear Waste Containers", rarity: "common" },
  { id: "missile_guidance_computer", name: "Missile Guidance Computer", rarity: "rare" },
  { id: "artillery_shells_disc", name: "Artillery Shells", rarity: "common" },
  { id: "weapon_prototype_parts", name: "Weapon Prototype Parts", rarity: "very_rare" },
  { id: "abandoned_armored_vehicle", name: "Abandoned Armored Vehicle", rarity: "common" },
  { id: "underground_supply_room", name: "Underground Supply Room", rarity: "common" },
  { id: "military_ration_stockpile", name: "Military Ration Stockpile", rarity: "common" },
  { id: "rare_cybernetic_implants", name: "Rare Cybernetic Implants", rarity: "rare" },
  { id: "stealth_drone_parts", name: "Stealth Drone Parts", rarity: "rare" },
  { id: "experimental_weapon_blueprint", name: "Experimental Weapon Blueprint", rarity: "very_rare" },
  { id: "alien_mineral_fragment", name: "Alien Mineral Fragment", rarity: "very_rare" },
  { id: "advanced_nanotech_parts", name: "Advanced Nanotech Parts", rarity: "very_rare" },
  { id: "ai_research_logs", name: "AI Research Logs", rarity: "rare" },
  { id: "orbital_weapon_codes", name: "Orbital Weapon Control Codes", rarity: "very_rare" },
  { id: "rare_isotope_materials", name: "Rare Isotope Materials", rarity: "rare" },
  { id: "lost_satellite_panel", name: "Lost Satellite Control Panel", rarity: "rare" },
  { id: "nuclear_warhead_casing", name: "Nuclear Warhead Casing", rarity: "very_rare" },
  { id: "prototype_energy_weapon", name: "Prototype Energy Weapon", rarity: "very_rare" },
  { id: "stealth_armor_plating", name: "Stealth Armor Plating", rarity: "rare" },
  { id: "mech_construction_parts", name: "Mech Construction Parts", rarity: "very_rare" },
];
