import type { WeaponDef, AmmoDef, MissileDef, VehicleWeaponDef, NuclearWeaponDef } from "@/engine/types";

export const WEAPONS: WeaponDef[] = [
  // ── SIDEARMS ────────────────────────────────────────────────────────
  { id: "lawgiver-mk1", name: "Arbiter Mk I", category: "sidearm", damage: 35, accuracy: 78, rateOfFire: 4, range: 50, cost: 800, ammoType: "standard_9mm", description: "Standard-issue Enforcer sidearm. Issued to every rookie. Outlives most of them." },
  { id: "lawgiver-mk2", name: "Arbiter Mk II", category: "sidearm", damage: 45, accuracy: 85, rateOfFire: 5, range: 60, cost: 1500, ammoType: "standard_9mm", description: "Upgraded Arbiter with enhanced targeting and burst fire." },
  { id: "widowmaker-pistol", name: "Widowmaker Pistol", category: "sidearm", damage: 50, accuracy: 72, rateOfFire: 2, range: 40, cost: 1200, ammoType: "heavy_magnum", description: "High-caliber hand cannon. One shot, one verdict." },
  { id: "scatter-blaster", name: "Scatter Blaster", category: "sidearm", damage: 55, accuracy: 60, rateOfFire: 2, range: 20, cost: 900, ammoType: "shotgun_shells", description: "Close-range scatter weapon for corridor sweeps." },
  { id: "viper-compact", name: "Viper Compact", category: "sidearm", damage: 28, accuracy: 82, rateOfFire: 6, range: 35, cost: 600, ammoType: "standard_9mm", description: "Concealed-carry backup sidearm. Fast draw." },
  { id: "jackal-45", name: "Jackal .45", category: "sidearm", damage: 42, accuracy: 74, rateOfFire: 3, range: 45, cost: 950, ammoType: "heavy_magnum", description: "Street-level enforcer favorite. Brutal stopping power." },
  { id: "ghost-9", name: "Ghost-9 Silenced", category: "sidearm", damage: 30, accuracy: 88, rateOfFire: 4, range: 40, cost: 1100, ammoType: "standard_9mm", description: "Integral suppressor. Covert operations standard." },
  { id: "deagle-mk3", name: "Desert Raptor Mk III", category: "sidearm", damage: 58, accuracy: 68, rateOfFire: 2, range: 50, cost: 1600, ammoType: "heavy_magnum", description: "Oversized magnum pistol. Intimidation factor: maximum." },
  { id: "twin-serpent", name: "Twin Serpent Auto-Pistol", category: "sidearm", damage: 22, accuracy: 70, rateOfFire: 10, range: 30, cost: 1300, ammoType: "standard_9mm", description: "Machine pistol variant. Spray and pray." },
  { id: "judge-revolver", name: "Enforcer Revolver", category: "sidearm", damage: 62, accuracy: 76, rateOfFire: 2, range: 55, cost: 1800, ammoType: "heavy_magnum", description: "Six-shot heavy revolver. Each round is a sentence." },
  { id: "needle-pistol", name: "Needle Pistol", category: "sidearm", damage: 18, accuracy: 92, rateOfFire: 8, range: 35, cost: 2200, ammoType: "neural_darts", description: "Flechette launcher. Silent, precise, lethal." },

  // ── SUBMACHINE GUNS ─────────────────────────────────────────────────
  { id: "cyclone-smg", name: "Cyclone SMG", category: "submachine_gun", damage: 25, accuracy: 65, rateOfFire: 15, range: 80, cost: 1800, ammoType: "standard_9mm", description: "High rate-of-fire submachine gun. Empties a corridor in three seconds." },
  { id: "razorwire-pdw", name: "Razorwire PDW", category: "submachine_gun", damage: 22, accuracy: 72, rateOfFire: 18, range: 60, cost: 1600, ammoType: "standard_9mm", description: "Ultra-compact personal defense weapon." },
  { id: "street-sweeper-smg", name: "Street Sweeper SMG", category: "submachine_gun", damage: 28, accuracy: 62, rateOfFire: 14, range: 70, cost: 2000, ammoType: "standard_9mm", description: "Drum-mag SMG. Forty rounds. One trigger pull. No survivors." },
  { id: "phantom-mp7", name: "Phantom MP-7", category: "submachine_gun", damage: 24, accuracy: 75, rateOfFire: 16, range: 90, cost: 2400, ammoType: "ap_9mm", description: "AP-capable PDW. Cuts through body armor." },
  { id: "vector-x", name: "Vector-X Kriss", category: "submachine_gun", damage: 26, accuracy: 78, rateOfFire: 20, range: 65, cost: 2800, ammoType: "standard_9mm", description: "Recoil-mitigation system. Controllable at full auto." },
  { id: "scorpion-micro", name: "Scorpion Micro", category: "submachine_gun", damage: 20, accuracy: 68, rateOfFire: 22, range: 50, cost: 1400, ammoType: "standard_9mm", description: "Smallest full-auto in the armory. Fits in a coat pocket. Empties in two seconds." },
  { id: "blackout-smg", name: "Blackout Integrally Suppressed", category: "submachine_gun", damage: 23, accuracy: 80, rateOfFire: 12, range: 75, cost: 3200, ammoType: "standard_9mm", description: "Whisper-quiet SMG for spec ops." },
  { id: "hornet-burst", name: "Hornet 3-Round Burst", category: "submachine_gun", damage: 30, accuracy: 76, rateOfFire: 9, range: 85, cost: 2100, ammoType: "standard_9mm", description: "Burst-fire only. Precision over volume." },

  // ── SHOTGUNS ─────────────────────────────────────────────────────────
  { id: "enforcer-shotgun", name: "Enforcer Tactical Shotgun", category: "shotgun", damage: 65, accuracy: 55, rateOfFire: 2, range: 25, cost: 1400, ammoType: "shotgun_shells", description: "Pump-action room clearer. Ka-chunk. Negotiation concluded." },
  { id: "street-judge-auto", name: "Street Enforcer Auto-Shotgun", category: "shotgun", damage: 58, accuracy: 50, rateOfFire: 4, range: 20, cost: 2200, ammoType: "shotgun_shells", description: "Semi-auto shotgun. Devastating at close range." },
  { id: "doorknocker-12g", name: "Doorknocker 12-Gauge", category: "shotgun", damage: 75, accuracy: 45, rateOfFire: 1, range: 15, cost: 1000, ammoType: "shotgun_shells", description: "Breaching shotgun. Blows hinges clean off." },
  { id: "dragons-breath", name: "Dragon's Breath Scattergun", category: "shotgun", damage: 60, accuracy: 40, rateOfFire: 2, range: 18, cost: 2600, ammoType: "inc_thermite", description: "Incendiary shotgun rounds. Sets everything ablaze." },
  { id: "slug-hunter", name: "Slug Hunter Rifled Shotgun", category: "shotgun", damage: 80, accuracy: 70, rateOfFire: 1, range: 60, cost: 1800, ammoType: "shotgun_shells", description: "Rifled barrel, slug ammunition. Sniper shotgun." },
  { id: "riot-breaker", name: "Riot Breaker Crowd Shotgun", category: "shotgun", damage: 30, accuracy: 35, rateOfFire: 3, range: 15, cost: 800, ammoType: "shotgun_shells", description: "Bean-bag capable. Non-lethal option." },
  { id: "quad-barrel", name: "Quad-Barrel Devastator", category: "shotgun", damage: 95, accuracy: 30, rateOfFire: 1, range: 12, cost: 3500, ammoType: "shotgun_shells", description: "Four barrels, one trigger. Point-blank annihilation." },
  { id: "flechette-auto", name: "Flechette Auto-Shotgun", category: "shotgun", damage: 45, accuracy: 60, rateOfFire: 5, range: 30, cost: 3000, ammoType: "shotgun_shells", description: "Fires steel darts. Armor-shredding spread." },

  // ── RIFLES ──────────────────────────────────────────────────────────
  { id: "enforcer-rifle", name: "Enforcer Assault Rifle", category: "rifle", damage: 40, accuracy: 80, rateOfFire: 8, range: 120, cost: 2200, ammoType: "rifle_556", description: "Standard patrol rifle. Boring on the spec sheet. Reliable in the alley." },
  { id: "punisher-carbine", name: "Punisher Carbine", category: "rifle", damage: 48, accuracy: 82, rateOfFire: 6, range: 150, cost: 3000, ammoType: "rifle_556", description: "Precision carbine for urban engagement." },
  { id: "longshot-sniper", name: "Longshot Sniper System", category: "rifle", damage: 90, accuracy: 95, rateOfFire: 1, range: 500, cost: 5000, ammoType: "sniper_762", description: "Long-range elimination platform." },
  { id: "bullpup-compact", name: "Bullpup Compact Rifle", category: "rifle", damage: 38, accuracy: 78, rateOfFire: 9, range: 100, cost: 2000, ammoType: "rifle_556", description: "Compact bullpup. Fits in a tank hatch. Crews swear by it." },
  { id: "marksman-dmr", name: "Marksman DMR", category: "rifle", damage: 65, accuracy: 90, rateOfFire: 3, range: 300, cost: 4200, ammoType: "sniper_762", description: "Designated marksman rifle. Bridge between rifle and sniper." },
  { id: "battle-rifle-762", name: "Battle Rifle 7.62", category: "rifle", damage: 55, accuracy: 82, rateOfFire: 5, range: 200, cost: 3500, ammoType: "heavy_762", description: "Hard-hitting battle rifle. Punches through cover." },
  { id: "stealth-carbine", name: "Stealth Carbine", category: "rifle", damage: 35, accuracy: 85, rateOfFire: 7, range: 110, cost: 3800, ammoType: "rifle_556", description: "Suppressed carbine with subsonic capability." },
  { id: "anti-material-rifle", name: "Anti-Materiel Rifle", category: "rifle", damage: 120, accuracy: 92, rateOfFire: 1, range: 800, cost: 8000, ammoType: "cannon_20mm", description: "Fires 20mm rounds. Destroys vehicles and walls." },
  { id: "burst-rifle-3rd", name: "Burst Rifle M3", category: "rifle", damage: 42, accuracy: 84, rateOfFire: 6, range: 140, cost: 2600, ammoType: "rifle_556", description: "Three-round burst. Conserves ammo, maximizes hits." },
  { id: "scout-rifle", name: "Scout Rifle", category: "rifle", damage: 50, accuracy: 88, rateOfFire: 4, range: 250, cost: 3200, ammoType: "sniper_762", description: "Lightweight scout platform. Fast acquisition." },

  // ── MACHINE GUNS ────────────────────────────────────────────────────
  { id: "thunderbolt-lmg", name: "Thunderbolt LMG", category: "machine_gun", damage: 55, accuracy: 60, rateOfFire: 12, range: 200, cost: 6000, ammoType: "heavy_762", description: "Belt-fed squad support. Suppresses anything dumb enough to lift its head." },
  { id: "suppressor-saw", name: "Suppressor SAW", category: "machine_gun", damage: 45, accuracy: 55, rateOfFire: 15, range: 180, cost: 5000, ammoType: "rifle_556", description: "Squad automatic weapon. Sustained fire platform." },
  { id: "minigun-m134", name: "Minigun M-134 Vulcan", category: "machine_gun", damage: 35, accuracy: 40, rateOfFire: 50, range: 150, cost: 12000, ammoType: "heavy_762", description: "Rotary barrel minigun. 6000 RPM of pure destruction." },
  { id: "coax-hmg", name: "Coaxial HMG", category: "machine_gun", damage: 70, accuracy: 58, rateOfFire: 8, range: 300, cost: 8000, ammoType: "heavy_762", description: "Vehicle-mounted HMG. Hammers cover until cover stops being cover." },
  { id: "gpmg-belt", name: "GPMG Belt-Fed", category: "machine_gun", damage: 50, accuracy: 62, rateOfFire: 10, range: 250, cost: 5500, ammoType: "heavy_762", description: "General purpose. Tripod-mounted, belt-fed, never satisfied." },
  { id: "chain-gun", name: "Chain Gun M242", category: "machine_gun", damage: 85, accuracy: 52, rateOfFire: 6, range: 350, cost: 15000, ammoType: "cannon_20mm", description: "25mm chain gun. Anti-vehicle suppression." },
  { id: "twin-linked-mg", name: "Twin-Linked MG", category: "machine_gun", damage: 40, accuracy: 48, rateOfFire: 20, range: 200, cost: 9000, ammoType: "heavy_762", description: "Dual-barrel synchronized fire system." },

  // ── HEAVY WEAPONS ───────────────────────────────────────────────────
  { id: "devastator-cannon", name: "Devastator Auto-Cannon", category: "heavy", damage: 85, accuracy: 55, rateOfFire: 4, range: 300, cost: 12000, ammoType: "cannon_20mm", description: "Vehicle-mounted rotary cannon." },
  { id: "hellfire-flamer", name: "Hellfire Flamethrower", category: "heavy", damage: 70, accuracy: 40, rateOfFire: 1, range: 30, cost: 4500, ammoType: "napalm_fuel", description: "Area denial incendiary weapon." },
  { id: "autocannon-30mm", name: "Autocannon 30mm", category: "heavy", damage: 100, accuracy: 50, rateOfFire: 3, range: 400, cost: 18000, ammoType: "cannon_20mm", description: "Heavy autocannon. Shreds light armor." },
  { id: "recoilless-rifle", name: "Recoilless Rifle", category: "heavy", damage: 130, accuracy: 65, rateOfFire: 1, range: 350, cost: 7000, ammoType: "exp_he", description: "Shoulder-fired anti-armor recoilless system." },
  { id: "mortar-60mm", name: "60mm Light Mortar", category: "heavy", damage: 90, accuracy: 35, rateOfFire: 2, range: 600, cost: 5000, ammoType: "exp_he", description: "Indirect fire support. Drop shells over walls." },
  { id: "heavy-flak", name: "Heavy Flak Cannon", category: "heavy", damage: 75, accuracy: 45, rateOfFire: 5, range: 500, cost: 10000, ammoType: "cannon_20mm", description: "Anti-air flak system. Repurposed for ground fire." },
  { id: "siege-breaker", name: "Siege Breaker Cannon", category: "heavy", damage: 200, accuracy: 60, rateOfFire: 1, range: 250, cost: 25000, ammoType: "exp_he", description: "Emplacement-level siege cannon. Levels structures." },

  // ── ENERGY WEAPONS ──────────────────────────────────────────────────
  { id: "plasma-lance", name: "Plasma Lance", category: "energy", damage: 95, accuracy: 75, rateOfFire: 2, range: 100, cost: 15000, ammoType: "plasma_cells", description: "Superheated plasma projection weapon." },
  { id: "arc-disruptor", name: "Arc Disruptor", category: "energy", damage: 60, accuracy: 70, rateOfFire: 3, range: 80, cost: 8000, ammoType: "energy_packs", description: "Electrical discharge weapon. Disables electronics." },
  { id: "pulse-cannon", name: "Pulse Cannon", category: "energy", damage: 110, accuracy: 65, rateOfFire: 1, range: 150, cost: 20000, ammoType: "fusion_cores", description: "Heavy energy weapon. Devastating against armor." },
  { id: "laser-carbine", name: "Laser Carbine", category: "energy", damage: 40, accuracy: 88, rateOfFire: 6, range: 120, cost: 6000, ammoType: "energy_packs", description: "Light laser weapon. No recoil, pinpoint accuracy." },
  { id: "ion-rifle", name: "Ion Disruption Rifle", category: "energy", damage: 55, accuracy: 82, rateOfFire: 3, range: 100, cost: 9000, ammoType: "ion_slugs", description: "Ionized beam weapon. Fries circuits on contact." },
  { id: "microwave-emitter", name: "Microwave Emitter", category: "energy", damage: 30, accuracy: 60, rateOfFire: 1, range: 40, cost: 7000, ammoType: "energy_packs", description: "Active denial system. Causes extreme pain." },
  { id: "cryo-beam", name: "Cryo-Beam Projector", category: "energy", damage: 45, accuracy: 72, rateOfFire: 2, range: 50, cost: 11000, ammoType: "energy_packs", description: "Supercooled beam. Flash-freezes targets." },
  { id: "tesla-arc", name: "Tesla Arc Cannon", category: "energy", damage: 80, accuracy: 55, rateOfFire: 2, range: 60, cost: 14000, ammoType: "energy_packs", description: "Chain-lightning weapon. Arcs between targets." },
  { id: "particle-beam", name: "Particle Beam Accelerator", category: "energy", damage: 150, accuracy: 90, rateOfFire: 1, range: 200, cost: 30000, ammoType: "fusion_cores", description: "Accelerated particles. Ignores most armor." },
  { id: "sonic-disruptor", name: "Sonic Disruptor", category: "energy", damage: 20, accuracy: 50, rateOfFire: 1, range: 30, cost: 5000, ammoType: "energy_packs", description: "Infrasonic weapon. Disorients and incapacitates." },

  // ── LAUNCHERS ────────────────────────────────────────────────────────
  { id: "frag-launcher", name: "Frag Grenade Launcher", category: "launcher", damage: 75, accuracy: 50, rateOfFire: 2, range: 200, cost: 4000, ammoType: "frag_grenades", description: "Multi-shot grenade launcher. Six rounds. Six rooms. No questions." },
  { id: "rocket-pod", name: "Rocket Pod System", category: "launcher", damage: 120, accuracy: 45, rateOfFire: 1, range: 400, cost: 10000, ammoType: "micro_rockets", description: "Shoulder-mounted rocket system." },
  { id: "rpg-7x", name: "RPG-7X Modernized", category: "launcher", damage: 140, accuracy: 55, rateOfFire: 1, range: 300, cost: 3500, ammoType: "micro_rockets", description: "Classic anti-armor rocket launcher." },
  { id: "multi-launcher", name: "Multi-Warhead Launcher", category: "launcher", damage: 100, accuracy: 40, rateOfFire: 3, range: 250, cost: 8000, ammoType: "micro_rockets", description: "Fires 4-round salvos. Area saturation." },
  { id: "smoke-launcher", name: "Smoke Launcher", category: "launcher", damage: 0, accuracy: 60, rateOfFire: 4, range: 150, cost: 1500, ammoType: "chem_tear_gas", description: "Deploys smoke screen. Blocks line of sight." },
  { id: "incendiary-launcher", name: "Incendiary Launcher", category: "launcher", damage: 65, accuracy: 48, rateOfFire: 2, range: 180, cost: 4500, ammoType: "inc_napalm_tip", description: "Napalm-filled grenades. Sets areas ablaze." },
  { id: "emp-launcher", name: "EMP Launcher", category: "launcher", damage: 10, accuracy: 55, rateOfFire: 1, range: 200, cost: 9000, ammoType: "emp_charges", description: "Electromagnetic pulse grenades. Kills electronics." },
  { id: "javelin-at", name: "Javelin Anti-Tank", category: "launcher", damage: 180, accuracy: 85, rateOfFire: 1, range: 500, cost: 12000, ammoType: "micro_rockets", description: "Top-attack anti-armor missile. Fire and forget." },

  // ── GRENADES & EXPLOSIVES ───────────────────────────────────────────
  { id: "frag-grenade", name: "Fragmentation Grenade", category: "grenade", damage: 60, accuracy: 50, rateOfFire: 1, range: 30, cost: 50, ammoType: "frag_grenades", description: "Standard frag. Pull pin. Count to four. Solve the room." },
  { id: "concussion-grenade", name: "Concussion Grenade", category: "grenade", damage: 25, accuracy: 50, rateOfFire: 1, range: 30, cost: 40, ammoType: "frag_grenades", description: "Concussive blast. Stuns and disorients." },
  { id: "flashbang", name: "Flashbang", category: "grenade", damage: 5, accuracy: 55, rateOfFire: 1, range: 25, cost: 30, ammoType: "frag_grenades", description: "Blinding flash and deafening bang." },
  { id: "incendiary-grenade", name: "Incendiary Grenade", category: "grenade", damage: 50, accuracy: 50, rateOfFire: 1, range: 30, cost: 80, ammoType: "inc_thermite", description: "Thermite grenade. Burns through steel." },
  { id: "gas-grenade", name: "Gas Grenade", category: "grenade", damage: 15, accuracy: 50, rateOfFire: 1, range: 30, cost: 60, ammoType: "chem_tear_gas", description: "Chemical irritant area denial." },
  { id: "emp-grenade", name: "EMP Grenade", category: "grenade", damage: 5, accuracy: 50, rateOfFire: 1, range: 25, cost: 200, ammoType: "emp_charges", description: "Localized electromagnetic pulse." },
  { id: "plasma-grenade", name: "Plasma Grenade", category: "grenade", damage: 85, accuracy: 48, rateOfFire: 1, range: 25, cost: 400, ammoType: "plasma_cells", description: "Superheated plasma burst. Melts everything." },
  { id: "cluster-mine", name: "Cluster Mine", category: "grenade", damage: 70, accuracy: 100, rateOfFire: 1, range: 5, cost: 150, ammoType: "exp_frag", description: "Proximity-triggered cluster munition." },
  { id: "breaching-charge", name: "Breaching Charge", category: "grenade", damage: 100, accuracy: 100, rateOfFire: 1, range: 3, cost: 120, ammoType: "exp_he", description: "Shaped charge. Cuts through doors and walls." },
  { id: "sticky-bomb", name: "Sticky Bomb", category: "grenade", damage: 90, accuracy: 65, rateOfFire: 1, range: 20, cost: 180, ammoType: "exp_he", description: "Adhesive explosive. Sticks to any surface." },

  // ── LAW ENFORCEMENT ─────────────────────────────────────────────────
  { id: "stun-baton", name: "Stun Baton", category: "law_enforcement", damage: 15, accuracy: 90, rateOfFire: 1, range: 2, cost: 200, ammoType: "none", description: "Non-lethal crowd control baton." },
  { id: "riot-shield-taser", name: "Riot Shield Taser", category: "law_enforcement", damage: 10, accuracy: 85, rateOfFire: 1, range: 5, cost: 500, ammoType: "energy_packs", description: "Shield-mounted taser. Block and shock." },
  { id: "net-launcher", name: "Net Launcher", category: "law_enforcement", damage: 2, accuracy: 70, rateOfFire: 1, range: 20, cost: 800, ammoType: "none", description: "Entanglement net. Immobilizes suspects." },
  { id: "rubber-bullet-gun", name: "Rubber Bullet Carbine", category: "law_enforcement", damage: 12, accuracy: 75, rateOfFire: 6, range: 60, cost: 1200, ammoType: "standard_9mm", description: "Non-lethal impact rounds. Crowd dispersal." },
  { id: "crowd-control-cannon", name: "Crowd Control Sonic Cannon", category: "law_enforcement", damage: 8, accuracy: 45, rateOfFire: 1, range: 50, cost: 3000, ammoType: "energy_packs", description: "LRAD sonic weapon. Disperses crowds at range." },
  { id: "tranq-rifle", name: "Tranquilizer Rifle", category: "law_enforcement", damage: 5, accuracy: 90, rateOfFire: 1, range: 80, cost: 2000, ammoType: "chem_toxin_darts", description: "Sedative dart rifle. Silent takedown." },
  { id: "pepperball-launcher", name: "Pepperball Launcher", category: "law_enforcement", damage: 8, accuracy: 65, rateOfFire: 8, range: 40, cost: 900, ammoType: "chem_tear_gas", description: "PAVA irritant rounds. Area denial." },
  { id: "water-cannon", name: "High-Pressure Water Cannon", category: "law_enforcement", damage: 10, accuracy: 50, rateOfFire: 1, range: 60, cost: 4000, ammoType: "none", description: "Vehicle-mounted water cannon. Knocks down rioters." },
  { id: "strobe-disorienter", name: "Strobe Disorienter", category: "law_enforcement", damage: 3, accuracy: 40, rateOfFire: 1, range: 30, cost: 600, ammoType: "energy_packs", description: "Seizure-inducing strobe device. Area effect." },
  { id: "bola-launcher", name: "Bola Launcher", category: "law_enforcement", damage: 5, accuracy: 72, rateOfFire: 1, range: 25, cost: 700, ammoType: "none", description: "Weighted bola wraps. Trips and binds." },

  // ── MELEE ───────────────────────────────────────────────────────────
  { id: "power-fist", name: "Power Fist", category: "melee", damage: 65, accuracy: 80, rateOfFire: 1, range: 2, cost: 3000, ammoType: "energy_packs", description: "Powered gauntlet for breaching and close combat." },
  { id: "mono-blade", name: "Mono-Molecular Blade", category: "melee", damage: 75, accuracy: 85, rateOfFire: 2, range: 2, cost: 5000, ammoType: "none", description: "Atom-thin edge. Cuts through anything." },
  { id: "shock-maul", name: "Shock Maul", category: "melee", damage: 45, accuracy: 78, rateOfFire: 1, range: 3, cost: 1500, ammoType: "energy_packs", description: "Electrified mace. Stuns on contact." },
  { id: "chain-sword", name: "Chain Sword", category: "melee", damage: 80, accuracy: 72, rateOfFire: 1, range: 3, cost: 4000, ammoType: "none", description: "Motorized chain-edge sword. Brutal but effective." },
  { id: "thermal-lance-melee", name: "Thermal Cutting Lance", category: "melee", damage: 90, accuracy: 70, rateOfFire: 1, range: 3, cost: 6000, ammoType: "plasma_cells", description: "Plasma-edged polearm. Melts through bulkheads." },
  { id: "riot-club", name: "Reinforced Riot Club", category: "melee", damage: 20, accuracy: 88, rateOfFire: 2, range: 2, cost: 300, ammoType: "none", description: "Durasteel club. Simple, reliable." },
  { id: "vibro-knife", name: "Vibro-Knife", category: "melee", damage: 35, accuracy: 90, rateOfFire: 3, range: 1, cost: 800, ammoType: "none", description: "High-frequency vibrating blade. Silent kills." },
  { id: "thunder-hammer", name: "Thunder Hammer", category: "melee", damage: 110, accuracy: 60, rateOfFire: 1, range: 3, cost: 8000, ammoType: "energy_packs", description: "Concussive discharge on impact. Sends targets flying." },

  // ── EXPERIMENTAL ────────────────────────────────────────────────────
  { id: "neural-disabler", name: "Neural Disabler", category: "experimental", damage: 5, accuracy: 88, rateOfFire: 3, range: 30, cost: 7000, ammoType: "neural_darts", description: "Targets nervous system. Instant incapacitation." },
  { id: "gravity-hammer", name: "Gravity Hammer", category: "experimental", damage: 130, accuracy: 50, rateOfFire: 1, range: 5, cost: 25000, ammoType: "grav_charges", description: "Experimental gravity manipulation weapon." },
  { id: "singularity-gun", name: "Singularity Gun", category: "experimental", damage: 200, accuracy: 45, rateOfFire: 1, range: 30, cost: 50000, ammoType: "grav_charges", description: "Creates micro black holes. Extremely unstable." },
  { id: "phase-rifle", name: "Phase Shift Rifle", category: "experimental", damage: 70, accuracy: 95, rateOfFire: 2, range: 150, cost: 35000, ammoType: "fusion_cores", description: "Shifts bullets through solid matter to hit targets." },
  { id: "chrono-displacer", name: "Chrono Displacer", category: "experimental", damage: 0, accuracy: 80, rateOfFire: 1, range: 40, cost: 40000, ammoType: "stasis_shells", description: "Displaces targets 3 seconds into the past." },
  { id: "nanite-swarm-gun", name: "Nanite Swarm Projector", category: "experimental", damage: 60, accuracy: 70, rateOfFire: 1, range: 50, cost: 28000, ammoType: "smart_rounds", description: "Launches self-replicating nanite swarm." },
  { id: "dark-matter-rifle", name: "Dark Matter Rifle", category: "experimental", damage: 180, accuracy: 60, rateOfFire: 1, range: 100, cost: 45000, ammoType: "fusion_cores", description: "Weaponized dark matter. Erases targets from existence." },
  { id: "quantum-entangler", name: "Quantum Entangler", category: "experimental", damage: 150, accuracy: 100, rateOfFire: 1, range: 1000, cost: 60000, ammoType: "fusion_cores", description: "Quantum-linked instant hit. Range is irrelevant." },
  { id: "antimatter-lance", name: "Antimatter Lance", category: "experimental", damage: 300, accuracy: 55, rateOfFire: 1, range: 80, cost: 80000, ammoType: "fusion_cores", description: "Antimatter annihilation beam. City-block-level threat." },

  // ── SPECIAL ─────────────────────────────────────────────────────────
  { id: "target-designator", name: "Target Designator", category: "special", damage: 0, accuracy: 95, rateOfFire: 1, range: 2000, cost: 5000, ammoType: "none", description: "Laser designator for orbital/artillery strikes." },
  { id: "deployable-turret", name: "Deployable Auto-Turret", category: "special", damage: 35, accuracy: 70, rateOfFire: 10, range: 100, cost: 8000, ammoType: "rifle_556", description: "AI-controlled autonomous turret. Set and forget." },
  { id: "drone-swarm-controller", name: "Drone Swarm Controller", category: "special", damage: 25, accuracy: 75, rateOfFire: 6, range: 200, cost: 15000, ammoType: "energy_packs", description: "Commands squad of armed micro-drones." },
  { id: "holographic-decoy", name: "Holographic Decoy Projector", category: "special", damage: 0, accuracy: 0, rateOfFire: 1, range: 50, cost: 3000, ammoType: "energy_packs", description: "Projects convincing holographic decoy." },
  { id: "grapple-gun", name: "Grapple Gun", category: "special", damage: 15, accuracy: 80, rateOfFire: 1, range: 100, cost: 2000, ammoType: "none", description: "Magnetic grappling hook launcher. Mobility tool." },
  { id: "cloaking-device", name: "Personal Cloaking Device", category: "special", damage: 0, accuracy: 0, rateOfFire: 1, range: 0, cost: 20000, ammoType: "energy_packs", description: "Thermoptic camouflage. Near-total invisibility." },
  { id: "shield-projector", name: "Portable Shield Projector", category: "special", damage: 0, accuracy: 0, rateOfFire: 1, range: 10, cost: 12000, ammoType: "energy_packs", description: "Energy barrier projector. Blocks incoming fire." },
  { id: "seismic-charge", name: "Seismic Charge", category: "special", damage: 150, accuracy: 100, rateOfFire: 1, range: 5, cost: 5000, ammoType: "exp_he", description: "Ground-penetrating seismic blast. Collapses tunnels." },
];

export const AMMO_TYPES: AmmoDef[] = [
  { id: "standard_9mm", name: "Standard 9mm Rounds", category: "standard", costPer100: 50, damage_modifier: 1.0, description: "Mass-produced. Shipped by the pallet. Burned through in a shift." },
  { id: "heavy_magnum", name: "Heavy Magnum Rounds", category: "standard", costPer100: 120, damage_modifier: 1.3, description: "High-caliber magnum. Recoil bruises the shoulder. The wounds end conversations." },
  { id: "shotgun_shells", name: "Shotgun Shells", category: "standard", costPer100: 80, damage_modifier: 1.1, description: "12-gauge buckshot. Doesn't ask. Doesn't miss at five meters." },
  { id: "rifle_556", name: "5.56mm Rifle Rounds", category: "standard", costPer100: 60, damage_modifier: 1.0, description: "Cheap, abundant, accountable. The ledger eats them by the case." },
  { id: "sniper_762", name: "7.62mm Sniper Rounds", category: "standard", costPer100: 150, damage_modifier: 1.4, description: "Match-grade. Hand-loaded. Each round costs more than a citizen's daily ration." },
  { id: "heavy_762", name: "7.62mm Belt-Fed", category: "standard", costPer100: 90, damage_modifier: 1.2, description: "Belt-linked. Fed in 200-round chains. Sustains fire until the barrel glows." },
  { id: "cannon_20mm", name: "20mm Cannon Shells", category: "standard", costPer100: 500, damage_modifier: 2.0, description: "Auto-cannon caliber explosive shells." },
  { id: "ap_9mm", name: "AP 9mm Penetrators", category: "armor_piercing", costPer100: 120, damage_modifier: 1.5, description: "Tungsten-core armor-piercing 9mm." },
  { id: "ap_556", name: "AP 5.56mm Rounds", category: "armor_piercing", costPer100: 140, damage_modifier: 1.6, description: "Armor-piercing rifle rounds." },
  { id: "ap_762", name: "AP 7.62mm Rounds", category: "armor_piercing", costPer100: 200, damage_modifier: 1.8, description: "Heavy AP rounds for fortified targets." },
  { id: "ap_sabot", name: "Sabot Penetrators", category: "armor_piercing", costPer100: 350, damage_modifier: 2.2, description: "Discarding-sabot. Sheds its skirt mid-flight. The core punches through plate like paper." },
  { id: "ap_depleted_uranium", name: "Depleted Uranium Tips", category: "armor_piercing", costPer100: 600, damage_modifier: 2.8, description: "DU-core. Punches through anything. Leaves the entry sector glowing for decades." },
  { id: "inc_tracer", name: "Incendiary Tracers", category: "incendiary", costPer100: 100, damage_modifier: 1.2, description: "Phosphorus-tipped tracer rounds." },
  { id: "inc_thermite", name: "Thermite Rounds", category: "incendiary", costPer100: 200, damage_modifier: 1.6, description: "Burns through metal on impact." },
  { id: "inc_napalm_tip", name: "Napalm-Tipped Shells", category: "incendiary", costPer100: 250, damage_modifier: 1.8, description: "Gel-based incendiary warheads." },
  { id: "napalm_fuel", name: "Napalm Fuel Canisters", category: "incendiary", costPer100: 300, damage_modifier: 2.0, description: "Pressurized incendiary fuel for flamethrowers." },
  { id: "inc_white_phosphorus", name: "White Phosphorus Shells", category: "incendiary", costPer100: 400, damage_modifier: 2.2, description: "Area denial chemical incendiary." },
  { id: "exp_frag", name: "Fragmentation Rounds", category: "explosive", costPer100: 180, damage_modifier: 1.4, description: "Airburst fragmentation ammunition." },
  { id: "frag_grenades", name: "Frag Grenades", category: "explosive", costPer100: 500, damage_modifier: 2.0, description: "40mm fragmentation grenades." },
  { id: "exp_he", name: "High-Explosive Shells", category: "explosive", costPer100: 600, damage_modifier: 2.5, description: "Heavy explosive ordnance." },
  { id: "micro_rockets", name: "Micro Rockets", category: "explosive", costPer100: 800, damage_modifier: 3.0, description: "Miniaturized rocket propelled grenades." },
  { id: "exp_cluster", name: "Cluster Munitions", category: "explosive", costPer100: 1000, damage_modifier: 3.5, description: "Multi-warhead area saturation." },
  { id: "energy_packs", name: "Energy Packs", category: "energy", costPer100: 200, damage_modifier: 1.0, description: "Rechargeable cells. Plug into any wall the grid still feeds." },
  { id: "plasma_cells", name: "Plasma Cells", category: "energy", costPer100: 500, damage_modifier: 1.5, description: "Superheated plasma containment cells." },
  { id: "fusion_cores", name: "Fusion Cores", category: "energy", costPer100: 1200, damage_modifier: 2.0, description: "Miniaturized fusion power cells." },
  { id: "emp_charges", name: "EMP Charges", category: "energy", costPer100: 800, damage_modifier: 0.5, description: "Electromagnetic pulse disruptors." },
  { id: "ion_slugs", name: "Ion Slugs", category: "energy", costPer100: 600, damage_modifier: 1.3, description: "Ionized projectiles for energy weapons." },
  { id: "chem_tear_gas", name: "Tear Gas Rounds", category: "chemical", costPer100: 80, damage_modifier: 0.3, description: "Officially non-lethal. Asthmatics disagree." },
  { id: "chem_nerve_agent", name: "Nerve Agent Capsules", category: "chemical", costPer100: 400, damage_modifier: 2.0, description: "Banned by treaty. Stocked in three depots anyway." },
  { id: "chem_rad_rounds", name: "Irradiated Rounds", category: "chemical", costPer100: 350, damage_modifier: 1.8, description: "Low-level radiation contamination rounds." },
  { id: "chem_toxin_darts", name: "Toxin Darts", category: "chemical", costPer100: 300, damage_modifier: 1.5, description: "Biological toxin delivery projectiles." },
  { id: "chem_corrosive", name: "Corrosive Acid Shells", category: "chemical", costPer100: 250, damage_modifier: 1.6, description: "Acid-filled anti-armor rounds." },
  { id: "neural_darts", name: "Neural Disruption Darts", category: "special", costPer100: 400, damage_modifier: 0.2, description: "Targets central nervous system." },
  { id: "grav_charges", name: "Gravity Charges", category: "special", costPer100: 2000, damage_modifier: 3.0, description: "Experimental graviton manipulation charges." },
  { id: "smart_rounds", name: "Smart Tracking Rounds", category: "special", costPer100: 800, damage_modifier: 1.5, description: "Self-guiding micro-processor rounds." },
  { id: "stasis_shells", name: "Stasis Field Shells", category: "special", costPer100: 1500, damage_modifier: 0.1, description: "Temporal stasis containment projectiles." },
  { id: "none", name: "No Ammunition", category: "standard", costPer100: 0, damage_modifier: 1.0, description: "Melee weapon — no ammunition required." },
  { id: "msl_standard", name: "Standard Missile Fuel", category: "missile", costPer100: 1000, damage_modifier: 2.0, description: "Solid-fuel rocket propellant." },
  { id: "msl_advanced", name: "Advanced Missile Propellant", category: "missile", costPer100: 2500, damage_modifier: 3.0, description: "High-energy liquid propellant." },
  { id: "msl_nuclear", name: "Nuclear Warhead Material", category: "missile", costPer100: 10000, damage_modifier: 10.0, description: "Enriched fissile warhead material. Maximum clearance." },
];

export const MISSILES: MissileDef[] = [
  { id: "msl-frag-1", name: "Frag Rocket Mk I", tier: 1, damage: 80, range: 200, blastRadius: 10, cost: 500, guidance: "unguided", description: "Unguided fragmentation. Point in the general direction. Hope clears the rest." },
  { id: "msl-frag-2", name: "Frag Rocket Mk II", tier: 1, damage: 120, range: 300, blastRadius: 15, cost: 800, guidance: "unguided", description: "Improved frag rocket. Same dumb fire. Longer reach." },
  { id: "msl-heat-1", name: "Sidewinder Heat Seeker", tier: 2, damage: 150, range: 500, blastRadius: 8, cost: 1200, guidance: "heat_seeking", description: "Infrared seeker. Locks on body heat. The dark hides nothing." },
  { id: "msl-heat-2", name: "Firestorm Heat Seeker", tier: 2, damage: 200, range: 600, blastRadius: 12, cost: 1800, guidance: "heat_seeking", description: "Advanced heat-seeking with flare resistance." },
  { id: "msl-heat-3", name: "Inferno Seeker", tier: 3, damage: 280, range: 800, blastRadius: 15, cost: 3000, guidance: "heat_seeking", description: "Multi-spectrum thermal tracking missile." },
  { id: "msl-laser-1", name: "Lancer Guided Missile", tier: 2, damage: 180, range: 700, blastRadius: 5, cost: 2000, guidance: "laser_guided", description: "Laser-designated. A spotter paints the target. The missile finishes the conversation." },
  { id: "msl-laser-2", name: "Excalibur Precision", tier: 3, damage: 250, range: 1000, blastRadius: 8, cost: 3500, guidance: "laser_guided", description: "Extended-range precision guided munition." },
  { id: "msl-laser-3", name: "Deadeye Strike System", tier: 4, damage: 350, range: 1500, blastRadius: 10, cost: 5000, guidance: "laser_guided", description: "Surgical strike platform. Near-zero collateral." },
  { id: "msl-sat-1", name: "Skywatch GPS Missile", tier: 3, damage: 300, range: 2000, blastRadius: 20, cost: 4000, guidance: "satellite", description: "Satellite-guided cruise missile. Launched here, lands a sector away. Nobody hears it coming." },
  { id: "msl-sat-2", name: "Orbital Strike Missile", tier: 4, damage: 500, range: 5000, blastRadius: 30, cost: 8000, guidance: "satellite", description: "Sub-orbital trajectory strategic missile." },
  { id: "msl-sat-3", name: "God's Eye Orbital", tier: 5, damage: 800, range: 10000, blastRadius: 50, cost: 15000, guidance: "satellite", description: "Orbital bombardment platform missile." },
  { id: "msl-ai-1", name: "Sentinel AI Missile", tier: 3, damage: 220, range: 1200, blastRadius: 8, cost: 5000, guidance: "ai_guided", description: "Autonomous target-identifying smart missile." },
  { id: "msl-ai-2", name: "Predator Swarm Missile", tier: 4, damage: 350, range: 2000, blastRadius: 15, cost: 8000, guidance: "ai_guided", description: "AI-coordinated swarm missile cluster." },
  { id: "msl-ai-3", name: "Omega Autonomous Strike", tier: 5, damage: 600, range: 5000, blastRadius: 25, cost: 12000, guidance: "ai_guided", description: "Fully autonomous seek-and-destroy platform." },
  { id: "msl-bunker-1", name: "Bunker Buster Mk I", tier: 2, damage: 250, range: 400, blastRadius: 5, cost: 2500, guidance: "laser_guided", description: "Penetration warhead for fortified targets." },
  { id: "msl-bunker-2", name: "Deep Penetrator", tier: 4, damage: 450, range: 600, blastRadius: 8, cost: 6000, guidance: "laser_guided", description: "Multi-stage underground bunker buster." },
  { id: "msl-emp-1", name: "EMP Warhead Missile", tier: 3, damage: 50, range: 1000, blastRadius: 100, cost: 6000, guidance: "satellite", description: "Electromagnetic pulse area denial." },
  { id: "msl-cluster-1", name: "Cluster Warhead Missile", tier: 3, damage: 200, range: 800, blastRadius: 60, cost: 4500, guidance: "satellite", description: "Disperses sub-munitions over wide area." },
  { id: "msl-thermobaric", name: "Thermobaric Warhead", tier: 4, damage: 550, range: 1000, blastRadius: 40, cost: 9000, guidance: "satellite", description: "Fuel-air explosive. Devastating in enclosed areas." },
  { id: "msl-nuclear-tac", name: "Tactical Nuclear Missile", tier: 5, damage: 2000, range: 10000, blastRadius: 200, cost: 50000, guidance: "ai_guided", description: "Low-yield nuclear warhead. Codename: Last Resort. Used twice already." },
];

export const WEAPON_CATEGORIES: Record<string, string> = {
  sidearm: "SIDEARMS",
  submachine_gun: "SUBMACHINE GUNS",
  shotgun: "SHOTGUNS",
  rifle: "RIFLES",
  machine_gun: "MACHINE GUNS",
  heavy: "HEAVY WEAPONS",
  energy: "ENERGY WEAPONS",
  launcher: "LAUNCHERS",
  grenade: "GRENADES & EXPLOSIVES",
  law_enforcement: "LAW ENFORCEMENT",
  melee: "MELEE",
  experimental: "EXPERIMENTAL",
  special: "SPECIAL",
};

export const AMMO_CATEGORIES: Record<string, string> = {
  standard: "STANDARD",
  armor_piercing: "ARMOR PIERCING",
  incendiary: "INCENDIARY",
  explosive: "EXPLOSIVE",
  energy: "ENERGY",
  chemical: "CHEMICAL",
  special: "SPECIAL",
  missile: "MISSILE PROPELLANT",
};

export const MISSILE_GUIDANCE_LABELS: Record<string, string> = {
  unguided: "UNGUIDED",
  heat_seeking: "HEAT SEEKING",
  laser_guided: "LASER GUIDED",
  satellite: "SATELLITE",
  ai_guided: "AI GUIDED",
};

export const VEHICLE_WEAPON_CATEGORIES: Record<string, string> = {
  cannon: "CANNONS",
  machine_gun: "MACHINE GUNS",
  missile_system: "MISSILE SYSTEMS",
  rocket: "ROCKETS",
  energy_weapon: "ENERGY WEAPONS",
  experimental_weapon: "EXPERIMENTAL",
  defensive: "DEFENSIVE",
  exotic: "EXOTIC SYSTEMS",
};

export const VEHICLE_WEAPONS: VehicleWeaponDef[] = [
  { id: "vw-light-autocannon", name: "Light Autocannon", category: "cannon", damage: 60, range: 300, cost: 8000, description: "Rapid-fire light cannon. Fits any APC turret. Chews through unarmored crowds." },
  { id: "vw-heavy-autocannon", name: "Heavy Autocannon", category: "cannon", damage: 85, range: 400, cost: 12000, description: "High-caliber autocannon. Standard MBT loadout. Recoil cracks pavement." },
  { id: "vw-hv-cannon", name: "High Velocity Cannon", category: "cannon", damage: 110, range: 600, cost: 18000, description: "Hypervelocity kinetic penetrator cannon." },
  { id: "vw-rail-cannon", name: "Rail Cannon", category: "cannon", damage: 150, range: 800, cost: 30000, description: "Electromagnetic rail-accelerated projectiles." },
  { id: "vw-magnetic-coil", name: "Magnetic Coil Cannon", category: "cannon", damage: 130, range: 700, cost: 25000, description: "Coilgun technology for silent, devastating fire." },
  { id: "vw-plasma-burst", name: "Plasma Burst Cannon", category: "cannon", damage: 140, range: 500, cost: 35000, description: "Superheated plasma projectiles. Melts armor." },
  { id: "vw-frag-cannon", name: "Fragmentation Cannon", category: "cannon", damage: 75, range: 350, cost: 10000, description: "Anti-personnel fragmentation shells." },
  { id: "vw-inc-cannon", name: "Incendiary Cannon", category: "cannon", damage: 70, range: 300, cost: 11000, description: "Fires thermite-filled incendiary shells." },
  { id: "vw-hmg-turret", name: "Heavy Machine Gun Turret", category: "machine_gun", damage: 55, range: 250, cost: 6000, description: "Pintle-mount HMG. Operator stands in the open. Most don't last two tours." },
  { id: "vw-twin-rotary", name: "Twin Rotary Cannon", category: "machine_gun", damage: 45, range: 200, cost: 9000, description: "Dual-barrel rotary. Doubles the noise. Doubles the morgue receipts." },
  { id: "vw-smart-gatling", name: "Smart Targeting Gatling Gun", category: "machine_gun", damage: 40, range: 250, cost: 12000, description: "AI-assisted targeting rotary gun." },
  { id: "vw-anti-drone-gun", name: "Anti-Drone Autogun", category: "machine_gun", damage: 35, range: 300, cost: 8000, description: "Rapid-fire system optimized for drone targets." },
  { id: "vw-suppression-mini", name: "Suppression Minigun", category: "machine_gun", damage: 30, range: 200, cost: 7000, description: "High ROF area suppression weapon." },
  { id: "vw-micro-missile", name: "Micro Missile Pod", category: "missile_system", damage: 80, range: 500, cost: 10000, description: "Cluster of miniature guided missiles." },
  { id: "vw-at-missile", name: "Anti-Tank Missile Launcher", category: "missile_system", damage: 200, range: 800, cost: 15000, description: "Wire-guided anti-armor missile system." },
  { id: "vw-guided-rack", name: "Guided Missile Rack", category: "missile_system", damage: 150, range: 1000, cost: 18000, description: "Multi-tube guided missile system." },
  { id: "vw-swarm-launcher", name: "Swarm Missile Launcher", category: "missile_system", damage: 120, range: 600, cost: 20000, description: "Fires coordinated missile swarm." },
  { id: "vw-emp-missile", name: "EMP Missile Pod", category: "missile_system", damage: 30, range: 700, cost: 16000, description: "Electromagnetic pulse warhead missiles." },
  { id: "vw-aa-missile", name: "Anti-Air Missile Rack", category: "missile_system", damage: 180, range: 1200, cost: 22000, description: "Surface-to-air missile launcher system." },
  { id: "vw-cruise-tube", name: "Heavy Cruise Missile Tube", category: "missile_system", damage: 350, range: 5000, cost: 40000, description: "Long-range cruise missile launch system." },
  { id: "vw-riot-rocket", name: "Riot Control Rocket Pod", category: "rocket", damage: 20, range: 300, cost: 5000, description: "Non-lethal crowd dispersal rockets." },
  { id: "vw-thermobaric-rack", name: "Thermobaric Rocket Rack", category: "rocket", damage: 180, range: 400, cost: 14000, description: "Fuel-air explosive rocket system." },
  { id: "vw-smoke-launcher", name: "Smoke Rocket Launcher", category: "rocket", damage: 0, range: 200, cost: 3000, description: "Concealment smoke deployment." },
  { id: "vw-cluster-rocket", name: "Cluster Rocket Pod", category: "rocket", damage: 100, range: 350, cost: 12000, description: "Sub-munition dispersal rockets." },
  { id: "vw-bunker-rocket", name: "Anti-Bunker Rocket", category: "rocket", damage: 250, range: 300, cost: 16000, description: "Penetration warhead for fortifications." },
  { id: "vw-laser-cannon", name: "Laser Cannon", category: "energy_weapon", damage: 90, range: 500, cost: 20000, description: "Focused beam weapon. Silent. Cuts through cover before the target hears the hum." },
  { id: "vw-pulse-laser", name: "Pulse Laser Turret", category: "energy_weapon", damage: 70, range: 400, cost: 18000, description: "Rapid-pulse laser weapon system." },
  { id: "vw-particle-beam", name: "Particle Beam", category: "energy_weapon", damage: 120, range: 600, cost: 28000, description: "Accelerated particle weapon. Ignores armor." },
  { id: "vw-ion-disruptor", name: "Ion Disruptor", category: "energy_weapon", damage: 50, range: 350, cost: 15000, description: "Disables electronic systems." },
  { id: "vw-microwave", name: "Microwave Weapon", category: "energy_weapon", damage: 40, range: 250, cost: 12000, description: "Anti-personnel directed energy." },
  { id: "vw-gravity-pulse", name: "Gravity Pulse Projector", category: "experimental_weapon", damage: 100, range: 200, cost: 40000, description: "Localized gravity disruption weapon." },
  { id: "vw-shockwave", name: "Shockwave Emitter", category: "experimental_weapon", damage: 80, range: 150, cost: 25000, description: "Concussive blast wave generator." },
  { id: "vw-cryo-beam", name: "Cryogenic Beam", category: "experimental_weapon", damage: 60, range: 200, cost: 22000, description: "Flash-freeze beam weapon." },
  { id: "vw-sonic-cannon", name: "Sonic Cannon", category: "experimental_weapon", damage: 45, range: 250, cost: 18000, description: "Devastating sonic frequency weapon." },
  { id: "vw-em-rail-turret", name: "Electromagnetic Rail Turret", category: "experimental_weapon", damage: 160, range: 900, cost: 35000, description: "Vehicle-mounted railgun turret." },
  { id: "vw-counter-missile", name: "Counter-Missile System", category: "defensive", damage: 50, range: 300, cost: 15000, description: "Active missile defense. Tracks incoming. Fires in milliseconds. Never sleeps." },
  { id: "vw-anti-drone-pulse", name: "Anti-Drone Pulse Emitter", category: "defensive", damage: 25, range: 200, cost: 10000, description: "EMP pulse targeting drones." },
  { id: "vw-smoke-screen", name: "Smoke Screen Dispenser", category: "defensive", damage: 0, range: 50, cost: 3000, description: "Rapid smoke concealment system." },
  { id: "vw-reactive-mine", name: "Reactive Armor Mine Launcher", category: "defensive", damage: 80, range: 100, cost: 8000, description: "Deploys anti-pursuit mines." },
  { id: "vw-nanite-swarm", name: "Nanite Swarm Dispenser", category: "exotic", damage: 70, range: 200, cost: 30000, description: "Self-replicating nanite cloud weapon." },
  { id: "vw-rad-beam", name: "Radiation Beam Projector", category: "exotic", damage: 90, range: 400, cost: 25000, description: "Focused radiation beam." },
  { id: "vw-plasma-flak", name: "Plasma Flak Cannon", category: "exotic", damage: 65, range: 500, cost: 20000, description: "Plasma-based anti-air bursts." },
  { id: "vw-mag-net", name: "Magnetic Net Launcher", category: "exotic", damage: 10, range: 150, cost: 8000, description: "Electromagnetic capture net." },
  { id: "vw-holo-decoy", name: "Holographic Decoy Launcher", category: "exotic", damage: 0, range: 200, cost: 12000, description: "Projects vehicle decoys." },
  { id: "vw-drone-bay", name: "Drone Launch Bay", category: "exotic", damage: 50, range: 500, cost: 18000, description: "Deploys armed micro-drones." },
  { id: "vw-auto-turret", name: "Automated Defense Turret", category: "exotic", damage: 40, range: 250, cost: 14000, description: "AI-controlled point defense turret." },
  { id: "vw-crowd-sonic", name: "Crowd Control Sonic Emitter", category: "exotic", damage: 15, range: 200, cost: 9000, description: "Mass area sonic weapon." },
  { id: "vw-inc-gel", name: "Incendiary Gel Launcher", category: "exotic", damage: 75, range: 150, cost: 11000, description: "Sticky incendiary gel projector." },
  { id: "vw-neural-field", name: "Neural Disruption Field", category: "exotic", damage: 20, range: 100, cost: 22000, description: "Area neural disruption." },
  { id: "vw-seeker-mine", name: "Seeker Mine Launcher", category: "exotic", damage: 90, range: 150, cost: 13000, description: "Self-guiding mine deployment." },
];

export const NUCLEAR_WEAPON_CATEGORIES: Record<string, string> = {
  tactical: "TACTICAL NUCLEAR",
  strategic: "STRATEGIC NUCLEAR",
  experimental_nuclear: "EXPERIMENTAL NUCLEAR",
  exotic_nuclear: "EXOTIC NUCLEAR",
  delivery_platform: "DELIVERY PLATFORMS",
  advanced_concept: "ADVANCED CONCEPTS",
  classified: "CLASSIFIED SYSTEMS",
};

export const NUCLEAR_WEAPONS: NuclearWeaponDef[] = [
  { id: "nw-tactical-bomb", name: "Tactical Nuclear Bomb", category: "tactical", yield: 5, range: 50, cost: 50000, description: "Five kilotons. Battlefield use only — paperwork-wise." },
  { id: "nw-tactical-missile", name: "Tactical Nuclear Missile", category: "tactical", yield: 10, range: 500, cost: 80000, description: "Short-range nuclear-tipped. Launched in minutes. Regretted in decades." },
  { id: "nw-nuclear-shell", name: "Nuclear Artillery Shell", category: "tactical", yield: 1, range: 30, cost: 30000, description: "Nuclear warhead for heavy artillery." },
  { id: "nw-depth-charge", name: "Nuclear Depth Charge", category: "tactical", yield: 5, range: 10, cost: 40000, description: "Underwater nuclear weapon." },
  { id: "nw-demo-charge", name: "Nuclear Demolition Charge", category: "tactical", yield: 2, range: 1, cost: 25000, description: "Emplaced nuclear demolition device." },
  { id: "nw-land-mine", name: "Nuclear Land Mine", category: "tactical", yield: 1, range: 1, cost: 20000, description: "Nuclear-armed land mine." },
  { id: "nw-neutron-bomb", name: "Tactical Neutron Bomb", category: "tactical", yield: 3, range: 40, cost: 60000, description: "Enhanced radiation weapon. Kills crew, preserves equipment." },
  { id: "nw-micro-rocket", name: "Micro Nuclear Rocket", category: "tactical", yield: 0.5, range: 100, cost: 35000, description: "Miniaturized nuclear rocket." },
  { id: "nw-icbm", name: "Intercontinental Nuclear Missile", category: "strategic", yield: 500, range: 10000, cost: 500000, description: "Half a megaton. Crosses oceans in 30 minutes. Ends maps." },
  { id: "nw-sub-missile", name: "Submarine Nuclear Missile", category: "strategic", yield: 300, range: 8000, cost: 450000, description: "Sub-launched. Surfaces. Fires. Vanishes. The coast never sees the boat." },
  { id: "nw-heavy-bomb", name: "Heavy Strategic Nuclear Bomb", category: "strategic", yield: 1000, range: 100, cost: 300000, description: "Maximum-yield strategic nuclear bomb." },
  { id: "nw-hypersonic-nuke", name: "Hypersonic Nuclear Missile", category: "strategic", yield: 200, range: 5000, cost: 600000, description: "Hypersonic delivery impossible to intercept." },
  { id: "nw-orbital-strike", name: "Orbital Nuclear Strike Weapon", category: "strategic", yield: 400, range: 20000, cost: 800000, description: "Space-based nuclear weapon platform." },
  { id: "nw-cruise-nuke", name: "Nuclear Cruise Missile", category: "strategic", yield: 150, range: 3000, cost: 250000, description: "Long-range nuclear cruise missile." },
  { id: "nw-mirv", name: "Multiple Warhead Nuclear Missile", category: "strategic", yield: 800, range: 12000, cost: 700000, description: "One launch. Ten cities scratched off the map." },
  { id: "nw-cobalt-bomb", name: "Cobalt Bomb", category: "experimental_nuclear", yield: 100, range: 50, cost: 200000, description: "Maximizes radioactive contamination." },
  { id: "nw-salted-warhead", name: "Salted Nuclear Warhead", category: "experimental_nuclear", yield: 50, range: 500, cost: 180000, description: "Long-lasting radioactive fallout weapon." },
  { id: "nw-enhanced-rad", name: "Enhanced Radiation Bomb", category: "experimental_nuclear", yield: 20, range: 40, cost: 120000, description: "Maximized radiation, minimized blast." },
  { id: "nw-low-fallout", name: "Low Fallout Tactical Device", category: "experimental_nuclear", yield: 5, range: 200, cost: 90000, description: "Clean nuclear weapon. Minimal contamination." },
  { id: "nw-dirty-warhead", name: "Dirty Nuclear Warhead", category: "experimental_nuclear", yield: 10, range: 300, cost: 70000, description: "Maximizes area contamination." },
  { id: "nw-pulse-bomb", name: "Nuclear Pulse Bomb", category: "exotic_nuclear", yield: 30, range: 100, cost: 150000, description: "EMP-focused nuclear detonation." },
  { id: "nw-plasma-warhead", name: "Plasma Nuclear Warhead", category: "exotic_nuclear", yield: 80, range: 400, cost: 250000, description: "Hybrid plasma-nuclear warhead." },
  { id: "nw-nuclear-emp", name: "Nuclear EMP Weapon", category: "exotic_nuclear", yield: 15, range: 1000, cost: 200000, description: "High-altitude nuclear EMP burst." },
  { id: "nw-fusion-bomb", name: "Fusion Bomb", category: "exotic_nuclear", yield: 500, range: 80, cost: 400000, description: "Pure fusion weapon. No fission trigger." },
  { id: "nw-anti-bunker-nuke", name: "Anti-Bunker Nuclear Warhead", category: "exotic_nuclear", yield: 25, range: 50, cost: 160000, description: "Earth-penetrating nuclear warhead." },
  { id: "nw-torpedo", name: "Nuclear Torpedo", category: "delivery_platform", yield: 20, range: 50, cost: 100000, description: "Nuclear-armed heavy torpedo." },
  { id: "nw-drone-warhead", name: "Nuclear Drone Warhead", category: "delivery_platform", yield: 5, range: 500, cost: 80000, description: "Autonomous nuclear delivery drone." },
  { id: "nw-satellite-weapon", name: "Nuclear Satellite Weapon", category: "delivery_platform", yield: 100, range: 20000, cost: 600000, description: "Orbital nuclear weapon platform." },
  { id: "nw-arty-missile", name: "Nuclear Artillery Missile", category: "delivery_platform", yield: 3, range: 100, cost: 50000, description: "Artillery-launched nuclear projectile." },
  { id: "nw-airburst", name: "Nuclear Airburst Bomb", category: "delivery_platform", yield: 50, range: 60, cost: 120000, description: "Optimized for airburst detonation." },
  { id: "nw-planetary-defense", name: "Planetary Defense Nuclear Missile", category: "advanced_concept", yield: 2000, range: 50000, cost: 1000000, description: "Two megatons. Kept in a silo for a threat that hasn't come yet." },
  { id: "nw-anti-asteroid", name: "Anti-Asteroid Nuclear Warhead", category: "advanced_concept", yield: 1000, range: 100000, cost: 900000, description: "Deep-space asteroid deflection." },
  { id: "nw-cluster-nuke", name: "Nuclear Cluster Missile", category: "advanced_concept", yield: 200, range: 5000, cost: 500000, description: "Disperses multiple nuclear submunitions." },
  { id: "nw-mobile-launcher", name: "Mobile Launcher Nuclear Missile", category: "advanced_concept", yield: 100, range: 3000, cost: 350000, description: "Vehicle-mobile nuclear launch system." },
  { id: "nw-underground-penetrator", name: "Underground Nuclear Penetrator", category: "advanced_concept", yield: 50, range: 200, cost: 200000, description: "Bores deep underground before detonation." },
  { id: "nw-stealth-missile", name: "Stealth Nuclear Missile", category: "classified", yield: 150, range: 4000, cost: 450000, description: "Radar-invisible nuclear delivery system." },
  { id: "nw-autonomous-drone", name: "Autonomous Nuclear Drone", category: "classified", yield: 10, range: 2000, cost: 300000, description: "AI-controlled nuclear strike drone." },
  { id: "nw-reactor-det", name: "Reactor Detonation Weapon", category: "classified", yield: 75, range: 1, cost: 150000, description: "Weaponized reactor meltdown device." },
  { id: "nw-gamma-pulse", name: "Gamma Pulse Nuclear Device", category: "classified", yield: 40, range: 500, cost: 250000, description: "Maximized gamma radiation output." },
  { id: "nw-city-eraser", name: "Strategic City Eraser Warhead", category: "classified", yield: 5000, range: 200, cost: 2000000, description: "Five megatons. Authorization requires three keys. Two of them are missing." },
];

export const ADDITIONAL_AMMO: AmmoDef[] = [
  { id: "standard_ball", name: "Standard Ball Rounds", category: "standard", costPer100: 40, damage_modifier: 1.0, description: "Basic kinetic. The stuff every sidearm eats. Stockpiled by the pallet." },
  { id: "hollowpoint", name: "Hollowpoint Rounds", category: "standard", costPer100: 70, damage_modifier: 1.4, description: "Mushrooms on impact. Hospitals call it the unfixable wound." },
  { id: "rubber_suppression", name: "Rubber Suppression Rounds", category: "standard", costPer100: 30, damage_modifier: 0.3, description: "Non-lethal riot control ammunition." },
  { id: "tracer_rounds", name: "Tracer Rounds", category: "standard", costPer100: 55, damage_modifier: 1.0, description: "Bright orange streak in the dark. Tells the enemy exactly where you are." },
  { id: "high_velocity", name: "High Velocity Rounds", category: "standard", costPer100: 90, damage_modifier: 1.3, description: "Extended range and accuracy." },
  { id: "sonic_shock", name: "Sonic Shock Rounds", category: "special", costPer100: 180, damage_modifier: 1.2, description: "Create concussive blast on impact." },
  { id: "gas_payload", name: "Gas Payload Rounds", category: "chemical", costPer100: 120, damage_modifier: 0.4, description: "Release tear gas or riot chemicals." },
  { id: "cryo_rounds", name: "Cryo Rounds", category: "special", costPer100: 300, damage_modifier: 1.1, description: "Flash-freeze targets briefly." },
  { id: "emp_microburst", name: "EMP Microburst Rounds", category: "energy", costPer100: 400, damage_modifier: 0.5, description: "Disables drones and electronics." },
  { id: "corrosive_rounds", name: "Corrosive Rounds", category: "chemical", costPer100: 200, damage_modifier: 1.5, description: "Damage armor slowly over time." },
  { id: "magnetic_rail_slugs", name: "Magnetic Rail Slugs", category: "special", costPer100: 500, damage_modifier: 2.5, description: "Railgun ammunition. Extreme velocity." },
  { id: "tracking_microchip", name: "Tracking Microchip Rounds", category: "special", costPer100: 350, damage_modifier: 0.8, description: "Embed tracker for surveillance." },
  { id: "hmg_belts", name: "Heavy Machine Gun Belts", category: "standard", costPer100: 100, damage_modifier: 1.2, description: "Sustained fire belt ammunition." },
  { id: "depleted_metal_pen", name: "Depleted Metal Penetrators", category: "armor_piercing", costPer100: 400, damage_modifier: 2.5, description: "Anti-vehicle penetrator rounds." },
  { id: "explosive_cannon", name: "Explosive Cannon Shells", category: "explosive", costPer100: 700, damage_modifier: 2.8, description: "Impact detonation cannon shells." },
  { id: "shrapnel_burst", name: "Shrapnel Burst Shells", category: "explosive", costPer100: 550, damage_modifier: 2.2, description: "Area fragmentation damage." },
  { id: "bunker_breaker", name: "Bunker Breaker Shells", category: "explosive", costPer100: 900, damage_modifier: 3.0, description: "Penetrates fortified structures." },
  { id: "anti_air_flak", name: "Anti-Air Flak Shells", category: "explosive", costPer100: 450, damage_modifier: 2.0, description: "Proximity fuse anti-aircraft." },
  { id: "thermobaric_shell", name: "Thermobaric Shells", category: "explosive", costPer100: 800, damage_modifier: 3.2, description: "Fuel-air explosion warhead." },
  { id: "smart_targeting", name: "Smart Targeting Shells", category: "special", costPer100: 1000, damage_modifier: 2.5, description: "Guided artillery ammunition." },
  { id: "emp_artillery", name: "EMP Artillery Shells", category: "energy", costPer100: 700, damage_modifier: 0.5, description: "Electronic disruption blast." },
  { id: "riot_gas_mortar", name: "Riot Gas Mortar Shells", category: "chemical", costPer100: 150, damage_modifier: 0.3, description: "Chemical dispersal mortar rounds." },
  { id: "he_rocket_ammo", name: "Standard HE Rockets", category: "explosive", costPer100: 600, damage_modifier: 2.5, description: "Basic high-explosive rockets." },
  { id: "at_rocket_ammo", name: "Anti-Tank Rockets", category: "armor_piercing", costPer100: 800, damage_modifier: 3.0, description: "Shaped-charge anti-armor rockets." },
  { id: "cluster_rocket_ammo", name: "Cluster Rockets", category: "explosive", costPer100: 1200, damage_modifier: 3.5, description: "Multi-bomblet dispersal rockets." },
  { id: "incendiary_rocket_ammo", name: "Incendiary Rockets", category: "incendiary", costPer100: 700, damage_modifier: 2.0, description: "Creates large fire zones." },
  { id: "smoke_rocket_ammo", name: "Smoke Screen Rockets", category: "chemical", costPer100: 200, damage_modifier: 0.0, description: "Concealment smoke rockets." },
  { id: "breaching_rocket_ammo", name: "Breaching Rockets", category: "explosive", costPer100: 900, damage_modifier: 3.2, description: "Wall destruction rockets." },
  { id: "nano_swarm_rocket", name: "Nano Swarm Rockets", category: "special", costPer100: 2000, damage_modifier: 2.0, description: "Releases micro attack drones." },
  { id: "radiation_rocket_ammo", name: "Radiation Rockets", category: "chemical", costPer100: 1500, damage_modifier: 1.5, description: "Creates contaminated zones." },
  { id: "sam_ammo", name: "Surface-to-Air Missiles", category: "missile", costPer100: 1500, damage_modifier: 2.5, description: "Anti-air defense missiles." },
  { id: "atgm_ammo", name: "Anti-Tank Guided Missiles", category: "missile", costPer100: 2000, damage_modifier: 3.5, description: "Precision vehicle killer." },
  { id: "cruise_missile_ammo", name: "Cruise Missile Propellant", category: "missile", costPer100: 3000, damage_modifier: 4.0, description: "Long range precision strike." },
  { id: "bunker_buster_ammo", name: "Bunker Buster Missiles", category: "missile", costPer100: 2500, damage_modifier: 3.5, description: "Penetrates underground targets." },
  { id: "emp_missile_ammo", name: "EMP Missile Warheads", category: "missile", costPer100: 2000, damage_modifier: 0.5, description: "Citywide electronic blackout." },
  { id: "hypersonic_ammo", name: "Hypersonic Missile Fuel", category: "missile", costPer100: 5000, damage_modifier: 5.0, description: "Extreme speed strike." },
  { id: "drone_carrier_ammo", name: "Drone Carrier Missiles", category: "missile", costPer100: 3500, damage_modifier: 2.0, description: "Deploys multiple attack drones." },
  { id: "seeker_missile_ammo", name: "Seeker Missile Guidance", category: "missile", costPer100: 2500, damage_modifier: 3.0, description: "Autonomous target hunting." },
  { id: "orbital_strike_ammo", name: "Orbital Strike Propellant", category: "missile", costPer100: 8000, damage_modifier: 8.0, description: "Space platform launch fuel." },
];
