// AUTO-GENERATED by .local/remap_locations.mjs — do not hand-edit.
// All 216 location positions placed onto the North American landmass.
// Coordinate system: WORLD_MAP_BOUNDS 0..1000, aligned 1:1 with the NA coastline overlay.
// Region hint after each entry comes from description keyword classification.
//
// STARTING_REGIONS spawn coordinates intentionally do NOT live here — they are
// authored on each STARTING_REGIONS entry as playerX/playerY (see worldMap.ts)
// and consumed directly by the new-game flow. The map validator pulls those
// coordinates straight from STARTING_REGIONS so land-mask and lore checks run
// against the canonical spawn position. Don't add region ids to this map.
export const LOCATION_POSITIONS: Record<string, { x: number; y: number }> = {
  "megacity": { x: 472, y: 406 }, // red mesa site
  "nova-pacifica": { x: 362, y: 334 }, // california
  "iron-khanate": { x: 384, y: 354 }, // california
  "helix-commune": { x: 355, y: 271 }, // pnw
  "aureus-dominion": { x: 701, y: 288 }, // northeast
  "verdant-enclave": { x: 620, y: 511 }, // centam
  "null-zone-confederacy": { x: 514, y: 317 }, // plains
  "ghost-meridian": { x: 463, y: 346 }, // southwest
  "crimson-reach": { x: 521, y: 300 }, // former city-core site
  "silent-ark": { x: 535, y: 138 }, // arctic-can
  "beneath": { x: 592, y: 306 }, // midwest
  "iron-armada": { x: 767, y: 267 }, // maritimes
  "terminus-prime": { x: 670, y: 540 }, // centam
  "new-olympus": { x: 451, y: 284 }, // rockies
  "panopticon": { x: 549, y: 121 }, // arctic-can
  "ashfall-dominion": { x: 390, y: 268 }, // pnw
  "the-recursion": { x: 818, y: 254 }, // maritimes
  "dusthaven": { x: 520, y: 458 }, // mexico-n
  "irongate": { x: 434, y: 274 }, // rockies
  "port-sulphur": { x: 697, y: 305 }, // northeast
  "new-eden": { x: 444, y: 334 }, // rockies
  "scrapyard-city": { x: 436, y: 352 }, // southwest
  "blackridge": { x: 630, y: 284 }, // midwest
  "pilgrim-station": { x: 417, y: 324 }, // southwest
  "mireholm": { x: 537, y: 390 }, // gulf
  "vault-town": { x: 500, y: 276 }, // plains
  "ember-falls": { x: 355, y: 291 }, // pnw
  "rustfield": { x: 617, y: 315 }, // midwest
  "chem-springs": { x: 632, y: 358 }, // southeast
  "fort-stern": { x: 510, y: 380 }, // plains
  "market-crossing": { x: 645, y: 298 }, // great-lakes
  "silo-nine": { x: 496, y: 300 }, // plains
  "candlewick": { x: 560, y: 370 }, // midwest
  "ashmouth": { x: 374, y: 277 }, // pnw
  "scaffold": { x: 666, y: 355 }, // southeast
  "greywater": { x: 575, y: 281 }, // midwest
  "burnside": { x: 675, y: 332 }, // midwest
  "ghost-relay": { x: 477, y: 332 }, // southwest
  "sunken-arcadia": { x: 587, y: 387 }, // gulf
  "the-crucible": { x: 459, y: 260 }, // rockies
  "sky-haven": { x: 607, y: 372 }, // southeast
  "echo-chamber": { x: 552, y: 253 }, // plains
  "black-atlantic-rig": { x: 727, y: 283 }, // northeast
  "cathedral-of-rust": { x: 706, y: 268 }, // northeast
  "monument-of-compliance": { x: 416, y: 262 }, // rockies
  "sector-zero-crater": { x: 634, y: 260 }, // great-lakes
  "undercity-market": { x: 580, y: 334 }, // midwest
  "the-perimeter": { x: 522, y: 334 }, // plains
  "dead-zone-seven": { x: 470, y: 300 }, // rockies
  "sky-needle": { x: 409, y: 288 }, // rockies
  "gene-vault-prime": { x: 460, y: 360 }, // plains
  "the-glass-desert": { x: 415, y: 350 }, // southwest
  "bone-road": { x: 555, y: 359 }, // plains
  "signal-grave": { x: 520, y: 410 }, // midwest
  "chrome-cathedral": { x: 530, y: 352 }, // plains
  "fungal-deeps": { x: 607, y: 331 }, // midwest
  "iron-garden": { x: 340, y: 249 }, // pnw
  "echo-bunker": { x: 542, y: 269 }, // plains
  "the-screaming-mesa": { x: 450, y: 378 }, // southwest
  "the-pit": { x: 445, y: 312 }, // rockies
  "kharkov-line": { x: 660, y: 210 }, // midwest
  "old-highway-99": { x: 632, y: 334 }, // southeast
  "reactor-seven": { x: 645, y: 371 }, // southeast
  "the-broadcast-tower": { x: 687, y: 308 }, // northeast
  "mass-grave-delta": { x: 558, y: 382 }, // gulf
  "trade-nexus-alpha": { x: 675, y: 315 }, // midwest
  "frozen-circuit": { x: 491, y: 116 }, // arctic-can
  "abyssal-vent": { x: 663, y: 310 }, // northeast
  "the-obelisk-field": { x: 612, y: 297 }, // midwest
  "graveyard-orbit": { x: 509, y: 426 }, // mexico-n
  "the-vermillion-lake": { x: 508, y: 360 }, // plains
  "the-hanging-prison": { x: 472, y: 388 }, // mexico-n
  "worm-sign": { x: 530, y: 240 }, // midwest
  "tribunal-ruins": { x: 547, y: 314 }, // plains
  "the-wailing-fields": { x: 570, y: 245 }, // plains
  "the-spire-of-names": { x: 487, y: 434 }, // mexico-n
  "null-zone-bazaar": { x: 745, y: 253 }, // maritimes
  "the-memory-archive": { x: 584, y: 265 }, // midwest
  "petrified-army": { x: 497, y: 141 }, // arctic-can
  "anchor-point": { x: 584, y: 270 }, // midwest
  "flesh-market": { x: 473, y: 276 }, // rockies
  "the-quiet-zone": { x: 490, y: 353 }, // plains
  "the-cradle": { x: 620, y: 235 }, // plains
  "refinery-omega": { x: 640, y: 245 }, // midwest
  "clock-tower": { x: 787, y: 240 }, // maritimes
  "the-parliament-of-crows": { x: 653, y: 339 }, // southeast
  "impact-site-phi": { x: 812, y: 230 }, // maritimes
  "data-cemetery": { x: 664, y: 259 }, // great-lakes
  "the-conductor": { x: 411, y: 307 }, // rockies
  "blood-falls": { x: 436, y: 253 }, // rockies
  "the-last-library": { x: 615, y: 300 }, // midwest
  "mirror-lake": { x: 715, y: 250 }, // great-lakes
  "the-furnace": { x: 489, y: 414 }, // mexico-n
  "hyena-highway": { x: 495, y: 322 }, // plains
  "bone-road-terminus": { x: 647, y: 275 }, // great-lakes
  "chrome-boneyard": { x: 424, y: 369 }, // southwest
  "serpent-canyon": { x: 470, y: 365 }, // southwest
  "king-cog-foundry": { x: 517, y: 259 }, // plains
  "ironclad-garrison": { x: 520, y: 365 }, // plains
  "ash-caldera": { x: 380, y: 251 }, // pnw
  "obsidian-labs": { x: 589, y: 289 }, // midwest
  "iron-wolves-compound": { x: 518, y: 358 }, // plains
  "throne-of-steel": { x: 533, y: 252 }, // plains
  "hunger-domain": { x: 490, y: 380 }, // southwest
  "machine-temple": { x: 570, y: 365 }, // midwest
  "golden-vault": { x: 620, y: 245 }, // midwest
  "reactor-throne-complex": { x: 519, y: 343 }, // plains
  "knight-fortress": { x: 420, y: 405 }, // southwest
  "dredge-port": { x: 619, y: 386 }, // gulf
  "thornwall": { x: 491, y: 359 }, // plains
  "copper-hills": { x: 460, y: 323 }, // rockies
  "relay-station-12": { x: 837, y: 250 }, // maritimes
  "glasstown": { x: 601, y: 317 }, // midwest
  "piston-camp": { x: 656, y: 270 }, // great-lakes
  "candleholm": { x: 682, y: 257 }, // great-lakes
  "bunker-84": { x: 524, y: 307 }, // plains
  "rust-republic": { x: 431, y: 313 }, // rockies
  "sky-citadel": { x: 460, y: 235 }, // plains
  "the-drowning-road": { x: 532, y: 414 }, // gulf
  "satellite-graveyard": { x: 444, y: 301 }, // rockies
  "old-parliament": { x: 706, y: 306 }, // northeast
  "vault-zero": { x: 501, y: 288 }, // plains
  "the-broadcast": { x: 619, y: 274 }, // great-lakes
  "acid-lake": { x: 532, y: 285 }, // plains
  "the-antenna-farm": { x: 585, y: 320 }, // midwest
  "the-wall-of-names": { x: 515, y: 285 }, // rockies
  "reactor-twelve": { x: 454, y: 414 }, // mexico-n
  "the-chorus": { x: 425, y: 264 }, // rockies
  "dead-satellite-field": { x: 727, y: 265 }, // northeast
  "the-great-scar": { x: 592, y: 315 }, // midwest
  "bunker-city": { x: 572, y: 329 }, // midwest
  "the-hanging-gardens": { x: 483, y: 273 }, // rockies
  "engine-block": { x: 789, y: 271 }, // maritimes
  "quarantine-ring": { x: 726, y: 301 }, // northeast
  "the-pillar": { x: 681, y: 341 }, // southeast
  "mass-grave-17": { x: 670, y: 290 }, // northeast
  "solar-array-east": { x: 700, y: 200 }, // midwest
  "the-maze": { x: 563, y: 275 }, // midwest
  "weather-station-prime": { x: 405, y: 230 }, // rockies
  "the-nursery": { x: 570, y: 230 }, // midwest
  "rail-junction-9": { x: 412, y: 291 }, // rockies
  "static-forest": { x: 360, y: 245 }, // pnw
  "the-eye": { x: 629, y: 278 }, // great-lakes
  "pipeline-alpha": { x: 654, y: 282 }, // great-lakes
  "the-threshold": { x: 480, y: 305 }, // plains
  "overflow-basin": { x: 756, y: 239 }, // maritimes
  "the-museum": { x: 612, y: 354 }, // southeast
  "crystal-caves": { x: 556, y: 327 }, // midwest
  "the-orphanage": { x: 660, y: 325 }, // great-lakes
  "meridian-bridge": { x: 479, y: 264 }, // rockies
  "the-cage": { x: 560, y: 290 }, // midwest
  "salt-flats": { x: 410, y: 382 }, // southwest
  "the-stockpile": { x: 621, y: 268 }, // midwest
  "whalefall": { x: 502, y: 396 }, // mexico-n
  "the-grid": { x: 637, y: 347 }, // southeast
  "gaslight-alley": { x: 605, y: 277 }, // midwest
  "dam-of-saints": { x: 650, y: 400 }, // great-lakes
  "the-wound": { x: 400, y: 320 }, // midwest
  "echo-canyon": { x: 433, y: 268 }, // rockies
  "the-dock-of-ghosts": { x: 392, y: 359 }, // california
  "spore-field": { x: 380, y: 296 }, // pnw
  "the-bridge-to-nowhere": { x: 468, y: 428 }, // mexico-n
  "cinder-heap": { x: 570, y: 308 }, // midwest
  "harbor-of-teeth": { x: 718, y: 287 }, // northeast
  "monument-zero": { x: 748, y: 275 }, // maritimes
  "rot-garden": { x: 369, y: 267 }, // pnw
  "iron-curtain-wall": { x: 600, y: 220 }, // midwest
  "the-apothecary": { x: 640, y: 316 }, // midwest
  "the-lighthouse": { x: 748, y: 266 }, // maritimes
  "hollow-mountain": { x: 441, y: 255 }, // rockies
  "train-graveyard": { x: 762, y: 273 }, // maritimes
  "the-foundry": { x: 431, y: 304 }, // rockies
  "rn-iron-gulch": { x: 687, y: 302 }, // northeast
  "rn-blackwater-seep": { x: 684, y: 276 }, // northeast
  "rn-verdant-hollow": { x: 541, y: 330 }, // plains
  "rn-rust-canyon": { x: 439, y: 297 }, // rockies
  "rn-staghorn-wastes": { x: 470, y: 320 }, // plains
  "rn-aquifer-seven": { x: 585, y: 325 }, // midwest
  "rn-datacore-crash": { x: 490, y: 335 }, // plains
  "rn-spore-caves": { x: 614, y: 279 }, // great-lakes
  "rn-pipeline-junction": { x: 772, y: 229 }, // maritimes
  "rn-boneyard-flats": { x: 504, y: 338 }, // plains
  "rn-crystal-ridge": { x: 441, y: 262 }, // rockies
  "rn-marshbloom-delta": { x: 543, y: 383 }, // gulf
  "rn-silent-springs": { x: 544, y: 307 }, // plains
  "rn-predator-vale": { x: 441, y: 279 }, // rockies
  "rn-bunker-19-wreck": { x: 606, y: 380 }, // gulf
  "rn-glowing-basin": { x: 592, y: 349 }, // midwest
  "rn-copper-teeth": { x: 545, y: 345 }, // rockies
  "rn-razorback-range": { x: 444, y: 433 }, // mexico-n
  "rn-magma-vents": { x: 516, y: 266 }, // plains
  "rn-fossil-quarry": { x: 480, y: 286 }, // rockies
  "rn-windmill-graveyard": { x: 498, y: 285 }, // plains
  "rn-thunder-plains": { x: 492, y: 272 }, // plains
  "rn-mistveil-springs": { x: 378, y: 292 }, // pnw
  "rn-orbital-debris-field": { x: 734, y: 272 }, // northeast
  "rn-fungal-grottos": { x: 686, y: 266 }, // northeast
  "rn-greenhouse-ruins": { x: 596, y: 327 }, // midwest
  "rn-uranium-pit": { x: 426, y: 325 }, // rockies
  "rn-tar-pits-collective": { x: 757, y: 262 }, // maritimes
  "rn-saltmarsh-shallows": { x: 628, y: 302 }, // midwest
  "rn-titan-bones": { x: 670, y: 262 }, // great-lakes
  "rn-tidewreck-shoals": { x: 783, y: 290 }, // maritimes coast
  "rn-saltworks-pans": { x: 373, y: 380 }, // pacific south
  "rn-blackreef-platform": { x: 622, y: 410 }, // gulf offshore
  "rn-leviathan-grounds": { x: 790, y: 250 }, // north atlantic
  "rn-glacier-melt": { x: 368, y: 252 }, // pnw alpine
  "rn-cistern-vault": { x: 618, y: 342 }, // midwest
  "rn-server-sepulchre": { x: 712, y: 318 }, // northeast wasteland
  "rn-trauma-ward-7": { x: 558, y: 296 }, // megacity periphery
  "rn-orbital-anchor": { x: 648, y: 472 }, // equatorial wastes
  "rn-munitions-vault": { x: 500, y: 250 }, // northern plains
  "rn-pipeline-graveyard": { x: 532, y: 358 }, // southern plains
  "rn-pharma-tomb": { x: 442, y: 232 }, // northern rockies
  "cheyenne-mountain": { x: 455, y: 304 }, // colorado front range
  "grand-canyon": { x: 432, y: 320 }, // southwest plateau
};
