// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/MegacityTrailer.tsx": () => import("../components/mockups/MegacityTrailer.tsx"),
  "./components/mockups/font-comparison/FontComparison.tsx": () => import("../components/mockups/font-comparison/FontComparison.tsx"),
  "./components/mockups/steam-card/BuyMeTea.tsx": () => import("../components/mockups/steam-card/BuyMeTea.tsx"),
  "./components/mockups/store-copy/StoreCopy.tsx": () => import("../components/mockups/store-copy/StoreCopy.tsx"),
  "./components/mockups/tactical-sidecar/InContext.tsx": () => import("../components/mockups/tactical-sidecar/InContext.tsx"),
  "./components/mockups/tactical-sidecar/TacticalSidecar.tsx": () => import("../components/mockups/tactical-sidecar/TacticalSidecar.tsx"),
  "./components/mockups/world-map/AmericasMap.tsx": () => import("../components/mockups/world-map/AmericasMap.tsx"),
  "./components/mockups/world-map/EnhancedMap.tsx": () => import("../components/mockups/world-map/EnhancedMap.tsx"),
  "./components/mockups/world-map/PencilMap.tsx": () => import("../components/mockups/world-map/PencilMap.tsx")
};
