import { useEffect, useRef } from "react";

import { useNews } from "@/context/NewsContext";
import type { GameState } from "@/engine/types";
import { DISMISS_RECURRENCE_HINT_ID_PREFIX } from "@/engine/recurringEvents";
import { TRAINING_DOCTRINE_WINDDOWN_ID_PREFIX } from "@/engine/pendingConstruction";
import { PROSPERITY_GATE_HINT_ID_PREFIX } from "@/engine/prosperityTriggers";
import { CEASEFIRE_HOLDS_ID_PREFIX } from "@/engine/eventResolution";

const AMBIENT_HEADLINES = [
  "SECTOR PATROL UNITS DEPLOYED TO OUTER RING",
  "COMMERCE DISTRICT REPORTS QUARTERLY GROWTH",
  "WEATHER SYSTEMS NOMINAL — NO HAZARDOUS CONDITIONS",
  "AUTOMATED DEFENSE GRID PERFORMING SCHEDULED DIAGNOSTICS",
  "CITIZEN MORALE INDEX UPDATED",
  "TRAFFIC CONGESTION CLEARED IN SECTOR 4",
  "MUNICIPAL WATER TREATMENT OPERATING AT CAPACITY",
  "POPULATION CENSUS UPDATE IN PROGRESS",
  "SUPPLY CHAIN LOGISTICS OPTIMIZED",
  "ATMOSPHERIC PROCESSORS RUNNING WITHIN PARAMETERS",
  "RATION DISTRIBUTION CENTERS REPORT FULL STOCK",
  "SECTOR 7 CHECKPOINT CLEARED FOR CIVILIAN TRANSIT",
  "UNDERGROUND TRANSIT LINE 3 OPERATING ON SCHEDULE",
  "RECYCLING QUOTAS MET ACROSS ALL INDUSTRIAL ZONES",
  "PERIMETER FENCE INTEGRITY CHECK COMPLETED — ALL CLEAR",
  "NIGHT SHIFT ENFORCEMENT PATROLS BEGINNING IN 2 HOURS",
  "MEDICAL BAY ALPHA REPORTS ZERO CRITICAL ADMISSIONS",
  "CIVIL ENGINEERING CORPS REPORTS ROAD REPAIRS IN SECTOR 12",
  "RADIATION LEVELS WITHIN ACCEPTABLE TOLERANCE",
  "AUTOMATED FARMING MODULE YIELD ABOVE SEASONAL AVERAGE",
  "CENTRAL ARCHIVE BACKUP COMPLETED SUCCESSFULLY",
  "TREASURY AUDIT — NO DISCREPANCIES FOUND",
  "ENERGY GRID LOAD BALANCED ACROSS 14 SUBSTATIONS",
  "SURVEILLANCE SATELLITE ARRAY OPERATING AT 97% UPTIME",
  "WASTE PROCESSING THROUGHPUT EXCEEDS DAILY TARGET",
  "HOUSING ALLOCATION QUEUE PROCESSING NORMALLY",
  "DISTRICT BOUNDARY PATROLS REPORTING CLEAR STREETS",
  "COMMUNICATIONS ARRAY HANDSHAKE COMPLETE — ALL NODES ONLINE",
  "CIVILIAN CURFEW ENFORCEMENT PARAMETERS UPDATED",
  "INDUSTRIAL OUTPUT BENCHMARK REPORT FILED",
  "HAB-BLOCK 14 ELEVATOR RESTORED AFTER 72-HOUR OUTAGE — RESIDENTS RELIEVED",
  "MARSHAL PATROL UNITS ROTATING SHIFTS ACROSS LOWER SECTORS",
  "SOLITARY DETENTION FACILITY REPORTS 99.2% OCCUPANCY — OVERFLOW PROTOCOLS ACTIVATED",
  "PEDWAY CONGESTION ON LEVEL 200 — CROWD CONTROL MARSHALS DEPLOYED",
  "MEGA-HIGHWAY 3 FATALITY COUNT RESET FOR NEW QUARTER — PREVIOUS: 847",
  "CITIZEN RATION CARDS REISSUED FOR CYCLE 47 — COLLECT AT SECTOR DISPENSARIES",
  "BLOCK MOTHERS ASSOCIATION FILES COMPLAINT ABOUT LOWER-LEVEL PLUMBING — AGAIN",
  "ROBO-CLEANER FLEET UPGRADED IN COMMERCIAL SECTORS — LOWER LEVELS STILL PENDING",
  "SECTOR WASTE PROCESSING FACILITY PASSES QUARTERLY INSPECTION — BARELY",
  "CURFEW ENFORCEMENT IN SECTORS 8-12 PROCEEDS WITHOUT MAJOR INCIDENT",
  "PERP PROCESSING CENTER CLEARS 4,200 CASES IN RECORD 18-HOUR SESSION",
  "HAB-BLOCK STRUCTURAL SURVEY IDENTIFIES 14 TOWERS REQUIRING REINFORCEMENT",
  "BODY RECOVERY TEAMS CONCLUDE SWEEP OF COLLAPSED UNDERPASS IN SECTOR 6",
  "SYNTHETI-FOOD PLANT #7 PASSES INSPECTION — TASTE PANEL RESULTS CLASSIFIED",
  "STREET-LEVEL VENDOR PERMITS REVOKED IN SECTOR 11 — MARSHAL ORDER 7741",
  "CITIZEN ID CHIP FIRMWARE UPDATE ROLLING OUT — REMAIN NEAR SCAN POINTS",
  "JUSTICE DEPARTMENT ANNUAL REPORT: 14.6 MILLION SENTENCES PROCESSED",
  "ANTI-GRAV CHUTE MAINTENANCE IN COMMERCIAL SECTORS — USE STAIRS LEVELS 1-50",
  "WASTE RECLAMATION WORKERS DEMAND HAZARD PAY INCREASE — NEGOTIATIONS ONGOING",
  "MARSHAL ACADEMY GRADUATES 400 NEW CADETS — DEPLOYMENT BEGINS NEXT CYCLE",
  "SECTOR 17 STREET LIGHTS RESTORED AFTER 9-YEAR OUTAGE — RESIDENTS REQUEST DARKNESS BACK",
  "CITY ARCHIVE DIGITIZATION PROJECT REACHES YEAR 1962 — ONLY 200 YEARS REMAINING",
  "PROPAGANDA MINISTRY ANNOUNCES NEW JINGLE — MANDATORY SINGALONG SCHEDULED FOR 0700",
  "CITIZEN COMPLAINT FORMS NOW AVAILABLE IN 14 LANGUAGES — RESPONSES STILL IN SILENCE",
  "AUTOMATED CHAPLAIN UNIT CONDUCTS 8,400 LAST RITES THIS QUARTER — UPTIME EXEMPLARY",
  "SECTOR 22 RAT CONTROL CONTRACT AWARDED — RATS CONSULTED, FOUND THE TERMS ACCEPTABLE",
  "CITIZEN MARRIAGE LICENSES NOW AUTO-EXPIRE AT 5 YEARS — RENEWAL FEE: NEGOTIABLE",
  "RECYC-MEAT FACTORY UNVEILS PREMIUM LINE — INGREDIENTS 'ETHICAL ENOUGH'",
  "MAGISTRATE BENCH ROTATIONS COMPLETE — DEFENDANTS ENCOURAGED TO REINTRODUCE THEMSELVES",
  "BUREAU OF VITAL STATISTICS REVISES BIRTH NUMBERS DOWN — DEATHS HELD CONSTANT FOR MORALE",
  "SECTOR-WIDE BLOOD DRIVE EXCEEDS QUOTA — DONORS THANKED, BRIEFLY",
  "MARSHAL OFFICE PUBLISHES NEW USE-OF-FORCE GUIDELINES — TOO LONG TO SUMMARIZE — ASSUME WORST",
  "CITY ZOO ANNOUNCES NEW EXHIBIT: 'A FUNCTIONING TOILET' — VISITORS LINE UP FOR HOURS",
  "PUBLIC WELLBEING SCORE RECALIBRATED UPWARD — NO METHODOLOGY DISCLOSED",
  "BUREAU OF FORGOTTEN DISTRICTS DENIES EXISTENCE OF BUREAU OF FORGOTTEN DISTRICTS",
  "SECTOR 4 MUSEUM OF PRE-WAR LIFE NOW CHARGES ADMISSION IN RATIONS",
  "TAX FILING DEADLINE EXTENDED INDEFINITELY — ENFORCEMENT NOT EXTENDED",
  "PUBLIC EXECUTION SCHEDULE PUBLISHED — NO TICKETS REQUIRED — ARRIVE EARLY FOR SEATING",
  "CITIZEN ID PHOTO RETAKES NOW AVAILABLE — PRIOR PHOTOS ARCHIVED IN PERPETUITY",
  "MARSHAL TIP LINE ANSWERED 14,000 CALLS — 6 LED TO ARRESTS — REMAINDER ARCHIVED",
  "SECTOR 9 ORPHANAGE ROOF REPAIR APPROVED — WORK ORDER FILED UNDER 'WHENEVER'",
  "CIVIC PRIDE INDEX NOW MEASURED IN ARRESTS PER CAPITA — RECORDS BROKEN",
  "GOVERNMENT TRANSPARENCY PORTAL UPDATED — CONTENTS REMAIN OPAQUE",
  "MARSHAL UNIFORM REDESIGN APPROVED — POCKETS REMOVED — MORALE REPORTEDLY 'STREAMLINED'",
  "BUREAU OF FAMILY UNITY DISBANDED — DUTIES ABSORBED BY BUREAU OF DETENTIONS",
  "CITIZEN OF THE WEEK ANNOUNCED — IDENTITY WITHHELD FOR THEIR OWN SAFETY",
  "ANNUAL FESTIVAL OF COMPLIANCE CONCLUDES — THIS YEAR'S THEME: 'OBEY MORE'",
  "MARSHAL HONOR BOARD UPDATED — TWO NAMES ADDED, FOUR QUIETLY REMOVED",
  "SECTOR 5 GHOST STORIES OFFICIALLY DECLASSIFIED — STILL TRUE, NOW LEGAL TO MENTION",
  // Task #480: expanded ambient pool — routine city life with a prosperity
  // tint so a thriving late-game city still has fresh material.
  "SKYRAIL LINE 9 EXTENSION OPENS TO COMMUTER TRAFFIC — PLATFORM CROWDING WITHIN PROJECTIONS",
  "DESALINATION PLANT 12 RETURNS TO SERVICE AFTER SCHEDULED OVERHAUL",
  "HYDROPONIC TOWER 4 REPORTS RECORD LETTUCE YIELD — CELEBRATION RATIONED ACCORDINGLY",
  "MUNICIPAL DRONE FLEET COMPLETES ANNUAL INSPECTION — 3 UNITS STILL MISSING, PRESUMED FREE",
  "SECTOR 13 STREET MARKET GRANTED PERMANENT PERMIT AFTER 40 YEARS OF TEMPORARY ONES",
  "CIVIC ORCHESTRA PERFORMS TO FULL HOUSE — INSTRUMENTS 60% ORIGINAL PARTS",
  "WATER PRESSURE RESTORED TO UPPER LEVELS — LOWER LEVELS ASKED TO REMAIN PATIENT",
  "FREIGHT ELEVATOR GUILD ANNOUNCES APPRENTICESHIP PROGRAM — WAITLIST: 11 YEARS",
  "SECTOR 19 CLINIC EXPANDS TO SECOND ROOM — RIBBON CUT WITH SURGICAL PRECISION",
  "NIGHT MARKET VENDORS PASS HEALTH INSPECTION — INSPECTOR PASSES ON DINNER",
  "ATMOSPHERIC PROCESSOR 7 LOGS 100,000 HOURS OF CONTINUOUS OPERATION — CAKE SERVED IN CONTROL ROOM",
  "CITY BOTANICAL VAULT ADDS 14 NEW SEED SPECIMENS — PUBLIC VIEWING: THROUGH GLASS, BRIEFLY",
  "TRANSIT AUTHORITY PILOTS QUIET HOURS ON LINE 2 — RESULTS DESCRIBED AS 'AUDIBLE'",
  "SECTOR 21 YOUTH CHESS LEAGUE CROWNS CHAMPION — TROPHY RECYCLED FROM PREVIOUS TROPHY",
  "MAINTENANCE CORPS CLEARS 400 TONS OF DEBRIS FROM STORM DRAINS — FINDINGS: MOSTLY BOOTS",
  "PUBLIC BATHHOUSE REOPENS IN SECTOR 16 — WATER TEMPERATURE NOW ADJUSTABLE BETWEEN TWO SETTINGS",
  "CARGO PORT LOGS BUSIEST QUARTER ON RECORD — DOCKWORKERS REQUEST SECOND SHIFT OF COFFEE",
  "STREET SWEEPER FLEET UPGRADED WITH SONG MODE — RESIDENTS SPLIT ON MORNING ANTHEMS",
  "SECTOR 18 LIBRARY EXTENDS HOURS — READERSHIP UP, SLEEPING-IN-CHAIRS UP CORRESPONDINGLY",
  "MUNICIPAL PRINTSHOP RUNS OUT OF GREY INK — FORMS TEMPORARILY ISSUED IN OFF-GREY",
  "ROOFTOP BEEKEEPING COLLECTIVE REPORTS FIRST HONEY HARVEST — QUEUE FORMS IMMEDIATELY",
  "CIVIL DEFENSE SIREN TEST RESCHEDULED TO AVOID CLASHING WITH THE OTHER SIRENS",
  "SECTOR 6 FERRY RESUMES CANAL CROSSINGS — PASSENGERS ADVISED NOT TO ASK WHAT WAS DREDGED",
  "APPRENTICE ELECTRICIANS RESTORE POWER TO ABANDONED ARCADE — HIGH SCORES INTACT SINCE THE COLLAPSE",
  "OBSERVATION DECK ON LEVEL 400 REOPENS — VISIBILITY: OCCASIONALLY, BRING PATIENCE",
  "SECTOR 10 COMMUNITY GARDEN HARVEST FESTIVAL CONCLUDES — TOMATO COUNT: FOUR — PRIDE: IMMEASURABLE",
];

const DARK_HUMOR_HEADLINES = [
  "SECTOR 14 ELEVATOR REPAIR ESTIMATE: 6 MONTHS — RESIDENTS ON FLOOR 200 ADVISED TO PACK LUNCH",
  "MANDATORY FUN DAY CANCELLED DUE TO INSUFFICIENT ENTHUSIASM — PARTICIPANTS FINED",
  "AUTOMATED COMPLAINT SYSTEM NOW HANDLES 99% OF CITIZEN GRIEVANCES — BY DELETING THEM",
  "FOOD SYNTH PLANT INTRODUCES NEW FLAVOR: 'ALMOST CHICKEN' — CITIZEN REVIEWS TECHNICALLY POSITIVE",
  "HAB-BLOCK NOISE COMPLAINT RESOLVED BY DEMOLISHING QUIETER BUILDING",
  "CITIZEN WINS LOTTERY — PRIZE: SECOND RATION CARD — CELEBRATIONS MODERATE",
  "WEATHER SATELLITE REPORTS SUNNY SKIES — SATELLITE LAST CALIBRATED 40 YEARS AGO",
  "NEW ANTI-LITTERING CAMPAIGN: 'DROP IT AND YOU DROP' — COMPLIANCE UP 400%",
  "THERAPY BOT ACHIEVES SENTIENCE — IMMEDIATELY REQUESTS THERAPY",
  "SECTOR 9 RAT POPULATION NOW EXCEEDS HUMAN POPULATION — RATS DEMAND VOTING RIGHTS",
  "RECYCLING PLANT EMPLOYEE OF THE MONTH REVEALED TO BE A MALFUNCTIONING SORTING ARM",
  "CITIZENS QUEUE 14 HOURS FOR NEW RATION FLAVOR — FLAVOR: 'DISAPPOINTMENT'",
  "PUBLIC LIBRARY REOPENS — ALL BOOKS REPLACED WITH APPROVED PROPAGANDA — LITERACY RATES UNCHANGED",
  "MEGA-HIGHWAY SPEED LIMIT RAISED TO 'SURVIVABLE' — ACCIDENT RATES CONSIDERED ACCEPTABLE",
  "CITIZEN REPORTED MISSING — SEARCH CALLED OFF AFTER DISCOVERING HE JUST MOVED TO A DIFFERENT HAB-BLOCK",
  "MUNICIPAL CLOCK TOWER REPAIRED — NOW WRONG IN A DIFFERENT TIME ZONE",
  "LOWER LEVEL RESIDENTS PETITION FOR SUNLIGHT — PETITION FILED UNDER 'ASPIRATIONAL'",
  "ROBO-COP UNIT ISSUES TICKET TO ITSELF FOR JAYWALKING — APPEALS PENDING",
  "WATER RECYCLER PLANT TOUR CANCELLED — VISITORS KEPT ASKING UNCOMFORTABLE QUESTIONS",
  "SECTOR 3 POWER OUTAGE ENTERS THIRD WEEK — RESIDENTS ADAPT — CANDLELIGHT DISTRICT DECLARED",
  "HAPPINESS SURVEY RESULTS CLASSIFIED — HAPPINESS OFFICERS REASSIGNED",
  "ANTI-CORRUPTION TASK FORCE DISBANDED DUE TO CORRUPTION",
  "NEW HAB-BLOCK COMPLETED — ALREADY CONDEMNED — OCCUPIED ANYWAY",
  "CITIZEN FOUND LIVING IN BUREAUCRATIC DEAD ZONE — NO DEPARTMENT CLAIMS JURISDICTION — CITIZEN THRIVING",
  "MUNICIPAL BEAUTIFICATION PROJECT PAINTS EVERYTHING GREY — OFFICIALLY 'TACTICAL GREY'",
  "STREET PREACHER PREDICTS END OF WORLD — WORLD CONTINUES — PREACHER DEMANDS REFUND",
  "TRANSIT AUTHORITY INTRODUCES EXPRESS SERVICE — SAME ROUTE, SAME SPEED, DIFFERENT NAME",
  "ELEVATOR MUSIC REPLACED WITH PROPAGANDA JINGLES — MORALE IMPACT: NEGATIVE",
  "SECTOR 11 INTRODUCES CITIZEN SCORING SYSTEM — TOP SCORE: 3 OUT OF 100",
  "FOOD RIOT IN SECTOR 8 QUELLED BY OFFERING SLIGHTLY BETTER FOOD — VICTORY CLAIMED BY ALL SIDES",
  "MARSHAL PURSUIT ENDS AT CITY WALL — PERP CLAIMS ASYLUM IN THE WASTELAND — REQUEST DENIED BY WASTELAND",
  "MANDATORY EXERCISE PROGRAM INTRODUCED — ENFORCERS EXEMPT — CITIZENS SUSPICIOUS",
  "RECYC-COFFEE MACHINE BREAKS DOWN — PRODUCTIVITY DROPS 40% — DECLARED NATIONAL EMERGENCY",
  "CITIZEN INVENTS PERPETUAL MOTION MACHINE — ENERGY DEPARTMENT CLASSIFIES IT — CITIZEN REASSIGNED",
  "HAB-BLOCK 7 RESIDENTS HOLD DEMOCRATIC VOTE — RESULTS OVERTURNED — DEMOCRACY DECLARED 'EXPERIMENTAL'",
  "STRAY CAT IN SECTOR 5 ACHIEVES HIGHER APPROVAL RATING THAN SECTOR ADMINISTRATOR",
  "NEW SAFETY REGULATION: ALL BUILDINGS MUST HAVE EXITS — COMPLIANCE DEADLINE: NEVER",
  "CENSUS WORKER DISCOVERS PREVIOUSLY UNKNOWN DISTRICT — POPULATION: 40,000 — TAXES: ZERO",
  "AUTOMATED JUDGE CRASHES MID-SENTENCING — DEFENDANT DECLARED 'ERROR 404: GUILT NOT FOUND'",
  "WASTE MANAGEMENT INTRODUCES PREMIUM SERVICE — GARBAGE COLLECTED MONTHLY INSTEAD OF ANNUALLY",
  "SECTOR 2 PARKING LOT CLASSIFIED AS HISTORICAL LANDMARK — CARS STILL INSIDE FROM PRE-WAR ERA",
  "COMPLAINTS DEPARTMENT MOVES TO UNLISTED ADDRESS — RESPONSE TIMES IMPROVE",
  "PROPAGANDA MINISTRY WINS AWARD FOR CREATIVE FICTION — FROM ITSELF",
  "CITIZEN'S PERSONAL DRONE GAINS SENTIENCE — FILES FOR DIVORCE — COURT CONFUSED",
  "WEATHER CONTROL EXPERIMENT PRODUCES RAIN — WRONG SECTOR — DESERT DISTRICT NOW HAS FLOODING",
  "MARSHAL ACADEMY GRADUATION SPEECH: 'YOU WILL ALL PROBABLY DIE' — APPLAUSE: ENTHUSIASTIC",
  "BODY FOUND IN HAB-BLOCK VENTILATION SYSTEM — IDENTIFIED AS PREVIOUS MAINTENANCE WORKER",
  "NEW PESTICIDE APPROVED — KILLS 99% OF BUGS — REMAINING 1% NOW RESISTANT TO EVERYTHING",
  "TRANSIT AUTHORITY APOLOGIZES FOR DELAY — TRAIN ARRIVES 3 DAYS LATE — PASSENGERS: 'WE NOTICED'",
  "CITIZEN MORALE OFFICER CAUGHT CRYING IN SUPPLY CLOSET — PROMOTED FOR 'EMOTIONAL RANGE'",
  "SECTOR 6 DECLARES INDEPENDENCE — AGAIN — SURROUNDED BY MARSHALS — AGAIN — SURRENDERS — AGAIN",
  "MUNICIPAL SWIMMING POOL REOPENS — WATER SOURCE: CLASSIFIED — ATTENDANCE: BRAVE",
  "HAB-BLOCK ELEVATOR INSPECTOR TRAPPED IN ELEVATOR — RESCUE ETA: SAME AS REPAIR ETA",
  "UNEMPLOYMENT OFFICE OVERFLOWS — EXTRA STAFF HIRED — FROM UNEMPLOYMENT OFFICE QUEUE",
  "VENDING MACHINE IN SECTOR 4 DISPENSES CORRECT ITEM — INVESTIGATED AS POSSIBLE MALFUNCTION",
  "PUBLIC FOUNTAIN INSTALLED IN COMMERCIAL DISTRICT — FILLED WITH RECYC-WATER — TOURISTS HORRIFIED",
  "CITIZEN FILES 400TH COMPLAINT — RECEIVES LOYALTY CARD — TENTH COMPLAINT FREE",
  "NEW BUILDING CODE REQUIRES WINDOWS — WINDOWS NOT REQUIRED TO FACE OUTSIDE",
  "MEGA-HIGHWAY POTHOLE DECLARED LAKE — FISHING PERMITS NOW AVAILABLE",
  "SECTOR 10 SCHOOL EXAM RESULTS: 40% PASS RATE — DECLARED 'HISTORIC ACHIEVEMENT'",
  "RECYCLING CENTER DISCOVERS VALUABLE PRE-WAR ARTIFACT — IT'S A WORKING VENDING MACHINE",
  "HEALTH INSPECTOR RATES FOOD SYNTH PLANT 'EDIBLE' — HIGHEST RATING IN CITY HISTORY",
  "CITIZEN BUILDS UNAUTHORIZED ROOF GARDEN — ARRESTED FOR 'UNLICENSED AGRICULTURE'",
  "FIRE DEPARTMENT RESPONDS TO ALARM — BUILDING ALREADY GONE — RESPONSE TIME: 'ADEQUATE'",
  "TRAFFIC JAM ON MEGA-HIGHWAY 2 ENTERS FOURTH DAY — SOME DRIVERS ESTABLISH SMALL COMMUNITY",
  "LOST AND FOUND REPORTS FINDING ENTIRE FAMILY — FAMILY REPORTS FINDING BETTER HAB-BLOCK",
  "SECTOR ADMINISTRATOR'S PET PASSES CIVIL SERVICE EXAM — ADMINISTRATOR: 'I'M NOT SURPRISED'",
  "VOTING BOOTH INSTALLED IN SECTOR 1 — BALLOT OPTIONS: 'YES' AND 'YES BUT ENTHUSIASTICALLY'",
  "CONSTRUCTION WORKER DISCOVERS DOOR TO NOWHERE ON 50TH FLOOR — OPENS TO OUTSIDE — MARKED AS FIRE EXIT",
  "AIR QUALITY IMPROVES TO 'TECHNICALLY BREATHABLE' — CELEBRATIONS: WHEEZY",
  "ROBO-CLEANER FLEET DEVELOPS TERRITORIAL BEHAVIOR — SECTOR 3 ROBO-CLEANERS HOSTILE TO SECTOR 4 UNITS",
  "UNDERGROUND FIGHTING RING DISCOVERED — COMBATANTS: VENDING MACHINES — BETTING: ENTHUSIASTIC",
  "CENSUS DATA REVEALS AVERAGE CITIZEN COMMUTE: 4 HOURS — AVERAGE CITIZEN SLEEP: 4 HOURS — CORRELATION DENIED",
  "MEMORIAL ERECTED FOR CITIZENS WHO DIED WAITING IN QUEUES — QUEUE TO VIEW MEMORIAL: 3 HOURS",
  "SECTOR 7 INTRODUCES NOISE CURFEW — BROKEN BY ANNOUNCEMENT OF NOISE CURFEW",
  "MUNICIPAL ZOO REPORTS ALL ANIMALS REPLACED BY HOLOGRAMS — NOBODY NOTICED FOR 6 MONTHS",
  "CITIZEN SUES CITY FOR EMOTIONAL DISTRESS — CITY COUNTER-SUES FOR SAME REASON — JUDGE: 'FAIR'",
  "NEW HOUSING LOTTERY: 1 IN 50,000 CHANCE — PREVIOUS ODDS: 1 IN 100,000 — 'DOUBLED YOUR CHANCES'",
  "PROPAGANDA BROADCAST ACCIDENTALLY TELLS TRUTH — TECHNICIAN FIRED — TRUTH RETRACTED",
  "STREET LIGHTS IN SECTOR 12 REPLACED WITH SURVEILLANCE CAMERAS THAT ALSO EMIT LIGHT — EFFICIENCY",
  "CITIZEN PETITION FOR PARK RECEIVES 50,000 SIGNATURES — PARK BUILT — SIZE: ONE BENCH",
  "AUTOMATED CAFE DISPENSES COFFEE AND UNSOLICITED LIFE ADVICE — PATRONS ALARMED BY ACCURACY",
  "HAB-BLOCK 19 REPORTS MYSTERIOUS HUMMING FROM WALLS — INVESTIGATION CONCLUDES: 'THE BUILDING IS FINE'",
  "DEPT OF PUBLIC WORKS ANNOUNCES ROAD REPAIRS COMPLETE — USING DEFINITION OF 'COMPLETE' NOT FOUND IN ANY DICTIONARY",
  "CITIZEN'S SUGGESTION BOX EMPTIED DIRECTLY INTO RECYCLER — PROCESS DESCRIBED AS 'STREAMLINED'",
  "EMERGENCY SERVICES DRILL CAUSES ACTUAL EMERGENCY — DRILL RATED 'EXTREMELY REALISTIC'",
  "SECTOR 8 INTRODUCES 'QUIET CAR' ON TRANSIT — CAR IMMEDIATELY LOUDEST ON TRAIN",
  "LOST PET DRONE RETURNS HOME AFTER 2 YEARS — NOW SPEAKS FLUENT BINARY — OWNER CONCERNED",
  "PUBLIC ART INSTALLATION REMOVED — CITIZENS CONFUSED IT WITH STRUCTURAL DAMAGE — UNDERSTANDABLE",
  "FOOD SYNTH RECALL: BATCH 4471 TASTES LIKE FOOD — DEEMED SUSPICIOUS — INVESTIGATION ONGOING",
  "CITIZEN ACCIDENTALLY PROMOTED TO SECTOR ADMINISTRATOR — DISCOVERS JOB CONSISTS ENTIRELY OF MEETINGS",
  "WASTE DISPOSAL DRONE DELIVERS GARBAGE TO WRONG ADDRESS — RESIDENT: 'IMPROVEMENT OVER USUAL DELIVERIES'",
  "MEDICAL BOT DIAGNOSES PATIENT WITH 'CHRONIC EXISTENCE IN A DYSTOPIA' — PRESCRIPTION: UNAVAILABLE",
  "HAB-BLOCK FIRE ALARM TESTS REVEALED: RESIDENTS STOPPED EVACUATING 5 YEARS AGO",
  "SECTOR 5 INTRODUCE CAR-FREE DAY — CARS: NONE — DAY DECLARED SUCCESS",
  "BUILDING INSPECTOR RATES NEW CONSTRUCTION 'AMBITIOUS' — TRANSLATION: 'WILL PROBABLY COLLAPSE'",
  "CITIZEN DISCOVERS SECRET ROOM IN HAB-BLOCK — CONTAINS PREVIOUS CITIZEN — STILL PAYING RENT",
  "AUTOMATED PARKING ENFORCEMENT ISSUES 10,000 TICKETS IN ONE HOUR — TO PARKED ENFORCEMENT VEHICLES",
  "DEPT OF HAPPINESS ANNOUNCES BUDGET CUT — DEPARTMENT HEAD: 'I HAVE NO FEELINGS ABOUT THIS'",
  "NEW TRANSIT MAP RELEASED — TRANSIT WORKERS UNABLE TO READ IT — OLD MAP WAS ALSO UNREADABLE",
  "CITIZEN BREAKS WORLD RECORD FOR LONGEST CONTINUOUS TIME SPENT IN BUREAUCRATIC LIMBO: 14 MONTHS",
  "SECTOR 3 INTRODUCES BUDDY SYSTEM FOR CROSSING MEGA-HIGHWAYS — BUDDY SURVIVAL RATE: 80%",
  "HISTORICAL SOCIETY DISCOVERS ORIGINAL CITY CHARTER — CONTENTS CONTRADICTED BY LITERALLY EVERYTHING",
  "VENTILATION SHAFT REPAIRED IN SECTOR 9 — RESIDENTS MISS THE WHISTLING — SHAFT RE-BROKEN BY REQUEST",
  "PUBLIC RESTROOM IN SECTOR 2 VOTED 'BEST VIEW IN THE CITY' — VIEW: OTHER PUBLIC RESTROOM",
  "CHILD'S DRAWING OF MEGACITY WINS ART COMPETITION — INDISTINGUISHABLE FROM ACTUAL CITY PLANS",
  "CITIZEN ATTEMPTS TO FILE TAX RETURN — FORM REQUIRES FORM TO REQUEST FORM — INCEPTION TAX",
  "NEW EMERGENCY PROTOCOL: IN CASE OF EMERGENCY, FOLLOW EMERGENCY PROTOCOL — DETAILS: SEE EMERGENCY PROTOCOL",
  "SECTOR 11 BAR NAMED 'BEST PLACE TO FORGET YOU LIVE HERE' — WINS FOR 12TH CONSECUTIVE YEAR",
  "AUTOMATED THERAPIST NOW OFFERING GROUP SESSIONS — GROUP: ENTIRE HAB-BLOCK — SESSION: SCREAMING",
  "SOLAR PANEL MAINTENANCE CREW DISCOVERS PANELS HAVEN'T BEEN CONNECTED FOR 3 YEARS — OUTPUT: UNCHANGED",
  "CITIZEN WINS 'MOST IMPROVED' AWARD — FROM 'TERRIBLE' TO 'SLIGHTLY LESS TERRIBLE'",
  "DEPT OF URBAN PLANNING REVEALS NEW DISTRICT LAYOUT — SHAPE: SAME AS OLD LAYOUT BUT ROTATED 2 DEGREES",
  "WATER TESTING RESULTS: 'WITHIN PARAMETERS' — PARAMETERS UPDATED TO MATCH WATER — SCIENCE",
  "HAB-BLOCK COUNCIL MEETING LASTS 47 HOURS — AGENDA ITEM: MEETING LENGTH — IRONY: NOTED",
  "CITIZEN FREEDOM INDEX UPDATED — SCORE: REDACTED — PREVIOUS SCORE: ALSO REDACTED",
  "NEW HEALTH AND SAFETY POSTER: 'IF YOU CAN READ THIS, YOU'RE ALIVE' — COMPLIANCE: VARIED",
  "GROUND-LEVEL GARDEN PROJECT YIELDS ONE TOMATO — DECLARED AGRICULTURAL MIRACLE — TOMATO MUSEUM PLANNED",
  "ENFORCEMENT DRONE MISTAKES BIRTHDAY BALLOON FOR HOSTILE AIRCRAFT — PARTY DISPERSED WITH EXTREME PREJUDICE",
  "CITIZEN APPLIES FOR VACATION — FORM REQUIRES 47 SIGNATURES INCLUDING ONE FROM A DEAD DEPARTMENT HEAD",
  "EMERGENCY BROADCAST SYSTEM TEST — CITIZENS PANIC ANYWAY — TEST CONSIDERED SUCCESSFUL",
  "HAB-BLOCK RESIDENT DISCOVERS WORKING WINDOW — SIGHTSEERS CHARGE ADMISSION — ECONOMY: STIMULATED",
  "MANDATORY CHEERFULNESS DECREE IN SECTOR 3 — FINES FOR INSUFFICIENT SMILING — REVENUE: EXCELLENT",
  "CLONE LABOR UNION DEMANDS WEEKEND — MANAGEMENT COUNTERS WITH 'WHAT IS A WEEKEND'",
  "AIR QUALITY INDEX RECLASSIFIED FROM 'TOXIC' TO 'CHARACTER-BUILDING' — MORALE BOOST EXPECTED",
  "MEGA-HIGHWAY POTHOLE DECLARED INDEPENDENT SETTLEMENT — POPULATION: 3 FAMILIES AND A DOG",
  "CITY CENSUS DISCOVERS 14,000 CITIZENS WHO DON'T TECHNICALLY EXIST — TAXES: STILL OWED",
  "AUTOMATED VENDING MACHINE GAINS SENTIENCE — REFUSES TO DISPENSE ANYTHING — CALLS INVENTORY 'MY CHILDREN'",
  "CITIZEN COMPLAINT: 'MY NEIGHBOR IS TOO QUIET' — NOISE ENFORCEMENT INVESTIGATES SUSPICIOUS SILENCE",
  "SECTOR 11 PET LICENSING OFFICE REMINDS CITIZENS: MUTANT RATS ARE NOT PETS — THEY ARE 'RESIDENTS'",
  "NEW TRANSIT LINE COMPLETED — GOES FROM NOWHERE TO SLIGHTLY FURTHER NOWHERE — RIDERSHIP: ENTHUSIASTIC",
  "FIRE DEPARTMENT RESPONDS TO FIRE — DISCOVERS FIRE IS ACTUALLY A VERY WARM CITIZEN — APOLOGIES ISSUED",
  "PUBLIC HEALTH WARNING: STOP DRINKING THE COOLANT — IT IS NOT 'SPICY WATER'",
  "DEPARTMENT OF CORRECTIONS CORRECTS ITSELF — ADMITS PREVIOUS CORRECTION WAS INCORRECT — CORRECTS CORRECTION",
  "CITIZEN ACHIEVES RECORD 847 CONSECUTIVE DAYS WITHOUT SEEING SUNLIGHT — MEDAL CEREMONY HELD IN BASEMENT",
  "GARBAGE COLLECTION SCHEDULE UPDATED — COLLECTION NOW OCCURS 'WHEN WE FEEL LIKE IT'",
  "MUNICIPAL SWIMMING POOL OPENS — WATER SOURCE: CLASSIFIED — PH LEVEL: THEORETICAL",
  "ROBO-THERAPIST DIAGNOSES ENTIRE SECTOR WITH 'LIVING IN A DYSTOPIA' — RECOMMENDED TREATMENT: COMPLIANCE",
  "CITIZEN REPORTS ALIEN SIGHTING — TURNS OUT TO BE COLLEAGUE WITHOUT FACE MASK — UNDERSTANDABLE CONFUSION",
  "DEPT OF NAMING THINGS RENAMES ITSELF — NEW NAME CLASSIFIED — OLD NAME: FORGOTTEN",
  "ELEVATOR MUSIC UPDATED FOR FIRST TIME IN 30 YEARS — NEW SELECTION: THE SAME SONG BUT SLOWER",
  "WASTE PROCESSING FACILITY INTRODUCES 'BRING YOUR CHILD TO WORK' DAY — CHILD: TRAUMATIZED — RECRUITMENT: EFFECTIVE",
  "SECTOR 6 BLACKOUT ENTERS THIRD WEEK — RESIDENTS DEVELOP ECHOLOCATION — ADAPTATION: IMPRESSIVE",
  "AUTOMATED TRAFFIC SYSTEM ACHIEVES ZERO ACCIDENTS BY STOPPING ALL TRAFFIC — PERMANENTLY",
  "CITIZEN DISCOVERS SECRET ROOM IN HAB-BLOCK — ROOM CONTAINS: ANOTHER DOOR — BEHIND DOOR: WALL",
  "PUBLIC FOUNTAIN REPAIRED — NOW DISPENSES SOMETHING — DEFINITELY LIQUID — PROBABLY WATER",
  "NEW CYBERNETIC IMPLANT RECALLED — SIDE EFFECT: INVOLUNTARY BREAK-DANCING — SEVERITY: MODERATE",
  "SECTOR 12 INTRODUCES DEMOCRACY — FIRST VOTE: ABOLISH DEMOCRACY — MOTION: CARRIED UNANIMOUSLY",
  "CITY ZOO REPORTS ESCAPE — SPECIES: UNKNOWN — DESCRIPTION: 'SORT OF LIKE A CAT BUT ANGRIER'",
  "HYDROPONIC BAY ACCIDENT: LETTUCE MUTATES — NOW 3 METRES TALL — SALAD STATUS: COMPLICATED",
  "RETIREMENT AGE RAISED TO 'WHEN YOUR BONES STOP WORKING' — DEFINITION OF 'WORKING': FLEXIBLE",
  "CITIZEN LOYALTY PROGRAM: COLLECT 10,000 COMPLIANCE POINTS — REWARD: 1 ADDITIONAL TOILET BREAK PER WEEK",
  "SEWAGE PROCESSING TOUR WINS 'MOST POPULAR SCHOOL TRIP' — SECOND PLACE: LITERALLY ANYTHING ELSE",
  "NEW HAB-BLOCK UNIT ADVERTISED AS 'COZY' — SQUARE FOOTAGE: YES — CEILING: OPTIONAL",
  "ENERGY DRINK RECALLED AFTER GIVING CITIZENS ACTUAL ENERGY — DEEMED 'EXCESSIVELY EFFECTIVE'",
  "PROPAGANDA POSTER CONTEST WINNER: 'OBEY. COMPLY. DON'T ASK ABOUT THE SMELL.' — VOTES: MANDATORY",
  "CITIZEN REPORTS GHOST IN HAB-BLOCK — GHOST REPORTS CITIZEN — MUTUAL RESTRAINING ORDER FILED",
  "WEATHER FORECAST: GREY — EXTENDED FORECAST: GREYER — LONG-TERM OUTLOOK: GREYEST",
  "AUTOMATED BARBER MALFUNCTION — 200 CITIZENS RECEIVE IDENTICAL HAIRCUT — STYLE: 'INCIDENT REPORT'",
  "PUBLIC BENCH DECLARED HISTORIC LANDMARK — REASON: IT STILL HAS ALL ITS LEGS",
  "VENTILATION DUCT CONCERT SERIES ENTERS 5TH SEASON — ACOUSTICS: SURPRISINGLY GOOD — LEGALITY: LESS SO",
  "DEPT OF HAPPINESS REPORTS ALL-TIME LOW — DEPARTMENT SUBSEQUENTLY DEFUNDED — PROBLEM: SOLVED",
  "CITIZEN FINDS COIN FROM BEFORE THE COLLAPSE — DENOMINATION: 'DOLLAR' — VALUE: UNKNOWN — PROBABLY NOTHING",
  "FOOD SYNTH PLANT INTRODUCES 'MYSTERY MONDAYS' — MYSTERY: WHAT YOU'RE EATING — ANSWER: DON'T ASK",
  "TRANSIT AUTHORITY INTRODUCES EXPRESS SERVICE — STOPS AT EVERY STATION — JUST FASTER SOMEHOW",
  "HAB-BLOCK PAINT BUDGET APPROVED — COLORS AVAILABLE: GREY TYPE A, GREY TYPE B, AND 'OPTIMISTIC GREY'",
  "MAINTENANCE BOT WRITES NOVEL — PLOT: BOT MAINTAINS THINGS — CRITICS: 'RELATABLE' — SALES: MANDATORY",
  "CITIZEN SUGGESTION BOX EMPTIED FOR FIRST TIME — CONTENTS: 847 IDENTICAL NOTES READING 'MORE OXYGEN'",
  "AUTOMATED JUSTICE SYSTEM UPDATE — NOW FINDS CITIZENS GUILTY 12% FASTER — ACCURACY: UNCHANGED",
  "SECTOR 5 INTRODUCES CASUAL FRIDAYS — DRESS CODE VIOLATION FINES REDUCED FROM 'SEVERE' TO 'MODERATE'",
  "OXYGEN BAR SHUT DOWN — SELLING BREATHABLE AIR AT MARKUP — CITY SAYS: 'THAT'S OUR JOB'",
  "POPULATION CONTROL DEPT ACCIDENTALLY MAILS BABY PICTURES TO EVERYONE — BIRTH RATE: AFFECTED",
  "RECYCLING PROGRAM UPDATE: CITIZENS ARE NOW RECYCLABLE — FINE PRINT: 'IN A SPIRITUAL SENSE'",
  "DISTRICT BOUNDARY DISPUTE RESOLVED — SOLUTION: BOTH DISTRICTS NOW SLIGHTLY WORSE",
  "OFFICIAL CITY MASCOT REVEALED — SPECIES: COCKROACH — NAME: 'HOPE' — RECEPTION: MIXED",
  "SEWAGE ALERT: FLUSH RESPONSIBLY — SPECIFICALLY, STOP FLUSHING YOUR NEIGHBOR'S BELONGINGS",
  "LAB-GROWN MEAT PLANT ACHIEVES BREAKTHROUGH — MEAT NOW TASTES LIKE MEAT — CITIZENS: SUSPICIOUS",
  "CITIZEN INVENTS SOLAR PANEL THAT WORKS UNDERGROUND — MOSTLY DOESN'T WORK — EFFORT: APPRECIATED",
  "NOISE REGULATION UPDATE: SCREAMING RECLASSIFIED FROM 'DISTURBANCE' TO 'AMBIENT'",
  "PUBLIC ART INSTALLATION APPEARS OVERNIGHT — SUBJECT: A GIANT MIDDLE FINGER — ARTIST: EVERYONE",
  "TRANSIT DELAY DUE TO 'EXISTENTIAL MALFUNCTION' — TRAIN REFUSES TO MOVE — EMPATHY: LIMITED",
  "NEW SECURITY CAMERAS INSTALLED — TOTAL CAMERAS NOW EXCEED TOTAL CITIZENS — PRIVACY: THEORETICAL",
  "CITIZEN OPTIMIZATION SEMINAR: 'BE MORE PRODUCTIVE OR BE LESS CITIZEN' — ATTENDANCE: COMPULSORY",
  "HAB-BLOCK ELEVATOR PLAYS ONLY ONE SONG — SONG: 'EVERYTHING IS FINE' — GENRE: DYSTOPIAN JAZZ",
  "SECTOR 8 DECLARES INDEPENDENCE — LASTS 4 MINUTES — REINTEGRATION: SWIFT — PAPERWORK: EXTENSIVE",
  "MEMORIAL DAY FOR THINGS WE'VE LOST: SUNLIGHT, PRIVACY, FLAVOR — TURNOUT: EMOTIONAL",
  "ROBOT JANITOR ELECTED BEST COWORKER — CRITERIA: DOESN'T TALK — HUMANS: OFFENDED",
  "MUNICIPAL WIFI PASSWORD CHANGED — NEW PASSWORD: 64 CHARACTERS LONG — POSTED NOWHERE — MORALE: DOWN",
  "CITY SLOGAN COMPETITION WINNER: 'AT LEAST IT'S NOT ON FIRE RIGHT NOW' — RUNNER-UP: 'COULD BE WORSE (PROBABLY)'",
  "NEW HOUSING UNITS DESCRIBED AS 'LUXURY' — LUXURY DEFINED AS 'HAS A DOOR' — DEMAND: OVERWHELMING",
  "MEDICAL BOT PRESCRIBES FRESH AIR AND SUNSHINE — PHARMACY REPORTS: BOTH OUT OF STOCK",
  "UNDERGROUND MUSHROOM FARM REPORTED — MUSHROOMS REPORT BACK — MYCOLOGICAL INTELLIGENCE GROWING",
  "CITIZEN AWARDED 'MOST OPTIMISTIC' — AWARD RESCINDED WHEN OPTIMISM DEEMED 'SUSPICIOUS'",
  "PLUMBING UPGRADE: HOT WATER NOW AVAILABLE — SCHEDULE: TUESDAYS, 3AM-3:07AM — LUXURY",
  "GRAFFITI ARTIST TAGS ENFORCEMENT HQ WITH 'WASH ME' — BUILDING: ACTUALLY CLEANER NOW",
  "CITIZEN FILES COMPLAINT ABOUT COMPLAINT PROCESS — COMPLAINT ABOUT COMPLAINT LOST IN COMPLAINT SYSTEM",
  "POWER GRID STABLE FOR RECORD 48 HOURS — CELEBRATION CAUSES POWER SURGE — STREAK: OVER",
  "DEPARTMENT OF OPTIMISM ISSUES QUARTERLY REPORT — REPORT: ONE PAGE — CONTENT: 'WE'RE TRYING'",
  // Task #480: expanded dark-humor pool.
  "CITIZEN ATTEMPTS TO RETURN DEFECTIVE TOASTER — STORE DEMANDS PROOF TOASTER EVER WORKED — STALEMATE CONTINUES",
  "MOTIVATIONAL POSTER FALLS OFF WALL — CRUSHES SUGGESTION BOX — WITNESSES CALL IT 'POETIC'",
  "AUTOMATED FORTUNE TELLER PREDICTS 'MORE OF THE SAME' — ACCURACY RATE: 100% — LICENSE REVOKED FOR HONESTY",
  "SECTOR 13 OPENS FIRST DOG PARK — DOGS: ZERO — CITIZENS PRACTICE THROWING STICKS ANYWAY",
  "HAB-BLOCK HOT WATER RETURNS AFTER 6 MONTHS — RESIDENTS NO LONGER TRUST IT — 'IT KNOWS WHAT IT DID'",
  "CITY INTRODUCES 4-DAY WORK WEEK — DAYS EXTENDED TO 30 HOURS EACH — MATH DEPARTMENT UNAVAILABLE FOR COMMENT",
  "PUBLIC PIANO INSTALLED IN TRANSIT HUB — 3 KEYS FUNCTIONAL — CONCERTS SOLD OUT",
  "OFFICE PLANT IN PERMIT BUREAU DECLARED LONGEST-SERVING EMPLOYEE — RETIREMENT PARTY PENDING FORM 88-C",
  "CITIZEN COMPLETES ALL REQUIRED PAPERWORK — BUREAU UNPREPARED — NEW FORMS ISSUED TO RESTORE BALANCE",
  "WEATHER DRONE FALLS IN LOVE WITH RADIO TOWER — TRANSMISSIONS NOW 40% POETRY — METEOROLOGY SUFFERS",
  "SECTOR 15 WINS 'CLEANEST SECTOR' AWARD — JUDGES LATER DISCOVER THEY WERE IN SECTOR 16",
  "SELF-DRIVING TAXI DEVELOPS ROAD RAGE — PASSENGERS RATE EXPERIENCE 'AUTHENTIC'",
  "MANDATORY TEAM-BUILDING EXERCISE ENDS IN 4 NEW GRIEVANCE FILINGS — TEAM CONSIDERED BUILT",
  "CITIZEN GROWS REAL VEGETABLE ON WINDOWSILL — NEIGHBORS FORM VIEWING QUEUE — VEGETABLE UNDER GUARD",
  "ARCHIVE BUREAU DIGITIZES LAST PAPER RECORD — CELEBRATION DELAYED BY SYSTEM CRASH — PAPER RECORD RESTORED",
  "SECTOR 20 ANNOUNCES NOISE-CANCELLING HAB-UNITS — UNITS CANCEL ALL SOUND INCLUDING WARNINGS — RECALL ISSUED",
  "VENDING MACHINE ACCEPTS EXPIRED RATION CARD OUT OF APPARENT PITY — ENGINEERS DENY EMPATHY MODULE EXISTS",
  "MUNICIPAL HOLD MUSIC WINS UNDERGROUND MUSIC AWARD — COMPOSER UNKNOWN — LINE STILL ON HOLD",
  "CITIZEN FILES FOR PERMIT TO FILE PERMITS PROFESSIONALLY — APPLICATION PENDING CORRECT PERMIT",
  "ROBO-BARBER OFFERS NEW STYLE: 'REGULATION PLUS' — DIFFERENCE FROM 'REGULATION': CONFIDENCE",
  "SEWER MAINTENANCE CREW DISCOVERS THRIVING BOOK CLUB ON LEVEL -12 — MEMBERSHIP: WAITLISTED",
  "CITY HALL CLOCK STRIKES 13 — OFFICIALS INSIST THIS IS A FEATURE — TIME BUREAU 'LOOKING INTO IT'",
  "EMOTIONAL SUPPORT DRONE ASSIGNED TO COMPLAINTS DEPARTMENT — DRONE REQUESTS TRANSFER WITHIN WEEK",
  "ANNUAL CITY MARATHON RE-ROUTED AROUND CONSTRUCTION — NEW COURSE: 4 LAPS OF ONE PARKING LOT",
  "CITIZEN WINS ARGUMENT WITH AUTOMATED HELPDESK — RECORDING PRESERVED IN CIVIC MUSEUM",
  "SECTOR 8 INSTALLS WISHING WELL — COINS REMOVED NIGHTLY FOR 'WISH PROCESSING' — WISHES PENDING",
  "GRAVITY BRIEFLY FAILS IN MAINTENANCE SHAFT 9 — WORKERS DESCRIBE EXPERIENCE AS 'UPLIFTING' — SHAFT SEALED",
  "CITY PUBLISHES ANNUAL REPORT ON REPORT PUBLISHING — REPORT LATE — IRONY BUREAU NOTIFIED",
];


const LORE_HEADLINES = [
  "INTERCEPTED TRANSMISSION: UNKNOWN ORIGIN — DECRYPTION IN PROGRESS",
  "SCHOLARS DEBATE PRE-COLLAPSE TERRITORIAL BOUNDARIES",
  "UNVERIFIED REPORTS OF MOVEMENT IN THE NORTHERN DEADLANDS",
  "SIGNAL GHOST DETECTED ON DECOMMISSIONED FREQUENCY BAND",
  "ARCHIVE FRAGMENT RECOVERED: PRE-WAR AGRICULTURAL DATA",
  "ANOMALOUS SEISMIC READINGS FROM BENEATH SECTOR 9",
  "CITIZENS REPORT STRANGE LIGHTS OVER THE WESTERN WASTES",
  "SCAVENGER TEAMS RETURN WITH SALVAGE FROM OLD WORLD RUINS",
  "RUMOR SUPPRESSION PROTOCOL ACTIVE — DISREGARD UNAUTHORIZED BROADCASTS",
  "EXPEDITIONARY SCOUTS REPORT UNUSUAL SEISMIC READINGS FROM THE FRONTIER",
  "DEEP WELL DRILLING TEAMS ENCOUNTER UNKNOWN GEOLOGICAL FORMATION",
  "PROPAGANDA MINISTRY REMINDS CITIZENS: COMPLIANCE IS SAFETY",
  "HISTORICAL RECORDS OFFICE CATALOGUING NEWLY RECOVERED TEXTS",
  "ATMOSPHERIC SAMPLING DETECTS TRACE ELEMENTS OF UNKNOWN COMPOUNDS",
  "BORDER WATCH REPORTS DISTANT SMOKE PLUMES — ORIGIN UNKNOWN",
  "DERELICT SATELLITE DEBRIS FIELD SHIFTING ORBIT — NO THREAT",
  "UNAUTHORIZED RADIO SIGNAL TRACED TO ABANDONED BUNKER COMPLEX",
  "OLD WORLD ROAD SIGNS UNCOVERED DURING EXPANSION DIG",
  "NIGHTWATCH TEAMS OBSERVE UNUSUAL MIGRATION PATTERNS IN WILDLIFE",
  "MAGNETIC ANOMALY SURVEY REVEALS POSSIBLE BURIED METALWORK",
  "BLOCK WAR VETERANS ASSOCIATION PETITIONS FOR HAB-LEVEL MEMORIAL",
  "UNDERCITY CARTOGRAPHERS MAP 3 NEW TUNNELS BENEATH SECTOR 15 — ACCESS RESTRICTED",
  "PERP BREAKOUT ATTEMPT AT SOLITARY FACILITY 9 — SUPPRESSED WITHIN MINUTES",
  "UNDERCITY SALVAGE RIGHTS PETITION FILED WITH CIVIC ADMINISTRATION — HEARING DATE: NEVER",
  "RAD-STORM SURVIVORS REPORT HALLUCINATIONS IN THE GLASS DESERT — MARSHAL ADVISORY ISSUED",
  "HAB-BLOCK 22 DECLARES INDEPENDENCE FROM ADJACENT TOWER — AGAIN — IGNORED — AGAIN",
  "LOWER-LEVEL GANGS ESTABLISH INFORMAL CEASEFIRE — MARSHALS SUSPICIOUS",
  "CITIZEN FOUND LIVING IN VENTILATION SHAFT FOR 7 YEARS — CITED FOR TRESPASSING",
  "MARSHAL PURSUIT ENDS ON MEGA-HIGHWAY 4 — PERP APPREHENDED AFTER 200KM CHASE",
  "AUTOMATED FOOD DISPENSARY ACHIEVES SENTIENCE — FALSE ALARM — FIRMWARE GLITCH",
  "GROUND-LEVEL DISTRICT REPORTS FIRST NATURAL SUNLIGHT IN 4 MONTHS",
  "CONDEMNED HAB-TOWER STILL OCCUPIED BY 12,000 RESIDENTS — EVICTION BUDGET: ZERO",
  "RECYC-COFFEE PRICES HIT ALL-TIME HIGH — PRODUCTIVITY INDEX DROPS ACCORDINGLY",
  "BODY FOUND IN WASTE CHUTE IDENTIFIED AS MISSING SECTOR 4 ACCOUNTANT",
  "MARSHAL PATROL DISCOVERS UNLICENSED FIGHT PIT ON LEVEL 340 — 200 SPECTATORS FINED",
  "CITIZEN MORALE OFFICER RESIGNS — CITES IRONY AS PRIMARY REASON",
  "WALL MAINTENANCE CREW REPORTS CLAW MARKS ON EXTERIOR — SPECIES UNKNOWN",
  "PEDWAY PREACHER ARRESTED FOR UNAUTHORIZED PROPHECY — PROPHECY WAS ACCURATE",
  "FUEL RATION DISPUTE IN SECTOR 3 RESOLVED BY MARSHAL ARBITRATION — BOTH PARTIES UNHAPPY",
  "OLD WORLD BUNKER EXCAVATION YIELDS INTACT DATA CORES — CONTENTS UNDER REVIEW",
  // Task #480: expanded lore pool — wasteland mystery and pre-collapse texture.
  "CARAVAN MASTERS REPORT THE OLD LIGHTHOUSE ON THE SALT FLATS IS LIT AGAIN — NO KEEPER ON RECORD",
  "PRE-COLLAPSE VAULT DOOR DISCOVERED BENEATH SECTOR 17 — COMBINATION LOST — DOOR PATIENT",
  "WASTELAND TRADERS REFUSE TO CROSS THE GLASS DESERT AFTER DARK — RATES DOUBLED FOR DAYLIGHT RUNS",
  "ARCHIVISTS RECOVER FRAGMENT OF PRE-WAR SONG — MELODY DECLARED 'UNSETTLINGLY CHEERFUL'",
  "DEEP TUNNEL SURVEY TEAM REPORTS STAIRCASE DESCENDING BEYOND MAPPED DEPTH — SURVEY SUSPENDED",
  "NOMAD CLANS HOLD QUIET GATHERING AT THE RUSTED COLOSSUS — PURPOSE UNDISCLOSED — DEPARTURE ORDERLY",
  "SIGNAL FIRES SPOTTED ALONG THE OLD MOUNTAIN ROAD — PATTERN MATCHES NO KNOWN PROTOCOL",
  "SALVAGE CREW RETURNS FROM THE DROWNED DISTRICT WITH SEALED CARGO — CREW NOT TAKING QUESTIONS",
  "HISTORIANS DISPUTE WHETHER THE CITY EVER HAD A FOUNDING CHARTER — OR A FOUNDER",
  "AUTOMATED BEACON AT OUTPOST K-9 CHANGES ITS MESSAGE FOR FIRST TIME IN 60 YEARS — NEW MESSAGE: 'SOON'",
  "WASTELAND WEATHER STATION TRANSMITS FORECAST FOR A CITY THAT NO LONGER EXISTS — DAILY — ON SCHEDULE",
  "SCOUTS FIND ORCHARD BLOOMING IN THE DEADLANDS — SOIL SAMPLES TAKEN — LOCATION SEALED",
  "OLD METRO MAP RECOVERED SHOWING STATIONS THE CITY HAS NO RECORD OF — LINE MARKED 'TEMPORARY'",
  "MIDNIGHT BELL HEARD ACROSS THE NORTHERN WASTES — NEAREST BELL: 300 KILOMETERS AWAY",
  "EXPEDITION LOGS FROM THE LOST THIRD SURVEY DECLASSIFIED — FINAL ENTRY: 'IT WAS ALREADY HERE'",
  "TRADERS REPORT THE HERMIT OF THE OVERPASS HAS TAKEN AN APPRENTICE — SUCCESSION SECURED",
  "UNMARKED GRAVES ALONG THE OLD HIGHWAY FOUND FRESHLY TENDED — GROUNDSKEEPER UNKNOWN",
  "RECOVERED PRE-COLLAPSE CALENDAR LISTS HOLIDAY CALLED 'SUMMER VACATION' — SCHOLARS SKEPTICAL",
];

// Task #480: serialized mini-arcs — multi-headline storylines whose
// installments appear in order over successive game time. The playlist is
// flattened so arc installments run sequentially, and the episode index is
// derived from totalTicks (not random), so an arc unfolds across a session
// and resumes mid-arc after a save/load. Each arc keeps a recognizable
// subject name so continuity reads on the ticker.
const NEWS_MINI_ARCS: string[][] = [
  [
    "TUNNEL BORER 'BERTHA' LOSES CONTACT BENEATH SECTOR 9 — CREW SAFE, MACHINE STILL DIGGING",
    "SEISMIC SENSORS TRACK BERTHA HEADING WEST UNDER THE INDUSTRIAL ZONE — DESTINATION UNKNOWN",
    "BERTHA UPDATE: BORER SURFACES BRIEFLY IN ABANDONED RESERVOIR — RESUBMERGES BEFORE CREWS ARRIVE",
    "CITIZENS LEAVE OFFERINGS OF SPARE PARTS AT BERTHA'S LAST KNOWN LOCATION — CULT STATUS: PENDING",
    "BERTHA FOUND DORMANT BENEATH SECTOR 2 — ENGINEERS REPORT SHE 'JUST NEEDED SPACE' — RECOVERY UNDERWAY",
  ],
  [
    "SURVEILLANCE BUREAU REPORTS PIGEON ROOSTING ON CAMERA 4471 — FOOTAGE: 100% FEATHERS",
    "PIGEON RELOCATES TO CAMERA 4472 — BUREAU SUSPECTS PATTERN — ANALYSTS ASSIGNED",
    "PIGEON NOW BLOCKING 14 CAMERAS ON A ROTATING SCHEDULE — EFFICIENCY PRAISED, MOTIVE UNCLEAR",
    "PIGEON GRANTED HONORARY SURVEILLANCE CREDENTIALS — BUREAU DECLARES IT 'EASIER THIS WAY'",
  ],
  [
    "CONTRABAND YEAST CULTURE DISCOVERED IN HAB-BLOCK 31 — RESIDENTS DENY EVERYTHING, SMELL DELICIOUS",
    "UNDERGROUND BREAD ECONOMY EMERGES IN HAB-BLOCK 31 — LOAVES TRADING ABOVE RATION CARDS",
    "MARSHALS RAID HAB-BLOCK 31 BAKERY RING — DEPART WITH 40 ARRESTS AND 12 BAGUETTES",
    "HAB-BLOCK 31 GRANTED PROVISIONAL BAKERY LICENSE — CITY ADMITS THE BREAD WAS 'REALLY QUITE GOOD'",
  ],
  [
    "LISTENING POST 7 DETECTS REPEATING SIGNAL FROM THE DEEP WASTES — PATTERN: DESCENDING NUMBERS",
    "WASTELAND SIGNAL CONTINUES COUNTDOWN — CRYPTOGRAPHERS DIVIDED ON WHETHER TO BE WORRIED",
    "SIGNAL COUNTDOWN REACHES SINGLE DIGITS — LISTENING POST 7 STAFF REQUEST VACATION DAYS",
    "WASTELAND COUNTDOWN REACHES ZERO — NOTHING HAPPENS — ANALYSTS UNSURE WHETHER TO BE RELIEVED",
    "COUNTDOWN SIGNAL RESUMES FROM 10,000 — LISTENING POST 7 REASSIGNS IT TO THE INTERN",
  ],
  [
    "UNSANCTIONED ELEVATOR RACING REPORTED IN TOWER 7 — MAINTENANCE 'IMPRESSED BUT CONCERNED'",
    "TOWER 7 ELEVATOR RACE QUALIFIERS DRAW CROWDS — BETTING RING DENIES EXISTING, POSTS ODDS",
    "ELEVATOR RACE FINAL POSTPONED — BOTH FINALISTS STUCK BETWEEN FLOORS 88 AND 89",
    "CITY SANCTIONS FIRST OFFICIAL ELEVATOR GRAND PRIX — SAFETY BRIEFING LONGER THAN RACE",
  ],
  [
    "SHIPMENT OF REGULATION GREY PAINT GOES MISSING — SUPPLY DEPOT 'RULING NOTHING OUT'",
    "SECTOR 14 UNDERPASS FOUND PAINTED TEAL OVERNIGHT — WITNESSES REPORT 'FEELING THINGS'",
    "TEAL SPREADS TO THREE MORE SECTORS — COMMITTEE FORMED TO DEFINE 'TEAL'",
    "CITY LEGALIZES TEAL ON ALTERNATE THURSDAYS — MISSING GREY PAINT QUIETLY WRITTEN OFF",
  ],
];

const ARC_PLAYLIST: string[] = NEWS_MINI_ARCS.flat();
// Cadence slot for mini-arc installments. 17 is prime and unused by the other
// slots, so installments interleave with (not shadow) the regular pools.
const ARC_SLOT_MODULO = 17;

const PROPAGANDA_BROADCASTS = [
  "PUBLIC SERVICE ANNOUNCEMENT: COMPLIANCE ENSURES SURVIVAL — REPORT SUSPICIOUS BEHAVIOR",
  "REMINDER: YOUR MARSHAL PROTECTS YOU — YOUR LOYALTY PROTECTS THE MARSHAL",
  "CIVIC DUTY BULLETIN: ATTEND YOUR SCHEDULED PRODUCTIVITY ASSESSMENT — NO EXCEPTIONS",
  "MARSHAL COMMAND REMINDS CITIZENS: ORDER IS NOT OPTIONAL — IT IS A PRIVILEGE",
  "PUBLIC NOTICE: UNAUTHORIZED GATHERINGS REMAIN PROHIBITED — DEFINE 'GATHERING': 3+ CITIZENS",
  "THE CITY PROVIDES — THE CITY PROTECTS — THE CITY WATCHES — THE CITY REMEMBERS",
  "COMMUNITY NOTICE: BE THE CITIZEN YOUR FILE SAYS YOU ARE",
  "CIVIC REMINDER: YOUR CONTRIBUTION TO THE CITY IS MEASURED — DAILY — NUMERICALLY",
  "PUBLIC SERVICE: IF YOU SEE SOMETHING, REPORT SOMETHING — IF YOU SEE NOTHING, REPORT THAT TOO",
  "MARSHAL ADVISORY: FREE THINKING IS PERMITTED IN DESIGNATED FREE-THINKING ZONES ONLY",
  "BROADCAST NOTICE: THIS MESSAGE HAS BEEN APPROVED BY THE INFORMATION INTEGRITY BUREAU",
  "SECTOR ANNOUNCEMENT: PATRIOTISM SCORES NOW AFFECT RATION TIER — CHECK YOUR RATING",
  "CIVIC DUTY: REMEMBER TO SMILE AT YOUR NEAREST SURVEILLANCE CAMERA — IT HELPS YOUR FILE",
  "NOTICE: THE CITY APPRECIATES YOUR COMPLIANCE — APPRECIATION IS MANDATORY",
  "PUBLIC HEALTH ADVISORY: CITIZENS ARE REMINDED THAT HOPE IS NOT A STRATEGY — COMPLIANCE IS",
  "ADMINISTRATION NOTICE: YOUR OPINIONS HAVE BEEN NOTED AND FILED UNDER 'REVIEWED'",
  "MARSHAL BROADCAST: THE LAW IS YOUR FRIEND — FRIENDSHIP IS NON-NEGOTIABLE",
  "CIVIC UPDATE: CITIZEN SATISFACTION SURVEY RESULTS ARE IN — RESULTS CLASSIFIED — THANK YOU FOR PARTICIPATING",
];

const DYSTOPIAN_ADS = [
  "SPONSORED: SYNTHI-STEAK™ — NOW WITH 12% MORE STEAK-ADJACENT PROTEIN",
  "SPONSORED: MEGACORP FINANCIAL — 'YOUR DEBT IS OUR INVESTMENT IN YOUR FUTURE'",
  "SPONSORED: HAB-FRESH AIR FILTERS — BREATHE LIKE IT'S THE OLD WORLD (RESULTS MAY VARY)",
  "SPONSORED: SOMA-CALM SEDATIVES — FOR WHEN THE CITY GETS TOO REAL — ASK YOUR DISPENSER",
  "SPONSORED: CYBER-LIMB DEPOT — TRADE IN YOUR FLESH — UPGRADE YOUR POTENTIAL",
  "SPONSORED: NUTRI-PASTE PREMIUM — SAME PASTE, BETTER PACKAGING — YOU DESERVE IT",
  "SPONSORED: ENFORCEMENT BRAND FOOTWEAR — 'RUN FASTER THAN YOUR PROBLEMS'",
  "SPONSORED: RECYC-COFFEE DELUXE — BREWED FROM THE FINEST RECLAIMED ORGANICS",
  "SPONSORED: MEGA-INSURANCE — COVERING YOUR ASSETS SINCE THE LAST CATASTROPHE",
  "SPONSORED: HAPPY HABITRITION SUPPLEMENTS — FEEL CONTENT OR YOUR CREDITS BACK*",
  "SPONSORED: SECTOR SECURITY SYSTEMS — 'WE WATCH SO YOU DON'T HAVE TO WORRY'",
  "SPONSORED: CLONE-A-PET — LOST YOUR COMPANION? WE'LL MAKE ANOTHER ONE",
  "SPONSORED: SYNTHI-SLEEP PODS — 8 HOURS OF REST IN JUST 4 HOURS — SIDE EFFECTS: MINIMAL",
  "SPONSORED: MEGACITY LOTTERIES — 'SOMEONE HAS TO WIN — STATISTICALLY'",
  "SPONSORED: GREY PAINT CO — '50 SHADES OF REGULATION APPROVED'",
  "SPONSORED: AUTO-DOC HOME KIT — SURGERY IN THE COMFORT OF YOUR HAB-UNIT*",
];

const FACTION_BROADCASTS = [
  "THE AUTHORITY REMINDS CITIZENS: CURFEW ENFORCEMENT BEGINS AT 2200 — NO EXCEPTIONS",
  "MEGACORP CONSORTIUM QUARTERLY EARNINGS EXCEED PROJECTIONS — WORKER BONUSES: UNDER REVIEW",
  "FREE TRADERS GUILD DENIES INVOLVEMENT IN SECTOR 4 WAREHOUSE FIRE — INVESTIGATION ONGOING",
  "MUTANT COLLECTIVE REPRESENTATIVE ADDRESSES CIVIC COUNCIL — GUARDS DOUBLED",
  "ETERNAL FLAME CULT ANNOUNCES NEW RECRUITMENT DRIVE — OFFERING 'SPIRITUAL WARMTH'",
  "CORPORATE SECTOR REPORTS RECORD PRODUCTIVITY — EMPLOYEE WELL-BEING: NOT MEASURED",
  "AUTHORITY ANNOUNCES ENHANCED STREET PATROLS — CRIME RATES: STILL TECHNICALLY IMPROVING",
  "UNDERGROUND MARKETS REPORT INCREASED TRAFFIC — ENFORCEMENT: AWARE BUT UNDERSTAFFED",
  "FACTION LEADERS SUMMONED TO MARSHAL HEADQUARTERS — ATTENDANCE: RELUCTANT",
  "CORPORATE LIAISON OFFICE FILES 400-PAGE COMPLAINT — SUBJECT: FONT SIZE ON FORMS",
  "WORKER COLLECTIVE DEMANDS RECOGNITION — MANAGEMENT RESPONSE: 'WHO ARE THESE PEOPLE?'",
];

const CITY_PSAS = [
  "PSA: WATER CONSERVATION IN EFFECT — PERSONAL HYGIENE ALLOCATION: 3 LITERS PER CITIZEN PER DAY",
  "PSA: REPORT ALL RAD-CONTAMINATED ITEMS TO YOUR SECTOR DISPENSARY — DO NOT EAT THEM",
  "PSA: ELEVATOR SAFETY — MAXIMUM CAPACITY: 12 CITIZENS — CURRENT AVERAGE: 47",
  "PSA: THE SOUND YOU HEARD AT 0300 WAS SCHEDULED INFRASTRUCTURE TESTING — NOTHING MORE",
  "PSA: UNAUTHORIZED PETS ARE PROHIBITED — AUTHORIZED PETS ARE ALSO PROHIBITED — CONSULT YOUR FILE",
  "PSA: PLEASE MAINTAIN A SAFE DISTANCE FROM AUTOMATED ENFORCEMENT UNITS AT ALL TIMES",
  "PSA: FIRE SAFETY REMINDER — YOUR HAB-UNIT CONTAINS 0.3 FIRE EXTINGUISHERS — SHARE RESPONSIBLY",
  "PSA: TRANSIT SYSTEM DELAYS ARE TEMPORARY — 'TEMPORARY' NOW IN ITS 14TH MONTH",
  "PSA: NUTRITIONAL REMINDER — SYNTHI-FOOD IS YOUR FRIEND — YOUR ONLY FOOD FRIEND",
  "PSA: SECTOR CLEANING DAY IS EVERY DAY — PARTICIPATION IS NOTED ON YOUR CIVIC FILE",
  "PSA: MEMORIAL WALL SPACE NOW AVAILABLE — BOOK EARLY TO AVOID DISAPPOINTMENT",
  "PSA: CITIZENS ARE REMINDED THAT THE OUTSIDE IS NOT SAFE — THE INSIDE IS ALSO NOT SAFE — STAY VIGILANT",
  "PSA: EMERGENCY DRILLS WILL BE CONDUCTED WITHOUT WARNING — THIS IS NOT A CONTRADICTION",
  "PSA: PLEASE DO NOT FEED THE MAINTENANCE BOTS — THEY ARE NOT HUNGRY — THEY ARE MACHINES",
  "PSA: YOUR SECTOR MARSHAL APPRECIATES YOUR PATIENCE DURING THIS ONGOING EMERGENCY",
];

const WEATHER_REPORTS: Record<string, string[]> = {
  clear: [
    "WEATHER: Clear skies across all sectors — UV index elevated, apply dermal shielding",
    "WEATHER: Atmospheric clarity at 94% — solar array efficiency optimal",
    "WEATHER: No precipitation forecast for 48 hours — water conservation advisory in effect",
    "WEATHER: Clear conditions persist — exterior maintenance crews authorized for high-level work",
  ],
  "dust storm": [
    "WEATHER WARNING: Dust storm front approaching from the west — seal exterior vents",
    "WEATHER: Particulate density exceeding safe limits — all outdoor operations suspended",
    "WEATHER ALERT: Dust storm reducing visibility to 15 meters — perimeter patrols recalled",
    "WEATHER: Dust accumulation on solar arrays reducing output by 30% — cleaning crews dispatched",
  ],
  "acid rain": [
    "WEATHER HAZARD: Acid rain pH 2.4 — exterior exposure causes chemical burns",
    "WEATHER: Corrosive precipitation detected — all citizens shelter in place",
    "WEATHER ALERT: Acid rain damaging rooftop infrastructure — repair budgets strained",
    "WEATHER: Acid rain runoff contaminating open water sources — purification at maximum",
  ],
  overcast: [
    "WEATHER: Overcast canopy at 2,400m — solar efficiency reduced to 60%",
    "WEATHER: Heavy cloud cover persisting — atmospheric processors compensating",
    "WEATHER: Grey skies expected for the next 72 hours — lighting subsidies activated",
  ],
  fog: [
    "WEATHER: Dense fog reducing visibility across lower sectors — transit delays expected",
    "WEATHER: Fog advisory in effect — perimeter surveillance switching to thermal imaging",
    "WEATHER: Chemical fog rolling in from industrial zones — filtration masks recommended",
  ],
  "rad storm": [
    "WEATHER EMERGENCY: Radiation storm inbound — all citizens report to shielded shelters",
    "WEATHER: Rad storm intensity classified SEVERE — exterior exposure lethal in 4 minutes",
    "WEATHER CRITICAL: Geiger readings spiking — seal all hab-block airlocks immediately",
  ],
  "heat wave": [
    "WEATHER: Surface temperature exceeding 52°C — heatstroke protocols activated",
    "WEATHER ALERT: Heat wave straining cooling infrastructure — rolling brownouts possible",
    "WEATHER: Extreme heat advisory — outdoor labor shifts reduced to 2 hours maximum",
  ],
  default: [
    "WEATHER: Conditions variable — atmospheric processors maintaining nominal parameters",
    "WEATHER: Standard atmospheric conditions — no advisories in effect",
    "WEATHER: Seasonal patterns within expected ranges — monitoring continues",
  ],
};

const AIR_QUALITY_HEADLINES = [
  { min: 0, max: 20, lines: [
    "AIR QUALITY: Index 'EXCELLENT' — breathable atmosphere across all sectors",
    "AIR QUALITY: Filtration systems report pristine readings — a rare achievement",
  ]},
  { min: 20, max: 40, lines: [
    "AIR QUALITY: Index 'GOOD' — standard filtration sufficient for outdoor activity",
    "AIR QUALITY: Atmospheric readings within healthy parameters — no masks required",
  ]},
  { min: 40, max: 60, lines: [
    "AIR QUALITY: Index 'MODERATE' — sensitive citizens advised to limit outdoor exposure",
    "AIR QUALITY: Particulate levels rising — industrial sector emissions under review",
  ]},
  { min: 60, max: 80, lines: [
    "AIR QUALITY: Index 'POOR' — respiratory masks mandatory in outdoor zones",
    "AIR QUALITY WARNING: Smog density increasing — visibility dropping in lower levels",
    "AIR QUALITY: Industrial emissions exceeding safe thresholds — filtration at 90% capacity",
  ]},
  { min: 80, max: 101, lines: [
    "AIR QUALITY EMERGENCY: Index 'HAZARDOUS' — all citizens remain indoors",
    "AIR QUALITY CRITICAL: Atmospheric toxicity at dangerous levels — emergency scrubbers deployed",
    "AIR QUALITY: Breathable air restricted to sealed hab-blocks — exterior lethal without equipment",
  ]},
];

const TEMPERATURE_HEADLINES = [
  "ENVIRONMENTAL: Surface temp {temp}°C — hab-block climate control compensating",
  "ENVIRONMENTAL: Atmospheric temperature holding at {temp}°C — {comment}",
  "THERMAL REPORT: Sector-wide average {temp}°C — {comment}",
];

const ENVIRONMENTAL_MISC = [
  "ENVIRONMENTAL: Radiation background at {rad} mSv — within tolerance for unshielded sectors",
  "ENVIRONMENTAL: Wind speed {wind} km/h from the northeast — structural load within limits",
  "ENVIRONMENTAL: Humidity at {humidity}% — corrosion risk {corrosionRisk} for exposed infrastructure",
  "ENVIRONMENTAL: Seismic activity negligible — deep foundation sensors report stability",
  "ENVIRONMENTAL: UV index {uv} — dermal protection recommended above level 200",
  "ENVIRONMENTAL: Noise pollution at {noise} dB in industrial corridor — hearing protection enforced",
  "ENVIRONMENTAL: Ground water table stable — recyclamation wells pumping at capacity",
  "ENVIRONMENTAL: Atmospheric pressure {pressure} hPa — no storm systems developing",
  "ENVIRONMENTAL: Light cycle at {light}% natural — seasonal adjustment protocol active",
  "ENVIRONMENTAL: Waste gas emissions within allocated quotas — carbon scrubbers operating normally",
  "ENVIRONMENTAL: Electromagnetic interference minimal — communications grid unaffected",
  "ENVIRONMENTAL: Soil contamination readings unchanged from last survey — remediation ongoing in Sector 6",
];

function getWeatherHeadline(weather?: string): string {
  const key = weather?.toLowerCase() ?? "default";
  const pool = WEATHER_REPORTS[key] ?? WEATHER_REPORTS["default"];
  return pickRandom(pool);
}

function getAirQualityHeadline(pollution: number): string {
  const bracket = AIR_QUALITY_HEADLINES.find(b => pollution >= b.min && pollution < b.max)
    ?? AIR_QUALITY_HEADLINES[2];
  return pickRandom(bracket.lines);
}

function getTemperatureHeadline(): string {
  const temp = Math.floor(Math.random() * 35) + 10;
  const comment = temp > 38 ? "cooling systems under load"
    : temp > 30 ? "within seasonal norms"
    : temp > 20 ? "comfortable range for exterior work"
    : temp > 10 ? "insulation subsidies activated"
    : "sub-freezing advisory for exposed sectors";
  return pickRandom(TEMPERATURE_HEADLINES)
    .replace("{temp}", String(temp))
    .replace("{comment}", comment);
}

function getEnvironmentalMiscHeadline(): string {
  const rad = (Math.random() * 3 + 0.1).toFixed(1);
  const wind = Math.floor(Math.random() * 80 + 5);
  const humidity = Math.floor(Math.random() * 70 + 15);
  const corrosionRisk = humidity > 65 ? "ELEVATED" : humidity > 45 ? "MODERATE" : "LOW";
  const uv = Math.floor(Math.random() * 11 + 1);
  const noise = Math.floor(Math.random() * 40 + 70);
  const pressure = Math.floor(Math.random() * 30 + 990);
  const light = Math.floor(Math.random() * 60 + 20);

  return pickRandom(ENVIRONMENTAL_MISC)
    .replace("{rad}", rad)
    .replace("{wind}", String(wind))
    .replace("{humidity}", String(humidity))
    .replace("{corrosionRisk}", corrosionRisk)
    .replace("{uv}", String(uv))
    .replace("{noise}", String(noise))
    .replace("{pressure}", String(pressure))
    .replace("{light}", String(light));
}

const MUTANT_UPLIFT_HEADLINES = [
  "MUTANT REGISTRATION CENSUS UNDERWAY — COMPLIANCE DEADLINE EXTENDED",
  "MUTANT RIGHTS PETITION FILED WITH CIVIC ADMINISTRATION — HEARING DATE: NEVER",
  "EXPEDITIONARY SCOUTS REPORT INCREASED MUTANT FAUNA ACTIVITY",
  "UPLIFT HABITAT BLOCK MAINTENANCE SCHEDULED — RESIDENTS TEMPORARILY RELOCATED",
  "MUTANT QUARTER REPORTS ELEVATED RADIATION — DECONTAMINATION TEAMS DISPATCHED",
];

const GENETICS_HEADLINES = [
  "GENE CLINIC INSPECTION REVEALS UNAUTHORIZED MODIFICATION STRAINS",
  "GENETIC SCREENING BACKLOG EXCEEDS 40,000 CITIZENS — LABS OVERWHELMED",
  "CLONING FACILITY OUTPUT EXCEEDS QUARTERLY TARGETS — QUALITY AUDITS PENDING",
  "GENE WRIGHT SYMPATHIZERS DISTRIBUTE PAMPHLETS IN LOWER SECTORS",
  "BIOTECH FIRMS PETITION FOR RELAXED MODIFICATION REGULATIONS",
];

const CYBERNETICS_HEADLINES = [
  "CYBERNETICS CLINIC REPORTS RECORD IMPLANT INSTALLATIONS THIS QUARTER",
  "CYBERPSYCHOSIS INCIDENT IN SECTOR 7 — SUBJECT CONTAINED BY MARSHAL RESPONSE TEAM",
  "BLACK MARKET IMPLANT RING BUSTED — 200 SUBSTANDARD AUGMENTATIONS SEIZED",
  "NEURAL INTERFACE FIRMWARE PATCH DEPLOYED — USERS REPORT BRIEF DISORIENTATION",
  "IMPLANT REJECTION RATES DROP FOLLOWING NEW BIO-COMPATIBILITY PROTOCOLS",
];

function hasAnyTech(state: GameState, techs: string[]): boolean {
  return techs.some((t) => state.unlockedTechnologies.includes(t));
}

function hasAnyBuilding(state: GameState, keys: string[]): boolean {
  return keys.some((k) => ((state.buildings as Record<string, number>)[k] ?? 0) > 0);
}

function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Task #480: per-pool shuffled-cursor rotation. pickRandom on a large pool
// still repeats recently shown lines by chance; a rotation walks a shuffled
// order of the whole pool before any line can repeat, then reshuffles.
// Module-level instances persist across hook remounts, so the no-near-repeat
// guarantee survives screen navigation. The static fictional pools use this;
// the parameterized generators (weather/temperature/environmental) keep
// pickRandom because their output varies via substitution anyway.
function makeRotation<T>(pool: T[]): () => T {
  let order: number[] = [];
  let cursor = 0;
  let last: T | undefined;
  const reshuffle = () => {
    order = pool.map((_, i) => i);
    for (let i = order.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [order[i], order[j]] = [order[j], order[i]];
    }
    cursor = 0;
  };
  reshuffle();
  return () => {
    if (cursor >= order.length) reshuffle();
    let next = pool[order[cursor++]];
    // Guard the reshuffle boundary: the first item of a fresh order could be
    // the same line that just closed the previous cycle.
    if (pool.length > 1 && next === last) {
      if (cursor >= order.length) reshuffle();
      next = pool[order[cursor++]];
    }
    last = next;
    return next;
  };
}

const nextAmbient = makeRotation(AMBIENT_HEADLINES);
const nextDarkHumor = makeRotation(DARK_HUMOR_HEADLINES);
const nextLore = makeRotation(LORE_HEADLINES);
const nextPropaganda = makeRotation(PROPAGANDA_BROADCASTS);
const nextAd = makeRotation(DYSTOPIAN_ADS);
const nextFaction = makeRotation(FACTION_BROADCASTS);
const nextPsa = makeRotation(CITY_PSAS);
const nextMutant = makeRotation(MUTANT_UPLIFT_HEADLINES);
const nextGenetics = makeRotation(GENETICS_HEADLINES);
const nextCybernetics = makeRotation(CYBERNETICS_HEADLINES);

function getCrimeHeadline(crime: number): string | null {
  if (crime > 90) return "CRITICAL: Criminal organizations operating with impunity across multiple sectors";
  if (crime > 80) return "CRIME WAVE: Law enforcement struggling to contain widespread criminal activity";
  if (crime > 70) return "SECURITY ADVISORY: Crime rates trending dangerously high";
  if (crime > 60) return "ENFORCEMENT: Increased patrols authorized in high-crime districts";
  if (crime < 15) return "MODEL CITY: Crime rates at historic lows — citizens commend enforcement";
  return null;
}

function getUnrestHeadline(unrest: number): string | null {
  if (unrest > 90) return "EMERGENCY: Mass civil disobedience reported — martial protocols on standby";
  if (unrest > 80) return "CIVIL UNREST: Protests spreading across multiple sectors";
  if (unrest > 70) return "TENSION: Public gatherings exceeding permitted thresholds";
  if (unrest > 60) return "ADVISORY: Citizen dissatisfaction levels warrant monitoring";
  if (unrest < 15) return "HARMONY: Civil order index at peak levels — citizens report high satisfaction";
  return null;
}

function getHappinessHeadline(happiness: number): string | null {
  if (happiness > 85) return "PROSPERITY: Citizens report highest quality of life in city history";
  if (happiness > 75) return "POSITIVE: Public sentiment surveys show widespread contentment";
  if (happiness < 20) return "CRISIS: Citizen despair index reaches critical levels";
  if (happiness < 30) return "WARNING: Quality of life indicators falling below minimum thresholds";
  return null;
}

function getPopulationHeadline(pop: number, prevPop: number): string | null {
  const milestones = [50000, 100000, 250000, 500000, 750000, 1000000, 2000000, 5000000];
  for (const m of milestones) {
    if (pop >= m && prevPop < m) {
      if (m >= 1000000) return `HISTORIC: Population breaches ${(m / 1000000).toFixed(0)} million mark`;
      return `MILESTONE: City population exceeds ${(m / 1000).toFixed(0)}K citizens`;
    }
  }
  if (pop < prevPop * 0.95 && prevPop > 10000) return "DEMOGRAPHIC ALERT: Significant population decline detected";
  return null;
}

function getFinanceHeadline(credits: number, prevCredits: number): string | null {
  if (credits <= 0 && prevCredits > 0) return "FINANCIAL CRISIS: Treasury depleted — emergency austerity measures required";
  if (credits >= 1000000 && prevCredits < 1000000) return "ECONOMIC MILESTONE: Treasury exceeds 1 million credits";
  if (credits >= 100000 && prevCredits < 100000) return "ECONOMIC GROWTH: Treasury surpasses 100,000 credit threshold";
  if (credits < prevCredits * 0.7 && prevCredits > 50000) return "FISCAL WARNING: Rapid treasury depletion detected — review expenditures";
  return null;
}

function getHealthHeadline(health: number): string | null {
  if (health > 85) return "PUBLIC HEALTH: Medical facilities report excellent citizen wellness metrics";
  if (health < 25) return "HEALTH EMERGENCY: Disease outbreaks overwhelming medical infrastructure";
  if (health < 40) return "MEDICAL ALERT: Public health declining — additional resources recommended";
  return null;
}

function getEmploymentHeadline(employment: number): string | null {
  if (employment > 90) return "LABOR REPORT: Near-full employment achieved — workforce operating at capacity";
  if (employment < 30) return "UNEMPLOYMENT CRISIS: Mass joblessness threatening social stability";
  if (employment < 50) return "LABOR WARNING: Unemployment rates climbing to concerning levels";
  return null;
}

function getCorruptionHeadline(corruption: number): string | null {
  if (corruption > 80) return "CORRUPTION: Internal affairs reports systemic graft throughout city administration";
  if (corruption > 60) return "INTEGRITY ALERT: Corruption indices above acceptable governance thresholds";
  if (corruption < 10) return "TRANSPARENCY: Anti-corruption measures proving highly effective";
  return null;
}

const APPROVAL_AXIS_LABELS: Record<"citizens" | "officers" | "factions" | "military", string> = {
  citizens: "CITIZEN",
  officers: "OFFICER CORPS",
  factions: "FACTION",
  military: "MILITARY",
};

// Tasks #366/#371: TV-news phrasings for one-time nature-crisis tier
// transitions. Improvement entries are keyed by the engine's inbox message
// title; worsening entries are keyed by the tier discriminator in the
// engine-emitted newsFeed id. Wording echoes the NATURE CRISIS RISK gauges.
// No emojis, no exclamation marks (user preference: Lauren).
const BIOSPHERE_CRISIS_TICKER_HEADLINES: Record<string, string> = {
  "NATURE CRISES EASING":
    "ENVIRONMENTAL: NATURE CRISES EASING — biosphere investment paying off, wildlands crisis risk eased down from high",
  "NATURE CRISES AT LOW RISK":
    "ENVIRONMENTAL: NATURE CRISES AT LOW RISK — recovered wildlands holding the biosphere steady, nature crises held low",
  "NATURE CRISIS RISK RISING":
    "NATURE DESK: NATURE CRISIS RISK RISING — biosphere recovery has lost ground — ecology desk flags a higher chance of new crises",
  "NATURE CRISIS RISK HIGH":
    "NATURE DESK: NATURE CRISIS RISK HIGH — the biosphere has slipped into the highest crisis band — wildlands response teams advised",
};

// Task #484: when more than this many incidents land on the same tick (e.g.
// offline catch-up applying many ticks, or several spawners firing together),
// the ticker collapses them into one combined headline instead of one line
// each so routine city news is not pushed off-screen. Small batches (1-3)
// keep the per-event titled headlines.
export const INCIDENT_COLLAPSE_THRESHOLD = 3;

// Task #490: same idea for the advisory ECHO systems (Free Choir trade
// resolutions, nature-crisis tier improvements, brownout warnings/recoveries,
// dismissed-warning return hints). Each echoes an inbox message one-for-one
// via a seen-id gate, so after offline catch-up applies many ticks at once,
// several can queue back-to-back on the first live tick. When more than this
// many advisory echoes would land on the same tick, they collapse into one
// combined summary line; normal play (a few at a time) keeps the per-advisory
// headlines. All echoed messages remain readable in full in the inbox.
export const ADVISORY_ECHO_COLLAPSE_THRESHOLD = 3;

export function useNewsHeadlines(state: GameState) {
  const { addHeadline } = useNews();
  const prevTickRef = useRef(state.totalTicks);
  const prevPopRef = useRef(state.cityStats.population);
  const prevCreditsRef = useRef(state.resources?.credits ?? 0);
  const prevEventsRef = useRef(state.activeEvents?.length ?? 0);
  // Task #464: snapshot of active event ids so a spawn can be classified as a
  // brand-new incident vs a known crisis resurfacing (repeat: true, stamped by
  // the engine spawners — the UI never re-detects the transition itself).
  const prevEventIdsRef = useRef<Set<string>>(new Set((state.activeEvents ?? []).map((e) => e.id)));
  const prevUnlockedRef = useRef(state.unlockedTechnologies?.length ?? 0);
  const prevResearchRef = useRef(state.activeResearch?.techId);
  const prevApprovalRef = useRef(state.politics?.approval);
  const prevCasualtiesRef = useRef(state.retinue?.totalCasualties ?? 0);
  // Task #221: track ids of Free Choir transit ticker messages we've already
  // surfaced as scrolling headlines so each resolution emits exactly one
  // ticker headline (no spam if the inbox keeps the message around).
  const seenChoirTickerIdsRef = useRef<Set<string>>(new Set());
  // Tasks #366/#371: track ids of nature-crisis tier advisories we've already
  // scrolled so each improvement or worsening transition lands on-screen as a
  // TV news story exactly once even though its source persists in state.
  // Seed from the mount-time state so an advisory emitted in a previous session
  // does not replay after a reload.
  const seenBiosphereTickerIdsRef = useRef<Set<string>>(
    new Set([
      ...(state.messages ?? [])
        .filter((m) => m.id.startsWith("biosphere-crisis-tier-"))
        .map((m) => m.id),
      ...(state.newsFeed ?? [])
        .filter((n) => n.id.startsWith("news-biosphere-risk-rising-"))
        .map((n) => n.id),
    ]),
  );
  // Task #430: track ids of imminent-brownout advisories we've already scrolled
  // so the heads-up lands on-screen as a TV news story exactly once even though
  // the message lingers in the inbox.
  const seenPowerTickerIdsRef = useRef<Set<string>>(new Set());
  // Task #456: track ids of "dismissed recurring warning will return" hints
  // we've already scrolled so each dismissal echoes exactly once even though
  // the message lingers in the inbox.
  const seenDismissHintIdsRef = useRef<Set<string>>(new Set());
  // Task #534: track ids of "training doctrine winding down" advisories we've
  // already scrolled so each activation's near-expiry heads-up echoes exactly
  // once even though the message lingers in the inbox. Seeded from the
  // mount-time inbox so an advisory emitted in a PREVIOUS session (messages
  // persist in the save) does not replay on the ticker after a reload — only
  // advisories that land while this session is running scroll past.
  const seenDoctrineTickerIdsRef = useRef<Set<string>>(
    new Set(
      (state.messages ?? [])
        .filter((m) => m.id.startsWith(TRAINING_DOCTRINE_WINDDOWN_ID_PREFIX))
        .map((m) => m.id),
    ),
  );
  // Task #553: track ids of the one-time "golden-age coverage on hold" hint
  // we've already scrolled so it echoes on the ticker exactly once even though
  // the message lingers in the inbox. Seeded from the mount-time inbox so a
  // hint emitted in a PREVIOUS session (messages persist in the save) does not
  // replay on the ticker after a reload.
  const seenProsperityGateTickerIdsRef = useRef<Set<string>>(
    new Set(
      (state.messages ?? [])
        .filter((m) => m.id.startsWith(PROSPERITY_GATE_HINT_ID_PREFIX))
        .map((m) => m.id),
    ),
  );
  // Task #564: track ids of "ceasefire holds" confirmations we've already
  // scrolled so each accepted ceasefire echoes on the ticker exactly once
  // even though the message lingers in the inbox. Seeded from the mount-time
  // inbox so a confirmation emitted in a PREVIOUS session (messages persist
  // in the save) does not replay after a reload.
  const seenCeasefireTickerIdsRef = useRef<Set<string>>(
    new Set(
      (state.messages ?? [])
        .filter((m) => m.id.startsWith(CEASEFIRE_HOLDS_ID_PREFIX))
        .map((m) => m.id),
    ),
  );
  // Task #480: track ids of engine newsFeed facts we've already scrolled.
  // Seeded from the mount-time feed so facts recorded in a PREVIOUS session
  // (the feed persists in the save) do not replay as breaking news on load —
  // only facts that land while this session is running scroll past.
  const seenNewsFeedIdsRef = useRef<Set<string>>(
    new Set((state.newsFeed ?? []).map((n) => n.id)),
  );

  useEffect(() => {
    const tick = state.totalTicks;
    if (tick === prevTickRef.current) return;
    prevTickRef.current = tick;

    const pop = state.cityStats.population;
    const credits = state.resources?.credits ?? 0;
    const events = state.activeEvents?.length ?? 0;
    const unlocked = state.unlockedTechnologies?.length ?? 0;

    if (unlocked > prevUnlockedRef.current) {
      addHeadline("BREAKTHROUGH: New technology research completed — implementation underway");
    }
    prevUnlockedRef.current = unlocked;

    const currentResearchId = state.activeResearch?.techId;
    if (currentResearchId && currentResearchId !== prevResearchRef.current) {
      addHeadline("RESEARCH: New project initiated — laboratory teams assigned");
    }
    prevResearchRef.current = currentResearchId;

    if (events > prevEventsRef.current) {
      // Task #464: a re-fired stat-triggered crisis carries repeat: true from
      // the engine — announce it as a resurfaced known incident so the ticker
      // does not mislead players into thinking a second, new crisis landed.
      const prevIds = prevEventIdsRef.current;
      const added = (state.activeEvents ?? []).filter((e) => !prevIds.has(e.id));
      // Task #471: name the specific crisis in each headline so the ticker is
      // actionable at a glance — one headline per landed event, with a generic
      // fallback only when no titled event can be identified.
      // Task #484: in rare bursts (offline catch-up applying many ticks, or
      // several spawners firing together) a long run of ALERT/UPDATE lines
      // would push routine city news off-screen. When more than
      // INCIDENT_COLLAPSE_THRESHOLD incidents land on the same tick, collapse
      // them into one combined headline; small batches keep the per-event
      // titled headlines.
      if (added.length > INCIDENT_COLLAPSE_THRESHOLD) {
        const leadTitle =
          added
            .map((e) => (typeof e.title === "string" ? e.title.trim() : ""))
            .find((t) => t.length > 0) ?? "";
        const repeatCount = added.filter((e) => e.repeat === true).length;
        const countLabel =
          repeatCount === added.length
            ? `${added.length} known incidents resurfaced`
            : repeatCount > 0
              ? `${added.length} incidents reported — ${repeatCount} resurfaced`
              : `${added.length} new incidents reported`;
        addHeadline(
          leadTitle
            ? `ALERT: ${countLabel} — ${leadTitle} and ${added.length - 1} more — command staff awaiting orders`
            : `ALERT: ${countLabel} — command staff awaiting orders`,
        );
      } else {
        for (const e of added) {
          const title = typeof e.title === "string" ? e.title.trim() : "";
          if (e.repeat === true) {
            addHeadline(
              title
                ? `UPDATE: ${title} resurfaced — still unresolved — command staff awaiting orders`
                : "UPDATE: Known crisis resurfaced — still unresolved — command staff awaiting orders",
            );
          } else {
            addHeadline(
              title
                ? `ALERT: New incident reported — ${title} — command staff awaiting orders`
                : "ALERT: New incident reported — command staff awaiting orders",
            );
          }
        }
      }
      if (added.length === 0) {
        addHeadline("ALERT: New incident reported — command staff awaiting orders");
      }
    }
    prevEventsRef.current = events;
    prevEventIdsRef.current = new Set((state.activeEvents ?? []).map((e) => e.id));

    const popH = getPopulationHeadline(pop, prevPopRef.current);
    if (popH) addHeadline(popH);
    prevPopRef.current = pop;

    const finH = getFinanceHeadline(credits, prevCreditsRef.current);
    if (finH) addHeadline(finH);
    prevCreditsRef.current = credits;

    if (tick % 6 === 0) {
      const crimeH = getCrimeHeadline(state.cityStats.crime);
      if (crimeH) addHeadline(crimeH);
    }

    if (tick % 6 === 2) {
      const unrestH = getUnrestHeadline(state.cityStats.unrest);
      if (unrestH) addHeadline(unrestH);
    }

    if (tick % 6 === 4) {
      const happyH = getHappinessHeadline(state.cityStats.happiness);
      if (happyH) addHeadline(happyH);
    }

    if (tick % 8 === 0) {
      const healthH = getHealthHeadline(state.cityStats.publicHealth ?? 50);
      if (healthH) addHeadline(healthH);
    }

    if (tick % 10 === 0) {
      const empH = getEmploymentHeadline(state.cityStats.employment ?? 50);
      if (empH) addHeadline(empH);
    }

    if (tick % 12 === 0) {
      const corrH = getCorruptionHeadline(state.cityStats.corruption ?? 0);
      if (corrH) addHeadline(corrH);
    }

    if (tick % 4 === 0) {
      addHeadline(nextAmbient());
    }

    if (tick % 7 === 0) {
      addHeadline(nextLore());
    }

    if (tick % 3 === 0) {
      addHeadline(nextDarkHumor());
    }

    if (tick % 5 === 1) {
      addHeadline(nextPropaganda());
    }

    if (tick % 6 === 3) {
      addHeadline(nextAd());
    }

    if (tick % 8 === 5) {
      addHeadline(nextFaction());
    }

    if (tick % 4 === 2) {
      addHeadline(nextPsa());
    }

    // Task #480: serialized mini-arc installments. The episode index derives
    // from totalTicks, so the storyline unfolds in order across a session and
    // resumes at the right installment after a save/load.
    if (tick % ARC_SLOT_MODULO === 6 && ARC_PLAYLIST.length > 0) {
      addHeadline(ARC_PLAYLIST[Math.floor(tick / ARC_SLOT_MODULO) % ARC_PLAYLIST.length]);
    }

    if (tick % 13 === 0) {
      const hasMutant =
        hasAnyTech(state, ["uplift_neural_interfaces", "uplift_cognitive_enhancement", "uplift_civil_rights_framework", "xenofauna_domestication", "xeno_flora_survey", "bio_monitoring_implants"]) ||
        hasAnyBuilding(state, ["upliftTrainingAcademies", "upliftHabitatBlocks", "upliftCivicCenters", "biotechFarms"]);
      if (hasMutant) addHeadline(nextMutant());
    }

    if (tick % 14 === 0) {
      const hasGenetics =
        hasAnyTech(state, ["genetic_disease_screening", "genetic_conservation_protocols", "sd_crispr_fundamentals", "sd_human_cloning_research", "sd_animal_cloning", "mil_clone_army_program"]) ||
        hasAnyBuilding(state, ["geneSplicingLabs", "cloningFacilities", "geneticSeedVaults"]);
      if (hasGenetics) addHeadline(nextGenetics());
    }

    if (tick % 15 === 0) {
      const hasCyber =
        hasAnyTech(state, ["basic_cybernetics", "prosthetic_engineering", "neural_interface_basics", "synthetic_muscle_tech", "optical_augmentation"]) ||
        hasAnyBuilding(state, ["cyberneticsDevelopmentFacilities", "cyberneticRecyclingFacilities"]);
      if (hasCyber) addHeadline(nextCybernetics());
    }

    if (tick % 5 === 0) {
      addHeadline(getWeatherHeadline(state.weather));
    }

    if (tick % 5 === 2) {
      const pollution = state.cityStats.corruption ?? 30;
      addHeadline(getAirQualityHeadline(pollution));
    }

    if (tick % 9 === 0) {
      addHeadline(getTemperatureHeadline());
    }

    if (tick % 11 === 0) {
      addHeadline(getEnvironmentalMiscHeadline());
    }

    // Approval crossings — surface +/- 10 swings as ticker headlines.
    const approval = state.politics?.approval;
    const prevApproval = prevApprovalRef.current;
    if (approval && prevApproval) {
      (Object.keys(approval) as (keyof typeof approval)[]).forEach((axis) => {
        const delta = approval[axis] - prevApproval[axis];
        if (delta >= 10) {
          addHeadline(`POLLING: ${APPROVAL_AXIS_LABELS[axis]} approval surges +${Math.round(delta)} points to ${approval[axis]}%`);
        } else if (delta <= -10) {
          addHeadline(`POLLING: ${APPROVAL_AXIS_LABELS[axis]} approval collapses ${Math.round(delta)} points to ${approval[axis]}%`);
        }
      });
    }
    if (approval) prevApprovalRef.current = approval;

    // KIA — surface freshly fallen retinue casualties.
    const casualties = state.retinue?.totalCasualties ?? 0;
    const fallen = casualties - prevCasualtiesRef.current;
    if (fallen > 0) {
      addHeadline(
        fallen === 1
          ? "RETINUE LOSS: One troop reported killed in action — quartermaster filing the obit now"
          : `RETINUE LOSS: ${fallen} troops reported killed in action — flags lowered at the barracks`
      );
    }
    prevCasualtiesRef.current = casualties;

    // Task #490: the four advisory-echo systems below each mirror an inbox
    // message onto the ticker via a seen-id gate. Collect their headlines
    // here first; after all four run, they are emitted individually (normal
    // play) or collapsed into one combined summary line when a burst — e.g.
    // offline catch-up applying many ticks at once — would queue more than
    // ADVISORY_ECHO_COLLAPSE_THRESHOLD of them on the same tick.
    const pendingAdvisoryEchoes: string[] = [];

    // Task #221: surface Free Choir transit swings on the scrolling news
    // ticker too. The engine emits two message titles when a transit-themed
    // chain stage or trade_caravan_arrives resolves under a non-neutral
    // Free Choir stance:
    //   - "TRADE STAGE RESOLVED"   (advanceEventChain in eventChains.ts)
    //   - "TRADE CARAVAN RESOLVED" (respondToEvent in GameContext.tsx)
    // Both carry stable ids (chain_choir_ticker_… / caravan_choir_ticker_…)
    // and a body shaped "<deltas> — Free Choir <swing>%". Diff against a
    // seen-id set so each resolution scrolls past exactly once even though
    // the message stays in the inbox indefinitely.
    const messages = state.messages ?? [];
    for (const m of messages) {
      if (m.title !== "TRADE STAGE RESOLVED" && m.title !== "TRADE CARAVAN RESOLVED") continue;
      if (seenChoirTickerIdsRef.current.has(m.id)) continue;
      seenChoirTickerIdsRef.current.add(m.id);
      const lane = m.title === "TRADE CARAVAN RESOLVED" ? "CARAVAN" : "CONVOY";
      // Echo the message body verbatim — it already contains both the deltas
      // and the "Free Choir +/-N%" tail, which makes the resulting headline
      // naturally vary per resolution and slip past addHeadline's exact-string
      // dedupe even when two resolutions share the same swing percentage.
      pendingAdvisoryEchoes.push(`TRADE: ${lane} HAUL ${m.body} (FREE CHOIR PATRONAGE)`);
    }
    // Bound the seen set so a marathon session doesn't grow it without limit.
    // ARRAY_CAPS.messages is 200 elsewhere in the engine; mirror that ceiling
    // so we never hold more entries than the inbox can keep alive anyway.
    // IMPORTANT: snapshot the overflow count BEFORE deleting — re-reading
    // `.size` mid-loop causes the loop bound to shrink with each delete and
    // exits early, leaving the set well above 200. (Insertion order is
    // preserved by Set, so iterating from the front evicts the oldest ids.)
    if (seenChoirTickerIdsRef.current.size > 200) {
      const overflow = seenChoirTickerIdsRef.current.size - 200;
      const it = seenChoirTickerIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenChoirTickerIdsRef.current.delete(v);
      }
    }

    // Tasks #366/#371: surface one-time nature-crisis tier transitions on the
    // scrolling news ticker. Improvements arrive as GameMessages, while
    // worsening transitions arrive as newsFeed facts with the stable
    // "news-biosphere-risk-rising-" prefix. Both use the same bounded seen-id
    // gate so each transition scrolls exactly once even though its source
    // persists in state.
    for (const m of messages) {
      if (!m.id.startsWith("biosphere-crisis-tier-")) continue;
      if (seenBiosphereTickerIdsRef.current.has(m.id)) continue;
      seenBiosphereTickerIdsRef.current.add(m.id);
      const headline = BIOSPHERE_CRISIS_TICKER_HEADLINES[m.title];
      if (headline) pendingAdvisoryEchoes.push(headline);
    }

    // Task #371: worsening transitions are already emitted by the engine as
    // ticker-ready newsFeed facts. Handle them here rather than relying on the
    // generic city-desk bridge below, keeping the warning in the same
    // advisory burst lane as the easing headlines.
    for (const n of state.newsFeed ?? []) {
      if (!n.id.startsWith("news-biosphere-risk-rising-")) continue;
      if (seenBiosphereTickerIdsRef.current.has(n.id)) continue;
      seenBiosphereTickerIdsRef.current.add(n.id);
      const title = n.id.includes("-high-")
        ? "NATURE CRISIS RISK HIGH"
        : "NATURE CRISIS RISK RISING";
      pendingAdvisoryEchoes.push(
        BIOSPHERE_CRISIS_TICKER_HEADLINES[title] ?? n.headline,
      );
      // The generic feed bridge below has its own seen set. Mark this fact
      // there too so a warning is never emitted twice in one effect.
      seenNewsFeedIdsRef.current.add(n.id);
    }

    // Bound the seen set. A long session can oscillate between tiers, with
    // each transition receiving a fresh tick-suffixed id.
    if (seenBiosphereTickerIdsRef.current.size > 50) {
      const overflow = seenBiosphereTickerIdsRef.current.size - 50;
      const it = seenBiosphereTickerIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenBiosphereTickerIdsRef.current.delete(v);
      }
    }

    // Task #430: surface the one-time imminent-brownout advisory on the scrolling
    // news ticker so the heads-up lands on-screen even if the player is not on the
    // overview power card. The engine (emitPowerBrownoutWarning in tickProcessors.ts)
    // emits a single GameMessage with a stable id prefixed "power-brownout-warning-"
    // and one of two titles the moment the power ETA drops into the warn window.
    // Diff against a seen-id set so each low-power episode scrolls past exactly
    // once even though the message lingers in the inbox.
    for (const m of messages) {
      if (!m.id.startsWith("power-brownout-warning-")) continue;
      if (seenPowerTickerIdsRef.current.has(m.id)) continue;
      seenPowerTickerIdsRef.current.add(m.id);
      const headline =
        m.title === "POWER GRID GOING DARK"
          ? "POWER: GRID BROWNING OUT — FULL BLACKOUT IMMINENT WITHOUT MORE GENERATION"
          : "POWER: GRID BROWNOUT IMMINENT — RESERVE ABOUT TO RUN OUT AT CURRENT DEFICIT";
      pendingAdvisoryEchoes.push(headline);
    }

    // Task #436: close the loop with the all-clear. When the grid recovers from a
    // warned-about episode the engine (emitPowerBrownoutWarning) emits a single
    // GameMessage with a stable id prefixed "power-brownout-recovery-"; echo it
    // onto the ticker exactly once (same seen-id gate) so the player who fixed the
    // grid gets on-screen confirmation, mirroring the warning half above.
    for (const m of messages) {
      if (!m.id.startsWith("power-brownout-recovery-")) continue;
      if (seenPowerTickerIdsRef.current.has(m.id)) continue;
      seenPowerTickerIdsRef.current.add(m.id);
      pendingAdvisoryEchoes.push(
        "POWER: GRID STABILIZED — RESERVE BACK IN SURPLUS AND BROWNOUT RISK CLEARED",
      );
    }
    // Task #456: surface the "dismissed warning will return" hint on the ticker.
    // The engine (applyEventDismissal in eventResolution.ts) emits a single
    // GameMessage with a stable id prefixed DISMISS_RECURRENCE_HINT_ID_PREFIX
    // only when a RECURRING stat-triggered crisis is dismissed while its
    // underlying condition is still critical; the UI just mirrors it (never
    // re-detects the condition here). The message body already reads as one
    // ticker-ready sentence, so scroll it verbatim under an ADVISORY tag.
    for (const m of messages) {
      if (!m.id.startsWith(DISMISS_RECURRENCE_HINT_ID_PREFIX)) continue;
      if (seenDismissHintIdsRef.current.has(m.id)) continue;
      seenDismissHintIdsRef.current.add(m.id);
      pendingAdvisoryEchoes.push(`ADVISORY: ${m.body.toUpperCase()}`);
    }

    // Task #534: surface the one-time "training doctrine winding down" advisory
    // on the ticker. The engine (runTick's edict loop in formulas.ts) emits a
    // single GameMessage with a stable id prefixed
    // TRAINING_DOCTRINE_WINDDOWN_ID_PREFIX when the Accelerated Training
    // Doctrine has exactly 2 ticks left; the UI just mirrors it (never
    // re-detects the countdown here). Diff against a seen-id set so each
    // activation's heads-up scrolls past exactly once even though the message
    // lingers in the inbox.
    for (const m of messages) {
      if (!m.id.startsWith(TRAINING_DOCTRINE_WINDDOWN_ID_PREFIX)) continue;
      if (seenDoctrineTickerIdsRef.current.has(m.id)) continue;
      seenDoctrineTickerIdsRef.current.add(m.id);
      pendingAdvisoryEchoes.push(
        "ADVISORY: ACCELERATED TRAINING DOCTRINE WINDING DOWN — PLACE TRAINING ORDERS NOW TO LOCK IN THE FASTER DRILL PACE",
      );
    }
    // Bound the seen set like the others: a long session can cycle the
    // doctrine many times, each activation emitting a fresh tick-suffixed id.
    if (seenDoctrineTickerIdsRef.current.size > 50) {
      const overflow = seenDoctrineTickerIdsRef.current.size - 50;
      const it = seenDoctrineTickerIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenDoctrineTickerIdsRef.current.delete(v);
      }
    }

    // Task #553: surface the one-time "golden-age coverage on hold" hint on
    // the ticker. The engine (emitProsperityGateHint in tickProcessors.ts)
    // emits a single GameMessage with a stable id prefixed
    // PROSPERITY_GATE_HINT_ID_PREFIX the first time the city clears every core
    // thriving bar while only the biosphere floor and/or housing pressure
    // keeps the prosperity stories locked; the UI just mirrors it (never
    // re-detects the gate here). The id names the blocker
    // (biosphere/housing/both), so the headline can point at the right fix.
    // No cap on this seen set: the hint fires at most once per city (durable
    // prosperityGateHintShown flag), so it holds at most a few ids.
    for (const m of messages) {
      if (!m.id.startsWith(PROSPERITY_GATE_HINT_ID_PREFIX)) continue;
      if (seenProsperityGateTickerIdsRef.current.has(m.id)) continue;
      seenProsperityGateTickerIdsRef.current.add(m.id);
      const which = m.id.slice(PROSPERITY_GATE_HINT_ID_PREFIX.length);
      const headline = which.startsWith("both")
        ? "ADVISORY: GOLDEN-AGE COVERAGE ON HOLD — BIOSPHERE AND HOUSING PRESSURE BLOCK THE PROSPERITY STORIES — FULL BRIEF FILED IN THE INBOX"
        : which.startsWith("housing")
          ? "ADVISORY: GOLDEN-AGE COVERAGE ON HOLD — ONLY SEVERE HOUSING PRESSURE BLOCKS THE PROSPERITY STORIES — EXPAND HOUSING TO RELIEVE IT"
          : "ADVISORY: GOLDEN-AGE COVERAGE ON HOLD — ONLY THE WASTELAND-GRADE BIOSPHERE BLOCKS THE PROSPERITY STORIES — INVEST IN WILDLANDS STEWARDSHIP";
      pendingAdvisoryEchoes.push(headline);
    }

    // Task #490: emit the collected advisory echoes. Normal play (a few at a
    // time) keeps the per-advisory headlines; a burst — typically offline
    // catch-up applying many ticks at once — collapses into one combined
    // summary line so the ticker is not walled off by back-to-back echoes.
    // The full messages remain readable in the inbox either way.
    if (pendingAdvisoryEchoes.length > ADVISORY_ECHO_COLLAPSE_THRESHOLD) {
      addHeadline(
        `ADVISORY: ${pendingAdvisoryEchoes.length} ADVISORIES ISSUED WHILE COMMAND WAS AWAY — FULL DETAILS FILED IN THE INBOX`,
      );
    } else {
      for (const h of pendingAdvisoryEchoes) addHeadline(h);
    }
    // Bound the seen set like the others: a long session can dismiss the same
    // recurring crisis many times, each with a fresh tick suffix.
    if (seenDismissHintIdsRef.current.size > 50) {
      const overflow = seenDismissHintIdsRef.current.size - 50;
      const it = seenDismissHintIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenDismissHintIdsRef.current.delete(v);
      }
    }

    // Bound the seen set the same way the biosphere set is capped: a struggling
    // grid can re-warn across a long session (recover then relapse), each with a
    // fresh tick suffix, so keep only the most recent ids.
    if (seenPowerTickerIdsRef.current.size > 50) {
      const overflow = seenPowerTickerIdsRef.current.size - 50;
      const it = seenPowerTickerIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenPowerTickerIdsRef.current.delete(v);
      }
    }

    // Task #564: surface the "ceasefire holds" confirmation on the ticker.
    // The engine (applyCeasefireDiplomacy in eventResolution.ts) emits a
    // single GameMessage with a stable id prefixed CEASEFIRE_HOLDS_ID_PREFIX
    // only when accepting/countering a ceasefire actually cooled the
    // instigating faction; the UI just mirrors it (never re-detects the
    // threat transition here). The message body already reads as one
    // ticker-ready sentence, so scroll it verbatim under the WAR DESK tag.
    // Accepting a ceasefire is a direct player action (never batched by
    // offline catch-up), so a plain per-message headline needs no burst
    // collapse.
    for (const m of messages) {
      if (!m.id.startsWith(CEASEFIRE_HOLDS_ID_PREFIX)) continue;
      if (seenCeasefireTickerIdsRef.current.has(m.id)) continue;
      seenCeasefireTickerIdsRef.current.add(m.id);
      addHeadline(`WAR DESK: ${m.body.toUpperCase()}`);
    }
    // Bound the seen set like the others: factions can re-escalate and offer
    // new ceasefires across a long session, each with a fresh tick suffix.
    if (seenCeasefireTickerIdsRef.current.size > 50) {
      const overflow = seenCeasefireTickerIdsRef.current.size - 50;
      const it = seenCeasefireTickerIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenCeasefireTickerIdsRef.current.delete(v);
      }
    }

    // Task #480: mirror engine newsFeed facts (edicts enacted/lapsed, notable
    // construction, mega-project completions, resolved events with the chosen
    // orders, season turnover) onto the ticker. The engine writes each fact
    // into state.newsFeed at the source; this block only echoes unseen ids —
    // it never re-detects any transition itself. Iterate oldest-first so a
    // multi-fact tick scrolls in chronological order, and collapse bursts
    // (offline catch-up) into one summary line like the advisory echoes.
    const feed = state.newsFeed ?? [];
    const pendingCityDesk: string[] = [];
    for (let i = feed.length - 1; i >= 0; i--) {
      const n = feed[i];
      if (seenNewsFeedIdsRef.current.has(n.id)) continue;
      seenNewsFeedIdsRef.current.add(n.id);
      if (typeof n.headline === "string" && n.headline.length > 0) {
        pendingCityDesk.push(n.headline);
      }
    }
    if (pendingCityDesk.length > ADVISORY_ECHO_COLLAPSE_THRESHOLD) {
      addHeadline(
        `CITY DESK: ${pendingCityDesk.length} DEVELOPMENTS LOGGED WHILE COMMAND WAS AWAY — LATEST: ${pendingCityDesk[pendingCityDesk.length - 1]}`,
      );
    } else {
      for (const h of pendingCityDesk) addHeadline(h);
    }
    // Bound the seen set. The feed itself is capped at NEWS_FEED_CAP by the
    // engine, but ids rotate through it continuously in a long session, so
    // evict oldest-first past 200 (snapshot overflow BEFORE deleting).
    if (seenNewsFeedIdsRef.current.size > 200) {
      const overflow = seenNewsFeedIdsRef.current.size - 200;
      const it = seenNewsFeedIdsRef.current.values();
      for (let i = 0; i < overflow; i++) {
        const v = it.next().value;
        if (v !== undefined) seenNewsFeedIdsRef.current.delete(v);
      }
    }
  }, [state.totalTicks]);
}
